testthat::test_that('validation activates exactly its aggregations and required wells', {
  withr::local_dir(rprojroot::find_root(rprojroot::has_file("pixi.toml")))
  withr::local_envvar(MULTIOMER_VALIDATION = '0')
  normal <- read_aggregation_config_tibble()
  testthat::expect_identical(normal$aggregation[vapply(normal$is_active, isTRUE, logical(1))], 'immune_human_2x')
  normal_wells <- build_active_GEM_well_tibble(build_GEM_well_tibble())
  testthat::expect_setequal(normal_wells$GEM_well_ID, c('healthy_PBMC_human','lymphoma_lymph_human'))
  Sys.setenv(MULTIOMER_VALIDATION = '1')
  validation <- read_aggregation_config_tibble()
  selected <- vapply(validation$is_active, isTRUE, logical(1))
  testthat::expect_setequal(validation$aggregation[selected], validation_aggregations())
  wells <- build_active_GEM_well_tibble(build_GEM_well_tibble())
  testthat::expect_setequal(wells$GEM_well_ID, unlist(validation$aggregation_GEM_well_IDs[selected]))
  testthat::expect_equal(nrow(wells), 33L)
  Sys.setenv(MULTIOMER_VALIDATION = 'all')
  testthat::expect_error(validation_aggregations(), 'must be 0 or 1')
})

testthat::test_that('resource probes reject ignored ranges and oversized responses', {
  withr::local_dir(rprojroot::find_root(rprojroot::has_file("pixi.toml")))
  probe <- new.env(parent = globalenv())
  sys.source('validation/preflight.R', envir = probe)
  file <- tempfile()
  withr::defer(unlink(file))
  writeBin(charToRaw('PAR1'), file)
  probe$system2 <- function(...) '200'
  testthat::expect_error(probe$fetch_validation_resource('https://example.test/file', file, 4, '0-3'), 'Live resource check failed')
  probe$system2 <- function(...) '206'
  testthat::expect_silent(probe$fetch_validation_resource('https://example.test/file', file, 4, '0-3'))
  writeBin(charToRaw('PAR1extra'), file)
  testthat::expect_error(probe$fetch_validation_resource('https://example.test/file', file, 4, '0-3'), 'Invalid response size')
  testthat::expect_error(parse_open_targets_listing('<html>error</html>'), 'No Parquet')
  testthat::expect_identical(parse_open_targets_listing('<a href="part-01.parquet">part</a>'), 'part-01.parquet')
})
