%%{init: {'flowchart': {'defaultRenderer': 'elk'}}}%%
flowchart TB
  consensus_peak_GRanges.ATAC.brain_mouse(["consensus_peak_GRanges.ATAC"]):::none --> chromVAR_obj.ATAC.brain_mouse(["chromVAR_obj.ATAC"]):::none
  metadata_w_cell_types_tibble.ATAC.brain_mouse(["metadata_w_cell_types_tibble.ATAC"]):::none --> chromVAR_obj.ATAC.brain_mouse(["chromVAR_obj.ATAC"]):::none
  consensus_peak_GRanges.ATAC.immune_human_2x(["consensus_peak_GRanges.ATAC"]):::none --> chromVAR_obj.ATAC.immune_human_2x(["chromVAR_obj.ATAC"]):::none
  metadata_w_cell_types_tibble.ATAC.immune_human_2x(["metadata_w_cell_types_tibble.ATAC"]):::none --> chromVAR_obj.ATAC.immune_human_2x(["chromVAR_obj.ATAC"]):::none
  metadata_w_cell_types_tibble.ATAC.PBMC_human_6x(["metadata_w_cell_types_tibble.ATAC"]):::none --> chromVAR_obj.ATAC.PBMC_human_6x(["chromVAR_obj.ATAC"]):::none
  consensus_peak_GRanges.ATAC.PBMC_human_6x(["consensus_peak_GRanges.ATAC"]):::none --> chromVAR_obj.ATAC.PBMC_human_6x(["chromVAR_obj.ATAC"]):::none
  combined_BPCells_fragment_obj.ATAC.brain_mouse(["combined_BPCells_fragment_obj.ATAC"]):::none --> consensus_peak_BPCells_matrix_dir.ATAC.brain_mouse(["consensus_peak_BPCells_matrix_dir.ATAC"]):::none
  metadata_w_cell_types_tibble.GEX.brain_mouse(["metadata_w_cell_types_tibble.GEX"]):::none --> consensus_peak_BPCells_matrix_dir.ATAC.brain_mouse(["consensus_peak_BPCells_matrix_dir.ATAC"]):::none
  consensus_peak_GRanges.ATAC.brain_mouse(["consensus_peak_GRanges.ATAC"]):::none --> consensus_peak_BPCells_matrix_dir.ATAC.brain_mouse(["consensus_peak_BPCells_matrix_dir.ATAC"]):::none
  consensus_peak_GRanges.ATAC.immune_human_2x(["consensus_peak_GRanges.ATAC"]):::none --> consensus_peak_BPCells_matrix_dir.ATAC.immune_human_2x(["consensus_peak_BPCells_matrix_dir.ATAC"]):::none
  combined_BPCells_fragment_obj.ATAC.immune_human_2x(["combined_BPCells_fragment_obj.ATAC"]):::none --> consensus_peak_BPCells_matrix_dir.ATAC.immune_human_2x(["consensus_peak_BPCells_matrix_dir.ATAC"]):::none
  metadata_w_cell_types_tibble.GEX.immune_human_2x(["metadata_w_cell_types_tibble.GEX"]):::none --> consensus_peak_BPCells_matrix_dir.ATAC.immune_human_2x(["consensus_peak_BPCells_matrix_dir.ATAC"]):::none
  consensus_peak_GRanges.ATAC.PBMC_human_6x(["consensus_peak_GRanges.ATAC"]):::none --> consensus_peak_BPCells_matrix_dir.ATAC.PBMC_human_6x(["consensus_peak_BPCells_matrix_dir.ATAC"]):::none
  metadata_w_cell_types_tibble.GEX.PBMC_human_6x(["metadata_w_cell_types_tibble.GEX"]):::none --> consensus_peak_BPCells_matrix_dir.ATAC.PBMC_human_6x(["consensus_peak_BPCells_matrix_dir.ATAC"]):::none
  combined_BPCells_fragment_obj.ATAC.PBMC_human_6x(["combined_BPCells_fragment_obj.ATAC"]):::none --> consensus_peak_BPCells_matrix_dir.ATAC.PBMC_human_6x(["consensus_peak_BPCells_matrix_dir.ATAC"]):::none
  within_clusters_collapsed_peaks_per_cluster_GRanges.ATAC.brain_mouse["within_clusters_collapsed_peaks_per_cluster_GRanges.ATAC"]:::none --> consensus_peak_GRanges.ATAC.brain_mouse(["consensus_peak_GRanges.ATAC"]):::none
  within_clusters_collapsed_peaks_per_cluster_GRanges.ATAC.immune_human_2x["within_clusters_collapsed_peaks_per_cluster_GRanges.ATAC"]:::none --> consensus_peak_GRanges.ATAC.immune_human_2x(["consensus_peak_GRanges.ATAC"]):::none
  within_clusters_collapsed_peaks_per_cluster_GRanges.ATAC.PBMC_human_6x["within_clusters_collapsed_peaks_per_cluster_GRanges.ATAC"]:::none --> consensus_peak_GRanges.ATAC.PBMC_human_6x(["consensus_peak_GRanges.ATAC"]):::none
  LSI_BPCells.ATAC.brain_mouse(["LSI_BPCells.ATAC"]):::none --> harmony_embeddings_matrix.ATAC.brain_mouse(["harmony_embeddings_matrix.ATAC"]):::none
  LSI_BPCells.ATAC.immune_human_2x(["LSI_BPCells.ATAC"]):::none --> harmony_embeddings_matrix.ATAC.immune_human_2x(["harmony_embeddings_matrix.ATAC"]):::none
  LSI_BPCells.ATAC.PBMC_human_6x(["LSI_BPCells.ATAC"]):::none --> harmony_embeddings_matrix.ATAC.PBMC_human_6x(["harmony_embeddings_matrix.ATAC"]):::none
  LSI_BPCells.ATAC.subgroups.brain_mouse["LSI_BPCells.ATAC.subgroups"]:::none --> harmony_embeddings_matrix.ATAC.subgroups.brain_mouse["harmony_embeddings_matrix.ATAC.subgroups"]:::none
  LSI_BPCells.ATAC.subgroups.immune_human_2x["LSI_BPCells.ATAC.subgroups"]:::none --> harmony_embeddings_matrix.ATAC.subgroups.immune_human_2x["harmony_embeddings_matrix.ATAC.subgroups"]:::none
  LSI_BPCells.ATAC.subgroups.PBMC_human_6x["LSI_BPCells.ATAC.subgroups"]:::none --> harmony_embeddings_matrix.ATAC.subgroups.PBMC_human_6x["harmony_embeddings_matrix.ATAC.subgroups"]:::none
  harmony_embeddings_matrix.ATAC.brain_mouse(["harmony_embeddings_matrix.ATAC"]):::none --> LSI_clusters.ATAC.brain_mouse(["LSI_clusters.ATAC"]):::none
  harmony_embeddings_matrix.ATAC.immune_human_2x(["harmony_embeddings_matrix.ATAC"]):::none --> LSI_clusters.ATAC.immune_human_2x(["LSI_clusters.ATAC"]):::none
  harmony_embeddings_matrix.ATAC.PBMC_human_6x(["harmony_embeddings_matrix.ATAC"]):::none --> LSI_clusters.ATAC.PBMC_human_6x(["LSI_clusters.ATAC"]):::none
  harmony_embeddings_matrix.ATAC.subgroups.brain_mouse["harmony_embeddings_matrix.ATAC.subgroups"]:::none --> LSI_clusters.ATAC.subgroups.brain_mouse["LSI_clusters.ATAC.subgroups"]:::none
  harmony_embeddings_matrix.ATAC.subgroups.immune_human_2x["harmony_embeddings_matrix.ATAC.subgroups"]:::none --> LSI_clusters.ATAC.subgroups.immune_human_2x["LSI_clusters.ATAC.subgroups"]:::none
  harmony_embeddings_matrix.ATAC.subgroups.PBMC_human_6x["harmony_embeddings_matrix.ATAC.subgroups"]:::none --> LSI_clusters.ATAC.subgroups.PBMC_human_6x["LSI_clusters.ATAC.subgroups"]:::none
  scDblFinder_results_df.ATAC.brain_mouse(["scDblFinder_results_df.ATAC"]):::none --> metadata_w_cell_types_tibble.ATAC.brain_mouse(["metadata_w_cell_types_tibble.ATAC"]):::none
  scDblFinder_results_df.ATAC.immune_human_2x(["scDblFinder_results_df.ATAC"]):::none --> metadata_w_cell_types_tibble.ATAC.immune_human_2x(["metadata_w_cell_types_tibble.ATAC"]):::none
  scDblFinder_results_df.ATAC.PBMC_human_6x(["scDblFinder_results_df.ATAC"]):::none --> metadata_w_cell_types_tibble.ATAC.PBMC_human_6x(["metadata_w_cell_types_tibble.ATAC"]):::none
  ATAC_marker_TFs_list.brain_mouse(["ATAC_marker_TFs_list"]):::none --> peak_TF_motif_matrix.ATAC.brain_mouse(["peak_TF_motif_matrix.ATAC"]):::none
  consensus_peak_GRanges.ATAC.brain_mouse(["consensus_peak_GRanges.ATAC"]):::none --> peak_TF_motif_matrix.ATAC.brain_mouse(["peak_TF_motif_matrix.ATAC"]):::none
  consensus_peak_GRanges.ATAC.immune_human_2x(["consensus_peak_GRanges.ATAC"]):::none --> peak_TF_motif_matrix.ATAC.immune_human_2x(["peak_TF_motif_matrix.ATAC"]):::none
  ATAC_marker_TFs_list.immune_human_2x(["ATAC_marker_TFs_list"]):::none --> peak_TF_motif_matrix.ATAC.immune_human_2x(["peak_TF_motif_matrix.ATAC"]):::none
  consensus_peak_GRanges.ATAC.PBMC_human_6x(["consensus_peak_GRanges.ATAC"]):::none --> peak_TF_motif_matrix.ATAC.PBMC_human_6x(["peak_TF_motif_matrix.ATAC"]):::none
  ATAC_marker_TFs_list.PBMC_human_6x(["ATAC_marker_TFs_list"]):::none --> peak_TF_motif_matrix.ATAC.PBMC_human_6x(["peak_TF_motif_matrix.ATAC"]):::none
  combined_BPCells_fragment_obj.ATAC.brain_mouse(["combined_BPCells_fragment_obj.ATAC"]):::none --> peaks_per_cluster_narrowPeaks.peaks.ATAC.brain_mouse["peaks_per_cluster_narrowPeaks.peaks.ATAC"]:::none
  combined_BPCells_fragment_obj.ATAC.immune_human_2x(["combined_BPCells_fragment_obj.ATAC"]):::none --> peaks_per_cluster_narrowPeaks.peaks.ATAC.immune_human_2x["peaks_per_cluster_narrowPeaks.peaks.ATAC"]:::none
  combined_BPCells_fragment_obj.ATAC.PBMC_human_6x(["combined_BPCells_fragment_obj.ATAC"]):::none --> peaks_per_cluster_narrowPeaks.peaks.ATAC.PBMC_human_6x["peaks_per_cluster_narrowPeaks.peaks.ATAC"]:::none
  harmony_embeddings_matrix.ATAC.brain_mouse(["harmony_embeddings_matrix.ATAC"]):::none --> UMAP_embeddings_tibble.ATAC.brain_mouse(["UMAP_embeddings_tibble.ATAC"]):::none
  harmony_embeddings_matrix.ATAC.immune_human_2x(["harmony_embeddings_matrix.ATAC"]):::none --> UMAP_embeddings_tibble.ATAC.immune_human_2x(["UMAP_embeddings_tibble.ATAC"]):::none
  harmony_embeddings_matrix.ATAC.PBMC_human_6x(["harmony_embeddings_matrix.ATAC"]):::none --> UMAP_embeddings_tibble.ATAC.PBMC_human_6x(["UMAP_embeddings_tibble.ATAC"]):::none
  harmony_embeddings_matrix.ATAC.subgroups.brain_mouse["harmony_embeddings_matrix.ATAC.subgroups"]:::none --> UMAP_embeddings_tibble.ATAC.subgroups.brain_mouse["UMAP_embeddings_tibble.ATAC.subgroups"]:::none
  harmony_embeddings_matrix.ATAC.subgroups.immune_human_2x["harmony_embeddings_matrix.ATAC.subgroups"]:::none --> UMAP_embeddings_tibble.ATAC.subgroups.immune_human_2x["UMAP_embeddings_tibble.ATAC.subgroups"]:::none
  harmony_embeddings_matrix.ATAC.subgroups.PBMC_human_6x["harmony_embeddings_matrix.ATAC.subgroups"]:::none --> UMAP_embeddings_tibble.ATAC.subgroups.PBMC_human_6x["UMAP_embeddings_tibble.ATAC.subgroups"]:::none
  metadata_w_cell_types_tibble.GEX.brain_mouse(["metadata_w_cell_types_tibble.GEX"]):::none --> peaks_per_cluster_narrowPeaks.peaks.ATAC.brain_mouse["peaks_per_cluster_narrowPeaks.peaks.ATAC"]:::none
  metadata_w_cell_types_tibble.GEX.immune_human_2x(["metadata_w_cell_types_tibble.GEX"]):::none --> peaks_per_cluster_narrowPeaks.peaks.ATAC.immune_human_2x["peaks_per_cluster_narrowPeaks.peaks.ATAC"]:::none
  metadata_w_cell_types_tibble.GEX.PBMC_human_6x(["metadata_w_cell_types_tibble.GEX"]):::none --> peaks_per_cluster_narrowPeaks.peaks.ATAC.PBMC_human_6x["peaks_per_cluster_narrowPeaks.peaks.ATAC"]:::none
  chromVAR_obj.ATAC.brain_mouse(["chromVAR_obj.ATAC"]):::none --> TF_activity_BPCells_matrix_dir.ATAC.brain_mouse(["TF_activity_BPCells_matrix_dir.ATAC"]):::none
  chromVAR_obj.ATAC.immune_human_2x(["chromVAR_obj.ATAC"]):::none --> TF_activity_BPCells_matrix_dir.ATAC.immune_human_2x(["TF_activity_BPCells_matrix_dir.ATAC"]):::none
  chromVAR_obj.ATAC.PBMC_human_6x(["chromVAR_obj.ATAC"]):::none --> TF_activity_BPCells_matrix_dir.ATAC.PBMC_human_6x(["TF_activity_BPCells_matrix_dir.ATAC"]):::none
  peak_TF_motif_matrix.ATAC.brain_mouse(["peak_TF_motif_matrix.ATAC"]):::none --> TF_activity_BPCells_matrix_dir.ATAC.brain_mouse(["TF_activity_BPCells_matrix_dir.ATAC"]):::none
  peak_TF_motif_matrix.ATAC.immune_human_2x(["peak_TF_motif_matrix.ATAC"]):::none --> TF_activity_BPCells_matrix_dir.ATAC.immune_human_2x(["TF_activity_BPCells_matrix_dir.ATAC"]):::none
  peak_TF_motif_matrix.ATAC.PBMC_human_6x(["peak_TF_motif_matrix.ATAC"]):::none --> TF_activity_BPCells_matrix_dir.ATAC.PBMC_human_6x(["TF_activity_BPCells_matrix_dir.ATAC"]):::none
  metadata_w_cell_types_tibble.ATAC.brain_mouse(["metadata_w_cell_types_tibble.ATAC"]):::none --> harmony_embeddings_matrix.ATAC.subgroups.brain_mouse["harmony_embeddings_matrix.ATAC.subgroups"]:::none
  harmony_embeddings_matrix.ATAC.brain_mouse(["harmony_embeddings_matrix.ATAC"]):::none --> harmony_embeddings_matrix.ATAC.subgroups.brain_mouse["harmony_embeddings_matrix.ATAC.subgroups"]:::none
  metadata_w_cell_types_tibble.ATAC.brain_mouse(["metadata_w_cell_types_tibble.ATAC"]):::none --> LSI_BPCells.ATAC.subgroups.brain_mouse["LSI_BPCells.ATAC.subgroups"]:::none
  harmony_embeddings_matrix.ATAC.brain_mouse(["harmony_embeddings_matrix.ATAC"]):::none --> LSI_BPCells.ATAC.subgroups.brain_mouse["LSI_BPCells.ATAC.subgroups"]:::none
  harmony_embeddings_matrix.ATAC.immune_human_2x(["harmony_embeddings_matrix.ATAC"]):::none --> harmony_embeddings_matrix.ATAC.subgroups.immune_human_2x["harmony_embeddings_matrix.ATAC.subgroups"]:::none
  metadata_w_cell_types_tibble.ATAC.immune_human_2x(["metadata_w_cell_types_tibble.ATAC"]):::none --> harmony_embeddings_matrix.ATAC.subgroups.immune_human_2x["harmony_embeddings_matrix.ATAC.subgroups"]:::none
  harmony_embeddings_matrix.ATAC.immune_human_2x(["harmony_embeddings_matrix.ATAC"]):::none --> LSI_BPCells.ATAC.subgroups.immune_human_2x["LSI_BPCells.ATAC.subgroups"]:::none
  metadata_w_cell_types_tibble.ATAC.immune_human_2x(["metadata_w_cell_types_tibble.ATAC"]):::none --> LSI_BPCells.ATAC.subgroups.immune_human_2x["LSI_BPCells.ATAC.subgroups"]:::none
  metadata_w_cell_types_tibble.ATAC.PBMC_human_6x(["metadata_w_cell_types_tibble.ATAC"]):::none --> harmony_embeddings_matrix.ATAC.subgroups.PBMC_human_6x["harmony_embeddings_matrix.ATAC.subgroups"]:::none
  harmony_embeddings_matrix.ATAC.PBMC_human_6x(["harmony_embeddings_matrix.ATAC"]):::none --> harmony_embeddings_matrix.ATAC.subgroups.PBMC_human_6x["harmony_embeddings_matrix.ATAC.subgroups"]:::none
  metadata_w_cell_types_tibble.ATAC.PBMC_human_6x(["metadata_w_cell_types_tibble.ATAC"]):::none --> LSI_BPCells.ATAC.subgroups.PBMC_human_6x["LSI_BPCells.ATAC.subgroups"]:::none
  harmony_embeddings_matrix.ATAC.PBMC_human_6x(["harmony_embeddings_matrix.ATAC"]):::none --> LSI_BPCells.ATAC.subgroups.PBMC_human_6x["LSI_BPCells.ATAC.subgroups"]:::none
  consensus_peak_BPCells_matrix_dir.ATAC.brain_mouse(["consensus_peak_BPCells_matrix_dir.ATAC"]):::none --> chromVAR_obj.ATAC.brain_mouse(["chromVAR_obj.ATAC"]):::none
  consensus_peak_BPCells_matrix_dir.ATAC.brain_mouse(["consensus_peak_BPCells_matrix_dir.ATAC"]):::none --> peak_TF_motif_matrix.ATAC.brain_mouse(["peak_TF_motif_matrix.ATAC"]):::none
  consensus_peak_BPCells_matrix_dir.ATAC.brain_mouse(["consensus_peak_BPCells_matrix_dir.ATAC"]):::none --> LSI_BPCells.ATAC.brain_mouse(["LSI_BPCells.ATAC"]):::none
  consensus_peak_BPCells_matrix_dir.ATAC.brain_mouse(["consensus_peak_BPCells_matrix_dir.ATAC"]):::none --> LSI_BPCells.ATAC.subgroups.brain_mouse["LSI_BPCells.ATAC.subgroups"]:::none
  consensus_peak_BPCells_matrix_dir.ATAC.brain_mouse(["consensus_peak_BPCells_matrix_dir.ATAC"]):::none --> harmony_embeddings_matrix.ATAC.brain_mouse(["harmony_embeddings_matrix.ATAC"]):::none
  consensus_peak_BPCells_matrix_dir.ATAC.brain_mouse(["consensus_peak_BPCells_matrix_dir.ATAC"]):::none --> scDblFinder_results_df.ATAC.brain_mouse(["scDblFinder_results_df.ATAC"]):::none
  consensus_peak_BPCells_matrix_dir.ATAC.brain_mouse(["consensus_peak_BPCells_matrix_dir.ATAC"]):::none --> metadata_w_cell_types_tibble.ATAC.brain_mouse(["metadata_w_cell_types_tibble.ATAC"]):::none
  consensus_peak_BPCells_matrix_dir.ATAC.immune_human_2x(["consensus_peak_BPCells_matrix_dir.ATAC"]):::none --> chromVAR_obj.ATAC.immune_human_2x(["chromVAR_obj.ATAC"]):::none
  consensus_peak_BPCells_matrix_dir.ATAC.immune_human_2x(["consensus_peak_BPCells_matrix_dir.ATAC"]):::none --> peak_TF_motif_matrix.ATAC.immune_human_2x(["peak_TF_motif_matrix.ATAC"]):::none
  consensus_peak_BPCells_matrix_dir.ATAC.immune_human_2x(["consensus_peak_BPCells_matrix_dir.ATAC"]):::none --> LSI_BPCells.ATAC.immune_human_2x(["LSI_BPCells.ATAC"]):::none
  consensus_peak_BPCells_matrix_dir.ATAC.immune_human_2x(["consensus_peak_BPCells_matrix_dir.ATAC"]):::none --> LSI_BPCells.ATAC.subgroups.immune_human_2x["LSI_BPCells.ATAC.subgroups"]:::none
  consensus_peak_BPCells_matrix_dir.ATAC.immune_human_2x(["consensus_peak_BPCells_matrix_dir.ATAC"]):::none --> harmony_embeddings_matrix.ATAC.immune_human_2x(["harmony_embeddings_matrix.ATAC"]):::none
  consensus_peak_BPCells_matrix_dir.ATAC.immune_human_2x(["consensus_peak_BPCells_matrix_dir.ATAC"]):::none --> scDblFinder_results_df.ATAC.immune_human_2x(["scDblFinder_results_df.ATAC"]):::none
  consensus_peak_BPCells_matrix_dir.ATAC.immune_human_2x(["consensus_peak_BPCells_matrix_dir.ATAC"]):::none --> metadata_w_cell_types_tibble.ATAC.immune_human_2x(["metadata_w_cell_types_tibble.ATAC"]):::none
  consensus_peak_BPCells_matrix_dir.ATAC.PBMC_human_6x(["consensus_peak_BPCells_matrix_dir.ATAC"]):::none --> chromVAR_obj.ATAC.PBMC_human_6x(["chromVAR_obj.ATAC"]):::none
  consensus_peak_BPCells_matrix_dir.ATAC.PBMC_human_6x(["consensus_peak_BPCells_matrix_dir.ATAC"]):::none --> peak_TF_motif_matrix.ATAC.PBMC_human_6x(["peak_TF_motif_matrix.ATAC"]):::none
  consensus_peak_BPCells_matrix_dir.ATAC.PBMC_human_6x(["consensus_peak_BPCells_matrix_dir.ATAC"]):::none --> LSI_BPCells.ATAC.PBMC_human_6x(["LSI_BPCells.ATAC"]):::none
  consensus_peak_BPCells_matrix_dir.ATAC.PBMC_human_6x(["consensus_peak_BPCells_matrix_dir.ATAC"]):::none --> LSI_BPCells.ATAC.subgroups.PBMC_human_6x["LSI_BPCells.ATAC.subgroups"]:::none
  consensus_peak_BPCells_matrix_dir.ATAC.PBMC_human_6x(["consensus_peak_BPCells_matrix_dir.ATAC"]):::none --> harmony_embeddings_matrix.ATAC.PBMC_human_6x(["harmony_embeddings_matrix.ATAC"]):::none
  consensus_peak_BPCells_matrix_dir.ATAC.PBMC_human_6x(["consensus_peak_BPCells_matrix_dir.ATAC"]):::none --> scDblFinder_results_df.ATAC.PBMC_human_6x(["scDblFinder_results_df.ATAC"]):::none
  consensus_peak_BPCells_matrix_dir.ATAC.PBMC_human_6x(["consensus_peak_BPCells_matrix_dir.ATAC"]):::none --> metadata_w_cell_types_tibble.ATAC.PBMC_human_6x(["metadata_w_cell_types_tibble.ATAC"]):::none
  LSI_BPCells.ATAC.brain_mouse(["LSI_BPCells.ATAC"]):::none --> scDblFinder_results_df.ATAC.brain_mouse(["scDblFinder_results_df.ATAC"]):::none
  LSI_BPCells.ATAC.immune_human_2x(["LSI_BPCells.ATAC"]):::none --> scDblFinder_results_df.ATAC.immune_human_2x(["scDblFinder_results_df.ATAC"]):::none
  LSI_BPCells.ATAC.PBMC_human_6x(["LSI_BPCells.ATAC"]):::none --> scDblFinder_results_df.ATAC.PBMC_human_6x(["scDblFinder_results_df.ATAC"]):::none
  combined_BPCells_fragment_obj.ATAC.brain_mouse(["combined_BPCells_fragment_obj.ATAC"]):::none --> harmony_embeddings_matrix.ATAC.brain_mouse(["harmony_embeddings_matrix.ATAC"]):::none
  metadata_w_cell_types_tibble.GEX.brain_mouse(["metadata_w_cell_types_tibble.GEX"]):::none --> harmony_embeddings_matrix.ATAC.brain_mouse(["harmony_embeddings_matrix.ATAC"]):::none
  consensus_peak_GRanges.ATAC.brain_mouse(["consensus_peak_GRanges.ATAC"]):::none --> harmony_embeddings_matrix.ATAC.brain_mouse(["harmony_embeddings_matrix.ATAC"]):::none
  combined_BPCells_fragment_obj.ATAC.brain_mouse(["combined_BPCells_fragment_obj.ATAC"]):::none --> metadata_w_cell_types_tibble.ATAC.brain_mouse(["metadata_w_cell_types_tibble.ATAC"]):::none
  metadata_w_cell_types_tibble.GEX.brain_mouse(["metadata_w_cell_types_tibble.GEX"]):::none --> metadata_w_cell_types_tibble.ATAC.brain_mouse(["metadata_w_cell_types_tibble.ATAC"]):::none
  consensus_peak_GRanges.ATAC.brain_mouse(["consensus_peak_GRanges.ATAC"]):::none --> metadata_w_cell_types_tibble.ATAC.brain_mouse(["metadata_w_cell_types_tibble.ATAC"]):::none
  combined_BPCells_fragment_obj.ATAC.brain_mouse(["combined_BPCells_fragment_obj.ATAC"]):::none --> scDblFinder_results_df.ATAC.brain_mouse(["scDblFinder_results_df.ATAC"]):::none
  metadata_w_cell_types_tibble.GEX.brain_mouse(["metadata_w_cell_types_tibble.GEX"]):::none --> scDblFinder_results_df.ATAC.brain_mouse(["scDblFinder_results_df.ATAC"]):::none
  consensus_peak_GRanges.ATAC.brain_mouse(["consensus_peak_GRanges.ATAC"]):::none --> scDblFinder_results_df.ATAC.brain_mouse(["scDblFinder_results_df.ATAC"]):::none
  consensus_peak_GRanges.ATAC.immune_human_2x(["consensus_peak_GRanges.ATAC"]):::none --> harmony_embeddings_matrix.ATAC.immune_human_2x(["harmony_embeddings_matrix.ATAC"]):::none
  combined_BPCells_fragment_obj.ATAC.immune_human_2x(["combined_BPCells_fragment_obj.ATAC"]):::none --> harmony_embeddings_matrix.ATAC.immune_human_2x(["harmony_embeddings_matrix.ATAC"]):::none
  metadata_w_cell_types_tibble.GEX.immune_human_2x(["metadata_w_cell_types_tibble.GEX"]):::none --> harmony_embeddings_matrix.ATAC.immune_human_2x(["harmony_embeddings_matrix.ATAC"]):::none
  consensus_peak_GRanges.ATAC.immune_human_2x(["consensus_peak_GRanges.ATAC"]):::none --> metadata_w_cell_types_tibble.ATAC.immune_human_2x(["metadata_w_cell_types_tibble.ATAC"]):::none
  combined_BPCells_fragment_obj.ATAC.immune_human_2x(["combined_BPCells_fragment_obj.ATAC"]):::none --> metadata_w_cell_types_tibble.ATAC.immune_human_2x(["metadata_w_cell_types_tibble.ATAC"]):::none
  metadata_w_cell_types_tibble.GEX.immune_human_2x(["metadata_w_cell_types_tibble.GEX"]):::none --> metadata_w_cell_types_tibble.ATAC.immune_human_2x(["metadata_w_cell_types_tibble.ATAC"]):::none
  consensus_peak_GRanges.ATAC.immune_human_2x(["consensus_peak_GRanges.ATAC"]):::none --> scDblFinder_results_df.ATAC.immune_human_2x(["scDblFinder_results_df.ATAC"]):::none
  combined_BPCells_fragment_obj.ATAC.immune_human_2x(["combined_BPCells_fragment_obj.ATAC"]):::none --> scDblFinder_results_df.ATAC.immune_human_2x(["scDblFinder_results_df.ATAC"]):::none
  metadata_w_cell_types_tibble.GEX.immune_human_2x(["metadata_w_cell_types_tibble.GEX"]):::none --> scDblFinder_results_df.ATAC.immune_human_2x(["scDblFinder_results_df.ATAC"]):::none
  consensus_peak_GRanges.ATAC.PBMC_human_6x(["consensus_peak_GRanges.ATAC"]):::none --> harmony_embeddings_matrix.ATAC.PBMC_human_6x(["harmony_embeddings_matrix.ATAC"]):::none
  metadata_w_cell_types_tibble.GEX.PBMC_human_6x(["metadata_w_cell_types_tibble.GEX"]):::none --> harmony_embeddings_matrix.ATAC.PBMC_human_6x(["harmony_embeddings_matrix.ATAC"]):::none
  combined_BPCells_fragment_obj.ATAC.PBMC_human_6x(["combined_BPCells_fragment_obj.ATAC"]):::none --> harmony_embeddings_matrix.ATAC.PBMC_human_6x(["harmony_embeddings_matrix.ATAC"]):::none
  consensus_peak_GRanges.ATAC.PBMC_human_6x(["consensus_peak_GRanges.ATAC"]):::none --> metadata_w_cell_types_tibble.ATAC.PBMC_human_6x(["metadata_w_cell_types_tibble.ATAC"]):::none
  metadata_w_cell_types_tibble.GEX.PBMC_human_6x(["metadata_w_cell_types_tibble.GEX"]):::none --> metadata_w_cell_types_tibble.ATAC.PBMC_human_6x(["metadata_w_cell_types_tibble.ATAC"]):::none
  combined_BPCells_fragment_obj.ATAC.PBMC_human_6x(["combined_BPCells_fragment_obj.ATAC"]):::none --> metadata_w_cell_types_tibble.ATAC.PBMC_human_6x(["metadata_w_cell_types_tibble.ATAC"]):::none
  consensus_peak_GRanges.ATAC.PBMC_human_6x(["consensus_peak_GRanges.ATAC"]):::none --> scDblFinder_results_df.ATAC.PBMC_human_6x(["scDblFinder_results_df.ATAC"]):::none
  metadata_w_cell_types_tibble.GEX.PBMC_human_6x(["metadata_w_cell_types_tibble.GEX"]):::none --> scDblFinder_results_df.ATAC.PBMC_human_6x(["scDblFinder_results_df.ATAC"]):::none
  combined_BPCells_fragment_obj.ATAC.PBMC_human_6x(["combined_BPCells_fragment_obj.ATAC"]):::none --> scDblFinder_results_df.ATAC.PBMC_human_6x(["scDblFinder_results_df.ATAC"]):::none
  UCell_GEX_marker_genes_list.brain_mouse(["UCell_GEX_marker_genes_list"]):::none --> harmony_embeddings_matrix.ATAC.subgroups.brain_mouse["harmony_embeddings_matrix.ATAC.subgroups"]:::none
  UCell_GEX_marker_genes_list.brain_mouse(["UCell_GEX_marker_genes_list"]):::none --> LSI_BPCells.ATAC.subgroups.brain_mouse["LSI_BPCells.ATAC.subgroups"]:::none
  UCell_GEX_marker_genes_list.immune_human_2x(["UCell_GEX_marker_genes_list"]):::none --> harmony_embeddings_matrix.ATAC.subgroups.immune_human_2x["harmony_embeddings_matrix.ATAC.subgroups"]:::none
  UCell_GEX_marker_genes_list.immune_human_2x(["UCell_GEX_marker_genes_list"]):::none --> LSI_BPCells.ATAC.subgroups.immune_human_2x["LSI_BPCells.ATAC.subgroups"]:::none
  UCell_GEX_marker_genes_list.PBMC_human_6x(["UCell_GEX_marker_genes_list"]):::none --> harmony_embeddings_matrix.ATAC.subgroups.PBMC_human_6x["harmony_embeddings_matrix.ATAC.subgroups"]:::none
  UCell_GEX_marker_genes_list.PBMC_human_6x(["UCell_GEX_marker_genes_list"]):::none --> LSI_BPCells.ATAC.subgroups.PBMC_human_6x["LSI_BPCells.ATAC.subgroups"]:::none
  UCell_GEX_marker_genes_list.brain_mouse(["UCell_GEX_marker_genes_list"]):::none --> metadata_w_cell_types_tibble.ATAC.brain_mouse(["metadata_w_cell_types_tibble.ATAC"]):::none
  UMAP_embeddings_tibble.ATAC.brain_mouse(["UMAP_embeddings_tibble.ATAC"]):::none --> metadata_w_cell_types_tibble.ATAC.brain_mouse(["metadata_w_cell_types_tibble.ATAC"]):::none
  LSI_clusters.ATAC.brain_mouse(["LSI_clusters.ATAC"]):::none --> metadata_w_cell_types_tibble.ATAC.brain_mouse(["metadata_w_cell_types_tibble.ATAC"]):::none
  UCell_GEX_marker_genes_list.brain_mouse(["UCell_GEX_marker_genes_list"]):::none --> scDblFinder_results_df.ATAC.brain_mouse(["scDblFinder_results_df.ATAC"]):::none
  UMAP_embeddings_tibble.ATAC.brain_mouse(["UMAP_embeddings_tibble.ATAC"]):::none --> scDblFinder_results_df.ATAC.brain_mouse(["scDblFinder_results_df.ATAC"]):::none
  LSI_clusters.ATAC.brain_mouse(["LSI_clusters.ATAC"]):::none --> scDblFinder_results_df.ATAC.brain_mouse(["scDblFinder_results_df.ATAC"]):::none
  UCell_GEX_marker_genes_list.immune_human_2x(["UCell_GEX_marker_genes_list"]):::none --> metadata_w_cell_types_tibble.ATAC.immune_human_2x(["metadata_w_cell_types_tibble.ATAC"]):::none
  UMAP_embeddings_tibble.ATAC.immune_human_2x(["UMAP_embeddings_tibble.ATAC"]):::none --> metadata_w_cell_types_tibble.ATAC.immune_human_2x(["metadata_w_cell_types_tibble.ATAC"]):::none
  LSI_clusters.ATAC.immune_human_2x(["LSI_clusters.ATAC"]):::none --> metadata_w_cell_types_tibble.ATAC.immune_human_2x(["metadata_w_cell_types_tibble.ATAC"]):::none
  UCell_GEX_marker_genes_list.immune_human_2x(["UCell_GEX_marker_genes_list"]):::none --> scDblFinder_results_df.ATAC.immune_human_2x(["scDblFinder_results_df.ATAC"]):::none
  UMAP_embeddings_tibble.ATAC.immune_human_2x(["UMAP_embeddings_tibble.ATAC"]):::none --> scDblFinder_results_df.ATAC.immune_human_2x(["scDblFinder_results_df.ATAC"]):::none
  LSI_clusters.ATAC.immune_human_2x(["LSI_clusters.ATAC"]):::none --> scDblFinder_results_df.ATAC.immune_human_2x(["scDblFinder_results_df.ATAC"]):::none
  UCell_GEX_marker_genes_list.PBMC_human_6x(["UCell_GEX_marker_genes_list"]):::none --> metadata_w_cell_types_tibble.ATAC.PBMC_human_6x(["metadata_w_cell_types_tibble.ATAC"]):::none
  LSI_clusters.ATAC.PBMC_human_6x(["LSI_clusters.ATAC"]):::none --> metadata_w_cell_types_tibble.ATAC.PBMC_human_6x(["metadata_w_cell_types_tibble.ATAC"]):::none
  UMAP_embeddings_tibble.ATAC.PBMC_human_6x(["UMAP_embeddings_tibble.ATAC"]):::none --> metadata_w_cell_types_tibble.ATAC.PBMC_human_6x(["metadata_w_cell_types_tibble.ATAC"]):::none
  UCell_GEX_marker_genes_list.PBMC_human_6x(["UCell_GEX_marker_genes_list"]):::none --> scDblFinder_results_df.ATAC.PBMC_human_6x(["scDblFinder_results_df.ATAC"]):::none
  LSI_clusters.ATAC.PBMC_human_6x(["LSI_clusters.ATAC"]):::none --> scDblFinder_results_df.ATAC.PBMC_human_6x(["scDblFinder_results_df.ATAC"]):::none
  UMAP_embeddings_tibble.ATAC.PBMC_human_6x(["UMAP_embeddings_tibble.ATAC"]):::none --> scDblFinder_results_df.ATAC.PBMC_human_6x(["scDblFinder_results_df.ATAC"]):::none
  UCell_GEX_marker_genes_list.brain_mouse(["UCell_GEX_marker_genes_list"]):::none --> metadata_w_cell_types_tibble.GEX.brain_mouse(["metadata_w_cell_types_tibble.GEX"]):::none
  UCell_GEX_marker_genes_list.immune_human_2x(["UCell_GEX_marker_genes_list"]):::none --> metadata_w_cell_types_tibble.GEX.immune_human_2x(["metadata_w_cell_types_tibble.GEX"]):::none
  UCell_GEX_marker_genes_list.PBMC_human_6x(["UCell_GEX_marker_genes_list"]):::none --> metadata_w_cell_types_tibble.GEX.PBMC_human_6x(["metadata_w_cell_types_tibble.GEX"]):::none
  combined_BPCells_fragment_obj.ATAC.brain_mouse(["combined_BPCells_fragment_obj.ATAC"]):::none --> LSI_BPCells.ATAC.brain_mouse(["LSI_BPCells.ATAC"]):::none
  metadata_w_cell_types_tibble.GEX.brain_mouse(["metadata_w_cell_types_tibble.GEX"]):::none --> LSI_BPCells.ATAC.brain_mouse(["LSI_BPCells.ATAC"]):::none
  consensus_peak_GRanges.ATAC.brain_mouse(["consensus_peak_GRanges.ATAC"]):::none --> LSI_BPCells.ATAC.brain_mouse(["LSI_BPCells.ATAC"]):::none
  combined_BPCells_fragment_obj.ATAC.brain_mouse(["combined_BPCells_fragment_obj.ATAC"]):::none --> LSI_BPCells.ATAC.subgroups.brain_mouse["LSI_BPCells.ATAC.subgroups"]:::none
  metadata_w_cell_types_tibble.GEX.brain_mouse(["metadata_w_cell_types_tibble.GEX"]):::none --> LSI_BPCells.ATAC.subgroups.brain_mouse["LSI_BPCells.ATAC.subgroups"]:::none
  consensus_peak_GRanges.ATAC.brain_mouse(["consensus_peak_GRanges.ATAC"]):::none --> LSI_BPCells.ATAC.subgroups.brain_mouse["LSI_BPCells.ATAC.subgroups"]:::none
  consensus_peak_GRanges.ATAC.immune_human_2x(["consensus_peak_GRanges.ATAC"]):::none --> LSI_BPCells.ATAC.immune_human_2x(["LSI_BPCells.ATAC"]):::none
  combined_BPCells_fragment_obj.ATAC.immune_human_2x(["combined_BPCells_fragment_obj.ATAC"]):::none --> LSI_BPCells.ATAC.immune_human_2x(["LSI_BPCells.ATAC"]):::none
  metadata_w_cell_types_tibble.GEX.immune_human_2x(["metadata_w_cell_types_tibble.GEX"]):::none --> LSI_BPCells.ATAC.immune_human_2x(["LSI_BPCells.ATAC"]):::none
  consensus_peak_GRanges.ATAC.immune_human_2x(["consensus_peak_GRanges.ATAC"]):::none --> LSI_BPCells.ATAC.subgroups.immune_human_2x["LSI_BPCells.ATAC.subgroups"]:::none
  combined_BPCells_fragment_obj.ATAC.immune_human_2x(["combined_BPCells_fragment_obj.ATAC"]):::none --> LSI_BPCells.ATAC.subgroups.immune_human_2x["LSI_BPCells.ATAC.subgroups"]:::none
  metadata_w_cell_types_tibble.GEX.immune_human_2x(["metadata_w_cell_types_tibble.GEX"]):::none --> LSI_BPCells.ATAC.subgroups.immune_human_2x["LSI_BPCells.ATAC.subgroups"]:::none
  consensus_peak_GRanges.ATAC.PBMC_human_6x(["consensus_peak_GRanges.ATAC"]):::none --> LSI_BPCells.ATAC.PBMC_human_6x(["LSI_BPCells.ATAC"]):::none
  metadata_w_cell_types_tibble.GEX.PBMC_human_6x(["metadata_w_cell_types_tibble.GEX"]):::none --> LSI_BPCells.ATAC.PBMC_human_6x(["LSI_BPCells.ATAC"]):::none
  combined_BPCells_fragment_obj.ATAC.PBMC_human_6x(["combined_BPCells_fragment_obj.ATAC"]):::none --> LSI_BPCells.ATAC.PBMC_human_6x(["LSI_BPCells.ATAC"]):::none
  consensus_peak_GRanges.ATAC.PBMC_human_6x(["consensus_peak_GRanges.ATAC"]):::none --> LSI_BPCells.ATAC.subgroups.PBMC_human_6x["LSI_BPCells.ATAC.subgroups"]:::none
  metadata_w_cell_types_tibble.GEX.PBMC_human_6x(["metadata_w_cell_types_tibble.GEX"]):::none --> LSI_BPCells.ATAC.subgroups.PBMC_human_6x["LSI_BPCells.ATAC.subgroups"]:::none
  combined_BPCells_fragment_obj.ATAC.PBMC_human_6x(["combined_BPCells_fragment_obj.ATAC"]):::none --> LSI_BPCells.ATAC.subgroups.PBMC_human_6x["LSI_BPCells.ATAC.subgroups"]:::none
  ATAC_marker_TFs_list.brain_mouse(["ATAC_marker_TFs_list"]):::none --> TF_activity_BPCells_matrix_dir.ATAC.brain_mouse(["TF_activity_BPCells_matrix_dir.ATAC"]):::none
  ATAC_marker_TFs_list.immune_human_2x(["ATAC_marker_TFs_list"]):::none --> TF_activity_BPCells_matrix_dir.ATAC.immune_human_2x(["TF_activity_BPCells_matrix_dir.ATAC"]):::none
  ATAC_marker_TFs_list.PBMC_human_6x(["ATAC_marker_TFs_list"]):::none --> TF_activity_BPCells_matrix_dir.ATAC.PBMC_human_6x(["TF_activity_BPCells_matrix_dir.ATAC"]):::none
  metadata_w_cell_types_tibble.GEX.brain_mouse(["metadata_w_cell_types_tibble.GEX"]):::none --> within_clusters_collapsed_peaks_per_cluster_GRanges.ATAC.brain_mouse["within_clusters_collapsed_peaks_per_cluster_GRanges.ATAC"]:::none
  metadata_w_cell_types_tibble.GEX.immune_human_2x(["metadata_w_cell_types_tibble.GEX"]):::none --> within_clusters_collapsed_peaks_per_cluster_GRanges.ATAC.immune_human_2x["within_clusters_collapsed_peaks_per_cluster_GRanges.ATAC"]:::none
  metadata_w_cell_types_tibble.GEX.PBMC_human_6x(["metadata_w_cell_types_tibble.GEX"]):::none --> within_clusters_collapsed_peaks_per_cluster_GRanges.ATAC.PBMC_human_6x["within_clusters_collapsed_peaks_per_cluster_GRanges.ATAC"]:::none
  peaks_per_cluster_narrowPeaks.peaks.ATAC.brain_mouse["peaks_per_cluster_narrowPeaks.peaks.ATAC"]:::none --> within_clusters_collapsed_peaks_per_cluster_GRanges.ATAC.brain_mouse["within_clusters_collapsed_peaks_per_cluster_GRanges.ATAC"]:::none
  peaks_per_cluster_narrowPeaks.peaks.ATAC.immune_human_2x["peaks_per_cluster_narrowPeaks.peaks.ATAC"]:::none --> within_clusters_collapsed_peaks_per_cluster_GRanges.ATAC.immune_human_2x["within_clusters_collapsed_peaks_per_cluster_GRanges.ATAC"]:::none
  peaks_per_cluster_narrowPeaks.peaks.ATAC.PBMC_human_6x["peaks_per_cluster_narrowPeaks.peaks.ATAC"]:::none --> within_clusters_collapsed_peaks_per_cluster_GRanges.ATAC.PBMC_human_6x["within_clusters_collapsed_peaks_per_cluster_GRanges.ATAC"]:::none
