%%{init: {'flowchart': {'defaultRenderer': 'elk'}}}%%
flowchart TB
  UCell_GEX_marker_genes_list.muscle(["UCell_GEX_marker_genes_list.&lt;dataset_name&gt;"]):::none --> ATAC_coverage_marker_genes.muscle(["ATAC_coverage_marker_genes.&lt;dataset_name&gt;"]):::none
  UCell_GEX_marker_genes_list.muscle_test(["UCell_GEX_marker_genes_list.&lt;aggregation_name&gt;"]):::none --> ATAC_coverage_marker_genes.muscle_test(["ATAC_coverage_marker_genes.&lt;aggregation_name&gt;"]):::none
  JASPAR_motif_family_members_tibble(["JASPAR_motif_family_members_tibble"]):::none --> ATAC_marker_motif_families_list.muscle(["ATAC_marker_motif_families_list.&lt;dataset_name&gt;"]):::none
  JASPAR_motif_family_members_tibble(["JASPAR_motif_family_members_tibble"]):::none --> ATAC_marker_motif_families_list.muscle_test(["ATAC_marker_motif_families_list.&lt;aggregation_name&gt;"]):::none
  metadata_w_cell_types_tibble.ATAC.muscle(["metadata_w_cell_types_tibble.ATAC.&lt;dataset_name&gt;"]):::none --> chromVAR_obj.ATAC.muscle(["chromVAR_obj.ATAC.&lt;dataset_name&gt;"]):::none
  consensus_peak_GRanges.ATAC.muscle(["consensus_peak_GRanges.ATAC.&lt;dataset_name&gt;"]):::none --> chromVAR_obj.ATAC.muscle(["chromVAR_obj.ATAC.&lt;dataset_name&gt;"]):::none
  consensus_peak_GRanges.ATAC.muscle_test(["consensus_peak_GRanges.ATAC.&lt;aggregation_name&gt;"]):::none --> chromVAR_obj.ATAC.muscle_test(["chromVAR_obj.ATAC.&lt;aggregation_name&gt;"]):::none
  metadata_w_cell_types_tibble.ATAC.muscle_test(["metadata_w_cell_types_tibble.ATAC.&lt;aggregation_name&gt;"]):::none --> chromVAR_obj.ATAC.muscle_test(["chromVAR_obj.ATAC.&lt;aggregation_name&gt;"]):::none
  peak_TF_motif_family_matrix.ATAC.muscle(["peak_TF_motif_family_matrix.ATAC.&lt;dataset_name&gt;"]):::none --> chromVAR_TF_motif_family_matrix.ATAC.muscle(["chromVAR_TF_motif_family_matrix.ATAC.&lt;dataset_name&gt;"]):::none
  chromVAR_obj.ATAC.muscle(["chromVAR_obj.ATAC.&lt;dataset_name&gt;"]):::none --> chromVAR_TF_motif_family_matrix.ATAC.muscle(["chromVAR_TF_motif_family_matrix.ATAC.&lt;dataset_name&gt;"]):::none
  chromVAR_obj.ATAC.muscle_test(["chromVAR_obj.ATAC.&lt;aggregation_name&gt;"]):::none --> chromVAR_TF_motif_family_matrix.ATAC.muscle_test(["chromVAR_TF_motif_family_matrix.ATAC.&lt;aggregation_name&gt;"]):::none
  peak_TF_motif_family_matrix.ATAC.muscle_test(["peak_TF_motif_family_matrix.ATAC.&lt;aggregation_name&gt;"]):::none --> chromVAR_TF_motif_family_matrix.ATAC.muscle_test(["chromVAR_TF_motif_family_matrix.ATAC.&lt;aggregation_name&gt;"]):::none
  combined_BPCells_fragment_obj.ATAC.muscle(["combined_BPCells_fragment_obj.ATAC.&lt;dataset_name&gt;"]):::none --> consensus_peak_BPCells_matrix_dir.ATAC.muscle(["consensus_peak_BPCells_matrix_dir.ATAC.&lt;dataset_name&gt;"]):::none
  metadata_w_cell_types_tibble.GEX.muscle(["metadata_w_cell_types_tibble.GEX.&lt;dataset_name&gt;"]):::none --> consensus_peak_BPCells_matrix_dir.ATAC.muscle(["consensus_peak_BPCells_matrix_dir.ATAC.&lt;dataset_name&gt;"]):::none
  consensus_peak_GRanges.ATAC.muscle(["consensus_peak_GRanges.ATAC.&lt;dataset_name&gt;"]):::none --> consensus_peak_BPCells_matrix_dir.ATAC.muscle(["consensus_peak_BPCells_matrix_dir.ATAC.&lt;dataset_name&gt;"]):::none
  combined_BPCells_fragment_obj.ATAC.muscle_test(["combined_BPCells_fragment_obj.ATAC.&lt;aggregation_name&gt;"]):::none --> consensus_peak_BPCells_matrix_dir.ATAC.muscle_test(["consensus_peak_BPCells_matrix_dir.ATAC.&lt;aggregation_name&gt;"]):::none
  consensus_peak_GRanges.ATAC.muscle_test(["consensus_peak_GRanges.ATAC.&lt;aggregation_name&gt;"]):::none --> consensus_peak_BPCells_matrix_dir.ATAC.muscle_test(["consensus_peak_BPCells_matrix_dir.ATAC.&lt;aggregation_name&gt;"]):::none
  metadata_w_cell_types_tibble.GEX.muscle_test(["metadata_w_cell_types_tibble.GEX.&lt;aggregation_name&gt;"]):::none --> consensus_peak_BPCells_matrix_dir.ATAC.muscle_test(["consensus_peak_BPCells_matrix_dir.ATAC.&lt;aggregation_name&gt;"]):::none
  within_clusters_collapsed_peaks_per_cluster_GRanges.ATAC.muscle["within_clusters_collapsed_peaks_per_cluster_GRanges.ATAC.&lt;dataset_name&gt;"]:::none --> consensus_peak_GRanges.ATAC.muscle(["consensus_peak_GRanges.ATAC.&lt;dataset_name&gt;"]):::none
  within_clusters_collapsed_peaks_per_cluster_GRanges.ATAC.muscle_test["within_clusters_collapsed_peaks_per_cluster_GRanges.ATAC.&lt;aggregation_name&gt;"]:::none --> consensus_peak_GRanges.ATAC.muscle_test(["consensus_peak_GRanges.ATAC.&lt;aggregation_name&gt;"]):::none
  LSI_BPCells.ATAC.muscle(["LSI_BPCells.ATAC.&lt;dataset_name&gt;"]):::none --> harmony_embeddings_matrix.ATAC.muscle(["harmony_embeddings_matrix.ATAC.&lt;dataset_name&gt;"]):::none
  LSI_BPCells.ATAC.muscle_test(["LSI_BPCells.ATAC.&lt;aggregation_name&gt;"]):::none --> harmony_embeddings_matrix.ATAC.muscle_test(["harmony_embeddings_matrix.ATAC.&lt;aggregation_name&gt;"]):::none
  TF_motif_matrix_list(["TF_motif_matrix_list"]):::none --> JASPAR_motif_family_members_tibble(["JASPAR_motif_family_members_tibble"]):::none
  JASPAR2024_vertebrate_motif_families_tsv(["JASPAR2024_vertebrate_motif_families_tsv"]):::none --> JASPAR_motif_family_members_tibble(["JASPAR_motif_family_members_tibble"]):::none
  harmony_embeddings_matrix.ATAC.muscle(["harmony_embeddings_matrix.ATAC.&lt;dataset_name&gt;"]):::none --> LSI_clusters.ATAC.muscle(["LSI_clusters.ATAC.&lt;dataset_name&gt;"]):::none
  harmony_embeddings_matrix.ATAC.muscle_test(["harmony_embeddings_matrix.ATAC.&lt;aggregation_name&gt;"]):::none --> LSI_clusters.ATAC.muscle_test(["LSI_clusters.ATAC.&lt;aggregation_name&gt;"]):::none
  scDblFinder_results_df.ATAC.muscle(["scDblFinder_results_df.ATAC.&lt;dataset_name&gt;"]):::none --> metadata_w_cell_types_tibble.ATAC.muscle(["metadata_w_cell_types_tibble.ATAC.&lt;dataset_name&gt;"]):::none
  scDblFinder_results_df.ATAC.muscle_test(["scDblFinder_results_df.ATAC.&lt;aggregation_name&gt;"]):::none --> metadata_w_cell_types_tibble.ATAC.muscle_test(["metadata_w_cell_types_tibble.ATAC.&lt;aggregation_name&gt;"]):::none
  JASPAR_motif_family_members_tibble(["JASPAR_motif_family_members_tibble"]):::none --> peak_TF_motif_family_matrix.ATAC.muscle(["peak_TF_motif_family_matrix.ATAC.&lt;dataset_name&gt;"]):::none
  peak_TF_motif_matrix.ATAC.muscle(["peak_TF_motif_matrix.ATAC.&lt;dataset_name&gt;"]):::none --> peak_TF_motif_family_matrix.ATAC.muscle(["peak_TF_motif_family_matrix.ATAC.&lt;dataset_name&gt;"]):::none
  JASPAR_motif_family_members_tibble(["JASPAR_motif_family_members_tibble"]):::none --> peak_TF_motif_family_matrix.ATAC.muscle_test(["peak_TF_motif_family_matrix.ATAC.&lt;aggregation_name&gt;"]):::none
  peak_TF_motif_matrix.ATAC.muscle_test(["peak_TF_motif_matrix.ATAC.&lt;aggregation_name&gt;"]):::none --> peak_TF_motif_family_matrix.ATAC.muscle_test(["peak_TF_motif_family_matrix.ATAC.&lt;aggregation_name&gt;"]):::none
  TF_motif_matrix_list(["TF_motif_matrix_list"]):::none --> peak_TF_motif_matrix.ATAC.muscle(["peak_TF_motif_matrix.ATAC.&lt;dataset_name&gt;"]):::none
  consensus_peak_GRanges.ATAC.muscle(["consensus_peak_GRanges.ATAC.&lt;dataset_name&gt;"]):::none --> peak_TF_motif_matrix.ATAC.muscle(["peak_TF_motif_matrix.ATAC.&lt;dataset_name&gt;"]):::none
  TF_motif_matrix_list(["TF_motif_matrix_list"]):::none --> peak_TF_motif_matrix.ATAC.muscle_test(["peak_TF_motif_matrix.ATAC.&lt;aggregation_name&gt;"]):::none
  consensus_peak_GRanges.ATAC.muscle_test(["consensus_peak_GRanges.ATAC.&lt;aggregation_name&gt;"]):::none --> peak_TF_motif_matrix.ATAC.muscle_test(["peak_TF_motif_matrix.ATAC.&lt;aggregation_name&gt;"]):::none
  combined_BPCells_fragment_obj.ATAC.muscle(["combined_BPCells_fragment_obj.ATAC.&lt;dataset_name&gt;"]):::none --> peaks_per_cluster_narrowPeaks.peaks.ATAC.muscle["peaks_per_cluster_narrowPeaks.peaks.ATAC.&lt;dataset_name&gt;"]:::none
  combined_BPCells_fragment_obj.ATAC.muscle_test(["combined_BPCells_fragment_obj.ATAC.&lt;aggregation_name&gt;"]):::none --> peaks_per_cluster_narrowPeaks.peaks.ATAC.muscle_test["peaks_per_cluster_narrowPeaks.peaks.ATAC.&lt;aggregation_name&gt;"]:::none
  harmony_embeddings_matrix.ATAC.muscle(["harmony_embeddings_matrix.ATAC.&lt;dataset_name&gt;"]):::none --> UMAP_embeddings_tibble.ATAC.muscle(["UMAP_embeddings_tibble.ATAC.&lt;dataset_name&gt;"]):::none
  harmony_embeddings_matrix.ATAC.muscle_test(["harmony_embeddings_matrix.ATAC.&lt;aggregation_name&gt;"]):::none --> UMAP_embeddings_tibble.ATAC.muscle_test(["UMAP_embeddings_tibble.ATAC.&lt;aggregation_name&gt;"]):::none
  metadata_w_cell_types_tibble.GEX.muscle(["metadata_w_cell_types_tibble.GEX.&lt;dataset_name&gt;"]):::none --> peaks_per_cluster_narrowPeaks.peaks.ATAC.muscle["peaks_per_cluster_narrowPeaks.peaks.ATAC.&lt;dataset_name&gt;"]:::none
  metadata_w_cell_types_tibble.GEX.muscle_test(["metadata_w_cell_types_tibble.GEX.&lt;aggregation_name&gt;"]):::none --> peaks_per_cluster_narrowPeaks.peaks.ATAC.muscle_test["peaks_per_cluster_narrowPeaks.peaks.ATAC.&lt;aggregation_name&gt;"]:::none
  chromVAR_obj.ATAC.muscle(["chromVAR_obj.ATAC.&lt;dataset_name&gt;"]):::none --> motif_family_accessibility_BPCells_matrix_dir.ATAC.muscle(["motif_family_accessibility_BPCells_matrix_dir.ATAC.&lt;dataset_name&gt;"]):::none
  chromVAR_obj.ATAC.muscle_test(["chromVAR_obj.ATAC.&lt;aggregation_name&gt;"]):::none --> motif_family_accessibility_BPCells_matrix_dir.ATAC.muscle_test(["motif_family_accessibility_BPCells_matrix_dir.ATAC.&lt;aggregation_name&gt;"]):::none
  consensus_peak_BPCells_matrix_dir.ATAC.muscle(["consensus_peak_BPCells_matrix_dir.ATAC.&lt;dataset_name&gt;"]):::none --> chromVAR_obj.ATAC.muscle(["chromVAR_obj.ATAC.&lt;dataset_name&gt;"]):::none
  consensus_peak_BPCells_matrix_dir.ATAC.muscle(["consensus_peak_BPCells_matrix_dir.ATAC.&lt;dataset_name&gt;"]):::none --> peak_TF_motif_matrix.ATAC.muscle(["peak_TF_motif_matrix.ATAC.&lt;dataset_name&gt;"]):::none
  consensus_peak_BPCells_matrix_dir.ATAC.muscle(["consensus_peak_BPCells_matrix_dir.ATAC.&lt;dataset_name&gt;"]):::none --> LSI_BPCells.ATAC.muscle(["LSI_BPCells.ATAC.&lt;dataset_name&gt;"]):::none
  consensus_peak_BPCells_matrix_dir.ATAC.muscle(["consensus_peak_BPCells_matrix_dir.ATAC.&lt;dataset_name&gt;"]):::none --> harmony_embeddings_matrix.ATAC.muscle(["harmony_embeddings_matrix.ATAC.&lt;dataset_name&gt;"]):::none
  consensus_peak_BPCells_matrix_dir.ATAC.muscle(["consensus_peak_BPCells_matrix_dir.ATAC.&lt;dataset_name&gt;"]):::none --> scDblFinder_results_df.ATAC.muscle(["scDblFinder_results_df.ATAC.&lt;dataset_name&gt;"]):::none
  consensus_peak_BPCells_matrix_dir.ATAC.muscle(["consensus_peak_BPCells_matrix_dir.ATAC.&lt;dataset_name&gt;"]):::none --> metadata_w_cell_types_tibble.ATAC.muscle(["metadata_w_cell_types_tibble.ATAC.&lt;dataset_name&gt;"]):::none
  consensus_peak_BPCells_matrix_dir.ATAC.muscle_test(["consensus_peak_BPCells_matrix_dir.ATAC.&lt;aggregation_name&gt;"]):::none --> chromVAR_obj.ATAC.muscle_test(["chromVAR_obj.ATAC.&lt;aggregation_name&gt;"]):::none
  consensus_peak_BPCells_matrix_dir.ATAC.muscle_test(["consensus_peak_BPCells_matrix_dir.ATAC.&lt;aggregation_name&gt;"]):::none --> peak_TF_motif_matrix.ATAC.muscle_test(["peak_TF_motif_matrix.ATAC.&lt;aggregation_name&gt;"]):::none
  consensus_peak_BPCells_matrix_dir.ATAC.muscle_test(["consensus_peak_BPCells_matrix_dir.ATAC.&lt;aggregation_name&gt;"]):::none --> LSI_BPCells.ATAC.muscle_test(["LSI_BPCells.ATAC.&lt;aggregation_name&gt;"]):::none
  consensus_peak_BPCells_matrix_dir.ATAC.muscle_test(["consensus_peak_BPCells_matrix_dir.ATAC.&lt;aggregation_name&gt;"]):::none --> harmony_embeddings_matrix.ATAC.muscle_test(["harmony_embeddings_matrix.ATAC.&lt;aggregation_name&gt;"]):::none
  consensus_peak_BPCells_matrix_dir.ATAC.muscle_test(["consensus_peak_BPCells_matrix_dir.ATAC.&lt;aggregation_name&gt;"]):::none --> scDblFinder_results_df.ATAC.muscle_test(["scDblFinder_results_df.ATAC.&lt;aggregation_name&gt;"]):::none
  consensus_peak_BPCells_matrix_dir.ATAC.muscle_test(["consensus_peak_BPCells_matrix_dir.ATAC.&lt;aggregation_name&gt;"]):::none --> metadata_w_cell_types_tibble.ATAC.muscle_test(["metadata_w_cell_types_tibble.ATAC.&lt;aggregation_name&gt;"]):::none
  LSI_BPCells.ATAC.muscle(["LSI_BPCells.ATAC.&lt;dataset_name&gt;"]):::none --> scDblFinder_results_df.ATAC.muscle(["scDblFinder_results_df.ATAC.&lt;dataset_name&gt;"]):::none
  LSI_BPCells.ATAC.muscle_test(["LSI_BPCells.ATAC.&lt;aggregation_name&gt;"]):::none --> scDblFinder_results_df.ATAC.muscle_test(["scDblFinder_results_df.ATAC.&lt;aggregation_name&gt;"]):::none
  metadata_w_cell_types_tibble.GEX.muscle(["metadata_w_cell_types_tibble.GEX.&lt;dataset_name&gt;"]):::none --> harmony_embeddings_matrix.ATAC.muscle(["harmony_embeddings_matrix.ATAC.&lt;dataset_name&gt;"]):::none
  consensus_peak_GRanges.ATAC.muscle(["consensus_peak_GRanges.ATAC.&lt;dataset_name&gt;"]):::none --> harmony_embeddings_matrix.ATAC.muscle(["harmony_embeddings_matrix.ATAC.&lt;dataset_name&gt;"]):::none
  combined_BPCells_fragment_obj.ATAC.muscle(["combined_BPCells_fragment_obj.ATAC.&lt;dataset_name&gt;"]):::none --> harmony_embeddings_matrix.ATAC.muscle(["harmony_embeddings_matrix.ATAC.&lt;dataset_name&gt;"]):::none
  metadata_w_cell_types_tibble.GEX.muscle(["metadata_w_cell_types_tibble.GEX.&lt;dataset_name&gt;"]):::none --> metadata_w_cell_types_tibble.ATAC.muscle(["metadata_w_cell_types_tibble.ATAC.&lt;dataset_name&gt;"]):::none
  consensus_peak_GRanges.ATAC.muscle(["consensus_peak_GRanges.ATAC.&lt;dataset_name&gt;"]):::none --> metadata_w_cell_types_tibble.ATAC.muscle(["metadata_w_cell_types_tibble.ATAC.&lt;dataset_name&gt;"]):::none
  combined_BPCells_fragment_obj.ATAC.muscle(["combined_BPCells_fragment_obj.ATAC.&lt;dataset_name&gt;"]):::none --> metadata_w_cell_types_tibble.ATAC.muscle(["metadata_w_cell_types_tibble.ATAC.&lt;dataset_name&gt;"]):::none
  metadata_w_cell_types_tibble.GEX.muscle(["metadata_w_cell_types_tibble.GEX.&lt;dataset_name&gt;"]):::none --> scDblFinder_results_df.ATAC.muscle(["scDblFinder_results_df.ATAC.&lt;dataset_name&gt;"]):::none
  consensus_peak_GRanges.ATAC.muscle(["consensus_peak_GRanges.ATAC.&lt;dataset_name&gt;"]):::none --> scDblFinder_results_df.ATAC.muscle(["scDblFinder_results_df.ATAC.&lt;dataset_name&gt;"]):::none
  combined_BPCells_fragment_obj.ATAC.muscle(["combined_BPCells_fragment_obj.ATAC.&lt;dataset_name&gt;"]):::none --> scDblFinder_results_df.ATAC.muscle(["scDblFinder_results_df.ATAC.&lt;dataset_name&gt;"]):::none
  metadata_w_cell_types_tibble.GEX.muscle_test(["metadata_w_cell_types_tibble.GEX.&lt;aggregation_name&gt;"]):::none --> harmony_embeddings_matrix.ATAC.muscle_test(["harmony_embeddings_matrix.ATAC.&lt;aggregation_name&gt;"]):::none
  consensus_peak_GRanges.ATAC.muscle_test(["consensus_peak_GRanges.ATAC.&lt;aggregation_name&gt;"]):::none --> harmony_embeddings_matrix.ATAC.muscle_test(["harmony_embeddings_matrix.ATAC.&lt;aggregation_name&gt;"]):::none
  combined_BPCells_fragment_obj.ATAC.muscle_test(["combined_BPCells_fragment_obj.ATAC.&lt;aggregation_name&gt;"]):::none --> harmony_embeddings_matrix.ATAC.muscle_test(["harmony_embeddings_matrix.ATAC.&lt;aggregation_name&gt;"]):::none
  metadata_w_cell_types_tibble.GEX.muscle_test(["metadata_w_cell_types_tibble.GEX.&lt;aggregation_name&gt;"]):::none --> metadata_w_cell_types_tibble.ATAC.muscle_test(["metadata_w_cell_types_tibble.ATAC.&lt;aggregation_name&gt;"]):::none
  consensus_peak_GRanges.ATAC.muscle_test(["consensus_peak_GRanges.ATAC.&lt;aggregation_name&gt;"]):::none --> metadata_w_cell_types_tibble.ATAC.muscle_test(["metadata_w_cell_types_tibble.ATAC.&lt;aggregation_name&gt;"]):::none
  combined_BPCells_fragment_obj.ATAC.muscle_test(["combined_BPCells_fragment_obj.ATAC.&lt;aggregation_name&gt;"]):::none --> metadata_w_cell_types_tibble.ATAC.muscle_test(["metadata_w_cell_types_tibble.ATAC.&lt;aggregation_name&gt;"]):::none
  metadata_w_cell_types_tibble.GEX.muscle_test(["metadata_w_cell_types_tibble.GEX.&lt;aggregation_name&gt;"]):::none --> scDblFinder_results_df.ATAC.muscle_test(["scDblFinder_results_df.ATAC.&lt;aggregation_name&gt;"]):::none
  consensus_peak_GRanges.ATAC.muscle_test(["consensus_peak_GRanges.ATAC.&lt;aggregation_name&gt;"]):::none --> scDblFinder_results_df.ATAC.muscle_test(["scDblFinder_results_df.ATAC.&lt;aggregation_name&gt;"]):::none
  combined_BPCells_fragment_obj.ATAC.muscle_test(["combined_BPCells_fragment_obj.ATAC.&lt;aggregation_name&gt;"]):::none --> scDblFinder_results_df.ATAC.muscle_test(["scDblFinder_results_df.ATAC.&lt;aggregation_name&gt;"]):::none
  UCell_GEX_marker_genes_list.muscle(["UCell_GEX_marker_genes_list.&lt;dataset_name&gt;"]):::none --> metadata_w_cell_types_tibble.ATAC.muscle(["metadata_w_cell_types_tibble.ATAC.&lt;dataset_name&gt;"]):::none
  LSI_clusters.ATAC.muscle(["LSI_clusters.ATAC.&lt;dataset_name&gt;"]):::none --> metadata_w_cell_types_tibble.ATAC.muscle(["metadata_w_cell_types_tibble.ATAC.&lt;dataset_name&gt;"]):::none
  UMAP_embeddings_tibble.ATAC.muscle(["UMAP_embeddings_tibble.ATAC.&lt;dataset_name&gt;"]):::none --> metadata_w_cell_types_tibble.ATAC.muscle(["metadata_w_cell_types_tibble.ATAC.&lt;dataset_name&gt;"]):::none
  UCell_GEX_marker_genes_list.muscle(["UCell_GEX_marker_genes_list.&lt;dataset_name&gt;"]):::none --> scDblFinder_results_df.ATAC.muscle(["scDblFinder_results_df.ATAC.&lt;dataset_name&gt;"]):::none
  LSI_clusters.ATAC.muscle(["LSI_clusters.ATAC.&lt;dataset_name&gt;"]):::none --> scDblFinder_results_df.ATAC.muscle(["scDblFinder_results_df.ATAC.&lt;dataset_name&gt;"]):::none
  UMAP_embeddings_tibble.ATAC.muscle(["UMAP_embeddings_tibble.ATAC.&lt;dataset_name&gt;"]):::none --> scDblFinder_results_df.ATAC.muscle(["scDblFinder_results_df.ATAC.&lt;dataset_name&gt;"]):::none
  UCell_GEX_marker_genes_list.muscle_test(["UCell_GEX_marker_genes_list.&lt;aggregation_name&gt;"]):::none --> metadata_w_cell_types_tibble.ATAC.muscle_test(["metadata_w_cell_types_tibble.ATAC.&lt;aggregation_name&gt;"]):::none
  LSI_clusters.ATAC.muscle_test(["LSI_clusters.ATAC.&lt;aggregation_name&gt;"]):::none --> metadata_w_cell_types_tibble.ATAC.muscle_test(["metadata_w_cell_types_tibble.ATAC.&lt;aggregation_name&gt;"]):::none
  UMAP_embeddings_tibble.ATAC.muscle_test(["UMAP_embeddings_tibble.ATAC.&lt;aggregation_name&gt;"]):::none --> metadata_w_cell_types_tibble.ATAC.muscle_test(["metadata_w_cell_types_tibble.ATAC.&lt;aggregation_name&gt;"]):::none
  UCell_GEX_marker_genes_list.muscle_test(["UCell_GEX_marker_genes_list.&lt;aggregation_name&gt;"]):::none --> scDblFinder_results_df.ATAC.muscle_test(["scDblFinder_results_df.ATAC.&lt;aggregation_name&gt;"]):::none
  LSI_clusters.ATAC.muscle_test(["LSI_clusters.ATAC.&lt;aggregation_name&gt;"]):::none --> scDblFinder_results_df.ATAC.muscle_test(["scDblFinder_results_df.ATAC.&lt;aggregation_name&gt;"]):::none
  UMAP_embeddings_tibble.ATAC.muscle_test(["UMAP_embeddings_tibble.ATAC.&lt;aggregation_name&gt;"]):::none --> scDblFinder_results_df.ATAC.muscle_test(["scDblFinder_results_df.ATAC.&lt;aggregation_name&gt;"]):::none
  UCell_GEX_marker_genes_list.muscle(["UCell_GEX_marker_genes_list.&lt;dataset_name&gt;"]):::none --> metadata_w_cell_types_tibble.GEX.muscle(["metadata_w_cell_types_tibble.GEX.&lt;dataset_name&gt;"]):::none
  UCell_GEX_marker_genes_list.muscle_test(["UCell_GEX_marker_genes_list.&lt;aggregation_name&gt;"]):::none --> metadata_w_cell_types_tibble.GEX.muscle_test(["metadata_w_cell_types_tibble.GEX.&lt;aggregation_name&gt;"]):::none
  metadata_w_cell_types_tibble.GEX.muscle(["metadata_w_cell_types_tibble.GEX.&lt;dataset_name&gt;"]):::none --> LSI_BPCells.ATAC.muscle(["LSI_BPCells.ATAC.&lt;dataset_name&gt;"]):::none
  consensus_peak_GRanges.ATAC.muscle(["consensus_peak_GRanges.ATAC.&lt;dataset_name&gt;"]):::none --> LSI_BPCells.ATAC.muscle(["LSI_BPCells.ATAC.&lt;dataset_name&gt;"]):::none
  combined_BPCells_fragment_obj.ATAC.muscle(["combined_BPCells_fragment_obj.ATAC.&lt;dataset_name&gt;"]):::none --> LSI_BPCells.ATAC.muscle(["LSI_BPCells.ATAC.&lt;dataset_name&gt;"]):::none
  metadata_w_cell_types_tibble.GEX.muscle_test(["metadata_w_cell_types_tibble.GEX.&lt;aggregation_name&gt;"]):::none --> LSI_BPCells.ATAC.muscle_test(["LSI_BPCells.ATAC.&lt;aggregation_name&gt;"]):::none
  consensus_peak_GRanges.ATAC.muscle_test(["consensus_peak_GRanges.ATAC.&lt;aggregation_name&gt;"]):::none --> LSI_BPCells.ATAC.muscle_test(["LSI_BPCells.ATAC.&lt;aggregation_name&gt;"]):::none
  combined_BPCells_fragment_obj.ATAC.muscle_test(["combined_BPCells_fragment_obj.ATAC.&lt;aggregation_name&gt;"]):::none --> LSI_BPCells.ATAC.muscle_test(["LSI_BPCells.ATAC.&lt;aggregation_name&gt;"]):::none
  chromVAR_TF_motif_family_matrix.ATAC.muscle(["chromVAR_TF_motif_family_matrix.ATAC.&lt;dataset_name&gt;"]):::none --> motif_family_accessibility_BPCells_matrix_dir.ATAC.muscle(["motif_family_accessibility_BPCells_matrix_dir.ATAC.&lt;dataset_name&gt;"]):::none
  chromVAR_TF_motif_family_matrix.ATAC.muscle_test(["chromVAR_TF_motif_family_matrix.ATAC.&lt;aggregation_name&gt;"]):::none --> motif_family_accessibility_BPCells_matrix_dir.ATAC.muscle_test(["motif_family_accessibility_BPCells_matrix_dir.ATAC.&lt;aggregation_name&gt;"]):::none
  metadata_w_cell_types_tibble.GEX.muscle(["metadata_w_cell_types_tibble.GEX.&lt;dataset_name&gt;"]):::none --> within_clusters_collapsed_peaks_per_cluster_GRanges.ATAC.muscle["within_clusters_collapsed_peaks_per_cluster_GRanges.ATAC.&lt;dataset_name&gt;"]:::none
  metadata_w_cell_types_tibble.GEX.muscle_test(["metadata_w_cell_types_tibble.GEX.&lt;aggregation_name&gt;"]):::none --> within_clusters_collapsed_peaks_per_cluster_GRanges.ATAC.muscle_test["within_clusters_collapsed_peaks_per_cluster_GRanges.ATAC.&lt;aggregation_name&gt;"]:::none
  peaks_per_cluster_narrowPeaks.peaks.ATAC.muscle["peaks_per_cluster_narrowPeaks.peaks.ATAC.&lt;dataset_name&gt;"]:::none --> within_clusters_collapsed_peaks_per_cluster_GRanges.ATAC.muscle["within_clusters_collapsed_peaks_per_cluster_GRanges.ATAC.&lt;dataset_name&gt;"]:::none
  peaks_per_cluster_narrowPeaks.peaks.ATAC.muscle_test["peaks_per_cluster_narrowPeaks.peaks.ATAC.&lt;aggregation_name&gt;"]:::none --> within_clusters_collapsed_peaks_per_cluster_GRanges.ATAC.muscle_test["within_clusters_collapsed_peaks_per_cluster_GRanges.ATAC.&lt;aggregation_name&gt;"]:::none
