%%{init: {'flowchart': {'defaultRenderer': 'elk'}}}%%
flowchart TB
    consensus_peak_GRanges.ATAC.brain_mouse(["consensus_peak_GRanges.ATAC.brain_mouse"]):::none --> chromVAR_obj.ATAC.brain_mouse(["chromVAR_obj.ATAC.brain_mouse"]):::none
    metadata_w_cell_types_tibble.ATAC.brain_mouse(["metadata_w_cell_types_tibble.ATAC.brain_mouse"]):::none --> chromVAR_obj.ATAC.brain_mouse(["chromVAR_obj.ATAC.brain_mouse"]):::none
    combined_BPCells_fragment_obj.ATAC.brain_mouse(["combined_BPCells_fragment_obj.ATAC.brain_mouse"]):::none --> consensus_peak_BPCells_matrix_dir.ATAC.brain_mouse(["consensus_peak_BPCells_matrix_dir.ATAC.brain_mouse"]):::none
    metadata_w_cell_types_tibble.GEX.brain_mouse(["metadata_w_cell_types_tibble.GEX.brain_mouse"]):::none --> consensus_peak_BPCells_matrix_dir.ATAC.brain_mouse(["consensus_peak_BPCells_matrix_dir.ATAC.brain_mouse"]):::none
    consensus_peak_GRanges.ATAC.brain_mouse(["consensus_peak_GRanges.ATAC.brain_mouse"]):::none --> consensus_peak_BPCells_matrix_dir.ATAC.brain_mouse(["consensus_peak_BPCells_matrix_dir.ATAC.brain_mouse"]):::none
    within_clusters_collapsed_peaks_per_cluster_GRanges.ATAC.brain_mouse["within_clusters_collapsed_peaks_per_cluster_GRanges.ATAC.brain_mouse"]:::none --> consensus_peak_GRanges.ATAC.brain_mouse(["consensus_peak_GRanges.ATAC.brain_mouse"]):::none
    LSI_BPCells.ATAC.brain_mouse(["LSI_BPCells.ATAC.brain_mouse"]):::none --> harmony_embeddings_matrix.ATAC.brain_mouse(["harmony_embeddings_matrix.ATAC.brain_mouse"]):::none
    harmony_embeddings_matrix.ATAC.brain_mouse(["harmony_embeddings_matrix.ATAC.brain_mouse"]):::none --> LSI_clusters.ATAC.brain_mouse(["LSI_clusters.ATAC.brain_mouse"]):::none
    scDblFinder_results_df.ATAC.brain_mouse(["scDblFinder_results_df.ATAC.brain_mouse"]):::none --> metadata_w_cell_types_tibble.ATAC.brain_mouse(["metadata_w_cell_types_tibble.ATAC.brain_mouse"]):::none
    ATAC_marker_TFs_list.brain_mouse(["ATAC_marker_TFs_list.brain_mouse"]):::none --> peak_TF_motif_matrix.ATAC.brain_mouse(["peak_TF_motif_matrix.ATAC.brain_mouse"]):::none
    consensus_peak_GRanges.ATAC.brain_mouse(["consensus_peak_GRanges.ATAC.brain_mouse"]):::none --> peak_TF_motif_matrix.ATAC.brain_mouse(["peak_TF_motif_matrix.ATAC.brain_mouse"]):::none
    combined_BPCells_fragment_obj.ATAC.brain_mouse(["combined_BPCells_fragment_obj.ATAC.brain_mouse"]):::none --> peaks_per_cluster_narrowPeaks.peaks.ATAC.brain_mouse["peaks_per_cluster_narrowPeaks.peaks.ATAC.brain_mouse"]:::none
    harmony_embeddings_matrix.ATAC.brain_mouse(["harmony_embeddings_matrix.ATAC.brain_mouse"]):::none --> UMAP_embeddings_tibble.ATAC.brain_mouse(["UMAP_embeddings_tibble.ATAC.brain_mouse"]):::none
    ATAC_marker_TFs_list.brain_mouse(["ATAC_marker_TFs_list.brain_mouse"]):::none --> TF_activity_BPCells_matrix_dir.ATAC.brain_mouse(["TF_activity_BPCells_matrix_dir.ATAC.brain_mouse"]):::none
    LSI_BPCells.ATAC.brain_mouse(["LSI_BPCells.ATAC.brain_mouse"]):::none --> scDblFinder_results_df.ATAC.brain_mouse(["scDblFinder_results_df.ATAC.brain_mouse"]):::none
    LSI_clusters.ATAC.brain_mouse(["LSI_clusters.ATAC.brain_mouse"]):::none --> metadata_w_cell_types_tibble.ATAC.brain_mouse(["metadata_w_cell_types_tibble.ATAC.brain_mouse"]):::none
    LSI_clusters.ATAC.brain_mouse(["LSI_clusters.ATAC.brain_mouse"]):::none --> scDblFinder_results_df.ATAC.brain_mouse(["scDblFinder_results_df.ATAC.brain_mouse"]):::none
    UMAP_embeddings_tibble.ATAC.brain_mouse(["UMAP_embeddings_tibble.ATAC.brain_mouse"]):::none --> metadata_w_cell_types_tibble.ATAC.brain_mouse(["metadata_w_cell_types_tibble.ATAC.brain_mouse"]):::none
    UMAP_embeddings_tibble.ATAC.brain_mouse(["UMAP_embeddings_tibble.ATAC.brain_mouse"]):::none --> scDblFinder_results_df.ATAC.brain_mouse(["scDblFinder_results_df.ATAC.brain_mouse"]):::none
    chromVAR_obj.ATAC.brain_mouse(["chromVAR_obj.ATAC.brain_mouse"]):::none --> TF_activity_BPCells_matrix_dir.ATAC.brain_mouse(["TF_activity_BPCells_matrix_dir.ATAC.brain_mouse"]):::none
    combined_BPCells_fragment_obj.ATAC.brain_mouse(["combined_BPCells_fragment_obj.ATAC.brain_mouse"]):::none --> LSI_BPCells.ATAC.brain_mouse(["LSI_BPCells.ATAC.brain_mouse"]):::none
    combined_BPCells_fragment_obj.ATAC.brain_mouse(["combined_BPCells_fragment_obj.ATAC.brain_mouse"]):::none --> harmony_embeddings_matrix.ATAC.brain_mouse(["harmony_embeddings_matrix.ATAC.brain_mouse"]):::none
    combined_BPCells_fragment_obj.ATAC.brain_mouse(["combined_BPCells_fragment_obj.ATAC.brain_mouse"]):::none --> metadata_w_cell_types_tibble.ATAC.brain_mouse(["metadata_w_cell_types_tibble.ATAC.brain_mouse"]):::none
    combined_BPCells_fragment_obj.ATAC.brain_mouse(["combined_BPCells_fragment_obj.ATAC.brain_mouse"]):::none --> scDblFinder_results_df.ATAC.brain_mouse(["scDblFinder_results_df.ATAC.brain_mouse"]):::none
    consensus_peak_BPCells_matrix_dir.ATAC.brain_mouse(["consensus_peak_BPCells_matrix_dir.ATAC.brain_mouse"]):::none --> LSI_BPCells.ATAC.brain_mouse(["LSI_BPCells.ATAC.brain_mouse"]):::none
    consensus_peak_BPCells_matrix_dir.ATAC.brain_mouse(["consensus_peak_BPCells_matrix_dir.ATAC.brain_mouse"]):::none --> chromVAR_obj.ATAC.brain_mouse(["chromVAR_obj.ATAC.brain_mouse"]):::none
    consensus_peak_BPCells_matrix_dir.ATAC.brain_mouse(["consensus_peak_BPCells_matrix_dir.ATAC.brain_mouse"]):::none --> harmony_embeddings_matrix.ATAC.brain_mouse(["harmony_embeddings_matrix.ATAC.brain_mouse"]):::none
    consensus_peak_BPCells_matrix_dir.ATAC.brain_mouse(["consensus_peak_BPCells_matrix_dir.ATAC.brain_mouse"]):::none --> metadata_w_cell_types_tibble.ATAC.brain_mouse(["metadata_w_cell_types_tibble.ATAC.brain_mouse"]):::none
    consensus_peak_BPCells_matrix_dir.ATAC.brain_mouse(["consensus_peak_BPCells_matrix_dir.ATAC.brain_mouse"]):::none --> peak_TF_motif_matrix.ATAC.brain_mouse(["peak_TF_motif_matrix.ATAC.brain_mouse"]):::none
    consensus_peak_BPCells_matrix_dir.ATAC.brain_mouse(["consensus_peak_BPCells_matrix_dir.ATAC.brain_mouse"]):::none --> scDblFinder_results_df.ATAC.brain_mouse(["scDblFinder_results_df.ATAC.brain_mouse"]):::none
    consensus_peak_GRanges.ATAC.brain_mouse(["consensus_peak_GRanges.ATAC.brain_mouse"]):::none --> LSI_BPCells.ATAC.brain_mouse(["LSI_BPCells.ATAC.brain_mouse"]):::none
    consensus_peak_GRanges.ATAC.brain_mouse(["consensus_peak_GRanges.ATAC.brain_mouse"]):::none --> harmony_embeddings_matrix.ATAC.brain_mouse(["harmony_embeddings_matrix.ATAC.brain_mouse"]):::none
    consensus_peak_GRanges.ATAC.brain_mouse(["consensus_peak_GRanges.ATAC.brain_mouse"]):::none --> metadata_w_cell_types_tibble.ATAC.brain_mouse(["metadata_w_cell_types_tibble.ATAC.brain_mouse"]):::none
    consensus_peak_GRanges.ATAC.brain_mouse(["consensus_peak_GRanges.ATAC.brain_mouse"]):::none --> scDblFinder_results_df.ATAC.brain_mouse(["scDblFinder_results_df.ATAC.brain_mouse"]):::none
    metadata_w_cell_types_tibble.GEX.brain_mouse(["metadata_w_cell_types_tibble.GEX.brain_mouse"]):::none --> LSI_BPCells.ATAC.brain_mouse(["LSI_BPCells.ATAC.brain_mouse"]):::none
    metadata_w_cell_types_tibble.GEX.brain_mouse(["metadata_w_cell_types_tibble.GEX.brain_mouse"]):::none --> harmony_embeddings_matrix.ATAC.brain_mouse(["harmony_embeddings_matrix.ATAC.brain_mouse"]):::none
    metadata_w_cell_types_tibble.GEX.brain_mouse(["metadata_w_cell_types_tibble.GEX.brain_mouse"]):::none --> metadata_w_cell_types_tibble.ATAC.brain_mouse(["metadata_w_cell_types_tibble.ATAC.brain_mouse"]):::none
    metadata_w_cell_types_tibble.GEX.brain_mouse(["metadata_w_cell_types_tibble.GEX.brain_mouse"]):::none --> peaks_per_cluster_narrowPeaks.peaks.ATAC.brain_mouse["peaks_per_cluster_narrowPeaks.peaks.ATAC.brain_mouse"]:::none
    metadata_w_cell_types_tibble.GEX.brain_mouse(["metadata_w_cell_types_tibble.GEX.brain_mouse"]):::none --> scDblFinder_results_df.ATAC.brain_mouse(["scDblFinder_results_df.ATAC.brain_mouse"]):::none
    metadata_w_cell_types_tibble.GEX.brain_mouse(["metadata_w_cell_types_tibble.GEX.brain_mouse"]):::none --> within_clusters_collapsed_peaks_per_cluster_GRanges.ATAC.brain_mouse["within_clusters_collapsed_peaks_per_cluster_GRanges.ATAC.brain_mouse"]:::none
    peak_TF_motif_matrix.ATAC.brain_mouse(["peak_TF_motif_matrix.ATAC.brain_mouse"]):::none --> TF_activity_BPCells_matrix_dir.ATAC.brain_mouse(["TF_activity_BPCells_matrix_dir.ATAC.brain_mouse"]):::none
    peaks_per_cluster_narrowPeaks.peaks.ATAC.brain_mouse["peaks_per_cluster_narrowPeaks.peaks.ATAC.brain_mouse"]:::none --> within_clusters_collapsed_peaks_per_cluster_GRanges.ATAC.brain_mouse["within_clusters_collapsed_peaks_per_cluster_GRanges.ATAC.brain_mouse"]:::none
