%%{init: {'flowchart': {'defaultRenderer': 'elk'}}}%%
flowchart TB
  feature_matrix_fit.DCA.differential_analyses.immune_human_2x["feature_matrix_fit.DCA"]:::none --> results_tibble.DCA.differential_analyses.immune_human_2x["results_tibble.DCA"]:::none
  feature_matrix_fit.DGE.differential_analyses.immune_human_2x["feature_matrix_fit.DGE"]:::none --> results_tibble.DGE.differential_analyses.immune_human_2x["results_tibble.DGE"]:::none
  feature_matrix_fit.DTFA.differential_analyses.immune_human_2x["feature_matrix_fit.DTFA"]:::none --> results_tibble.DTFA.differential_analyses.immune_human_2x["results_tibble.DTFA"]:::none
  feature_matrix_fit.DGE.differential_analyses.immune_human_2x["feature_matrix_fit.DGE"]:::none --> results.CP_KEGG_MEDICUS.GSEA.DGE.differential_analyses.immune_human_2x["results.CP_KEGG_MEDICUS.GSEA.DGE"]:::none
  feature_matrix_fit.DGE.differential_analyses.immune_human_2x["feature_matrix_fit.DGE"]:::none --> results.CUSTOM.GSEA.DGE.differential_analyses.immune_human_2x["results.CUSTOM.GSEA.DGE"]:::none
  feature_matrix_fit.DGE.differential_analyses.immune_human_2x["feature_matrix_fit.DGE"]:::none --> results.H.GSEA.DGE.differential_analyses.immune_human_2x["results.H.GSEA.DGE"]:::none
  feature_matrix_fit.DGE.differential_analyses.immune_human_2x["feature_matrix_fit.DGE"]:::none --> results.TFT_GTRD.GSEA.DGE.differential_analyses.immune_human_2x["results.TFT_GTRD.GSEA.DGE"]:::none
  models.differential_analyses.immune_human_2x(["models"]):::none --> feature_matrix_fit.DCA.differential_analyses.immune_human_2x["feature_matrix_fit.DCA"]:::none
  models.differential_analyses.immune_human_2x(["models"]):::none --> results_tibble.DCA.differential_analyses.immune_human_2x["results_tibble.DCA"]:::none
  models.differential_analyses.immune_human_2x(["models"]):::none --> feature_matrix_fit.DGE.differential_analyses.immune_human_2x["feature_matrix_fit.DGE"]:::none
  models.differential_analyses.immune_human_2x(["models"]):::none --> results_tibble.DGE.differential_analyses.immune_human_2x["results_tibble.DGE"]:::none
  models.differential_analyses.immune_human_2x(["models"]):::none --> results.CP_KEGG_MEDICUS.GSEA.DGE.differential_analyses.immune_human_2x["results.CP_KEGG_MEDICUS.GSEA.DGE"]:::none
  models.differential_analyses.immune_human_2x(["models"]):::none --> results.CUSTOM.GSEA.DGE.differential_analyses.immune_human_2x["results.CUSTOM.GSEA.DGE"]:::none
  models.differential_analyses.immune_human_2x(["models"]):::none --> results.H.GSEA.DGE.differential_analyses.immune_human_2x["results.H.GSEA.DGE"]:::none
  models.differential_analyses.immune_human_2x(["models"]):::none --> results.TFT_GTRD.GSEA.DGE.differential_analyses.immune_human_2x["results.TFT_GTRD.GSEA.DGE"]:::none
  models.differential_analyses.immune_human_2x(["models"]):::none --> feature_matrix_fit.DTFA.differential_analyses.immune_human_2x["feature_matrix_fit.DTFA"]:::none
  models.differential_analyses.immune_human_2x(["models"]):::none --> results_tibble.DTFA.differential_analyses.immune_human_2x["results_tibble.DTFA"]:::none
  pseudobulk_counts_BPCells_matrix_dir.ATAC.immune_human_2x(["pseudobulk_counts_BPCells_matrix_dir.ATAC"]):::none --> feature_matrix_fit.DCA.differential_analyses.immune_human_2x["feature_matrix_fit.DCA"]:::none
  pseudobulk_counts_BPCells_matrix_dir.GEX.immune_human_2x(["pseudobulk_counts_BPCells_matrix_dir.GEX"]):::none --> feature_matrix_fit.DGE.differential_analyses.immune_human_2x["feature_matrix_fit.DGE"]:::none
  pseudobulk_counts_BPCells_matrix_dir.ATAC.immune_human_2x(["pseudobulk_counts_BPCells_matrix_dir.ATAC"]):::none --> feature_matrix_fit.DGE.differential_analyses.immune_human_2x["feature_matrix_fit.DGE"]:::none
  pseudobulk_activity_matrix.TFA.immune_human_2x(["pseudobulk_activity_matrix.TFA"]):::none --> feature_matrix_fit.DTFA.differential_analyses.immune_human_2x["feature_matrix_fit.DTFA"]:::none
  pseudobulk_counts_BPCells_matrix_dir.ATAC.immune_human_2x(["pseudobulk_counts_BPCells_matrix_dir.ATAC"]):::none --> feature_matrix_fit.DTFA.differential_analyses.immune_human_2x["feature_matrix_fit.DTFA"]:::none
  pseudobulk_counts_BPCells_matrix_dir.ATAC.brain_mouse(["pseudobulk_counts_BPCells_matrix_dir.ATAC"]):::none --> pseudobulk_activity_matrix.TFA.brain_mouse(["pseudobulk_activity_matrix.TFA"]):::none
  pseudobulk_counts_BPCells_matrix_dir.ATAC.immune_human_2x(["pseudobulk_counts_BPCells_matrix_dir.ATAC"]):::none --> pseudobulk_activity_matrix.TFA.immune_human_2x(["pseudobulk_activity_matrix.TFA"]):::none
  pseudobulk_counts_BPCells_matrix_dir.ATAC.PBMC_human_6x(["pseudobulk_counts_BPCells_matrix_dir.ATAC"]):::none --> pseudobulk_activity_matrix.TFA.PBMC_human_6x(["pseudobulk_activity_matrix.TFA"]):::none
  model_results.DCTC.differential_analyses.immune_human_2x(["model_results.DCTC"]):::none
  pseudobulk_counts_BPCells_matrix_dir.GEX.brain_mouse(["pseudobulk_counts_BPCells_matrix_dir.GEX"]):::none
  pseudobulk_counts_BPCells_matrix_dir.GEX.PBMC_human_6x(["pseudobulk_counts_BPCells_matrix_dir.GEX"]):::none
