%%{init: {'flowchart': {'defaultRenderer': 'elk'}}}%%
flowchart TB
    chromVAR_peak_expectation.ATAC.immune_human_2x(["chromVAR_peak_expectation.ATAC.immune_human_2x"]):::none --> chromVAR_background_bins.ATAC.immune_human_2x(["chromVAR_background_bins.ATAC.immune_human_2x"]):::none
    GWAS_chromVAR_ZScore_records.single_cell.genetic_enrichment.immune_human_2x["GWAS_chromVAR_ZScore_records.single_cell.genetic_enrichment.immune_human_2x"]:::none --> GWAS_chromVAR_summarized_ZScores_tibble.genetic_enrichment.immune_human_2x(["GWAS_chromVAR_summarized_ZScores_tibble.genetic_enrichment.immune_human_2x"]):::none
    open_targets_credible_set_dataset_path(["open_targets_credible_set_dataset_path"]):::none --> GWAS_inputs_tibble.genetic_enrichment.immune_human_2x(["GWAS_inputs_tibble.genetic_enrichment.immune_human_2x"]):::none
    GWAS_chromVAR_peak_weight_matrix.genetic_enrichment.immune_human_2x(["GWAS_chromVAR_peak_weight_matrix.genetic_enrichment.immune_human_2x"]):::none --> psbulk_GWAS_chromVAR_activity_matrix.genetic_enrichment.immune_human_2x(["psbulk_GWAS_chromVAR_activity_matrix.genetic_enrichment.immune_human_2x"]):::none
    GWAS_inputs_tibble.genetic_enrichment.immune_human_2x(["GWAS_inputs_tibble.genetic_enrichment.immune_human_2x"]):::none --> psbulk_GWAS_chromVAR_results_tibble.genetic_enrichment.immune_human_2x(["psbulk_GWAS_chromVAR_results_tibble.genetic_enrichment.immune_human_2x"]):::none
    GWAS_chromVAR_ZScore_records.single_cell.genetic_enrichment.immune_human_2x["GWAS_chromVAR_ZScore_records.single_cell.genetic_enrichment.immune_human_2x"]:::none --> SCAVENGE_TRS_tibbles.SCAVENGE.WNN_harmony_SNN.genetic_enrichment.immune_human_2x["SCAVENGE_TRS_tibbles.SCAVENGE.WNN_harmony_SNN.genetic_enrichment.immune_human_2x"]:::none
    SCAVENGE_graph_matrix.SCAVENGE.WNN_harmony_SNN.genetic_enrichment.immune_human_2x(["SCAVENGE_graph_matrix.SCAVENGE.WNN_harmony_SNN.genetic_enrichment.immune_human_2x"]):::none --> SCAVENGE_TRS_tibbles.SCAVENGE.WNN_harmony_SNN.genetic_enrichment.immune_human_2x["SCAVENGE_TRS_tibbles.SCAVENGE.WNN_harmony_SNN.genetic_enrichment.immune_human_2x"]:::none
    GWAS_inputs_tibble.genetic_enrichment.immune_human_2x(["GWAS_inputs_tibble.genetic_enrichment.immune_human_2x"]):::none --> GWAS_chromVAR_ZScore_records.single_cell.genetic_enrichment.immune_human_2x["GWAS_chromVAR_ZScore_records.single_cell.genetic_enrichment.immune_human_2x"]:::none
    GWAS_inputs_tibble.genetic_enrichment.immune_human_2x(["GWAS_inputs_tibble.genetic_enrichment.immune_human_2x"]):::none --> GWAS_chromVAR_peak_weight_matrix.genetic_enrichment.immune_human_2x(["GWAS_chromVAR_peak_weight_matrix.genetic_enrichment.immune_human_2x"]):::none
    SCAVENGE_TRS_tibbles.SCAVENGE.WNN_harmony_SNN.genetic_enrichment.immune_human_2x["SCAVENGE_TRS_tibbles.SCAVENGE.WNN_harmony_SNN.genetic_enrichment.immune_human_2x"]:::none --> SCAVENGE_TRS_summary_tibble.SCAVENGE.WNN_harmony_SNN.genetic_enrichment.immune_human_2x(["SCAVENGE_TRS_summary_tibble.SCAVENGE.WNN_harmony_SNN.genetic_enrichment.immune_human_2x"]):::none
    chromVAR_background_bins.ATAC.immune_human_2x(["chromVAR_background_bins.ATAC.immune_human_2x"]):::none --> GWAS_chromVAR_ZScore_records.single_cell.genetic_enrichment.immune_human_2x["GWAS_chromVAR_ZScore_records.single_cell.genetic_enrichment.immune_human_2x"]:::none
    chromVAR_peak_expectation.ATAC.immune_human_2x(["chromVAR_peak_expectation.ATAC.immune_human_2x"]):::none --> GWAS_chromVAR_ZScore_records.single_cell.genetic_enrichment.immune_human_2x["GWAS_chromVAR_ZScore_records.single_cell.genetic_enrichment.immune_human_2x"]:::none
    open_targets_credible_set_dataset_path(["open_targets_credible_set_dataset_path"]):::none --> GWAS_chromVAR_ZScore_records.single_cell.genetic_enrichment.immune_human_2x["GWAS_chromVAR_ZScore_records.single_cell.genetic_enrichment.immune_human_2x"]:::none
    open_targets_credible_set_dataset_path(["open_targets_credible_set_dataset_path"]):::none --> GWAS_chromVAR_peak_weight_matrix.genetic_enrichment.immune_human_2x(["GWAS_chromVAR_peak_weight_matrix.genetic_enrichment.immune_human_2x"]):::none
    psbulk_GWAS_chromVAR_activity_matrix.genetic_enrichment.immune_human_2x(["psbulk_GWAS_chromVAR_activity_matrix.genetic_enrichment.immune_human_2x"]):::none --> psbulk_GWAS_chromVAR_results_tibble.genetic_enrichment.immune_human_2x(["psbulk_GWAS_chromVAR_results_tibble.genetic_enrichment.immune_human_2x"]):::none
    psbulk_GWAS_chromVAR_models.genetic_enrichment.immune_human_2x(["psbulk_GWAS_chromVAR_models.genetic_enrichment.immune_human_2x"]):::none --> psbulk_GWAS_chromVAR_results_tibble.genetic_enrichment.immune_human_2x(["psbulk_GWAS_chromVAR_results_tibble.genetic_enrichment.immune_human_2x"]):::none
    pseudobulk_counts_BPCells_matrix_dir.ATAC.immune_human_2x(["pseudobulk_counts_BPCells_matrix_dir.ATAC.immune_human_2x"]):::none --> psbulk_GWAS_chromVAR_activity_matrix.genetic_enrichment.immune_human_2x(["psbulk_GWAS_chromVAR_activity_matrix.genetic_enrichment.immune_human_2x"]):::none
    pseudobulk_counts_BPCells_matrix_dir.ATAC.immune_human_2x(["pseudobulk_counts_BPCells_matrix_dir.ATAC.immune_human_2x"]):::none --> psbulk_GWAS_chromVAR_results_tibble.genetic_enrichment.immune_human_2x(["psbulk_GWAS_chromVAR_results_tibble.genetic_enrichment.immune_human_2x"]):::none
