%%{init: {'flowchart': {'defaultRenderer': 'elk'}}}%%
flowchart TB
  peak_TF_motif_family_matrix.ATAC.brain_mouse(["peak_TF_motif_family_matrix.ATAC.&lt;aggregation_name&gt;"]):::none --> chromVAR_TF_motif_family_matrix.ATAC.brain_mouse(["chromVAR_TF_motif_family_matrix.ATAC.&lt;aggregation_name&gt;"]):::none
  CollecTRI_human_network_csv(["CollecTRI_human_network_csv"]):::none --> CollecTRI_human_network_tibble(["CollecTRI_human_network_tibble"]):::none
  CollecTRI_human_network_tibble(["CollecTRI_human_network_tibble"]):::none --> CollecTRI_JASPAR_family_map.differential_analyses.immune_human_2x(["CollecTRI_JASPAR_family_map.&lt;module_name&gt;.&lt;aggregation_name&gt;"]):::none
  JASPAR_motif_family_members_tibble(["JASPAR_motif_family_members_tibble"]):::none --> CollecTRI_JASPAR_family_map.differential_analyses.immune_human_2x(["CollecTRI_JASPAR_family_map.&lt;module_name&gt;.&lt;aggregation_name&gt;"]):::none
  donor_id_metadata_tibble.extended.differential_analyses.immune_human_2x(["donor_id_metadata_tibble.extended.&lt;module_name&gt;.&lt;aggregation_name&gt;"]):::none --> feature_matrix_fit.DCA.differential_analyses.immune_human_2x["feature_matrix_fit.DCA.&lt;module_name&gt;.&lt;aggregation_name&gt;"]:::none
  donor_id_metadata_tibble.extended.differential_analyses.immune_human_2x(["donor_id_metadata_tibble.extended.&lt;module_name&gt;.&lt;aggregation_name&gt;"]):::none --> feature_matrix_fit.DCTA.differential_analyses.immune_human_2x["feature_matrix_fit.DCTA.&lt;module_name&gt;.&lt;aggregation_name&gt;"]:::none
  donor_id_metadata_tibble.extended.differential_analyses.immune_human_2x(["donor_id_metadata_tibble.extended.&lt;module_name&gt;.&lt;aggregation_name&gt;"]):::none --> feature_matrix_fit.DGE.differential_analyses.immune_human_2x["feature_matrix_fit.DGE.&lt;module_name&gt;.&lt;aggregation_name&gt;"]:::none
  donor_id_metadata_tibble.extended.differential_analyses.immune_human_2x(["donor_id_metadata_tibble.extended.&lt;module_name&gt;.&lt;aggregation_name&gt;"]):::none --> feature_matrix_fit.DTFA.differential_analyses.immune_human_2x["feature_matrix_fit.DTFA.&lt;module_name&gt;.&lt;aggregation_name&gt;"]:::none
  JASPAR2026_vertebrate_familial_root_motifs_tf(["JASPAR2026_vertebrate_familial_root_motifs_tf"]):::none --> JASPAR_familial_root_motif_matrix_list(["JASPAR_familial_root_motif_matrix_list"]):::none
  JASPAR_familial_root_motif_matrix_list(["JASPAR_familial_root_motif_matrix_list"]):::none --> JASPAR_motif_family_members_tibble(["JASPAR_motif_family_members_tibble"]):::none
  JASPAR2026_vertebrate_motif_families_tsv(["JASPAR2026_vertebrate_motif_families_tsv"]):::none --> JASPAR_motif_family_members_tibble(["JASPAR_motif_family_members_tibble"]):::none
  donor_id_metadata_tibble.extended.differential_analyses.immune_human_2x(["donor_id_metadata_tibble.extended.&lt;module_name&gt;.&lt;aggregation_name&gt;"]):::none --> model_results.DCTC.differential_analyses.immune_human_2x(["model_results.DCTC.&lt;module_name&gt;.&lt;aggregation_name&gt;"]):::none
  JASPAR_familial_root_motif_matrix_list(["JASPAR_familial_root_motif_matrix_list"]):::none --> peak_TF_motif_family_matrix.ATAC.brain_mouse(["peak_TF_motif_family_matrix.ATAC.&lt;aggregation_name&gt;"]):::none
  CollecTRI_human_network_tibble(["CollecTRI_human_network_tibble"]):::none --> pseudobulk_CollecTRI_TF_activity_matrix.GEX.differential_analyses.immune_human_2x(["pseudobulk_CollecTRI_TF_activity_matrix.GEX.&lt;module_name&gt;.&lt;aggregation_name&gt;"]):::none
  chromVAR_TF_motif_family_matrix.ATAC.brain_mouse(["chromVAR_TF_motif_family_matrix.ATAC.&lt;aggregation_name&gt;"]):::none --> pseudobulk_motif_family_accessibility_matrix.ATAC.brain_mouse(["pseudobulk_motif_family_accessibility_matrix.ATAC.&lt;aggregation_name&gt;"]):::none
  feature_matrix_fit.DCA.differential_analyses.immune_human_2x["feature_matrix_fit.DCA.&lt;module_name&gt;.&lt;aggregation_name&gt;"]:::none --> results_tibble.DCA.differential_analyses.immune_human_2x["results_tibble.DCA.&lt;module_name&gt;.&lt;aggregation_name&gt;"]:::none
  feature_matrix_fit.DCTA.differential_analyses.immune_human_2x["feature_matrix_fit.DCTA.&lt;module_name&gt;.&lt;aggregation_name&gt;"]:::none --> results_tibble.DCTA.differential_analyses.immune_human_2x["results_tibble.DCTA.&lt;module_name&gt;.&lt;aggregation_name&gt;"]:::none
  feature_matrix_fit.DGE.differential_analyses.immune_human_2x["feature_matrix_fit.DGE.&lt;module_name&gt;.&lt;aggregation_name&gt;"]:::none --> results_tibble.DGE.differential_analyses.immune_human_2x["results_tibble.DGE.&lt;module_name&gt;.&lt;aggregation_name&gt;"]:::none
  feature_matrix_fit.DTFA.differential_analyses.immune_human_2x["feature_matrix_fit.DTFA.&lt;module_name&gt;.&lt;aggregation_name&gt;"]:::none --> results_tibble.DTFA.differential_analyses.immune_human_2x["results_tibble.DTFA.&lt;module_name&gt;.&lt;aggregation_name&gt;"]:::none
  feature_matrix_fit.DGE.differential_analyses.immune_human_2x["feature_matrix_fit.DGE.&lt;module_name&gt;.&lt;aggregation_name&gt;"]:::none --> results.CP_REACTOME.GSEA.DGE.differential_analyses.immune_human_2x["results.CP_REACTOME.GSEA.DGE.&lt;module_name&gt;.&lt;aggregation_name&gt;"]:::none
  feature_matrix_fit.DGE.differential_analyses.immune_human_2x["feature_matrix_fit.DGE.&lt;module_name&gt;.&lt;aggregation_name&gt;"]:::none --> results.H.GSEA.DGE.differential_analyses.immune_human_2x["results.H.GSEA.DGE.&lt;module_name&gt;.&lt;aggregation_name&gt;"]:::none
  TF_activity_family_comparison_tibble.CollecTRI_DTFA.differential_analyses.immune_human_2x(["TF_activity_family_comparison_tibble.CollecTRI_DTFA.&lt;module_name&gt;.&lt;aggregation_name&gt;"]):::none --> TF_activity_concordance_tibble.CollecTRI_DTFA.differential_analyses.immune_human_2x(["TF_activity_concordance_tibble.CollecTRI_DTFA.&lt;module_name&gt;.&lt;aggregation_name&gt;"]):::none
  TF_activity_source_comparison_tibble.CollecTRI_DTFA.differential_analyses.immune_human_2x(["TF_activity_source_comparison_tibble.CollecTRI_DTFA.&lt;module_name&gt;.&lt;aggregation_name&gt;"]):::none --> TF_activity_family_comparison_tibble.CollecTRI_DTFA.differential_analyses.immune_human_2x(["TF_activity_family_comparison_tibble.CollecTRI_DTFA.&lt;module_name&gt;.&lt;aggregation_name&gt;"]):::none
  results_tibble.DTFA.differential_analyses.immune_human_2x["results_tibble.DTFA.&lt;module_name&gt;.&lt;aggregation_name&gt;"]:::none --> TF_activity_source_comparison_tibble.CollecTRI_DTFA.differential_analyses.immune_human_2x(["TF_activity_source_comparison_tibble.CollecTRI_DTFA.&lt;module_name&gt;.&lt;aggregation_name&gt;"]):::none
  CollecTRI_JASPAR_family_map.differential_analyses.immune_human_2x(["CollecTRI_JASPAR_family_map.&lt;module_name&gt;.&lt;aggregation_name&gt;"]):::none --> TF_activity_source_comparison_tibble.CollecTRI_DTFA.differential_analyses.immune_human_2x(["TF_activity_source_comparison_tibble.CollecTRI_DTFA.&lt;module_name&gt;.&lt;aggregation_name&gt;"]):::none
  results_tibble.DGE.differential_analyses.immune_human_2x["results_tibble.DGE.&lt;module_name&gt;.&lt;aggregation_name&gt;"]:::none --> TF_activity_source_comparison_tibble.CollecTRI_DTFA.differential_analyses.immune_human_2x(["TF_activity_source_comparison_tibble.CollecTRI_DTFA.&lt;module_name&gt;.&lt;aggregation_name&gt;"]):::none
  results_tibble.DCTA.differential_analyses.immune_human_2x["results_tibble.DCTA.&lt;module_name&gt;.&lt;aggregation_name&gt;"]:::none --> TF_activity_source_comparison_tibble.CollecTRI_DTFA.differential_analyses.immune_human_2x(["TF_activity_source_comparison_tibble.CollecTRI_DTFA.&lt;module_name&gt;.&lt;aggregation_name&gt;"]):::none
  models.differential_analyses.immune_human_2x(["models.&lt;module_name&gt;.&lt;aggregation_name&gt;"]):::none --> feature_matrix_fit.DCA.differential_analyses.immune_human_2x["feature_matrix_fit.DCA.&lt;module_name&gt;.&lt;aggregation_name&gt;"]:::none
  models.differential_analyses.immune_human_2x(["models.&lt;module_name&gt;.&lt;aggregation_name&gt;"]):::none --> results_tibble.DCA.differential_analyses.immune_human_2x["results_tibble.DCA.&lt;module_name&gt;.&lt;aggregation_name&gt;"]:::none
  models.differential_analyses.immune_human_2x(["models.&lt;module_name&gt;.&lt;aggregation_name&gt;"]):::none --> feature_matrix_fit.DCTA.differential_analyses.immune_human_2x["feature_matrix_fit.DCTA.&lt;module_name&gt;.&lt;aggregation_name&gt;"]:::none
  models.differential_analyses.immune_human_2x(["models.&lt;module_name&gt;.&lt;aggregation_name&gt;"]):::none --> results_tibble.DCTA.differential_analyses.immune_human_2x["results_tibble.DCTA.&lt;module_name&gt;.&lt;aggregation_name&gt;"]:::none
  models.differential_analyses.immune_human_2x(["models.&lt;module_name&gt;.&lt;aggregation_name&gt;"]):::none --> feature_matrix_fit.DGE.differential_analyses.immune_human_2x["feature_matrix_fit.DGE.&lt;module_name&gt;.&lt;aggregation_name&gt;"]:::none
  models.differential_analyses.immune_human_2x(["models.&lt;module_name&gt;.&lt;aggregation_name&gt;"]):::none --> results_tibble.DGE.differential_analyses.immune_human_2x["results_tibble.DGE.&lt;module_name&gt;.&lt;aggregation_name&gt;"]:::none
  models.differential_analyses.immune_human_2x(["models.&lt;module_name&gt;.&lt;aggregation_name&gt;"]):::none --> results.CP_REACTOME.GSEA.DGE.differential_analyses.immune_human_2x["results.CP_REACTOME.GSEA.DGE.&lt;module_name&gt;.&lt;aggregation_name&gt;"]:::none
  models.differential_analyses.immune_human_2x(["models.&lt;module_name&gt;.&lt;aggregation_name&gt;"]):::none --> results.H.GSEA.DGE.differential_analyses.immune_human_2x["results.H.GSEA.DGE.&lt;module_name&gt;.&lt;aggregation_name&gt;"]:::none
  models.differential_analyses.immune_human_2x(["models.&lt;module_name&gt;.&lt;aggregation_name&gt;"]):::none --> feature_matrix_fit.DTFA.differential_analyses.immune_human_2x["feature_matrix_fit.DTFA.&lt;module_name&gt;.&lt;aggregation_name&gt;"]:::none
  models.differential_analyses.immune_human_2x(["models.&lt;module_name&gt;.&lt;aggregation_name&gt;"]):::none --> results_tibble.DTFA.differential_analyses.immune_human_2x["results_tibble.DTFA.&lt;module_name&gt;.&lt;aggregation_name&gt;"]:::none
  pseudobulk_counts_BPCells_matrix_dir.ATAC.brain_mouse(["pseudobulk_counts_BPCells_matrix_dir.ATAC.&lt;aggregation_name&gt;"]):::none --> feature_matrix_fit.DCA.differential_analyses.immune_human_2x["feature_matrix_fit.DCA.&lt;module_name&gt;.&lt;aggregation_name&gt;"]:::none
  pseudobulk_CollecTRI_TF_activity_matrix.GEX.differential_analyses.immune_human_2x(["pseudobulk_CollecTRI_TF_activity_matrix.GEX.&lt;module_name&gt;.&lt;aggregation_name&gt;"]):::none --> feature_matrix_fit.DCTA.differential_analyses.immune_human_2x["feature_matrix_fit.DCTA.&lt;module_name&gt;.&lt;aggregation_name&gt;"]:::none
  pseudobulk_counts_BPCells_matrix_dir.ATAC.brain_mouse(["pseudobulk_counts_BPCells_matrix_dir.ATAC.&lt;aggregation_name&gt;"]):::none --> feature_matrix_fit.DCTA.differential_analyses.immune_human_2x["feature_matrix_fit.DCTA.&lt;module_name&gt;.&lt;aggregation_name&gt;"]:::none
  pseudobulk_counts_BPCells_matrix_dir.GEX.brain_mouse(["pseudobulk_counts_BPCells_matrix_dir.GEX.&lt;aggregation_name&gt;"]):::none --> feature_matrix_fit.DGE.differential_analyses.immune_human_2x["feature_matrix_fit.DGE.&lt;module_name&gt;.&lt;aggregation_name&gt;"]:::none
  pseudobulk_counts_BPCells_matrix_dir.ATAC.brain_mouse(["pseudobulk_counts_BPCells_matrix_dir.ATAC.&lt;aggregation_name&gt;"]):::none --> feature_matrix_fit.DGE.differential_analyses.immune_human_2x["feature_matrix_fit.DGE.&lt;module_name&gt;.&lt;aggregation_name&gt;"]:::none
  pseudobulk_motif_family_accessibility_matrix.ATAC.brain_mouse(["pseudobulk_motif_family_accessibility_matrix.ATAC.&lt;aggregation_name&gt;"]):::none --> feature_matrix_fit.DTFA.differential_analyses.immune_human_2x["feature_matrix_fit.DTFA.&lt;module_name&gt;.&lt;aggregation_name&gt;"]:::none
  pseudobulk_counts_BPCells_matrix_dir.ATAC.brain_mouse(["pseudobulk_counts_BPCells_matrix_dir.ATAC.&lt;aggregation_name&gt;"]):::none --> feature_matrix_fit.DTFA.differential_analyses.immune_human_2x["feature_matrix_fit.DTFA.&lt;module_name&gt;.&lt;aggregation_name&gt;"]:::none
  pseudobulk_counts_BPCells_matrix_dir.ATAC.brain_mouse(["pseudobulk_counts_BPCells_matrix_dir.ATAC.&lt;aggregation_name&gt;"]):::none --> pseudobulk_motif_family_accessibility_matrix.ATAC.brain_mouse(["pseudobulk_motif_family_accessibility_matrix.ATAC.&lt;aggregation_name&gt;"]):::none
  pseudobulk_counts_BPCells_matrix_dir.GEX.brain_mouse(["pseudobulk_counts_BPCells_matrix_dir.GEX.&lt;aggregation_name&gt;"]):::none --> pseudobulk_CollecTRI_TF_activity_matrix.GEX.differential_analyses.immune_human_2x(["pseudobulk_CollecTRI_TF_activity_matrix.GEX.&lt;module_name&gt;.&lt;aggregation_name&gt;"]):::none
