%%{init: {'flowchart': {'defaultRenderer': 'elk'}}}%%
flowchart TB
  activity_accessibility_family_comparison_tibble.CollecTRI_JASPAR.differential_analyses.ENCODE_heart_LV_6x(["activity_accessibility_family_comparison_tibble.CollecTRI_JASPAR.&lt;module_name&gt;.&lt;aggregation_name&gt;"]):::none --> activity_accessibility_concordance_tibble.CollecTRI_JASPAR.differential_analyses.ENCODE_heart_LV_6x(["activity_accessibility_concordance_tibble.CollecTRI_JASPAR.&lt;module_name&gt;.&lt;aggregation_name&gt;"]):::none
  activity_accessibility_source_comparison_tibble.CollecTRI_JASPAR.differential_analyses.ENCODE_heart_LV_6x(["activity_accessibility_source_comparison_tibble.CollecTRI_JASPAR.&lt;module_name&gt;.&lt;aggregation_name&gt;"]):::none --> activity_accessibility_family_comparison_tibble.CollecTRI_JASPAR.differential_analyses.ENCODE_heart_LV_6x(["activity_accessibility_family_comparison_tibble.CollecTRI_JASPAR.&lt;module_name&gt;.&lt;aggregation_name&gt;"]):::none
  results_tibble.gene_expression.differential_analyses.ENCODE_heart_LV_6x["results_tibble.gene_expression.&lt;module_name&gt;.&lt;aggregation_name&gt;"]:::none --> activity_accessibility_source_comparison_tibble.CollecTRI_JASPAR.differential_analyses.ENCODE_heart_LV_6x(["activity_accessibility_source_comparison_tibble.CollecTRI_JASPAR.&lt;module_name&gt;.&lt;aggregation_name&gt;"]):::none
  results_tibble.transcription_factor_activity.differential_analyses.ENCODE_heart_LV_6x["results_tibble.transcription_factor_activity.&lt;module_name&gt;.&lt;aggregation_name&gt;"]:::none --> activity_accessibility_source_comparison_tibble.CollecTRI_JASPAR.differential_analyses.ENCODE_heart_LV_6x(["activity_accessibility_source_comparison_tibble.CollecTRI_JASPAR.&lt;module_name&gt;.&lt;aggregation_name&gt;"]):::none
  CollecTRI_JASPAR_family_map.differential_analyses.ENCODE_heart_LV_6x(["CollecTRI_JASPAR_family_map.&lt;module_name&gt;.&lt;aggregation_name&gt;"]):::none --> activity_accessibility_source_comparison_tibble.CollecTRI_JASPAR.differential_analyses.ENCODE_heart_LV_6x(["activity_accessibility_source_comparison_tibble.CollecTRI_JASPAR.&lt;module_name&gt;.&lt;aggregation_name&gt;"]):::none
  results_tibble.motif_family_accessibility.differential_analyses.ENCODE_heart_LV_6x["results_tibble.motif_family_accessibility.&lt;module_name&gt;.&lt;aggregation_name&gt;"]:::none --> activity_accessibility_source_comparison_tibble.CollecTRI_JASPAR.differential_analyses.ENCODE_heart_LV_6x(["activity_accessibility_source_comparison_tibble.CollecTRI_JASPAR.&lt;module_name&gt;.&lt;aggregation_name&gt;"]):::none
  peak_TF_motif_family_matrix.ATAC.ENCODE_heart_LV_6x(["peak_TF_motif_family_matrix.ATAC.&lt;aggregation_name&gt;"]):::none --> chromVAR_TF_motif_family_matrix.ATAC.ENCODE_heart_LV_6x(["chromVAR_TF_motif_family_matrix.ATAC.&lt;aggregation_name&gt;"]):::none
  CollecTRI_human_network_csv(["CollecTRI_human_network_csv"]):::none --> CollecTRI_human_network_tibble(["CollecTRI_human_network_tibble"]):::none
  CollecTRI_human_network_tibble(["CollecTRI_human_network_tibble"]):::none --> CollecTRI_JASPAR_family_map.differential_analyses.ENCODE_heart_LV_6x(["CollecTRI_JASPAR_family_map.&lt;module_name&gt;.&lt;aggregation_name&gt;"]):::none
  JASPAR_motif_family_members_tibble(["JASPAR_motif_family_members_tibble"]):::none --> CollecTRI_JASPAR_family_map.differential_analyses.ENCODE_heart_LV_6x(["CollecTRI_JASPAR_family_map.&lt;module_name&gt;.&lt;aggregation_name&gt;"]):::none
  models.differential_analyses.ENCODE_heart_LV_6x(["models.&lt;module_name&gt;.&lt;aggregation_name&gt;"]):::none --> donor_id_metadata_tibble.analysis.differential_analyses.ENCODE_heart_LV_6x(["donor_id_metadata_tibble.analysis.&lt;module_name&gt;.&lt;aggregation_name&gt;"]):::none
  models.cell_type_composition.differential_analyses.ENCODE_heart_LV_6x(["models.cell_type_composition.&lt;module_name&gt;.&lt;aggregation_name&gt;"]):::none --> donor_id_metadata_tibble.analysis.differential_analyses.ENCODE_heart_LV_6x(["donor_id_metadata_tibble.analysis.&lt;module_name&gt;.&lt;aggregation_name&gt;"]):::none
  donor_id_metadata_tibble.extended.differential_analyses.ENCODE_heart_LV_6x(["donor_id_metadata_tibble.extended.&lt;module_name&gt;.&lt;aggregation_name&gt;"]):::none --> donor_id_metadata_tibble.analysis.differential_analyses.ENCODE_heart_LV_6x(["donor_id_metadata_tibble.analysis.&lt;module_name&gt;.&lt;aggregation_name&gt;"]):::none
  donor_id_metadata_tibble.analysis.differential_analyses.ENCODE_heart_LV_6x(["donor_id_metadata_tibble.analysis.&lt;module_name&gt;.&lt;aggregation_name&gt;"]):::none --> feature_matrix_fit.chromatin_accessibility.differential_analyses.ENCODE_heart_LV_6x["feature_matrix_fit.chromatin_accessibility.&lt;module_name&gt;.&lt;aggregation_name&gt;"]:::none
  donor_id_metadata_tibble.analysis.differential_analyses.ENCODE_heart_LV_6x(["donor_id_metadata_tibble.analysis.&lt;module_name&gt;.&lt;aggregation_name&gt;"]):::none --> feature_matrix_fit.gene_expression.differential_analyses.ENCODE_heart_LV_6x["feature_matrix_fit.gene_expression.&lt;module_name&gt;.&lt;aggregation_name&gt;"]:::none
  donor_id_metadata_tibble.analysis.differential_analyses.ENCODE_heart_LV_6x(["donor_id_metadata_tibble.analysis.&lt;module_name&gt;.&lt;aggregation_name&gt;"]):::none --> feature_matrix_fit.motif_family_accessibility.differential_analyses.ENCODE_heart_LV_6x["feature_matrix_fit.motif_family_accessibility.&lt;module_name&gt;.&lt;aggregation_name&gt;"]:::none
  donor_id_metadata_tibble.analysis.differential_analyses.ENCODE_heart_LV_6x(["donor_id_metadata_tibble.analysis.&lt;module_name&gt;.&lt;aggregation_name&gt;"]):::none --> feature_matrix_fit.transcription_factor_activity.differential_analyses.ENCODE_heart_LV_6x["feature_matrix_fit.transcription_factor_activity.&lt;module_name&gt;.&lt;aggregation_name&gt;"]:::none
  JASPAR2026_vertebrate_familial_root_motifs_tf(["JASPAR2026_vertebrate_familial_root_motifs_tf"]):::none --> JASPAR_familial_root_motif_matrix_list(["JASPAR_familial_root_motif_matrix_list"]):::none
  JASPAR2026_vertebrate_motif_families_tsv(["JASPAR2026_vertebrate_motif_families_tsv"]):::none --> JASPAR_motif_family_members_tibble(["JASPAR_motif_family_members_tibble"]):::none
  JASPAR_familial_root_motif_matrix_list(["JASPAR_familial_root_motif_matrix_list"]):::none --> JASPAR_motif_family_members_tibble(["JASPAR_motif_family_members_tibble"]):::none
  donor_id_metadata_tibble.analysis.differential_analyses.ENCODE_heart_LV_6x(["donor_id_metadata_tibble.analysis.&lt;module_name&gt;.&lt;aggregation_name&gt;"]):::none --> model_data.cell_type_composition.differential_analyses.ENCODE_heart_LV_6x["model_data.cell_type_composition.&lt;module_name&gt;.&lt;aggregation_name&gt;"]:::none
  model_data.cell_type_composition.differential_analyses.ENCODE_heart_LV_6x["model_data.cell_type_composition.&lt;module_name&gt;.&lt;aggregation_name&gt;"]:::none --> model_results.cell_type_composition.differential_analyses.ENCODE_heart_LV_6x["model_results.cell_type_composition.&lt;module_name&gt;.&lt;aggregation_name&gt;"]:::none
  JASPAR_familial_root_motif_matrix_list(["JASPAR_familial_root_motif_matrix_list"]):::none --> peak_TF_motif_family_matrix.ATAC.ENCODE_heart_LV_6x(["peak_TF_motif_family_matrix.ATAC.&lt;aggregation_name&gt;"]):::none
  CollecTRI_human_network_tibble(["CollecTRI_human_network_tibble"]):::none --> pseudobulk_CollecTRI_TF_activity_matrix.GEX.differential_analyses.ENCODE_heart_LV_6x(["pseudobulk_CollecTRI_TF_activity_matrix.GEX.&lt;module_name&gt;.&lt;aggregation_name&gt;"]):::none
  chromVAR_TF_motif_family_matrix.ATAC.ENCODE_heart_LV_6x(["chromVAR_TF_motif_family_matrix.ATAC.&lt;aggregation_name&gt;"]):::none --> pseudobulk_motif_family_accessibility_matrix.ATAC.ENCODE_heart_LV_6x(["pseudobulk_motif_family_accessibility_matrix.ATAC.&lt;aggregation_name&gt;"]):::none
  feature_matrix_fit.chromatin_accessibility.differential_analyses.ENCODE_heart_LV_6x["feature_matrix_fit.chromatin_accessibility.&lt;module_name&gt;.&lt;aggregation_name&gt;"]:::none --> results_tibble.chromatin_accessibility.differential_analyses.ENCODE_heart_LV_6x["results_tibble.chromatin_accessibility.&lt;module_name&gt;.&lt;aggregation_name&gt;"]:::none
  feature_matrix_fit.gene_expression.differential_analyses.ENCODE_heart_LV_6x["feature_matrix_fit.gene_expression.&lt;module_name&gt;.&lt;aggregation_name&gt;"]:::none --> results_tibble.gene_expression.differential_analyses.ENCODE_heart_LV_6x["results_tibble.gene_expression.&lt;module_name&gt;.&lt;aggregation_name&gt;"]:::none
  feature_matrix_fit.motif_family_accessibility.differential_analyses.ENCODE_heart_LV_6x["feature_matrix_fit.motif_family_accessibility.&lt;module_name&gt;.&lt;aggregation_name&gt;"]:::none --> results_tibble.motif_family_accessibility.differential_analyses.ENCODE_heart_LV_6x["results_tibble.motif_family_accessibility.&lt;module_name&gt;.&lt;aggregation_name&gt;"]:::none
  feature_matrix_fit.transcription_factor_activity.differential_analyses.ENCODE_heart_LV_6x["feature_matrix_fit.transcription_factor_activity.&lt;module_name&gt;.&lt;aggregation_name&gt;"]:::none --> results_tibble.transcription_factor_activity.differential_analyses.ENCODE_heart_LV_6x["results_tibble.transcription_factor_activity.&lt;module_name&gt;.&lt;aggregation_name&gt;"]:::none
  feature_matrix_fit.gene_expression.differential_analyses.ENCODE_heart_LV_6x["feature_matrix_fit.gene_expression.&lt;module_name&gt;.&lt;aggregation_name&gt;"]:::none --> results.Hallmark.gene_set_enrichment.gene_expression.differential_analyses.ENCODE_heart_LV_6x["results.Hallmark.gene_set_enrichment.gene_expression.&lt;module_name&gt;.&lt;aggregation_name&gt;"]:::none
  feature_matrix_fit.gene_expression.differential_analyses.ENCODE_heart_LV_6x["feature_matrix_fit.gene_expression.&lt;module_name&gt;.&lt;aggregation_name&gt;"]:::none --> results.Reactome.gene_set_enrichment.gene_expression.differential_analyses.ENCODE_heart_LV_6x["results.Reactome.gene_set_enrichment.gene_expression.&lt;module_name&gt;.&lt;aggregation_name&gt;"]:::none
  models.cell_type_composition.differential_analyses.ENCODE_heart_LV_6x(["models.cell_type_composition.&lt;module_name&gt;.&lt;aggregation_name&gt;"]):::none --> model_data.cell_type_composition.differential_analyses.ENCODE_heart_LV_6x["model_data.cell_type_composition.&lt;module_name&gt;.&lt;aggregation_name&gt;"]:::none
  models.cell_type_composition.differential_analyses.ENCODE_heart_LV_6x(["models.cell_type_composition.&lt;module_name&gt;.&lt;aggregation_name&gt;"]):::none --> model_results.cell_type_composition.differential_analyses.ENCODE_heart_LV_6x["model_results.cell_type_composition.&lt;module_name&gt;.&lt;aggregation_name&gt;"]:::none
  models.differential_analyses.ENCODE_heart_LV_6x(["models.&lt;module_name&gt;.&lt;aggregation_name&gt;"]):::none --> feature_matrix_fit.chromatin_accessibility.differential_analyses.ENCODE_heart_LV_6x["feature_matrix_fit.chromatin_accessibility.&lt;module_name&gt;.&lt;aggregation_name&gt;"]:::none
  models.differential_analyses.ENCODE_heart_LV_6x(["models.&lt;module_name&gt;.&lt;aggregation_name&gt;"]):::none --> results_tibble.chromatin_accessibility.differential_analyses.ENCODE_heart_LV_6x["results_tibble.chromatin_accessibility.&lt;module_name&gt;.&lt;aggregation_name&gt;"]:::none
  models.differential_analyses.ENCODE_heart_LV_6x(["models.&lt;module_name&gt;.&lt;aggregation_name&gt;"]):::none --> feature_matrix_fit.gene_expression.differential_analyses.ENCODE_heart_LV_6x["feature_matrix_fit.gene_expression.&lt;module_name&gt;.&lt;aggregation_name&gt;"]:::none
  models.differential_analyses.ENCODE_heart_LV_6x(["models.&lt;module_name&gt;.&lt;aggregation_name&gt;"]):::none --> results_tibble.gene_expression.differential_analyses.ENCODE_heart_LV_6x["results_tibble.gene_expression.&lt;module_name&gt;.&lt;aggregation_name&gt;"]:::none
  models.differential_analyses.ENCODE_heart_LV_6x(["models.&lt;module_name&gt;.&lt;aggregation_name&gt;"]):::none --> results.Hallmark.gene_set_enrichment.gene_expression.differential_analyses.ENCODE_heart_LV_6x["results.Hallmark.gene_set_enrichment.gene_expression.&lt;module_name&gt;.&lt;aggregation_name&gt;"]:::none
  models.differential_analyses.ENCODE_heart_LV_6x(["models.&lt;module_name&gt;.&lt;aggregation_name&gt;"]):::none --> results.Reactome.gene_set_enrichment.gene_expression.differential_analyses.ENCODE_heart_LV_6x["results.Reactome.gene_set_enrichment.gene_expression.&lt;module_name&gt;.&lt;aggregation_name&gt;"]:::none
  models.differential_analyses.ENCODE_heart_LV_6x(["models.&lt;module_name&gt;.&lt;aggregation_name&gt;"]):::none --> feature_matrix_fit.motif_family_accessibility.differential_analyses.ENCODE_heart_LV_6x["feature_matrix_fit.motif_family_accessibility.&lt;module_name&gt;.&lt;aggregation_name&gt;"]:::none
  models.differential_analyses.ENCODE_heart_LV_6x(["models.&lt;module_name&gt;.&lt;aggregation_name&gt;"]):::none --> results_tibble.motif_family_accessibility.differential_analyses.ENCODE_heart_LV_6x["results_tibble.motif_family_accessibility.&lt;module_name&gt;.&lt;aggregation_name&gt;"]:::none
  models.differential_analyses.ENCODE_heart_LV_6x(["models.&lt;module_name&gt;.&lt;aggregation_name&gt;"]):::none --> feature_matrix_fit.transcription_factor_activity.differential_analyses.ENCODE_heart_LV_6x["feature_matrix_fit.transcription_factor_activity.&lt;module_name&gt;.&lt;aggregation_name&gt;"]:::none
  models.differential_analyses.ENCODE_heart_LV_6x(["models.&lt;module_name&gt;.&lt;aggregation_name&gt;"]):::none --> results_tibble.transcription_factor_activity.differential_analyses.ENCODE_heart_LV_6x["results_tibble.transcription_factor_activity.&lt;module_name&gt;.&lt;aggregation_name&gt;"]:::none
  pseudobulk_counts_BPCells_matrix_dir.ATAC.ENCODE_heart_LV_6x(["pseudobulk_counts_BPCells_matrix_dir.ATAC.&lt;aggregation_name&gt;"]):::none --> feature_matrix_fit.chromatin_accessibility.differential_analyses.ENCODE_heart_LV_6x["feature_matrix_fit.chromatin_accessibility.&lt;module_name&gt;.&lt;aggregation_name&gt;"]:::none
  pseudobulk_counts_BPCells_matrix_dir.GEX.ENCODE_heart_LV_6x(["pseudobulk_counts_BPCells_matrix_dir.GEX.&lt;aggregation_name&gt;"]):::none --> feature_matrix_fit.gene_expression.differential_analyses.ENCODE_heart_LV_6x["feature_matrix_fit.gene_expression.&lt;module_name&gt;.&lt;aggregation_name&gt;"]:::none
  pseudobulk_counts_BPCells_matrix_dir.ATAC.ENCODE_heart_LV_6x(["pseudobulk_counts_BPCells_matrix_dir.ATAC.&lt;aggregation_name&gt;"]):::none --> feature_matrix_fit.gene_expression.differential_analyses.ENCODE_heart_LV_6x["feature_matrix_fit.gene_expression.&lt;module_name&gt;.&lt;aggregation_name&gt;"]:::none
  pseudobulk_motif_family_accessibility_matrix.ATAC.ENCODE_heart_LV_6x(["pseudobulk_motif_family_accessibility_matrix.ATAC.&lt;aggregation_name&gt;"]):::none --> feature_matrix_fit.motif_family_accessibility.differential_analyses.ENCODE_heart_LV_6x["feature_matrix_fit.motif_family_accessibility.&lt;module_name&gt;.&lt;aggregation_name&gt;"]:::none
  pseudobulk_counts_BPCells_matrix_dir.ATAC.ENCODE_heart_LV_6x(["pseudobulk_counts_BPCells_matrix_dir.ATAC.&lt;aggregation_name&gt;"]):::none --> feature_matrix_fit.motif_family_accessibility.differential_analyses.ENCODE_heart_LV_6x["feature_matrix_fit.motif_family_accessibility.&lt;module_name&gt;.&lt;aggregation_name&gt;"]:::none
  pseudobulk_CollecTRI_TF_activity_matrix.GEX.differential_analyses.ENCODE_heart_LV_6x(["pseudobulk_CollecTRI_TF_activity_matrix.GEX.&lt;module_name&gt;.&lt;aggregation_name&gt;"]):::none --> feature_matrix_fit.transcription_factor_activity.differential_analyses.ENCODE_heart_LV_6x["feature_matrix_fit.transcription_factor_activity.&lt;module_name&gt;.&lt;aggregation_name&gt;"]:::none
  pseudobulk_counts_BPCells_matrix_dir.ATAC.ENCODE_heart_LV_6x(["pseudobulk_counts_BPCells_matrix_dir.ATAC.&lt;aggregation_name&gt;"]):::none --> feature_matrix_fit.transcription_factor_activity.differential_analyses.ENCODE_heart_LV_6x["feature_matrix_fit.transcription_factor_activity.&lt;module_name&gt;.&lt;aggregation_name&gt;"]:::none
  pseudobulk_counts_BPCells_matrix_dir.ATAC.ENCODE_heart_LV_6x(["pseudobulk_counts_BPCells_matrix_dir.ATAC.&lt;aggregation_name&gt;"]):::none --> pseudobulk_motif_family_accessibility_matrix.ATAC.ENCODE_heart_LV_6x(["pseudobulk_motif_family_accessibility_matrix.ATAC.&lt;aggregation_name&gt;"]):::none
  pseudobulk_counts_BPCells_matrix_dir.GEX.ENCODE_heart_LV_6x(["pseudobulk_counts_BPCells_matrix_dir.GEX.&lt;aggregation_name&gt;"]):::none --> pseudobulk_CollecTRI_TF_activity_matrix.GEX.differential_analyses.ENCODE_heart_LV_6x(["pseudobulk_CollecTRI_TF_activity_matrix.GEX.&lt;module_name&gt;.&lt;aggregation_name&gt;"]):::none
