%%{init: {'flowchart': {'defaultRenderer': 'elk'}}}%%
flowchart TB
  donor_id_metadata_tibble.extended.differential_analyses.immune_human_2x(["donor_id_metadata_tibble.extended.&lt;module_name&gt;.&lt;aggregation_name&gt;"]):::none --> feature_matrix_fit.DCA.differential_analyses.immune_human_2x["feature_matrix_fit.DCA.&lt;module_name&gt;.&lt;aggregation_name&gt;"]:::none
  donor_id_metadata_tibble.extended.differential_analyses.immune_human_2x(["donor_id_metadata_tibble.extended.&lt;module_name&gt;.&lt;aggregation_name&gt;"]):::none --> feature_matrix_fit.DGE.differential_analyses.immune_human_2x["feature_matrix_fit.DGE.&lt;module_name&gt;.&lt;aggregation_name&gt;"]:::none
  donor_id_metadata_tibble.extended.differential_analyses.immune_human_2x(["donor_id_metadata_tibble.extended.&lt;module_name&gt;.&lt;aggregation_name&gt;"]):::none --> feature_matrix_fit.DTFA.differential_analyses.immune_human_2x["feature_matrix_fit.DTFA.&lt;module_name&gt;.&lt;aggregation_name&gt;"]:::none
  donor_id_metadata_tibble.extended.differential_analyses.immune_human_2x(["donor_id_metadata_tibble.extended.&lt;module_name&gt;.&lt;aggregation_name&gt;"]):::none --> model_results.DCTC.differential_analyses.immune_human_2x(["model_results.DCTC.&lt;module_name&gt;.&lt;aggregation_name&gt;"]):::none
  feature_matrix_fit.DCA.differential_analyses.immune_human_2x["feature_matrix_fit.DCA.&lt;module_name&gt;.&lt;aggregation_name&gt;"]:::none --> results_tibble.DCA.differential_analyses.immune_human_2x["results_tibble.DCA.&lt;module_name&gt;.&lt;aggregation_name&gt;"]:::none
  feature_matrix_fit.DGE.differential_analyses.immune_human_2x["feature_matrix_fit.DGE.&lt;module_name&gt;.&lt;aggregation_name&gt;"]:::none --> results_tibble.DGE.differential_analyses.immune_human_2x["results_tibble.DGE.&lt;module_name&gt;.&lt;aggregation_name&gt;"]:::none
  feature_matrix_fit.DTFA.differential_analyses.immune_human_2x["feature_matrix_fit.DTFA.&lt;module_name&gt;.&lt;aggregation_name&gt;"]:::none --> results_tibble.DTFA.differential_analyses.immune_human_2x["results_tibble.DTFA.&lt;module_name&gt;.&lt;aggregation_name&gt;"]:::none
  feature_matrix_fit.DGE.differential_analyses.immune_human_2x["feature_matrix_fit.DGE.&lt;module_name&gt;.&lt;aggregation_name&gt;"]:::none --> results.CP_KEGG_MEDICUS.GSEA.DGE.differential_analyses.immune_human_2x["results.CP_KEGG_MEDICUS.GSEA.DGE.&lt;module_name&gt;.&lt;aggregation_name&gt;"]:::none
  feature_matrix_fit.DGE.differential_analyses.immune_human_2x["feature_matrix_fit.DGE.&lt;module_name&gt;.&lt;aggregation_name&gt;"]:::none --> results.CUSTOM.GSEA.DGE.differential_analyses.immune_human_2x["results.CUSTOM.GSEA.DGE.&lt;module_name&gt;.&lt;aggregation_name&gt;"]:::none
  feature_matrix_fit.DGE.differential_analyses.immune_human_2x["feature_matrix_fit.DGE.&lt;module_name&gt;.&lt;aggregation_name&gt;"]:::none --> results.H.GSEA.DGE.differential_analyses.immune_human_2x["results.H.GSEA.DGE.&lt;module_name&gt;.&lt;aggregation_name&gt;"]:::none
  feature_matrix_fit.DGE.differential_analyses.immune_human_2x["feature_matrix_fit.DGE.&lt;module_name&gt;.&lt;aggregation_name&gt;"]:::none --> results.TFT_GTRD.GSEA.DGE.differential_analyses.immune_human_2x["results.TFT_GTRD.GSEA.DGE.&lt;module_name&gt;.&lt;aggregation_name&gt;"]:::none
  models.differential_analyses.immune_human_2x(["models.&lt;module_name&gt;.&lt;aggregation_name&gt;"]):::none --> feature_matrix_fit.DCA.differential_analyses.immune_human_2x["feature_matrix_fit.DCA.&lt;module_name&gt;.&lt;aggregation_name&gt;"]:::none
  models.differential_analyses.immune_human_2x(["models.&lt;module_name&gt;.&lt;aggregation_name&gt;"]):::none --> results_tibble.DCA.differential_analyses.immune_human_2x["results_tibble.DCA.&lt;module_name&gt;.&lt;aggregation_name&gt;"]:::none
  models.differential_analyses.immune_human_2x(["models.&lt;module_name&gt;.&lt;aggregation_name&gt;"]):::none --> feature_matrix_fit.DGE.differential_analyses.immune_human_2x["feature_matrix_fit.DGE.&lt;module_name&gt;.&lt;aggregation_name&gt;"]:::none
  models.differential_analyses.immune_human_2x(["models.&lt;module_name&gt;.&lt;aggregation_name&gt;"]):::none --> results_tibble.DGE.differential_analyses.immune_human_2x["results_tibble.DGE.&lt;module_name&gt;.&lt;aggregation_name&gt;"]:::none
  models.differential_analyses.immune_human_2x(["models.&lt;module_name&gt;.&lt;aggregation_name&gt;"]):::none --> results.CP_KEGG_MEDICUS.GSEA.DGE.differential_analyses.immune_human_2x["results.CP_KEGG_MEDICUS.GSEA.DGE.&lt;module_name&gt;.&lt;aggregation_name&gt;"]:::none
  models.differential_analyses.immune_human_2x(["models.&lt;module_name&gt;.&lt;aggregation_name&gt;"]):::none --> results.CUSTOM.GSEA.DGE.differential_analyses.immune_human_2x["results.CUSTOM.GSEA.DGE.&lt;module_name&gt;.&lt;aggregation_name&gt;"]:::none
  models.differential_analyses.immune_human_2x(["models.&lt;module_name&gt;.&lt;aggregation_name&gt;"]):::none --> results.H.GSEA.DGE.differential_analyses.immune_human_2x["results.H.GSEA.DGE.&lt;module_name&gt;.&lt;aggregation_name&gt;"]:::none
  models.differential_analyses.immune_human_2x(["models.&lt;module_name&gt;.&lt;aggregation_name&gt;"]):::none --> results.TFT_GTRD.GSEA.DGE.differential_analyses.immune_human_2x["results.TFT_GTRD.GSEA.DGE.&lt;module_name&gt;.&lt;aggregation_name&gt;"]:::none
  models.differential_analyses.immune_human_2x(["models.&lt;module_name&gt;.&lt;aggregation_name&gt;"]):::none --> feature_matrix_fit.DTFA.differential_analyses.immune_human_2x["feature_matrix_fit.DTFA.&lt;module_name&gt;.&lt;aggregation_name&gt;"]:::none
  models.differential_analyses.immune_human_2x(["models.&lt;module_name&gt;.&lt;aggregation_name&gt;"]):::none --> results_tibble.DTFA.differential_analyses.immune_human_2x["results_tibble.DTFA.&lt;module_name&gt;.&lt;aggregation_name&gt;"]:::none
  pseudobulk_counts_BPCells_matrix_dir.ATAC.brain_mouse(["pseudobulk_counts_BPCells_matrix_dir.ATAC.&lt;aggregation_name&gt;"]):::none --> feature_matrix_fit.DCA.differential_analyses.immune_human_2x["feature_matrix_fit.DCA.&lt;module_name&gt;.&lt;aggregation_name&gt;"]:::none
  pseudobulk_counts_BPCells_matrix_dir.GEX.brain_mouse(["pseudobulk_counts_BPCells_matrix_dir.GEX.&lt;aggregation_name&gt;"]):::none --> feature_matrix_fit.DGE.differential_analyses.immune_human_2x["feature_matrix_fit.DGE.&lt;module_name&gt;.&lt;aggregation_name&gt;"]:::none
  pseudobulk_counts_BPCells_matrix_dir.ATAC.brain_mouse(["pseudobulk_counts_BPCells_matrix_dir.ATAC.&lt;aggregation_name&gt;"]):::none --> feature_matrix_fit.DGE.differential_analyses.immune_human_2x["feature_matrix_fit.DGE.&lt;module_name&gt;.&lt;aggregation_name&gt;"]:::none
  pseudobulk_activity_matrix.TFA.brain_mouse(["pseudobulk_activity_matrix.TFA.&lt;aggregation_name&gt;"]):::none --> feature_matrix_fit.DTFA.differential_analyses.immune_human_2x["feature_matrix_fit.DTFA.&lt;module_name&gt;.&lt;aggregation_name&gt;"]:::none
  pseudobulk_counts_BPCells_matrix_dir.ATAC.brain_mouse(["pseudobulk_counts_BPCells_matrix_dir.ATAC.&lt;aggregation_name&gt;"]):::none --> feature_matrix_fit.DTFA.differential_analyses.immune_human_2x["feature_matrix_fit.DTFA.&lt;module_name&gt;.&lt;aggregation_name&gt;"]:::none
  pseudobulk_counts_BPCells_matrix_dir.ATAC.brain_mouse(["pseudobulk_counts_BPCells_matrix_dir.ATAC.&lt;aggregation_name&gt;"]):::none --> pseudobulk_activity_matrix.TFA.brain_mouse(["pseudobulk_activity_matrix.TFA.&lt;aggregation_name&gt;"]):::none
  models.trait_level.pseudobulk.genetic_enrichment.immune_human_2x(["models.trait_level.pseudobulk.&lt;module_name&gt;.&lt;aggregation_name&gt;"]):::none
