%%{init: {'flowchart': {'defaultRenderer': 'elk'}}}%%
flowchart TB
  WNN_results.subgroups.brain_mouse["WNN_results.subgroups.&lt;aggregation_name&gt;"]:::none --> clusters_tibble.WNN.subgroups.brain_mouse["clusters_tibble.WNN.subgroups.&lt;aggregation_name&gt;"]:::none
  harmony_embeddings_matrix.ATAC.subgroups.brain_mouse["harmony_embeddings_matrix.ATAC.subgroups.&lt;aggregation_name&gt;"]:::none --> embedding_matrices.subgroups.brain_mouse["embedding_matrices.subgroups.&lt;aggregation_name&gt;"]:::none
  metadata_tibble.subgroups.brain_mouse["metadata_tibble.subgroups.&lt;aggregation_name&gt;"]:::none --> embedding_matrices.subgroups.brain_mouse["embedding_matrices.subgroups.&lt;aggregation_name&gt;"]:::none
  harmony_embeddings_matrix.GEX.subgroups.brain_mouse["harmony_embeddings_matrix.GEX.subgroups.&lt;aggregation_name&gt;"]:::none --> embedding_matrices.subgroups.brain_mouse["embedding_matrices.subgroups.&lt;aggregation_name&gt;"]:::none
  metadata_tibble.subgroups.brain_mouse["metadata_tibble.subgroups.&lt;aggregation_name&gt;"]:::none --> harmony_embeddings_matrix.ATAC.subgroups.brain_mouse["harmony_embeddings_matrix.ATAC.subgroups.&lt;aggregation_name&gt;"]:::none
  LSI_BPCells.ATAC.subgroups.brain_mouse["LSI_BPCells.ATAC.subgroups.&lt;aggregation_name&gt;"]:::none --> harmony_embeddings_matrix.ATAC.subgroups.brain_mouse["harmony_embeddings_matrix.ATAC.subgroups.&lt;aggregation_name&gt;"]:::none
  metadata_tibble.subgroups.brain_mouse["metadata_tibble.subgroups.&lt;aggregation_name&gt;"]:::none --> harmony_embeddings_matrix.GEX.subgroups.brain_mouse["harmony_embeddings_matrix.GEX.subgroups.&lt;aggregation_name&gt;"]:::none
  PCA_BPCells.GEX.subgroups.brain_mouse["PCA_BPCells.GEX.subgroups.&lt;aggregation_name&gt;"]:::none --> harmony_embeddings_matrix.GEX.subgroups.brain_mouse["harmony_embeddings_matrix.GEX.subgroups.&lt;aggregation_name&gt;"]:::none
  metadata_tibble.subgroups.brain_mouse["metadata_tibble.subgroups.&lt;aggregation_name&gt;"]:::none --> LSI_BPCells.ATAC.subgroups.brain_mouse["LSI_BPCells.ATAC.subgroups.&lt;aggregation_name&gt;"]:::none
  harmony_embeddings_matrix.ATAC.subgroups.brain_mouse["harmony_embeddings_matrix.ATAC.subgroups.&lt;aggregation_name&gt;"]:::none --> LSI_clusters.ATAC.subgroups.brain_mouse["LSI_clusters.ATAC.subgroups.&lt;aggregation_name&gt;"]:::none
  metadata_w_clusters_tibble_filtered.subgroups.brain_mouse["metadata_w_clusters_tibble_filtered.subgroups.&lt;aggregation_name&gt;"]:::none --> marker_tibbles.subgroups.brain_mouse["marker_tibbles.subgroups.&lt;aggregation_name&gt;"]:::none
  subgroups_to_process_vec.brain_mouse(["subgroups_to_process_vec.&lt;aggregation_name&gt;"]):::none --> metadata_tibble.subgroups.brain_mouse["metadata_tibble.subgroups.&lt;aggregation_name&gt;"]:::none
  metadata_w_clusters_tibble.subgroups.brain_mouse["metadata_w_clusters_tibble.subgroups.&lt;aggregation_name&gt;"]:::none --> metadata_w_clusters_tibble_filtered.subgroups.brain_mouse["metadata_w_clusters_tibble_filtered.subgroups.&lt;aggregation_name&gt;"]:::none
  WNN_results.subgroups.brain_mouse["WNN_results.subgroups.&lt;aggregation_name&gt;"]:::none --> metadata_w_clusters_tibble.subgroups.brain_mouse["metadata_w_clusters_tibble.subgroups.&lt;aggregation_name&gt;"]:::none
  UMAP_embeddings_tibble.GEX.subgroups.brain_mouse["UMAP_embeddings_tibble.GEX.subgroups.&lt;aggregation_name&gt;"]:::none --> metadata_w_clusters_tibble.subgroups.brain_mouse["metadata_w_clusters_tibble.subgroups.&lt;aggregation_name&gt;"]:::none
  metadata_tibble.subgroups.brain_mouse["metadata_tibble.subgroups.&lt;aggregation_name&gt;"]:::none --> metadata_w_clusters_tibble.subgroups.brain_mouse["metadata_w_clusters_tibble.subgroups.&lt;aggregation_name&gt;"]:::none
  UMAP_embeddings_tibble.WNN.subgroups.brain_mouse["UMAP_embeddings_tibble.WNN.subgroups.&lt;aggregation_name&gt;"]:::none --> metadata_w_clusters_tibble.subgroups.brain_mouse["metadata_w_clusters_tibble.subgroups.&lt;aggregation_name&gt;"]:::none
  clusters_tibble.WNN.subgroups.brain_mouse["clusters_tibble.WNN.subgroups.&lt;aggregation_name&gt;"]:::none --> metadata_w_clusters_tibble.subgroups.brain_mouse["metadata_w_clusters_tibble.subgroups.&lt;aggregation_name&gt;"]:::none
  UMAP_embeddings_tibble.ATAC.subgroups.brain_mouse["UMAP_embeddings_tibble.ATAC.subgroups.&lt;aggregation_name&gt;"]:::none --> metadata_w_clusters_tibble.subgroups.brain_mouse["metadata_w_clusters_tibble.subgroups.&lt;aggregation_name&gt;"]:::none
  LSI_clusters.ATAC.subgroups.brain_mouse["LSI_clusters.ATAC.subgroups.&lt;aggregation_name&gt;"]:::none --> metadata_w_clusters_tibble.subgroups.brain_mouse["metadata_w_clusters_tibble.subgroups.&lt;aggregation_name&gt;"]:::none
  PCA_clusters.GEX.subgroups.brain_mouse["PCA_clusters.GEX.subgroups.&lt;aggregation_name&gt;"]:::none --> metadata_w_clusters_tibble.subgroups.brain_mouse["metadata_w_clusters_tibble.subgroups.&lt;aggregation_name&gt;"]:::none
  metadata_tibble.subgroups.brain_mouse["metadata_tibble.subgroups.&lt;aggregation_name&gt;"]:::none --> PCA_BPCells.GEX.subgroups.brain_mouse["PCA_BPCells.GEX.subgroups.&lt;aggregation_name&gt;"]:::none
  harmony_embeddings_matrix.GEX.subgroups.brain_mouse["harmony_embeddings_matrix.GEX.subgroups.&lt;aggregation_name&gt;"]:::none --> PCA_clusters.GEX.subgroups.brain_mouse["PCA_clusters.GEX.subgroups.&lt;aggregation_name&gt;"]:::none
  harmony_embeddings_matrix.ATAC.subgroups.brain_mouse["harmony_embeddings_matrix.ATAC.subgroups.&lt;aggregation_name&gt;"]:::none --> UMAP_embeddings_tibble.ATAC.subgroups.brain_mouse["UMAP_embeddings_tibble.ATAC.subgroups.&lt;aggregation_name&gt;"]:::none
  harmony_embeddings_matrix.GEX.subgroups.brain_mouse["harmony_embeddings_matrix.GEX.subgroups.&lt;aggregation_name&gt;"]:::none --> UMAP_embeddings_tibble.GEX.subgroups.brain_mouse["UMAP_embeddings_tibble.GEX.subgroups.&lt;aggregation_name&gt;"]:::none
  WNN_results.subgroups.brain_mouse["WNN_results.subgroups.&lt;aggregation_name&gt;"]:::none --> UMAP_embeddings_tibble.WNN.subgroups.brain_mouse["UMAP_embeddings_tibble.WNN.subgroups.&lt;aggregation_name&gt;"]:::none
  embedding_matrices.subgroups.brain_mouse["embedding_matrices.subgroups.&lt;aggregation_name&gt;"]:::none --> WNN_results.subgroups.brain_mouse["WNN_results.subgroups.&lt;aggregation_name&gt;"]:::none
