%%{init: {'flowchart': {'defaultRenderer': 'elk'}}}%%
flowchart TB
  WNN_results.subgroups.muscle["WNN_results.subgroups.&lt;dataset_name&gt;"]:::none --> clusters_tibble.WNN.subgroups.muscle["clusters_tibble.WNN.subgroups.&lt;dataset_name&gt;"]:::none
  WNN_results.subgroups.muscle_test["WNN_results.subgroups.&lt;aggregation_name&gt;"]:::none --> clusters_tibble.WNN.subgroups.muscle_test["clusters_tibble.WNN.subgroups.&lt;aggregation_name&gt;"]:::none
  harmony_embeddings_matrix.GEX.subgroups.muscle["harmony_embeddings_matrix.GEX.subgroups.&lt;dataset_name&gt;"]:::none --> embedding_matrices.subgroups.muscle["embedding_matrices.subgroups.&lt;dataset_name&gt;"]:::none
  metadata_tibble.subgroups.muscle["metadata_tibble.subgroups.&lt;dataset_name&gt;"]:::none --> embedding_matrices.subgroups.muscle["embedding_matrices.subgroups.&lt;dataset_name&gt;"]:::none
  harmony_embeddings_matrix.ATAC.subgroups.muscle["harmony_embeddings_matrix.ATAC.subgroups.&lt;dataset_name&gt;"]:::none --> embedding_matrices.subgroups.muscle["embedding_matrices.subgroups.&lt;dataset_name&gt;"]:::none
  harmony_embeddings_matrix.ATAC.subgroups.muscle_test["harmony_embeddings_matrix.ATAC.subgroups.&lt;aggregation_name&gt;"]:::none --> embedding_matrices.subgroups.muscle_test["embedding_matrices.subgroups.&lt;aggregation_name&gt;"]:::none
  metadata_tibble.subgroups.muscle_test["metadata_tibble.subgroups.&lt;aggregation_name&gt;"]:::none --> embedding_matrices.subgroups.muscle_test["embedding_matrices.subgroups.&lt;aggregation_name&gt;"]:::none
  harmony_embeddings_matrix.GEX.subgroups.muscle_test["harmony_embeddings_matrix.GEX.subgroups.&lt;aggregation_name&gt;"]:::none --> embedding_matrices.subgroups.muscle_test["embedding_matrices.subgroups.&lt;aggregation_name&gt;"]:::none
  LSI_BPCells.ATAC.subgroups.muscle["LSI_BPCells.ATAC.subgroups.&lt;dataset_name&gt;"]:::none --> harmony_embeddings_matrix.ATAC.subgroups.muscle["harmony_embeddings_matrix.ATAC.subgroups.&lt;dataset_name&gt;"]:::none
  metadata_tibble.subgroups.muscle["metadata_tibble.subgroups.&lt;dataset_name&gt;"]:::none --> harmony_embeddings_matrix.ATAC.subgroups.muscle["harmony_embeddings_matrix.ATAC.subgroups.&lt;dataset_name&gt;"]:::none
  metadata_tibble.subgroups.muscle_test["metadata_tibble.subgroups.&lt;aggregation_name&gt;"]:::none --> harmony_embeddings_matrix.ATAC.subgroups.muscle_test["harmony_embeddings_matrix.ATAC.subgroups.&lt;aggregation_name&gt;"]:::none
  LSI_BPCells.ATAC.subgroups.muscle_test["LSI_BPCells.ATAC.subgroups.&lt;aggregation_name&gt;"]:::none --> harmony_embeddings_matrix.ATAC.subgroups.muscle_test["harmony_embeddings_matrix.ATAC.subgroups.&lt;aggregation_name&gt;"]:::none
  PCA_BPCells.GEX.subgroups.muscle["PCA_BPCells.GEX.subgroups.&lt;dataset_name&gt;"]:::none --> harmony_embeddings_matrix.GEX.subgroups.muscle["harmony_embeddings_matrix.GEX.subgroups.&lt;dataset_name&gt;"]:::none
  metadata_tibble.subgroups.muscle["metadata_tibble.subgroups.&lt;dataset_name&gt;"]:::none --> harmony_embeddings_matrix.GEX.subgroups.muscle["harmony_embeddings_matrix.GEX.subgroups.&lt;dataset_name&gt;"]:::none
  PCA_BPCells.GEX.subgroups.muscle_test["PCA_BPCells.GEX.subgroups.&lt;aggregation_name&gt;"]:::none --> harmony_embeddings_matrix.GEX.subgroups.muscle_test["harmony_embeddings_matrix.GEX.subgroups.&lt;aggregation_name&gt;"]:::none
  metadata_tibble.subgroups.muscle_test["metadata_tibble.subgroups.&lt;aggregation_name&gt;"]:::none --> harmony_embeddings_matrix.GEX.subgroups.muscle_test["harmony_embeddings_matrix.GEX.subgroups.&lt;aggregation_name&gt;"]:::none
  metadata_tibble.subgroups.muscle["metadata_tibble.subgroups.&lt;dataset_name&gt;"]:::none --> LSI_BPCells.ATAC.subgroups.muscle["LSI_BPCells.ATAC.subgroups.&lt;dataset_name&gt;"]:::none
  metadata_tibble.subgroups.muscle_test["metadata_tibble.subgroups.&lt;aggregation_name&gt;"]:::none --> LSI_BPCells.ATAC.subgroups.muscle_test["LSI_BPCells.ATAC.subgroups.&lt;aggregation_name&gt;"]:::none
  harmony_embeddings_matrix.ATAC.subgroups.muscle["harmony_embeddings_matrix.ATAC.subgroups.&lt;dataset_name&gt;"]:::none --> LSI_clusters.ATAC.subgroups.muscle["LSI_clusters.ATAC.subgroups.&lt;dataset_name&gt;"]:::none
  harmony_embeddings_matrix.ATAC.subgroups.muscle_test["harmony_embeddings_matrix.ATAC.subgroups.&lt;aggregation_name&gt;"]:::none --> LSI_clusters.ATAC.subgroups.muscle_test["LSI_clusters.ATAC.subgroups.&lt;aggregation_name&gt;"]:::none
  metadata_w_clusters_tibble_filtered.subgroups.muscle["metadata_w_clusters_tibble_filtered.subgroups.&lt;dataset_name&gt;"]:::none --> marker_tibbles.subgroups.muscle["marker_tibbles.subgroups.&lt;dataset_name&gt;"]:::none
  metadata_w_clusters_tibble_filtered.subgroups.muscle_test["metadata_w_clusters_tibble_filtered.subgroups.&lt;aggregation_name&gt;"]:::none --> marker_tibbles.subgroups.muscle_test["marker_tibbles.subgroups.&lt;aggregation_name&gt;"]:::none
  subgroups_to_process_vec.muscle(["subgroups_to_process_vec.&lt;dataset_name&gt;"]):::none --> metadata_tibble.subgroups.muscle["metadata_tibble.subgroups.&lt;dataset_name&gt;"]:::none
  subgroups_to_process_vec.muscle_test(["subgroups_to_process_vec.&lt;aggregation_name&gt;"]):::none --> metadata_tibble.subgroups.muscle_test["metadata_tibble.subgroups.&lt;aggregation_name&gt;"]:::none
  metadata_w_clusters_tibble.subgroups.muscle["metadata_w_clusters_tibble.subgroups.&lt;dataset_name&gt;"]:::none --> metadata_w_clusters_tibble_filtered.subgroups.muscle["metadata_w_clusters_tibble_filtered.subgroups.&lt;dataset_name&gt;"]:::none
  metadata_w_clusters_tibble.subgroups.muscle_test["metadata_w_clusters_tibble.subgroups.&lt;aggregation_name&gt;"]:::none --> metadata_w_clusters_tibble_filtered.subgroups.muscle_test["metadata_w_clusters_tibble_filtered.subgroups.&lt;aggregation_name&gt;"]:::none
  clusters_tibble.WNN.subgroups.muscle["clusters_tibble.WNN.subgroups.&lt;dataset_name&gt;"]:::none --> metadata_w_clusters_tibble.subgroups.muscle["metadata_w_clusters_tibble.subgroups.&lt;dataset_name&gt;"]:::none
  PCA_clusters.GEX.subgroups.muscle["PCA_clusters.GEX.subgroups.&lt;dataset_name&gt;"]:::none --> metadata_w_clusters_tibble.subgroups.muscle["metadata_w_clusters_tibble.subgroups.&lt;dataset_name&gt;"]:::none
  UMAP_embeddings_tibble.WNN.subgroups.muscle["UMAP_embeddings_tibble.WNN.subgroups.&lt;dataset_name&gt;"]:::none --> metadata_w_clusters_tibble.subgroups.muscle["metadata_w_clusters_tibble.subgroups.&lt;dataset_name&gt;"]:::none
  UMAP_embeddings_tibble.GEX.subgroups.muscle["UMAP_embeddings_tibble.GEX.subgroups.&lt;dataset_name&gt;"]:::none --> metadata_w_clusters_tibble.subgroups.muscle["metadata_w_clusters_tibble.subgroups.&lt;dataset_name&gt;"]:::none
  metadata_tibble.subgroups.muscle["metadata_tibble.subgroups.&lt;dataset_name&gt;"]:::none --> metadata_w_clusters_tibble.subgroups.muscle["metadata_w_clusters_tibble.subgroups.&lt;dataset_name&gt;"]:::none
  UMAP_embeddings_tibble.ATAC.subgroups.muscle["UMAP_embeddings_tibble.ATAC.subgroups.&lt;dataset_name&gt;"]:::none --> metadata_w_clusters_tibble.subgroups.muscle["metadata_w_clusters_tibble.subgroups.&lt;dataset_name&gt;"]:::none
  LSI_clusters.ATAC.subgroups.muscle["LSI_clusters.ATAC.subgroups.&lt;dataset_name&gt;"]:::none --> metadata_w_clusters_tibble.subgroups.muscle["metadata_w_clusters_tibble.subgroups.&lt;dataset_name&gt;"]:::none
  WNN_results.subgroups.muscle["WNN_results.subgroups.&lt;dataset_name&gt;"]:::none --> metadata_w_clusters_tibble.subgroups.muscle["metadata_w_clusters_tibble.subgroups.&lt;dataset_name&gt;"]:::none
  UMAP_embeddings_tibble.GEX.subgroups.muscle_test["UMAP_embeddings_tibble.GEX.subgroups.&lt;aggregation_name&gt;"]:::none --> metadata_w_clusters_tibble.subgroups.muscle_test["metadata_w_clusters_tibble.subgroups.&lt;aggregation_name&gt;"]:::none
  clusters_tibble.WNN.subgroups.muscle_test["clusters_tibble.WNN.subgroups.&lt;aggregation_name&gt;"]:::none --> metadata_w_clusters_tibble.subgroups.muscle_test["metadata_w_clusters_tibble.subgroups.&lt;aggregation_name&gt;"]:::none
  UMAP_embeddings_tibble.WNN.subgroups.muscle_test["UMAP_embeddings_tibble.WNN.subgroups.&lt;aggregation_name&gt;"]:::none --> metadata_w_clusters_tibble.subgroups.muscle_test["metadata_w_clusters_tibble.subgroups.&lt;aggregation_name&gt;"]:::none
  WNN_results.subgroups.muscle_test["WNN_results.subgroups.&lt;aggregation_name&gt;"]:::none --> metadata_w_clusters_tibble.subgroups.muscle_test["metadata_w_clusters_tibble.subgroups.&lt;aggregation_name&gt;"]:::none
  PCA_clusters.GEX.subgroups.muscle_test["PCA_clusters.GEX.subgroups.&lt;aggregation_name&gt;"]:::none --> metadata_w_clusters_tibble.subgroups.muscle_test["metadata_w_clusters_tibble.subgroups.&lt;aggregation_name&gt;"]:::none
  UMAP_embeddings_tibble.ATAC.subgroups.muscle_test["UMAP_embeddings_tibble.ATAC.subgroups.&lt;aggregation_name&gt;"]:::none --> metadata_w_clusters_tibble.subgroups.muscle_test["metadata_w_clusters_tibble.subgroups.&lt;aggregation_name&gt;"]:::none
  LSI_clusters.ATAC.subgroups.muscle_test["LSI_clusters.ATAC.subgroups.&lt;aggregation_name&gt;"]:::none --> metadata_w_clusters_tibble.subgroups.muscle_test["metadata_w_clusters_tibble.subgroups.&lt;aggregation_name&gt;"]:::none
  metadata_tibble.subgroups.muscle_test["metadata_tibble.subgroups.&lt;aggregation_name&gt;"]:::none --> metadata_w_clusters_tibble.subgroups.muscle_test["metadata_w_clusters_tibble.subgroups.&lt;aggregation_name&gt;"]:::none
  metadata_tibble.subgroups.muscle["metadata_tibble.subgroups.&lt;dataset_name&gt;"]:::none --> PCA_BPCells.GEX.subgroups.muscle["PCA_BPCells.GEX.subgroups.&lt;dataset_name&gt;"]:::none
  metadata_tibble.subgroups.muscle_test["metadata_tibble.subgroups.&lt;aggregation_name&gt;"]:::none --> PCA_BPCells.GEX.subgroups.muscle_test["PCA_BPCells.GEX.subgroups.&lt;aggregation_name&gt;"]:::none
  harmony_embeddings_matrix.GEX.subgroups.muscle["harmony_embeddings_matrix.GEX.subgroups.&lt;dataset_name&gt;"]:::none --> PCA_clusters.GEX.subgroups.muscle["PCA_clusters.GEX.subgroups.&lt;dataset_name&gt;"]:::none
  harmony_embeddings_matrix.GEX.subgroups.muscle_test["harmony_embeddings_matrix.GEX.subgroups.&lt;aggregation_name&gt;"]:::none --> PCA_clusters.GEX.subgroups.muscle_test["PCA_clusters.GEX.subgroups.&lt;aggregation_name&gt;"]:::none
  harmony_embeddings_matrix.ATAC.subgroups.muscle["harmony_embeddings_matrix.ATAC.subgroups.&lt;dataset_name&gt;"]:::none --> UMAP_embeddings_tibble.ATAC.subgroups.muscle["UMAP_embeddings_tibble.ATAC.subgroups.&lt;dataset_name&gt;"]:::none
  harmony_embeddings_matrix.ATAC.subgroups.muscle_test["harmony_embeddings_matrix.ATAC.subgroups.&lt;aggregation_name&gt;"]:::none --> UMAP_embeddings_tibble.ATAC.subgroups.muscle_test["UMAP_embeddings_tibble.ATAC.subgroups.&lt;aggregation_name&gt;"]:::none
  harmony_embeddings_matrix.GEX.subgroups.muscle["harmony_embeddings_matrix.GEX.subgroups.&lt;dataset_name&gt;"]:::none --> UMAP_embeddings_tibble.GEX.subgroups.muscle["UMAP_embeddings_tibble.GEX.subgroups.&lt;dataset_name&gt;"]:::none
  harmony_embeddings_matrix.GEX.subgroups.muscle_test["harmony_embeddings_matrix.GEX.subgroups.&lt;aggregation_name&gt;"]:::none --> UMAP_embeddings_tibble.GEX.subgroups.muscle_test["UMAP_embeddings_tibble.GEX.subgroups.&lt;aggregation_name&gt;"]:::none
  WNN_results.subgroups.muscle["WNN_results.subgroups.&lt;dataset_name&gt;"]:::none --> UMAP_embeddings_tibble.WNN.subgroups.muscle["UMAP_embeddings_tibble.WNN.subgroups.&lt;dataset_name&gt;"]:::none
  WNN_results.subgroups.muscle_test["WNN_results.subgroups.&lt;aggregation_name&gt;"]:::none --> UMAP_embeddings_tibble.WNN.subgroups.muscle_test["UMAP_embeddings_tibble.WNN.subgroups.&lt;aggregation_name&gt;"]:::none
  embedding_matrices.subgroups.muscle["embedding_matrices.subgroups.&lt;dataset_name&gt;"]:::none --> WNN_results.subgroups.muscle["WNN_results.subgroups.&lt;dataset_name&gt;"]:::none
  embedding_matrices.subgroups.muscle_test["embedding_matrices.subgroups.&lt;aggregation_name&gt;"]:::none --> WNN_results.subgroups.muscle_test["WNN_results.subgroups.&lt;aggregation_name&gt;"]:::none
