%%{init: {'flowchart': {'defaultRenderer': 'elk'}}}%%
flowchart TB
  WNN_results.subgroups.immune_human_2x["WNN_results.subgroups.&lt;aggregation_name&gt;"]:::none --> clusters_tibble.WNN.subgroups.immune_human_2x["clusters_tibble.WNN.subgroups.&lt;aggregation_name&gt;"]:::none
  harmony_embeddings_matrix.GEX.subgroups.immune_human_2x["harmony_embeddings_matrix.GEX.subgroups.&lt;aggregation_name&gt;"]:::none --> embedding_matrices.subgroups.immune_human_2x["embedding_matrices.subgroups.&lt;aggregation_name&gt;"]:::none
  metadata_tibble.subgroups.immune_human_2x["metadata_tibble.subgroups.&lt;aggregation_name&gt;"]:::none --> embedding_matrices.subgroups.immune_human_2x["embedding_matrices.subgroups.&lt;aggregation_name&gt;"]:::none
  harmony_embeddings_matrix.ATAC.subgroups.immune_human_2x["harmony_embeddings_matrix.ATAC.subgroups.&lt;aggregation_name&gt;"]:::none --> embedding_matrices.subgroups.immune_human_2x["embedding_matrices.subgroups.&lt;aggregation_name&gt;"]:::none
  LSI_BPCells.ATAC.subgroups.immune_human_2x["LSI_BPCells.ATAC.subgroups.&lt;aggregation_name&gt;"]:::none --> harmony_embeddings_matrix.ATAC.subgroups.immune_human_2x["harmony_embeddings_matrix.ATAC.subgroups.&lt;aggregation_name&gt;"]:::none
  metadata_tibble.subgroups.immune_human_2x["metadata_tibble.subgroups.&lt;aggregation_name&gt;"]:::none --> harmony_embeddings_matrix.ATAC.subgroups.immune_human_2x["harmony_embeddings_matrix.ATAC.subgroups.&lt;aggregation_name&gt;"]:::none
  metadata_tibble.subgroups.immune_human_2x["metadata_tibble.subgroups.&lt;aggregation_name&gt;"]:::none --> harmony_embeddings_matrix.GEX.subgroups.immune_human_2x["harmony_embeddings_matrix.GEX.subgroups.&lt;aggregation_name&gt;"]:::none
  PCA_BPCells.GEX.subgroups.immune_human_2x["PCA_BPCells.GEX.subgroups.&lt;aggregation_name&gt;"]:::none --> harmony_embeddings_matrix.GEX.subgroups.immune_human_2x["harmony_embeddings_matrix.GEX.subgroups.&lt;aggregation_name&gt;"]:::none
  metadata_tibble.subgroups.immune_human_2x["metadata_tibble.subgroups.&lt;aggregation_name&gt;"]:::none --> LSI_BPCells.ATAC.subgroups.immune_human_2x["LSI_BPCells.ATAC.subgroups.&lt;aggregation_name&gt;"]:::none
  harmony_embeddings_matrix.ATAC.subgroups.immune_human_2x["harmony_embeddings_matrix.ATAC.subgroups.&lt;aggregation_name&gt;"]:::none --> LSI_clusters.ATAC.subgroups.immune_human_2x["LSI_clusters.ATAC.subgroups.&lt;aggregation_name&gt;"]:::none
  metadata_w_clusters_tibble_filtered.subgroups.immune_human_2x["metadata_w_clusters_tibble_filtered.subgroups.&lt;aggregation_name&gt;"]:::none --> marker_tibbles.subgroups.immune_human_2x["marker_tibbles.subgroups.&lt;aggregation_name&gt;"]:::none
  subgroups_to_process_vec.immune_human_2x(["subgroups_to_process_vec.&lt;aggregation_name&gt;"]):::none --> metadata_tibble.subgroups.immune_human_2x["metadata_tibble.subgroups.&lt;aggregation_name&gt;"]:::none
  metadata_w_clusters_tibble.subgroups.immune_human_2x["metadata_w_clusters_tibble.subgroups.&lt;aggregation_name&gt;"]:::none --> metadata_w_clusters_tibble_filtered.subgroups.immune_human_2x["metadata_w_clusters_tibble_filtered.subgroups.&lt;aggregation_name&gt;"]:::none
  LSI_clusters.ATAC.subgroups.immune_human_2x["LSI_clusters.ATAC.subgroups.&lt;aggregation_name&gt;"]:::none --> metadata_w_clusters_tibble.subgroups.immune_human_2x["metadata_w_clusters_tibble.subgroups.&lt;aggregation_name&gt;"]:::none
  metadata_tibble.subgroups.immune_human_2x["metadata_tibble.subgroups.&lt;aggregation_name&gt;"]:::none --> metadata_w_clusters_tibble.subgroups.immune_human_2x["metadata_w_clusters_tibble.subgroups.&lt;aggregation_name&gt;"]:::none
  PCA_clusters.GEX.subgroups.immune_human_2x["PCA_clusters.GEX.subgroups.&lt;aggregation_name&gt;"]:::none --> metadata_w_clusters_tibble.subgroups.immune_human_2x["metadata_w_clusters_tibble.subgroups.&lt;aggregation_name&gt;"]:::none
  UMAP_embeddings_tibble.ATAC.subgroups.immune_human_2x["UMAP_embeddings_tibble.ATAC.subgroups.&lt;aggregation_name&gt;"]:::none --> metadata_w_clusters_tibble.subgroups.immune_human_2x["metadata_w_clusters_tibble.subgroups.&lt;aggregation_name&gt;"]:::none
  UMAP_embeddings_tibble.WNN.subgroups.immune_human_2x["UMAP_embeddings_tibble.WNN.subgroups.&lt;aggregation_name&gt;"]:::none --> metadata_w_clusters_tibble.subgroups.immune_human_2x["metadata_w_clusters_tibble.subgroups.&lt;aggregation_name&gt;"]:::none
  UMAP_embeddings_tibble.GEX.subgroups.immune_human_2x["UMAP_embeddings_tibble.GEX.subgroups.&lt;aggregation_name&gt;"]:::none --> metadata_w_clusters_tibble.subgroups.immune_human_2x["metadata_w_clusters_tibble.subgroups.&lt;aggregation_name&gt;"]:::none
  WNN_results.subgroups.immune_human_2x["WNN_results.subgroups.&lt;aggregation_name&gt;"]:::none --> metadata_w_clusters_tibble.subgroups.immune_human_2x["metadata_w_clusters_tibble.subgroups.&lt;aggregation_name&gt;"]:::none
  clusters_tibble.WNN.subgroups.immune_human_2x["clusters_tibble.WNN.subgroups.&lt;aggregation_name&gt;"]:::none --> metadata_w_clusters_tibble.subgroups.immune_human_2x["metadata_w_clusters_tibble.subgroups.&lt;aggregation_name&gt;"]:::none
  metadata_tibble.subgroups.immune_human_2x["metadata_tibble.subgroups.&lt;aggregation_name&gt;"]:::none --> PCA_BPCells.GEX.subgroups.immune_human_2x["PCA_BPCells.GEX.subgroups.&lt;aggregation_name&gt;"]:::none
  harmony_embeddings_matrix.GEX.subgroups.immune_human_2x["harmony_embeddings_matrix.GEX.subgroups.&lt;aggregation_name&gt;"]:::none --> PCA_clusters.GEX.subgroups.immune_human_2x["PCA_clusters.GEX.subgroups.&lt;aggregation_name&gt;"]:::none
  harmony_embeddings_matrix.ATAC.subgroups.immune_human_2x["harmony_embeddings_matrix.ATAC.subgroups.&lt;aggregation_name&gt;"]:::none --> UMAP_embeddings_tibble.ATAC.subgroups.immune_human_2x["UMAP_embeddings_tibble.ATAC.subgroups.&lt;aggregation_name&gt;"]:::none
  harmony_embeddings_matrix.GEX.subgroups.immune_human_2x["harmony_embeddings_matrix.GEX.subgroups.&lt;aggregation_name&gt;"]:::none --> UMAP_embeddings_tibble.GEX.subgroups.immune_human_2x["UMAP_embeddings_tibble.GEX.subgroups.&lt;aggregation_name&gt;"]:::none
  WNN_results.subgroups.immune_human_2x["WNN_results.subgroups.&lt;aggregation_name&gt;"]:::none --> UMAP_embeddings_tibble.WNN.subgroups.immune_human_2x["UMAP_embeddings_tibble.WNN.subgroups.&lt;aggregation_name&gt;"]:::none
  embedding_matrices.subgroups.immune_human_2x["embedding_matrices.subgroups.&lt;aggregation_name&gt;"]:::none --> WNN_results.subgroups.immune_human_2x["WNN_results.subgroups.&lt;aggregation_name&gt;"]:::none
