%%{init: {'flowchart': {'defaultRenderer': 'elk'}}}%%
flowchart TB
  chromVAR_obj.ATAC.immune_human_2x(["chromVAR_obj.ATAC.immune_human_2x"]):::none --> chromVAR_background_bins.ATAC.immune_human_2x(["chromVAR_background_bins.ATAC.immune_human_2x"]):::none
  chromVAR_peak_expectation.ATAC.immune_human_2x(["chromVAR_peak_expectation.ATAC.immune_human_2x"]):::none --> chromVAR_background_bins.ATAC.immune_human_2x(["chromVAR_background_bins.ATAC.immune_human_2x"]):::none
  chromVAR_obj.ATAC.immune_human_2x(["chromVAR_obj.ATAC.immune_human_2x"]):::none --> chromVAR_peak_expectation.ATAC.immune_human_2x(["chromVAR_peak_expectation.ATAC.immune_human_2x"]):::none
  open_targets_credible_set_dataset_path(["open_targets_credible_set_dataset_path"]):::none --> GWAS_inputs_tibble.genetic_enrichment.immune_human_2x(["GWAS_inputs_tibble.genetic_enrichment.immune_human_2x"]):::none
  graph_matrix.WNN_harmony_SNN.SCAVENGE.single_nucleus.genetic_enrichment.immune_human_2x(["graph_matrix.WNN_harmony_SNN.SCAVENGE.single_nucleus.genetic_enrichment.immune_human_2x"]):::none --> TRS_tibbles.WNN_harmony_SNN.SCAVENGE.single_nucleus.genetic_enrichment.immune_human_2x["TRS_tibbles.WNN_harmony_SNN.SCAVENGE.single_nucleus.genetic_enrichment.immune_human_2x"]:::none
  chromVAR_z_score_records.single_nucleus.genetic_enrichment.immune_human_2x["chromVAR_z_score_records.single_nucleus.genetic_enrichment.immune_human_2x"]:::none --> TRS_tibbles.WNN_harmony_SNN.SCAVENGE.single_nucleus.genetic_enrichment.immune_human_2x["TRS_tibbles.WNN_harmony_SNN.SCAVENGE.single_nucleus.genetic_enrichment.immune_human_2x"]:::none
  GWAS_inputs_tibble.genetic_enrichment.immune_human_2x(["GWAS_inputs_tibble.genetic_enrichment.immune_human_2x"]):::none --> GWAS_peak_weight_records.genetic_enrichment.immune_human_2x["GWAS_peak_weight_records.genetic_enrichment.immune_human_2x"]:::none
  GWAS_peak_weight_records.genetic_enrichment.immune_human_2x["GWAS_peak_weight_records.genetic_enrichment.immune_human_2x"]:::none --> chromVAR_z_score_records.single_nucleus.genetic_enrichment.immune_human_2x["chromVAR_z_score_records.single_nucleus.genetic_enrichment.immune_human_2x"]:::none
  TRS_tibbles.WNN_harmony_SNN.SCAVENGE.single_nucleus.genetic_enrichment.immune_human_2x["TRS_tibbles.WNN_harmony_SNN.SCAVENGE.single_nucleus.genetic_enrichment.immune_human_2x"]:::none --> TRS_summary_tibble.WNN_harmony_SNN.SCAVENGE.single_nucleus.genetic_enrichment.immune_human_2x(["TRS_summary_tibble.WNN_harmony_SNN.SCAVENGE.single_nucleus.genetic_enrichment.immune_human_2x"]):::none
  chromVAR_background_bins.ATAC.immune_human_2x(["chromVAR_background_bins.ATAC.immune_human_2x"]):::none --> chromVAR_z_score_records.single_nucleus.genetic_enrichment.immune_human_2x["chromVAR_z_score_records.single_nucleus.genetic_enrichment.immune_human_2x"]:::none
  chromVAR_obj.ATAC.immune_human_2x(["chromVAR_obj.ATAC.immune_human_2x"]):::none --> GWAS_peak_weight_records.genetic_enrichment.immune_human_2x["GWAS_peak_weight_records.genetic_enrichment.immune_human_2x"]:::none
  chromVAR_obj.ATAC.immune_human_2x(["chromVAR_obj.ATAC.immune_human_2x"]):::none --> chromVAR_z_score_records.single_nucleus.genetic_enrichment.immune_human_2x["chromVAR_z_score_records.single_nucleus.genetic_enrichment.immune_human_2x"]:::none
  chromVAR_peak_expectation.ATAC.immune_human_2x(["chromVAR_peak_expectation.ATAC.immune_human_2x"]):::none --> chromVAR_z_score_records.single_nucleus.genetic_enrichment.immune_human_2x["chromVAR_z_score_records.single_nucleus.genetic_enrichment.immune_human_2x"]:::none
  open_targets_credible_set_dataset_path(["open_targets_credible_set_dataset_path"]):::none --> GWAS_peak_weight_records.genetic_enrichment.immune_human_2x["GWAS_peak_weight_records.genetic_enrichment.immune_human_2x"]:::none
