%%{init: {'flowchart': {'defaultRenderer': 'elk'}}}%%
flowchart TB
  chromVAR_peak_expectation.ATAC.muscle(["chromVAR_peak_expectation.ATAC.&lt;dataset_name&gt;"]):::none --> chromVAR_background_bins.ATAC.muscle(["chromVAR_background_bins.ATAC.&lt;dataset_name&gt;"]):::none
  chromVAR_obj.ATAC.muscle(["chromVAR_obj.ATAC.&lt;dataset_name&gt;"]):::none --> chromVAR_background_bins.ATAC.muscle(["chromVAR_background_bins.ATAC.&lt;dataset_name&gt;"]):::none
  chromVAR_obj.ATAC.muscle_test(["chromVAR_obj.ATAC.&lt;aggregation_name&gt;"]):::none --> chromVAR_background_bins.ATAC.muscle_test(["chromVAR_background_bins.ATAC.&lt;aggregation_name&gt;"]):::none
  chromVAR_peak_expectation.ATAC.muscle_test(["chromVAR_peak_expectation.ATAC.&lt;aggregation_name&gt;"]):::none --> chromVAR_background_bins.ATAC.muscle_test(["chromVAR_background_bins.ATAC.&lt;aggregation_name&gt;"]):::none
  chromVAR_obj.ATAC.muscle(["chromVAR_obj.ATAC.&lt;dataset_name&gt;"]):::none --> chromVAR_peak_expectation.ATAC.muscle(["chromVAR_peak_expectation.ATAC.&lt;dataset_name&gt;"]):::none
  chromVAR_obj.ATAC.muscle_test(["chromVAR_obj.ATAC.&lt;aggregation_name&gt;"]):::none --> chromVAR_peak_expectation.ATAC.muscle_test(["chromVAR_peak_expectation.ATAC.&lt;aggregation_name&gt;"]):::none
  graph_matrix.PCA_harmony_SNN.SCAVENGE.single_nucleus.genetic_enrichment.muscle(["graph_matrix.PCA_harmony_SNN.SCAVENGE.single_nucleus.&lt;module_name&gt;.&lt;dataset_name&gt;"]):::none --> SCAVENGE_result_records.PCA_harmony_SNN.SCAVENGE.single_nucleus.genetic_enrichment.muscle["SCAVENGE_result_records.PCA_harmony_SNN.SCAVENGE.single_nucleus.&lt;module_name&gt;.&lt;dataset_name&gt;"]:::none
  chromVAR_z_score_records.single_nucleus.genetic_enrichment.muscle["chromVAR_z_score_records.single_nucleus.&lt;module_name&gt;.&lt;dataset_name&gt;"]:::none --> SCAVENGE_result_records.PCA_harmony_SNN.SCAVENGE.single_nucleus.genetic_enrichment.muscle["SCAVENGE_result_records.PCA_harmony_SNN.SCAVENGE.single_nucleus.&lt;module_name&gt;.&lt;dataset_name&gt;"]:::none
  chromVAR_z_score_records.single_nucleus.genetic_enrichment.muscle_test["chromVAR_z_score_records.single_nucleus.&lt;module_name&gt;.&lt;aggregation_name&gt;"]:::none --> SCAVENGE_result_records.PCA_harmony_SNN.SCAVENGE.single_nucleus.genetic_enrichment.muscle_test["SCAVENGE_result_records.PCA_harmony_SNN.SCAVENGE.single_nucleus.&lt;module_name&gt;.&lt;aggregation_name&gt;"]:::none
  graph_matrix.PCA_harmony_SNN.SCAVENGE.single_nucleus.genetic_enrichment.muscle_test(["graph_matrix.PCA_harmony_SNN.SCAVENGE.single_nucleus.&lt;module_name&gt;.&lt;aggregation_name&gt;"]):::none --> SCAVENGE_result_records.PCA_harmony_SNN.SCAVENGE.single_nucleus.genetic_enrichment.muscle_test["SCAVENGE_result_records.PCA_harmony_SNN.SCAVENGE.single_nucleus.&lt;module_name&gt;.&lt;aggregation_name&gt;"]:::none
  chromVAR_z_score_records.single_nucleus.genetic_enrichment.muscle["chromVAR_z_score_records.single_nucleus.&lt;module_name&gt;.&lt;dataset_name&gt;"]:::none --> SCAVENGE_result_records.WNN_harmony_SNN.SCAVENGE.single_nucleus.genetic_enrichment.muscle["SCAVENGE_result_records.WNN_harmony_SNN.SCAVENGE.single_nucleus.&lt;module_name&gt;.&lt;dataset_name&gt;"]:::none
  graph_matrix.WNN_harmony_SNN.SCAVENGE.single_nucleus.genetic_enrichment.muscle(["graph_matrix.WNN_harmony_SNN.SCAVENGE.single_nucleus.&lt;module_name&gt;.&lt;dataset_name&gt;"]):::none --> SCAVENGE_result_records.WNN_harmony_SNN.SCAVENGE.single_nucleus.genetic_enrichment.muscle["SCAVENGE_result_records.WNN_harmony_SNN.SCAVENGE.single_nucleus.&lt;module_name&gt;.&lt;dataset_name&gt;"]:::none
  chromVAR_z_score_records.single_nucleus.genetic_enrichment.muscle_test["chromVAR_z_score_records.single_nucleus.&lt;module_name&gt;.&lt;aggregation_name&gt;"]:::none --> SCAVENGE_result_records.WNN_harmony_SNN.SCAVENGE.single_nucleus.genetic_enrichment.muscle_test["SCAVENGE_result_records.WNN_harmony_SNN.SCAVENGE.single_nucleus.&lt;module_name&gt;.&lt;aggregation_name&gt;"]:::none
  graph_matrix.WNN_harmony_SNN.SCAVENGE.single_nucleus.genetic_enrichment.muscle_test(["graph_matrix.WNN_harmony_SNN.SCAVENGE.single_nucleus.&lt;module_name&gt;.&lt;aggregation_name&gt;"]):::none --> SCAVENGE_result_records.WNN_harmony_SNN.SCAVENGE.single_nucleus.genetic_enrichment.muscle_test["SCAVENGE_result_records.WNN_harmony_SNN.SCAVENGE.single_nucleus.&lt;module_name&gt;.&lt;aggregation_name&gt;"]:::none
  chromVAR_obj.ATAC.muscle(["chromVAR_obj.ATAC.&lt;dataset_name&gt;"]):::none --> chromVAR_z_score_records.single_nucleus.genetic_enrichment.muscle["chromVAR_z_score_records.single_nucleus.&lt;module_name&gt;.&lt;dataset_name&gt;"]:::none
  chromVAR_obj.ATAC.muscle_test(["chromVAR_obj.ATAC.&lt;aggregation_name&gt;"]):::none --> chromVAR_z_score_records.single_nucleus.genetic_enrichment.muscle_test["chromVAR_z_score_records.single_nucleus.&lt;module_name&gt;.&lt;aggregation_name&gt;"]:::none
  chromVAR_peak_expectation.ATAC.muscle(["chromVAR_peak_expectation.ATAC.&lt;dataset_name&gt;"]):::none --> chromVAR_z_score_records.single_nucleus.genetic_enrichment.muscle["chromVAR_z_score_records.single_nucleus.&lt;module_name&gt;.&lt;dataset_name&gt;"]:::none
  chromVAR_background_bins.ATAC.muscle(["chromVAR_background_bins.ATAC.&lt;dataset_name&gt;"]):::none --> chromVAR_z_score_records.single_nucleus.genetic_enrichment.muscle["chromVAR_z_score_records.single_nucleus.&lt;module_name&gt;.&lt;dataset_name&gt;"]:::none
  chromVAR_peak_expectation.ATAC.muscle_test(["chromVAR_peak_expectation.ATAC.&lt;aggregation_name&gt;"]):::none --> chromVAR_z_score_records.single_nucleus.genetic_enrichment.muscle_test["chromVAR_z_score_records.single_nucleus.&lt;module_name&gt;.&lt;aggregation_name&gt;"]:::none
  chromVAR_background_bins.ATAC.muscle_test(["chromVAR_background_bins.ATAC.&lt;aggregation_name&gt;"]):::none --> chromVAR_z_score_records.single_nucleus.genetic_enrichment.muscle_test["chromVAR_z_score_records.single_nucleus.&lt;module_name&gt;.&lt;aggregation_name&gt;"]:::none
  GWAS_peak_weight_records.genetic_enrichment.muscle["GWAS_peak_weight_records.&lt;module_name&gt;.&lt;dataset_name&gt;"]:::none --> chromVAR_z_score_records.single_nucleus.genetic_enrichment.muscle["chromVAR_z_score_records.single_nucleus.&lt;module_name&gt;.&lt;dataset_name&gt;"]:::none
  GWAS_peak_weight_records.genetic_enrichment.muscle_test["GWAS_peak_weight_records.&lt;module_name&gt;.&lt;aggregation_name&gt;"]:::none --> chromVAR_z_score_records.single_nucleus.genetic_enrichment.muscle_test["chromVAR_z_score_records.single_nucleus.&lt;module_name&gt;.&lt;aggregation_name&gt;"]:::none
  chromVAR_obj.ATAC.muscle(["chromVAR_obj.ATAC.&lt;dataset_name&gt;"]):::none --> GWAS_peak_weight_records.genetic_enrichment.muscle["GWAS_peak_weight_records.&lt;module_name&gt;.&lt;dataset_name&gt;"]:::none
  chromVAR_obj.ATAC.muscle_test(["chromVAR_obj.ATAC.&lt;aggregation_name&gt;"]):::none --> GWAS_peak_weight_records.genetic_enrichment.muscle_test["GWAS_peak_weight_records.&lt;module_name&gt;.&lt;aggregation_name&gt;"]:::none
  open_targets_credible_set_dataset_path(["open_targets_credible_set_dataset_path"]):::none --> GWAS_inputs_tibble.genetic_enrichment.muscle(["GWAS_inputs_tibble.&lt;module_name&gt;.&lt;dataset_name&gt;"]):::none
  open_targets_credible_set_dataset_path(["open_targets_credible_set_dataset_path"]):::none --> GWAS_peak_weight_records.genetic_enrichment.muscle["GWAS_peak_weight_records.&lt;module_name&gt;.&lt;dataset_name&gt;"]:::none
  open_targets_credible_set_dataset_path(["open_targets_credible_set_dataset_path"]):::none --> GWAS_inputs_tibble.genetic_enrichment.muscle_test(["GWAS_inputs_tibble.&lt;module_name&gt;.&lt;aggregation_name&gt;"]):::none
  open_targets_credible_set_dataset_path(["open_targets_credible_set_dataset_path"]):::none --> GWAS_peak_weight_records.genetic_enrichment.muscle_test["GWAS_peak_weight_records.&lt;module_name&gt;.&lt;aggregation_name&gt;"]:::none
  SCAVENGE_result_records.PCA_harmony_SNN.SCAVENGE.single_nucleus.genetic_enrichment.muscle["SCAVENGE_result_records.PCA_harmony_SNN.SCAVENGE.single_nucleus.&lt;module_name&gt;.&lt;dataset_name&gt;"]:::none --> TRS_summary_tibble.PCA_harmony_SNN.SCAVENGE.single_nucleus.genetic_enrichment.muscle(["TRS_summary_tibble.PCA_harmony_SNN.SCAVENGE.single_nucleus.&lt;module_name&gt;.&lt;dataset_name&gt;"]):::none
  SCAVENGE_result_records.PCA_harmony_SNN.SCAVENGE.single_nucleus.genetic_enrichment.muscle_test["SCAVENGE_result_records.PCA_harmony_SNN.SCAVENGE.single_nucleus.&lt;module_name&gt;.&lt;aggregation_name&gt;"]:::none --> TRS_summary_tibble.PCA_harmony_SNN.SCAVENGE.single_nucleus.genetic_enrichment.muscle_test(["TRS_summary_tibble.PCA_harmony_SNN.SCAVENGE.single_nucleus.&lt;module_name&gt;.&lt;aggregation_name&gt;"]):::none
  SCAVENGE_result_records.WNN_harmony_SNN.SCAVENGE.single_nucleus.genetic_enrichment.muscle["SCAVENGE_result_records.WNN_harmony_SNN.SCAVENGE.single_nucleus.&lt;module_name&gt;.&lt;dataset_name&gt;"]:::none --> TRS_summary_tibble.WNN_harmony_SNN.SCAVENGE.single_nucleus.genetic_enrichment.muscle(["TRS_summary_tibble.WNN_harmony_SNN.SCAVENGE.single_nucleus.&lt;module_name&gt;.&lt;dataset_name&gt;"]):::none
  SCAVENGE_result_records.WNN_harmony_SNN.SCAVENGE.single_nucleus.genetic_enrichment.muscle_test["SCAVENGE_result_records.WNN_harmony_SNN.SCAVENGE.single_nucleus.&lt;module_name&gt;.&lt;aggregation_name&gt;"]:::none --> TRS_summary_tibble.WNN_harmony_SNN.SCAVENGE.single_nucleus.genetic_enrichment.muscle_test(["TRS_summary_tibble.WNN_harmony_SNN.SCAVENGE.single_nucleus.&lt;module_name&gt;.&lt;aggregation_name&gt;"]):::none
