%%{init: {'flowchart': {'defaultRenderer': 'elk'}}}%%
flowchart TB
    cellranger_ref_list.healthy_PBMC_human(["cellranger_ref_list.healthy_PBMC_human"]):::none --> aggregated_cellranger_ref_list.immune_human_2x(["aggregated_cellranger_ref_list.immune_human_2x"]):::none
    aggregated_GEX_BPCells_matrix_dir.GEX.immune_human_2x(["aggregated_GEX_BPCells_matrix_dir.GEX.immune_human_2x"]):::none --> aggregated_counts_BPCells_matrix.GEX.immune_human_2x(["aggregated_counts_BPCells_matrix.GEX.immune_human_2x"]):::none
    GEX_counts_BPCells_matrix.lymphoma_lymph_human(["GEX_counts_BPCells_matrix.lymphoma_lymph_human"]):::none --> aggregated_GEX_BPCells_matrix_dir.GEX.immune_human_2x(["aggregated_GEX_BPCells_matrix_dir.GEX.immune_human_2x"]):::none
    GEX_counts_BPCells_matrix.healthy_PBMC_human(["GEX_counts_BPCells_matrix.healthy_PBMC_human"]):::none --> aggregated_GEX_BPCells_matrix_dir.GEX.immune_human_2x(["aggregated_GEX_BPCells_matrix_dir.GEX.immune_human_2x"]):::none
    cellranger_barcodes_tsv.healthy_PBMC_human(["cellranger_barcodes_tsv.healthy_PBMC_human"]):::none --> amulet_metrics_tibble.healthy_PBMC_human(["amulet_metrics_tibble.healthy_PBMC_human"]):::none
    cellranger_summary_file.healthy_PBMC_human(["cellranger_summary_file.healthy_PBMC_human"]):::none --> amulet_metrics_tibble.healthy_PBMC_human(["amulet_metrics_tibble.healthy_PBMC_human"]):::none
    cellranger_barcodes_tsv.lymphoma_lymph_human(["cellranger_barcodes_tsv.lymphoma_lymph_human"]):::none --> amulet_metrics_tibble.lymphoma_lymph_human(["amulet_metrics_tibble.lymphoma_lymph_human"]):::none
    cellranger_summary_file.lymphoma_lymph_human(["cellranger_summary_file.lymphoma_lymph_human"]):::none --> amulet_metrics_tibble.lymphoma_lymph_human(["amulet_metrics_tibble.lymphoma_lymph_human"]):::none
    fragments_w_prefix_bpcells.healthy_PBMC_human(["fragments_w_prefix_bpcells.healthy_PBMC_human"]):::none --> ATAC_qc_metrics_tibble.healthy_PBMC_human(["ATAC_qc_metrics_tibble.healthy_PBMC_human"]):::none
    Ensembl_gene_annotation_GRanges_list(["Ensembl_gene_annotation_GRanges_list"]):::none --> ATAC_qc_metrics_tibble.healthy_PBMC_human(["ATAC_qc_metrics_tibble.healthy_PBMC_human"]):::none
    cellranger_ref_list.healthy_PBMC_human(["cellranger_ref_list.healthy_PBMC_human"]):::none --> ATAC_qc_metrics_tibble.healthy_PBMC_human(["ATAC_qc_metrics_tibble.healthy_PBMC_human"]):::none
    cellranger_ref_list.lymphoma_lymph_human(["cellranger_ref_list.lymphoma_lymph_human"]):::none --> ATAC_qc_metrics_tibble.lymphoma_lymph_human(["ATAC_qc_metrics_tibble.lymphoma_lymph_human"]):::none
    Ensembl_gene_annotation_GRanges_list(["Ensembl_gene_annotation_GRanges_list"]):::none --> ATAC_qc_metrics_tibble.lymphoma_lymph_human(["ATAC_qc_metrics_tibble.lymphoma_lymph_human"]):::none
    fragments_w_prefix_bpcells.lymphoma_lymph_human(["fragments_w_prefix_bpcells.lymphoma_lymph_human"]):::none --> ATAC_qc_metrics_tibble.lymphoma_lymph_human(["ATAC_qc_metrics_tibble.lymphoma_lymph_human"]):::none
    metadata_w_cell_types_tibble.GEX.immune_human_2x(["metadata_w_cell_types_tibble.GEX.immune_human_2x"]):::none --> BCs_per_peak_cluster_list.ATAC.immune_human_2x(["BCs_per_peak_cluster_list.ATAC.immune_human_2x"]):::none
    aggregated_cellranger_ref_list.immune_human_2x(["aggregated_cellranger_ref_list.immune_human_2x"]):::none --> blacklist_GRanges.ATAC.immune_human_2x(["blacklist_GRanges.ATAC.immune_human_2x"]):::none
    cellranger_summary_file.healthy_PBMC_human(["cellranger_summary_file.healthy_PBMC_human"]):::none --> cellranger_barcodes_tsv.healthy_PBMC_human(["cellranger_barcodes_tsv.healthy_PBMC_human"]):::none
    cellranger_summary_file.lymphoma_lymph_human(["cellranger_summary_file.lymphoma_lymph_human"]):::none --> cellranger_barcodes_tsv.lymphoma_lymph_human(["cellranger_barcodes_tsv.lymphoma_lymph_human"]):::none
    full_metadata_tibble.healthy_PBMC_human(["full_metadata_tibble.healthy_PBMC_human"]):::none --> cellranger_kept_metadata_tibble.healthy_PBMC_human(["cellranger_kept_metadata_tibble.healthy_PBMC_human"]):::none
    full_metadata_tibble.lymphoma_lymph_human(["full_metadata_tibble.lymphoma_lymph_human"]):::none --> cellranger_kept_metadata_tibble.lymphoma_lymph_human(["cellranger_kept_metadata_tibble.lymphoma_lymph_human"]):::none
    cellranger_summary_file.healthy_PBMC_human(["cellranger_summary_file.healthy_PBMC_human"]):::none --> cellsnp_dir.healthy_PBMC_human(["cellsnp_dir.healthy_PBMC_human"]):::none
    cellranger_barcodes_tsv.healthy_PBMC_human(["cellranger_barcodes_tsv.healthy_PBMC_human"]):::none --> cellsnp_dir.healthy_PBMC_human(["cellsnp_dir.healthy_PBMC_human"]):::none
    cellranger_summary_file.lymphoma_lymph_human(["cellranger_summary_file.lymphoma_lymph_human"]):::none --> cellsnp_dir.lymphoma_lymph_human(["cellsnp_dir.lymphoma_lymph_human"]):::none
    cellranger_barcodes_tsv.lymphoma_lymph_human(["cellranger_barcodes_tsv.lymphoma_lymph_human"]):::none --> cellsnp_dir.lymphoma_lymph_human(["cellsnp_dir.lymphoma_lymph_human"]):::none
    chromVAR_obj.ATAC.immune_human_2x(["chromVAR_obj.ATAC.immune_human_2x"]):::none --> chromVAR_background_bins.ATAC.immune_human_2x(["chromVAR_background_bins.ATAC.immune_human_2x"]):::none
    chromVAR_peak_expectation.ATAC.immune_human_2x(["chromVAR_peak_expectation.ATAC.immune_human_2x"]):::none --> chromVAR_background_bins.ATAC.immune_human_2x(["chromVAR_background_bins.ATAC.immune_human_2x"]):::none
    chromVAR_obj.ATAC.immune_human_2x(["chromVAR_obj.ATAC.immune_human_2x"]):::none --> chromVAR_cell_chunks.ATAC.immune_human_2x(["chromVAR_cell_chunks.ATAC.immune_human_2x"]):::none
    chromVAR_cell_chunks.ATAC.immune_human_2x(["chromVAR_cell_chunks.ATAC.immune_human_2x"]):::none --> chromVAR_chunk_context_records.ATAC.immune_human_2x["chromVAR_chunk_context_records.ATAC.immune_human_2x"]:::none
    chromVAR_background_bins.ATAC.immune_human_2x(["chromVAR_background_bins.ATAC.immune_human_2x"]):::none --> chromVAR_chunk_context_records.ATAC.immune_human_2x["chromVAR_chunk_context_records.ATAC.immune_human_2x"]:::none
    chromVAR_obj.ATAC.immune_human_2x(["chromVAR_obj.ATAC.immune_human_2x"]):::none --> chromVAR_chunk_context_records.ATAC.immune_human_2x["chromVAR_chunk_context_records.ATAC.immune_human_2x"]:::none
    chromVAR_peak_expectation.ATAC.immune_human_2x(["chromVAR_peak_expectation.ATAC.immune_human_2x"]):::none --> chromVAR_chunk_context_records.ATAC.immune_human_2x["chromVAR_chunk_context_records.ATAC.immune_human_2x"]:::none
    aggregated_cellranger_ref_list.immune_human_2x(["aggregated_cellranger_ref_list.immune_human_2x"]):::none --> chromVAR_obj.ATAC.immune_human_2x(["chromVAR_obj.ATAC.immune_human_2x"]):::none
    metadata_w_cell_types_tibble.ATAC.immune_human_2x(["metadata_w_cell_types_tibble.ATAC.immune_human_2x"]):::none --> chromVAR_obj.ATAC.immune_human_2x(["chromVAR_obj.ATAC.immune_human_2x"]):::none
    consensus_peak_BPCells_matrix.ATAC.immune_human_2x(["consensus_peak_BPCells_matrix.ATAC.immune_human_2x"]):::none --> chromVAR_obj.ATAC.immune_human_2x(["chromVAR_obj.ATAC.immune_human_2x"]):::none
    consensus_peak_GRanges.ATAC.immune_human_2x(["consensus_peak_GRanges.ATAC.immune_human_2x"]):::none --> chromVAR_obj.ATAC.immune_human_2x(["chromVAR_obj.ATAC.immune_human_2x"]):::none
    chromVAR_obj.ATAC.immune_human_2x(["chromVAR_obj.ATAC.immune_human_2x"]):::none --> chromVAR_peak_expectation.ATAC.immune_human_2x(["chromVAR_peak_expectation.ATAC.immune_human_2x"]):::none
    WNN_results_raw.immune_human_2x(["WNN_results_raw.immune_human_2x"]):::none --> clusters_tibble_raw.WNN.immune_human_2x(["clusters_tibble_raw.WNN.immune_human_2x"]):::none
    clusters_tibble_raw.WNN.immune_human_2x(["clusters_tibble_raw.WNN.immune_human_2x"]):::none --> clusters_tibble.WNN.immune_human_2x(["clusters_tibble.WNN.immune_human_2x"]):::none
    fragments_w_prefix_bpcells.healthy_PBMC_human(["fragments_w_prefix_bpcells.healthy_PBMC_human"]):::none --> combined_BPCells_fragment_obj.ATAC.immune_human_2x(["combined_BPCells_fragment_obj.ATAC.immune_human_2x"]):::none
    organism_chr.immune_human_2x(["organism_chr.immune_human_2x"]):::none --> combined_BPCells_fragment_obj.ATAC.immune_human_2x(["combined_BPCells_fragment_obj.ATAC.immune_human_2x"]):::none
    fragments_w_prefix_bpcells.lymphoma_lymph_human(["fragments_w_prefix_bpcells.lymphoma_lymph_human"]):::none --> combined_BPCells_fragment_obj.ATAC.immune_human_2x(["combined_BPCells_fragment_obj.ATAC.immune_human_2x"]):::none
    metadata_w_cell_types_tibble.GEX.immune_human_2x(["metadata_w_cell_types_tibble.GEX.immune_human_2x"]):::none --> consensus_peak_BPCells_matrix_dir.ATAC.immune_human_2x(["consensus_peak_BPCells_matrix_dir.ATAC.immune_human_2x"]):::none
    combined_BPCells_fragment_obj.ATAC.immune_human_2x(["combined_BPCells_fragment_obj.ATAC.immune_human_2x"]):::none --> consensus_peak_BPCells_matrix_dir.ATAC.immune_human_2x(["consensus_peak_BPCells_matrix_dir.ATAC.immune_human_2x"]):::none
    consensus_peak_GRanges.ATAC.immune_human_2x(["consensus_peak_GRanges.ATAC.immune_human_2x"]):::none --> consensus_peak_BPCells_matrix_dir.ATAC.immune_human_2x(["consensus_peak_BPCells_matrix_dir.ATAC.immune_human_2x"]):::none
    consensus_peak_BPCells_matrix_dir.ATAC.immune_human_2x(["consensus_peak_BPCells_matrix_dir.ATAC.immune_human_2x"]):::none --> consensus_peak_BPCells_matrix.ATAC.immune_human_2x(["consensus_peak_BPCells_matrix.ATAC.immune_human_2x"]):::none
    within_clusters_collapsed_peaks_per_cluster_GRanges.ATAC.immune_human_2x["within_clusters_collapsed_peaks_per_cluster_GRanges.ATAC.immune_human_2x"]:::none --> consensus_peak_GRanges.ATAC.immune_human_2x(["consensus_peak_GRanges.ATAC.immune_human_2x"]):::none
    donor_id_metadata_tsv.immune_human_2x(["donor_id_metadata_tsv.immune_human_2x"]):::none --> donor_id_metadata_tibble.immune_human_2x(["donor_id_metadata_tibble.immune_human_2x"]):::none
    harmony_embeddings_matrix.GEX.immune_human_2x(["harmony_embeddings_matrix.GEX.immune_human_2x"]):::none --> embedding_matrices.WNN.immune_human_2x(["embedding_matrices.WNN.immune_human_2x"]):::none
    metadata_w_cell_types_tibble.ATAC.immune_human_2x(["metadata_w_cell_types_tibble.ATAC.immune_human_2x"]):::none --> embedding_matrices.WNN.immune_human_2x(["embedding_matrices.WNN.immune_human_2x"]):::none
    harmony_embeddings_matrix.ATAC.immune_human_2x(["harmony_embeddings_matrix.ATAC.immune_human_2x"]):::none --> embedding_matrices.WNN.immune_human_2x(["embedding_matrices.WNN.immune_human_2x"]):::none
    full_metadata_tibble.healthy_PBMC_human(["full_metadata_tibble.healthy_PBMC_human"]):::none --> excluded_cellranger_only_barcodes_by_type_list.healthy_PBMC_human(["excluded_cellranger_only_barcodes_by_type_list.healthy_PBMC_human"]):::none
    full_metadata_tibble.lymphoma_lymph_human(["full_metadata_tibble.lymphoma_lymph_human"]):::none --> excluded_cellranger_only_barcodes_by_type_list.lymphoma_lymph_human(["excluded_cellranger_only_barcodes_by_type_list.lymphoma_lymph_human"]):::none
    combined_BPCells_fragment_obj.ATAC.immune_human_2x(["combined_BPCells_fragment_obj.ATAC.immune_human_2x"]):::none --> fragments_per_peak_calling_cluster_discovery.fragments.ATAC.immune_human_2x["fragments_per_peak_calling_cluster_discovery.fragments.ATAC.immune_human_2x"]:::none
    peak_calling_cluster_discovery_tibble.ATAC.immune_human_2x(["peak_calling_cluster_discovery_tibble.ATAC.immune_human_2x"]):::none --> fragments_per_peak_calling_cluster_discovery.fragments.ATAC.immune_human_2x["fragments_per_peak_calling_cluster_discovery.fragments.ATAC.immune_human_2x"]:::none
    cellranger_summary_file.healthy_PBMC_human(["cellranger_summary_file.healthy_PBMC_human"]):::none --> fragments_w_prefix_bpcells_dir.healthy_PBMC_human(["fragments_w_prefix_bpcells_dir.healthy_PBMC_human"]):::none
    cellranger_summary_file.lymphoma_lymph_human(["cellranger_summary_file.lymphoma_lymph_human"]):::none --> fragments_w_prefix_bpcells_dir.lymphoma_lymph_human(["fragments_w_prefix_bpcells_dir.lymphoma_lymph_human"]):::none
    fragments_w_prefix_bpcells_dir.healthy_PBMC_human(["fragments_w_prefix_bpcells_dir.healthy_PBMC_human"]):::none --> fragments_w_prefix_bpcells.healthy_PBMC_human(["fragments_w_prefix_bpcells.healthy_PBMC_human"]):::none
    fragments_w_prefix_bpcells_dir.lymphoma_lymph_human(["fragments_w_prefix_bpcells_dir.lymphoma_lymph_human"]):::none --> fragments_w_prefix_bpcells.lymphoma_lymph_human(["fragments_w_prefix_bpcells.lymphoma_lymph_human"]):::none
    per_barcode_metrics_tibble.healthy_PBMC_human(["per_barcode_metrics_tibble.healthy_PBMC_human"]):::none --> full_metadata_tibble.healthy_PBMC_human(["full_metadata_tibble.healthy_PBMC_human"]):::none
    GEX_basic_metadata_tibble.healthy_PBMC_human(["GEX_basic_metadata_tibble.healthy_PBMC_human"]):::none --> full_metadata_tibble.healthy_PBMC_human(["full_metadata_tibble.healthy_PBMC_human"]):::none
    amulet_metrics_tibble.healthy_PBMC_human(["amulet_metrics_tibble.healthy_PBMC_human"]):::none --> full_metadata_tibble.healthy_PBMC_human(["full_metadata_tibble.healthy_PBMC_human"]):::none
    vireo_donor_ids_tibble.healthy_PBMC_human(["vireo_donor_ids_tibble.healthy_PBMC_human"]):::none --> full_metadata_tibble.healthy_PBMC_human(["full_metadata_tibble.healthy_PBMC_human"]):::none
    ATAC_qc_metrics_tibble.healthy_PBMC_human(["ATAC_qc_metrics_tibble.healthy_PBMC_human"]):::none --> full_metadata_tibble.healthy_PBMC_human(["full_metadata_tibble.healthy_PBMC_human"]):::none
    amulet_metrics_tibble.lymphoma_lymph_human(["amulet_metrics_tibble.lymphoma_lymph_human"]):::none --> full_metadata_tibble.lymphoma_lymph_human(["full_metadata_tibble.lymphoma_lymph_human"]):::none
    per_barcode_metrics_tibble.lymphoma_lymph_human(["per_barcode_metrics_tibble.lymphoma_lymph_human"]):::none --> full_metadata_tibble.lymphoma_lymph_human(["full_metadata_tibble.lymphoma_lymph_human"]):::none
    ATAC_qc_metrics_tibble.lymphoma_lymph_human(["ATAC_qc_metrics_tibble.lymphoma_lymph_human"]):::none --> full_metadata_tibble.lymphoma_lymph_human(["full_metadata_tibble.lymphoma_lymph_human"]):::none
    GEX_basic_metadata_tibble.lymphoma_lymph_human(["GEX_basic_metadata_tibble.lymphoma_lymph_human"]):::none --> full_metadata_tibble.lymphoma_lymph_human(["full_metadata_tibble.lymphoma_lymph_human"]):::none
    vireo_donor_ids_tibble.lymphoma_lymph_human(["vireo_donor_ids_tibble.lymphoma_lymph_human"]):::none --> full_metadata_tibble.lymphoma_lymph_human(["full_metadata_tibble.lymphoma_lymph_human"]):::none
    cellranger_summary_file.healthy_PBMC_human(["cellranger_summary_file.healthy_PBMC_human"]):::none --> gene_features_df.healthy_PBMC_human(["gene_features_df.healthy_PBMC_human"]):::none
    gene_features_df.healthy_PBMC_human(["gene_features_df.healthy_PBMC_human"]):::none --> gene_features_df.immune_human_2x(["gene_features_df.immune_human_2x"]):::none
    cellranger_summary_file.lymphoma_lymph_human(["cellranger_summary_file.lymphoma_lymph_human"]):::none --> gene_features_df.lymphoma_lymph_human(["gene_features_df.lymphoma_lymph_human"]):::none
    chromVAR_obj.ATAC.immune_human_2x(["chromVAR_obj.ATAC.immune_human_2x"]):::none --> genetic_enrichment_peak_ranges.genetic_enrichment.immune_human_2x(["genetic_enrichment_peak_ranges.genetic_enrichment.immune_human_2x"]):::none
    GEX_counts_BPCells_matrix.healthy_PBMC_human(["GEX_counts_BPCells_matrix.healthy_PBMC_human"]):::none --> GEX_basic_metadata_tibble.healthy_PBMC_human(["GEX_basic_metadata_tibble.healthy_PBMC_human"]):::none
    GEX_counts_BPCells_matrix.lymphoma_lymph_human(["GEX_counts_BPCells_matrix.lymphoma_lymph_human"]):::none --> GEX_basic_metadata_tibble.lymphoma_lymph_human(["GEX_basic_metadata_tibble.lymphoma_lymph_human"]):::none
    cellranger_kept_metadata_tibble.lymphoma_lymph_human(["cellranger_kept_metadata_tibble.lymphoma_lymph_human"]):::none --> GEX_cellranger_kept_metadata_tibble.immune_human_2x(["GEX_cellranger_kept_metadata_tibble.immune_human_2x"]):::none
    cellranger_kept_metadata_tibble.healthy_PBMC_human(["cellranger_kept_metadata_tibble.healthy_PBMC_human"]):::none --> GEX_cellranger_kept_metadata_tibble.immune_human_2x(["GEX_cellranger_kept_metadata_tibble.immune_human_2x"]):::none
    excluded_cellranger_only_barcodes_by_type_list.lymphoma_lymph_human(["excluded_cellranger_only_barcodes_by_type_list.lymphoma_lymph_human"]):::none --> GEX_cellranger_kept_metadata_tibble.immune_human_2x(["GEX_cellranger_kept_metadata_tibble.immune_human_2x"]):::none
    excluded_cellranger_only_barcodes_by_type_list.healthy_PBMC_human(["excluded_cellranger_only_barcodes_by_type_list.healthy_PBMC_human"]):::none --> GEX_cellranger_kept_metadata_tibble.immune_human_2x(["GEX_cellranger_kept_metadata_tibble.immune_human_2x"]):::none
    cellbender_h5_file.healthy_PBMC_human(["cellbender_h5_file.healthy_PBMC_human"]):::none --> GEX_counts_BPcells_matrix_dir.healthy_PBMC_human(["GEX_counts_BPcells_matrix_dir.healthy_PBMC_human"]):::none
    cellranger_summary_file.healthy_PBMC_human(["cellranger_summary_file.healthy_PBMC_human"]):::none --> GEX_counts_BPcells_matrix_dir.healthy_PBMC_human(["GEX_counts_BPcells_matrix_dir.healthy_PBMC_human"]):::none
    gene_features_df.healthy_PBMC_human(["gene_features_df.healthy_PBMC_human"]):::none --> GEX_counts_BPcells_matrix_dir.healthy_PBMC_human(["GEX_counts_BPcells_matrix_dir.healthy_PBMC_human"]):::none
    gene_features_df.lymphoma_lymph_human(["gene_features_df.lymphoma_lymph_human"]):::none --> GEX_counts_BPcells_matrix_dir.lymphoma_lymph_human(["GEX_counts_BPcells_matrix_dir.lymphoma_lymph_human"]):::none
    cellbender_h5_file.lymphoma_lymph_human(["cellbender_h5_file.lymphoma_lymph_human"]):::none --> GEX_counts_BPcells_matrix_dir.lymphoma_lymph_human(["GEX_counts_BPcells_matrix_dir.lymphoma_lymph_human"]):::none
    cellranger_summary_file.lymphoma_lymph_human(["cellranger_summary_file.lymphoma_lymph_human"]):::none --> GEX_counts_BPcells_matrix_dir.lymphoma_lymph_human(["GEX_counts_BPcells_matrix_dir.lymphoma_lymph_human"]):::none
    GEX_counts_BPcells_matrix_dir.healthy_PBMC_human(["GEX_counts_BPcells_matrix_dir.healthy_PBMC_human"]):::none --> GEX_counts_BPCells_matrix.healthy_PBMC_human(["GEX_counts_BPCells_matrix.healthy_PBMC_human"]):::none
    GEX_counts_BPcells_matrix_dir.lymphoma_lymph_human(["GEX_counts_BPcells_matrix_dir.lymphoma_lymph_human"]):::none --> GEX_counts_BPCells_matrix.lymphoma_lymph_human(["GEX_counts_BPCells_matrix.lymphoma_lymph_human"]):::none
    GWAS_inputs_tibble.genetic_enrichment.immune_human_2x(["GWAS_inputs_tibble.genetic_enrichment.immune_human_2x"]):::none --> GWAS_analysis_inputs_tibble.genetic_enrichment.immune_human_2x(["GWAS_analysis_inputs_tibble.genetic_enrichment.immune_human_2x"]):::none
    open_targets_credible_set_dataset_path(["open_targets_credible_set_dataset_path"]):::none --> GWAS_chromVAR_input_records.genetic_enrichment.immune_human_2x["GWAS_chromVAR_input_records.genetic_enrichment.immune_human_2x"]:::none
    GWAS_analysis_inputs_tibble.genetic_enrichment.immune_human_2x(["GWAS_analysis_inputs_tibble.genetic_enrichment.immune_human_2x"]):::none --> GWAS_chromVAR_input_records.genetic_enrichment.immune_human_2x["GWAS_chromVAR_input_records.genetic_enrichment.immune_human_2x"]:::none
    GWAS_chromVAR_input_records.genetic_enrichment.immune_human_2x["GWAS_chromVAR_input_records.genetic_enrichment.immune_human_2x"]:::none --> GWAS_chromVAR_peak_weight_records.genetic_enrichment.immune_human_2x["GWAS_chromVAR_peak_weight_records.genetic_enrichment.immune_human_2x"]:::none
    posterior_probability_weighting_function.genetic_enrichment.immune_human_2x(["posterior_probability_weighting_function.genetic_enrichment.immune_human_2x"]):::none --> GWAS_chromVAR_peak_weight_records.genetic_enrichment.immune_human_2x["GWAS_chromVAR_peak_weight_records.genetic_enrichment.immune_human_2x"]:::none
    genetic_enrichment_peak_ranges.genetic_enrichment.immune_human_2x(["genetic_enrichment_peak_ranges.genetic_enrichment.immune_human_2x"]):::none --> GWAS_chromVAR_peak_weight_records.genetic_enrichment.immune_human_2x["GWAS_chromVAR_peak_weight_records.genetic_enrichment.immune_human_2x"]:::none
    GWAS_chromVAR_summarized_ZScores_tibble.genetic_enrichment.immune_human_2x(["GWAS_chromVAR_summarized_ZScores_tibble.genetic_enrichment.immune_human_2x"]):::none --> GWAS_chromVAR_summarized_Zscores_boxplot.genetic_enrichment.immune_human_2x(["GWAS_chromVAR_summarized_Zscores_boxplot.genetic_enrichment.immune_human_2x"]):::none
    GWAS_chromVAR_summarized_ZScores_tibble.genetic_enrichment.immune_human_2x(["GWAS_chromVAR_summarized_ZScores_tibble.genetic_enrichment.immune_human_2x"]):::none --> GWAS_chromVAR_summarized_Zscores_dotplot_data.genetic_enrichment.immune_human_2x(["GWAS_chromVAR_summarized_Zscores_dotplot_data.genetic_enrichment.immune_human_2x"]):::none
    GWAS_inputs_tibble.genetic_enrichment.immune_human_2x(["GWAS_inputs_tibble.genetic_enrichment.immune_human_2x"]):::none --> GWAS_chromVAR_summarized_Zscores_dotplot_data.genetic_enrichment.immune_human_2x(["GWAS_chromVAR_summarized_Zscores_dotplot_data.genetic_enrichment.immune_human_2x"]):::none
    GWAS_chromVAR_summarized_Zscores_dotplot_data.genetic_enrichment.immune_human_2x(["GWAS_chromVAR_summarized_Zscores_dotplot_data.genetic_enrichment.immune_human_2x"]):::none --> GWAS_chromVAR_summarized_Zscores_dotplot_scaled_data.genetic_enrichment.immune_human_2x(["GWAS_chromVAR_summarized_Zscores_dotplot_scaled_data.genetic_enrichment.immune_human_2x"]):::none
    GWAS_chromVAR_summarized_Zscores_dotplot_scaled_data.genetic_enrichment.immune_human_2x(["GWAS_chromVAR_summarized_Zscores_dotplot_scaled_data.genetic_enrichment.immune_human_2x"]):::none --> GWAS_chromVAR_summarized_Zscores_dotplot_scaled.genetic_enrichment.immune_human_2x(["GWAS_chromVAR_summarized_Zscores_dotplot_scaled.genetic_enrichment.immune_human_2x"]):::none
    GWAS_metadata_tracks_plot.genetic_enrichment.immune_human_2x(["GWAS_metadata_tracks_plot.genetic_enrichment.immune_human_2x"]):::none --> GWAS_chromVAR_summarized_Zscores_dotplot_scaled.genetic_enrichment.immune_human_2x(["GWAS_chromVAR_summarized_Zscores_dotplot_scaled.genetic_enrichment.immune_human_2x"]):::none
    GWAS_metadata_tracks_plot.genetic_enrichment.immune_human_2x(["GWAS_metadata_tracks_plot.genetic_enrichment.immune_human_2x"]):::none --> GWAS_chromVAR_summarized_Zscores_dotplot.genetic_enrichment.immune_human_2x(["GWAS_chromVAR_summarized_Zscores_dotplot.genetic_enrichment.immune_human_2x"]):::none
    GWAS_chromVAR_summarized_Zscores_dotplot_data.genetic_enrichment.immune_human_2x(["GWAS_chromVAR_summarized_Zscores_dotplot_data.genetic_enrichment.immune_human_2x"]):::none --> GWAS_chromVAR_summarized_Zscores_dotplot.genetic_enrichment.immune_human_2x(["GWAS_chromVAR_summarized_Zscores_dotplot.genetic_enrichment.immune_human_2x"]):::none
    GWAS_chromVAR_ZScore_records.single_cell.genetic_enrichment.immune_human_2x["GWAS_chromVAR_ZScore_records.single_cell.genetic_enrichment.immune_human_2x"]:::none --> GWAS_chromVAR_summarized_ZScores_tibble.genetic_enrichment.immune_human_2x(["GWAS_chromVAR_summarized_ZScores_tibble.genetic_enrichment.immune_human_2x"]):::none
    metadata_w_cell_types_tibble.WNN.immune_human_2x(["metadata_w_cell_types_tibble.WNN.immune_human_2x"]):::none --> GWAS_chromVAR_summarized_ZScores_tibble.genetic_enrichment.immune_human_2x(["GWAS_chromVAR_summarized_ZScores_tibble.genetic_enrichment.immune_human_2x"]):::none
    GWAS_chromVAR_ZScore_chunk_records.genetic_enrichment.immune_human_2x["GWAS_chromVAR_ZScore_chunk_records.genetic_enrichment.immune_human_2x"]:::none --> GWAS_chromVAR_ZScore_chunk_records_by_GWAS.genetic_enrichment.immune_human_2x(["GWAS_chromVAR_ZScore_chunk_records_by_GWAS.genetic_enrichment.immune_human_2x"]):::none
    chromVAR_chunk_context_records.ATAC.immune_human_2x["chromVAR_chunk_context_records.ATAC.immune_human_2x"]:::none --> GWAS_chromVAR_ZScore_chunk_records.genetic_enrichment.immune_human_2x["GWAS_chromVAR_ZScore_chunk_records.genetic_enrichment.immune_human_2x"]:::none
    chromVAR_obj.ATAC.immune_human_2x(["chromVAR_obj.ATAC.immune_human_2x"]):::none --> GWAS_chromVAR_ZScore_chunk_records.genetic_enrichment.immune_human_2x["GWAS_chromVAR_ZScore_chunk_records.genetic_enrichment.immune_human_2x"]:::none
    GWAS_chromVAR_peak_weight_records.genetic_enrichment.immune_human_2x["GWAS_chromVAR_peak_weight_records.genetic_enrichment.immune_human_2x"]:::none --> GWAS_chromVAR_ZScore_chunk_records.genetic_enrichment.immune_human_2x["GWAS_chromVAR_ZScore_chunk_records.genetic_enrichment.immune_human_2x"]:::none
    GWAS_chromVAR_ZScore_chunk_records_by_GWAS.genetic_enrichment.immune_human_2x(["GWAS_chromVAR_ZScore_chunk_records_by_GWAS.genetic_enrichment.immune_human_2x"]):::none --> GWAS_chromVAR_ZScore_records.single_cell.genetic_enrichment.immune_human_2x["GWAS_chromVAR_ZScore_records.single_cell.genetic_enrichment.immune_human_2x"]:::none
    open_targets_credible_set_dataset_path(["open_targets_credible_set_dataset_path"]):::none --> GWAS_inputs_tibble.genetic_enrichment.immune_human_2x(["GWAS_inputs_tibble.genetic_enrichment.immune_human_2x"]):::none
    GWAS_open_targets_metadata_tibble.genetic_enrichment.immune_human_2x(["GWAS_open_targets_metadata_tibble.genetic_enrichment.immune_human_2x"]):::none --> GWAS_metadata_tracks_plot.genetic_enrichment.immune_human_2x(["GWAS_metadata_tracks_plot.genetic_enrichment.immune_human_2x"]):::none
    GWAS_inputs_tibble.genetic_enrichment.immune_human_2x(["GWAS_inputs_tibble.genetic_enrichment.immune_human_2x"]):::none --> GWAS_open_targets_metadata_tibble.genetic_enrichment.immune_human_2x(["GWAS_open_targets_metadata_tibble.genetic_enrichment.immune_human_2x"]):::none
    open_targets_credible_set_dataset_path(["open_targets_credible_set_dataset_path"]):::none --> GWAS_open_targets_metadata_tibble.genetic_enrichment.immune_human_2x(["GWAS_open_targets_metadata_tibble.genetic_enrichment.immune_human_2x"]):::none
    open_targets_study_dataset_path(["open_targets_study_dataset_path"]):::none --> GWAS_open_targets_metadata_tibble.genetic_enrichment.immune_human_2x(["GWAS_open_targets_metadata_tibble.genetic_enrichment.immune_human_2x"]):::none
    LSI_BPCells.ATAC.immune_human_2x(["LSI_BPCells.ATAC.immune_human_2x"]):::none --> harmony_embeddings_matrix.ATAC.immune_human_2x(["harmony_embeddings_matrix.ATAC.immune_human_2x"]):::none
    metadata_filtered_tibble.ATAC.immune_human_2x(["metadata_filtered_tibble.ATAC.immune_human_2x"]):::none --> harmony_embeddings_matrix.ATAC.immune_human_2x(["harmony_embeddings_matrix.ATAC.immune_human_2x"]):::none
    metadata_tibble.GEX.immune_human_2x(["metadata_tibble.GEX.immune_human_2x"]):::none --> harmony_embeddings_matrix.GEX.immune_human_2x(["harmony_embeddings_matrix.GEX.immune_human_2x"]):::none
    PCA_BPCells.GEX.immune_human_2x(["PCA_BPCells.GEX.immune_human_2x"]):::none --> harmony_embeddings_matrix.GEX.immune_human_2x(["harmony_embeddings_matrix.GEX.immune_human_2x"]):::none
    peak_QC_filtered_BPCells_matrix.ATAC.immune_human_2x(["peak_QC_filtered_BPCells_matrix.ATAC.immune_human_2x"]):::none --> LSI_BPCells.ATAC.immune_human_2x(["LSI_BPCells.ATAC.immune_human_2x"]):::none
    harmony_embeddings_matrix.ATAC.immune_human_2x(["harmony_embeddings_matrix.ATAC.immune_human_2x"]):::none --> LSI_clusters.ATAC.immune_human_2x(["LSI_clusters.ATAC.immune_human_2x"]):::none
    LSI_BPCells.ATAC.immune_human_2x(["LSI_BPCells.ATAC.immune_human_2x"]):::none --> LSI_loadings_tibble.ATAC.immune_human_2x(["LSI_loadings_tibble.ATAC.immune_human_2x"]):::none
    metadata_w_QC_tibble.ATAC.immune_human_2x(["metadata_w_QC_tibble.ATAC.immune_human_2x"]):::none --> metadata_filtered_tibble.ATAC.immune_human_2x(["metadata_filtered_tibble.ATAC.immune_human_2x"]):::none
    QC_filtered_BCs.ATAC.immune_human_2x(["QC_filtered_BCs.ATAC.immune_human_2x"]):::none --> metadata_filtered_tibble.ATAC.immune_human_2x(["metadata_filtered_tibble.ATAC.immune_human_2x"]):::none
    GEX_cellranger_kept_metadata_tibble.immune_human_2x(["GEX_cellranger_kept_metadata_tibble.immune_human_2x"]):::none --> metadata_tibble.GEX.immune_human_2x(["metadata_tibble.GEX.immune_human_2x"]):::none
    PCA_BPCells.GEX.immune_human_2x(["PCA_BPCells.GEX.immune_human_2x"]):::none --> metadata_tibble.GEX.immune_human_2x(["metadata_tibble.GEX.immune_human_2x"]):::none
    donor_id_metadata_tibble.immune_human_2x(["donor_id_metadata_tibble.immune_human_2x"]):::none --> metadata_tibble.GEX.immune_human_2x(["metadata_tibble.GEX.immune_human_2x"]):::none
    reaction_ID_metadata_tibble.immune_human_2x(["reaction_ID_metadata_tibble.immune_human_2x"]):::none --> metadata_tibble.GEX.immune_human_2x(["metadata_tibble.GEX.immune_human_2x"]):::none
    scDblFinder_results_df.ATAC.immune_human_2x(["scDblFinder_results_df.ATAC.immune_human_2x"]):::none --> metadata_w_cell_types_tibble.ATAC.immune_human_2x(["metadata_w_cell_types_tibble.ATAC.immune_human_2x"]):::none
    metadata_w_cell_types_unfiltered_tibble.ATAC.immune_human_2x(["metadata_w_cell_types_unfiltered_tibble.ATAC.immune_human_2x"]):::none --> metadata_w_cell_types_tibble.ATAC.immune_human_2x(["metadata_w_cell_types_tibble.ATAC.immune_human_2x"]):::none
    metadata_w_cell_types_unfiltered_tibble.GEX.immune_human_2x(["metadata_w_cell_types_unfiltered_tibble.GEX.immune_human_2x"]):::none --> metadata_w_cell_types_tibble.GEX.immune_human_2x(["metadata_w_cell_types_tibble.GEX.immune_human_2x"]):::none
    scDblFinder_results_df.GEX.immune_human_2x(["scDblFinder_results_df.GEX.immune_human_2x"]):::none --> metadata_w_cell_types_tibble.GEX.immune_human_2x(["metadata_w_cell_types_tibble.GEX.immune_human_2x"]):::none
    metadata_w_clusters_tibble.WNN.immune_human_2x(["metadata_w_clusters_tibble.WNN.immune_human_2x"]):::none --> metadata_w_cell_types_tibble.WNN.immune_human_2x(["metadata_w_cell_types_tibble.WNN.immune_human_2x"]):::none
    UCell_GEX_marker_genes_list.immune_human_2x(["UCell_GEX_marker_genes_list.immune_human_2x"]):::none --> metadata_w_cell_types_tibble.WNN.immune_human_2x(["metadata_w_cell_types_tibble.WNN.immune_human_2x"]):::none
    metadata_w_clusters_tibble.ATAC.immune_human_2x(["metadata_w_clusters_tibble.ATAC.immune_human_2x"]):::none --> metadata_w_cell_types_unfiltered_tibble.ATAC.immune_human_2x(["metadata_w_cell_types_unfiltered_tibble.ATAC.immune_human_2x"]):::none
    UCell_GEX_marker_genes_list.immune_human_2x(["UCell_GEX_marker_genes_list.immune_human_2x"]):::none --> metadata_w_cell_types_unfiltered_tibble.ATAC.immune_human_2x(["metadata_w_cell_types_unfiltered_tibble.ATAC.immune_human_2x"]):::none
    UCell_GEX_marker_genes_list.immune_human_2x(["UCell_GEX_marker_genes_list.immune_human_2x"]):::none --> metadata_w_cell_types_unfiltered_tibble.GEX.immune_human_2x(["metadata_w_cell_types_unfiltered_tibble.GEX.immune_human_2x"]):::none
    aggregated_counts_BPCells_matrix.GEX.immune_human_2x(["aggregated_counts_BPCells_matrix.GEX.immune_human_2x"]):::none --> metadata_w_cell_types_unfiltered_tibble.GEX.immune_human_2x(["metadata_w_cell_types_unfiltered_tibble.GEX.immune_human_2x"]):::none
    metadata_w_clusters_tibble.GEX.immune_human_2x(["metadata_w_clusters_tibble.GEX.immune_human_2x"]):::none --> metadata_w_cell_types_unfiltered_tibble.GEX.immune_human_2x(["metadata_w_cell_types_unfiltered_tibble.GEX.immune_human_2x"]):::none
    metadata_filtered_tibble.ATAC.immune_human_2x(["metadata_filtered_tibble.ATAC.immune_human_2x"]):::none --> metadata_w_clusters_tibble.ATAC.immune_human_2x(["metadata_w_clusters_tibble.ATAC.immune_human_2x"]):::none
    LSI_clusters.ATAC.immune_human_2x(["LSI_clusters.ATAC.immune_human_2x"]):::none --> metadata_w_clusters_tibble.ATAC.immune_human_2x(["metadata_w_clusters_tibble.ATAC.immune_human_2x"]):::none
    UMAP_embeddings_tibble.ATAC.immune_human_2x(["UMAP_embeddings_tibble.ATAC.immune_human_2x"]):::none --> metadata_w_clusters_tibble.ATAC.immune_human_2x(["metadata_w_clusters_tibble.ATAC.immune_human_2x"]):::none
    PCA_clusters.GEX.immune_human_2x(["PCA_clusters.GEX.immune_human_2x"]):::none --> metadata_w_clusters_tibble.GEX.immune_human_2x(["metadata_w_clusters_tibble.GEX.immune_human_2x"]):::none
    metadata_tibble.GEX.immune_human_2x(["metadata_tibble.GEX.immune_human_2x"]):::none --> metadata_w_clusters_tibble.GEX.immune_human_2x(["metadata_w_clusters_tibble.GEX.immune_human_2x"]):::none
    UMAP_embeddings_tibble.GEX_non_harmony.immune_human_2x(["UMAP_embeddings_tibble.GEX_non_harmony.immune_human_2x"]):::none --> metadata_w_clusters_tibble.GEX.immune_human_2x(["metadata_w_clusters_tibble.GEX.immune_human_2x"]):::none
    UMAP_embeddings_tibble.GEX.immune_human_2x(["UMAP_embeddings_tibble.GEX.immune_human_2x"]):::none --> metadata_w_clusters_tibble.GEX.immune_human_2x(["metadata_w_clusters_tibble.GEX.immune_human_2x"]):::none
    WNN_results.immune_human_2x(["WNN_results.immune_human_2x"]):::none --> metadata_w_clusters_tibble.WNN.immune_human_2x(["metadata_w_clusters_tibble.WNN.immune_human_2x"]):::none
    metadata_w_cell_types_tibble.ATAC.immune_human_2x(["metadata_w_cell_types_tibble.ATAC.immune_human_2x"]):::none --> metadata_w_clusters_tibble.WNN.immune_human_2x(["metadata_w_clusters_tibble.WNN.immune_human_2x"]):::none
    clusters_tibble.WNN.immune_human_2x(["clusters_tibble.WNN.immune_human_2x"]):::none --> metadata_w_clusters_tibble.WNN.immune_human_2x(["metadata_w_clusters_tibble.WNN.immune_human_2x"]):::none
    UMAP_embeddings_tibble.WNN.immune_human_2x(["UMAP_embeddings_tibble.WNN.immune_human_2x"]):::none --> metadata_w_clusters_tibble.WNN.immune_human_2x(["metadata_w_clusters_tibble.WNN.immune_human_2x"]):::none
    UMAP_embeddings_tibble.GEX.immune_human_2x(["UMAP_embeddings_tibble.GEX.immune_human_2x"]):::none --> metadata_w_clusters_tibble.WNN.immune_human_2x(["metadata_w_clusters_tibble.WNN.immune_human_2x"]):::none
    blacklist_GRanges.ATAC.immune_human_2x(["blacklist_GRanges.ATAC.immune_human_2x"]):::none --> metadata_w_QC_tibble.ATAC.immune_human_2x(["metadata_w_QC_tibble.ATAC.immune_human_2x"]):::none
    combined_BPCells_fragment_obj.ATAC.immune_human_2x(["combined_BPCells_fragment_obj.ATAC.immune_human_2x"]):::none --> metadata_w_QC_tibble.ATAC.immune_human_2x(["metadata_w_QC_tibble.ATAC.immune_human_2x"]):::none
    aggregated_cellranger_ref_list.immune_human_2x(["aggregated_cellranger_ref_list.immune_human_2x"]):::none --> metadata_w_QC_tibble.ATAC.immune_human_2x(["metadata_w_QC_tibble.ATAC.immune_human_2x"]):::none
    consensus_peak_GRanges.ATAC.immune_human_2x(["consensus_peak_GRanges.ATAC.immune_human_2x"]):::none --> metadata_w_QC_tibble.ATAC.immune_human_2x(["metadata_w_QC_tibble.ATAC.immune_human_2x"]):::none
    consensus_peak_BPCells_matrix.ATAC.immune_human_2x(["consensus_peak_BPCells_matrix.ATAC.immune_human_2x"]):::none --> metadata_w_QC_tibble.ATAC.immune_human_2x(["metadata_w_QC_tibble.ATAC.immune_human_2x"]):::none
    metadata_w_cell_types_tibble.GEX.immune_human_2x(["metadata_w_cell_types_tibble.GEX.immune_human_2x"]):::none --> metadata_w_QC_tibble.ATAC.immune_human_2x(["metadata_w_QC_tibble.ATAC.immune_human_2x"]):::none
    aggregated_cellranger_ref_list.immune_human_2x(["aggregated_cellranger_ref_list.immune_human_2x"]):::none --> organism_chr.immune_human_2x(["organism_chr.immune_human_2x"]):::none
    GEX_cellranger_kept_metadata_tibble.immune_human_2x(["GEX_cellranger_kept_metadata_tibble.immune_human_2x"]):::none --> PCA_BPCells.GEX.immune_human_2x(["PCA_BPCells.GEX.immune_human_2x"]):::none
    organism_chr.immune_human_2x(["organism_chr.immune_human_2x"]):::none --> PCA_BPCells.GEX.immune_human_2x(["PCA_BPCells.GEX.immune_human_2x"]):::none
    reaction_ID_metadata_tibble.immune_human_2x(["reaction_ID_metadata_tibble.immune_human_2x"]):::none --> PCA_BPCells.GEX.immune_human_2x(["PCA_BPCells.GEX.immune_human_2x"]):::none
    donor_id_metadata_tibble.immune_human_2x(["donor_id_metadata_tibble.immune_human_2x"]):::none --> PCA_BPCells.GEX.immune_human_2x(["PCA_BPCells.GEX.immune_human_2x"]):::none
    aggregated_counts_BPCells_matrix.GEX.immune_human_2x(["aggregated_counts_BPCells_matrix.GEX.immune_human_2x"]):::none --> PCA_BPCells.GEX.immune_human_2x(["PCA_BPCells.GEX.immune_human_2x"]):::none
    harmony_embeddings_matrix.GEX.immune_human_2x(["harmony_embeddings_matrix.GEX.immune_human_2x"]):::none --> PCA_clusters.GEX.immune_human_2x(["PCA_clusters.GEX.immune_human_2x"]):::none
    peak_calling_cluster_names.ATAC.immune_human_2x(["peak_calling_cluster_names.ATAC.immune_human_2x"]):::none --> peak_calling_cluster_discovery_tibble.ATAC.immune_human_2x(["peak_calling_cluster_discovery_tibble.ATAC.immune_human_2x"]):::none
    BCs_per_peak_cluster_list.ATAC.immune_human_2x(["BCs_per_peak_cluster_list.ATAC.immune_human_2x"]):::none --> peak_calling_cluster_discovery_tibble.ATAC.immune_human_2x(["peak_calling_cluster_discovery_tibble.ATAC.immune_human_2x"]):::none
    metadata_w_cell_types_tibble.GEX.immune_human_2x(["metadata_w_cell_types_tibble.GEX.immune_human_2x"]):::none --> peak_calling_cluster_names.ATAC.immune_human_2x(["peak_calling_cluster_names.ATAC.immune_human_2x"]):::none
    peaks_per_cluster_narrowPeaks.peaks.ATAC.immune_human_2x["peaks_per_cluster_narrowPeaks.peaks.ATAC.immune_human_2x"]:::none --> peak_GRanges_per_cluster.ATAC.immune_human_2x["peak_GRanges_per_cluster.ATAC.immune_human_2x"]:::none
    blacklist_GRanges.ATAC.immune_human_2x(["blacklist_GRanges.ATAC.immune_human_2x"]):::none --> peak_GRanges_per_cluster.ATAC.immune_human_2x["peak_GRanges_per_cluster.ATAC.immune_human_2x"]:::none
    aggregated_cellranger_ref_list.immune_human_2x(["aggregated_cellranger_ref_list.immune_human_2x"]):::none --> peak_GRanges_per_cluster.ATAC.immune_human_2x["peak_GRanges_per_cluster.ATAC.immune_human_2x"]:::none
    consensus_peak_BPCells_matrix.ATAC.immune_human_2x(["consensus_peak_BPCells_matrix.ATAC.immune_human_2x"]):::none --> peak_QC_filtered_BPCells_matrix.ATAC.immune_human_2x(["peak_QC_filtered_BPCells_matrix.ATAC.immune_human_2x"]):::none
    QC_filtered_BCs.ATAC.immune_human_2x(["QC_filtered_BCs.ATAC.immune_human_2x"]):::none --> peak_QC_filtered_BPCells_matrix.ATAC.immune_human_2x(["peak_QC_filtered_BPCells_matrix.ATAC.immune_human_2x"]):::none
    aggregated_cellranger_ref_list.immune_human_2x(["aggregated_cellranger_ref_list.immune_human_2x"]):::none --> peaks_per_cluster_narrowPeaks.peaks.ATAC.immune_human_2x["peaks_per_cluster_narrowPeaks.peaks.ATAC.immune_human_2x"]:::none
    fragments_per_peak_calling_cluster_discovery.fragments.ATAC.immune_human_2x["fragments_per_peak_calling_cluster_discovery.fragments.ATAC.immune_human_2x"]:::none --> peaks_per_cluster_narrowPeaks.peaks.ATAC.immune_human_2x["peaks_per_cluster_narrowPeaks.peaks.ATAC.immune_human_2x"]:::none
    combined_BPCells_fragment_obj.ATAC.immune_human_2x(["combined_BPCells_fragment_obj.ATAC.immune_human_2x"]):::none --> peaks_per_cluster_narrowPeaks.peaks.ATAC.immune_human_2x["peaks_per_cluster_narrowPeaks.peaks.ATAC.immune_human_2x"]:::none
    peak_calling_cluster_discovery_tibble.ATAC.immune_human_2x(["peak_calling_cluster_discovery_tibble.ATAC.immune_human_2x"]):::none --> peaks_per_cluster_narrowPeaks.peaks.ATAC.immune_human_2x["peaks_per_cluster_narrowPeaks.peaks.ATAC.immune_human_2x"]:::none
    cellranger_summary_file.healthy_PBMC_human(["cellranger_summary_file.healthy_PBMC_human"]):::none --> per_barcode_metrics_tibble.healthy_PBMC_human(["per_barcode_metrics_tibble.healthy_PBMC_human"]):::none
    cellranger_summary_file.lymphoma_lymph_human(["cellranger_summary_file.lymphoma_lymph_human"]):::none --> per_barcode_metrics_tibble.lymphoma_lymph_human(["per_barcode_metrics_tibble.lymphoma_lymph_human"]):::none
    metadata_w_QC_tibble.ATAC.immune_human_2x(["metadata_w_QC_tibble.ATAC.immune_human_2x"]):::none --> QC_excluded_BCs_list.ATAC.immune_human_2x(["QC_excluded_BCs_list.ATAC.immune_human_2x"]):::none
    QC_excluded_BCs_list.ATAC.immune_human_2x(["QC_excluded_BCs_list.ATAC.immune_human_2x"]):::none --> QC_filtered_BCs.ATAC.immune_human_2x(["QC_filtered_BCs.ATAC.immune_human_2x"]):::none
    metadata_w_QC_tibble.ATAC.immune_human_2x(["metadata_w_QC_tibble.ATAC.immune_human_2x"]):::none --> QC_filtered_BCs.ATAC.immune_human_2x(["QC_filtered_BCs.ATAC.immune_human_2x"]):::none
    reaction_ID_metadata_tsv.immune_human_2x(["reaction_ID_metadata_tsv.immune_human_2x"]):::none --> reaction_ID_metadata_tibble.immune_human_2x(["reaction_ID_metadata_tibble.immune_human_2x"]):::none
    harmony_embeddings_matrix.ATAC.immune_human_2x(["harmony_embeddings_matrix.ATAC.immune_human_2x"]):::none --> SCAVENGE_graph_matrix.SCAVENGE.LSI_harmony_SNN.genetic_enrichment.immune_human_2x(["SCAVENGE_graph_matrix.SCAVENGE.LSI_harmony_SNN.genetic_enrichment.immune_human_2x"]):::none
    harmony_embeddings_matrix.GEX.immune_human_2x(["harmony_embeddings_matrix.GEX.immune_human_2x"]):::none --> SCAVENGE_graph_matrix.SCAVENGE.PCA_harmony_SNN.genetic_enrichment.immune_human_2x(["SCAVENGE_graph_matrix.SCAVENGE.PCA_harmony_SNN.genetic_enrichment.immune_human_2x"]):::none
    WNN_results.immune_human_2x(["WNN_results.immune_human_2x"]):::none --> SCAVENGE_graph_matrix.SCAVENGE.WNN_harmony_SNN.genetic_enrichment.immune_human_2x(["SCAVENGE_graph_matrix.SCAVENGE.WNN_harmony_SNN.genetic_enrichment.immune_human_2x"]):::none
    SCAVENGE_TRS_summary_tibbles.SCAVENGE.LSI_harmony_SNN.genetic_enrichment.immune_human_2x["SCAVENGE_TRS_summary_tibbles.SCAVENGE.LSI_harmony_SNN.genetic_enrichment.immune_human_2x"]:::none --> SCAVENGE_TRS_summary_tibble.SCAVENGE.LSI_harmony_SNN.genetic_enrichment.immune_human_2x(["SCAVENGE_TRS_summary_tibble.SCAVENGE.LSI_harmony_SNN.genetic_enrichment.immune_human_2x"]):::none
    SCAVENGE_TRS_summary_tibbles.SCAVENGE.PCA_harmony_SNN.genetic_enrichment.immune_human_2x["SCAVENGE_TRS_summary_tibbles.SCAVENGE.PCA_harmony_SNN.genetic_enrichment.immune_human_2x"]:::none --> SCAVENGE_TRS_summary_tibble.SCAVENGE.PCA_harmony_SNN.genetic_enrichment.immune_human_2x(["SCAVENGE_TRS_summary_tibble.SCAVENGE.PCA_harmony_SNN.genetic_enrichment.immune_human_2x"]):::none
    SCAVENGE_TRS_summary_tibbles.SCAVENGE.WNN_harmony_SNN.genetic_enrichment.immune_human_2x["SCAVENGE_TRS_summary_tibbles.SCAVENGE.WNN_harmony_SNN.genetic_enrichment.immune_human_2x"]:::none --> SCAVENGE_TRS_summary_tibble.SCAVENGE.WNN_harmony_SNN.genetic_enrichment.immune_human_2x(["SCAVENGE_TRS_summary_tibble.SCAVENGE.WNN_harmony_SNN.genetic_enrichment.immune_human_2x"]):::none
    SCAVENGE_TRS_tibbles.SCAVENGE.LSI_harmony_SNN.genetic_enrichment.immune_human_2x["SCAVENGE_TRS_tibbles.SCAVENGE.LSI_harmony_SNN.genetic_enrichment.immune_human_2x"]:::none --> SCAVENGE_TRS_summary_tibbles.SCAVENGE.LSI_harmony_SNN.genetic_enrichment.immune_human_2x["SCAVENGE_TRS_summary_tibbles.SCAVENGE.LSI_harmony_SNN.genetic_enrichment.immune_human_2x"]:::none
    metadata_w_cell_types_tibble.WNN.immune_human_2x(["metadata_w_cell_types_tibble.WNN.immune_human_2x"]):::none --> SCAVENGE_TRS_summary_tibbles.SCAVENGE.LSI_harmony_SNN.genetic_enrichment.immune_human_2x["SCAVENGE_TRS_summary_tibbles.SCAVENGE.LSI_harmony_SNN.genetic_enrichment.immune_human_2x"]:::none
    metadata_w_cell_types_tibble.WNN.immune_human_2x(["metadata_w_cell_types_tibble.WNN.immune_human_2x"]):::none --> SCAVENGE_TRS_summary_tibbles.SCAVENGE.PCA_harmony_SNN.genetic_enrichment.immune_human_2x["SCAVENGE_TRS_summary_tibbles.SCAVENGE.PCA_harmony_SNN.genetic_enrichment.immune_human_2x"]:::none
    SCAVENGE_TRS_tibbles.SCAVENGE.PCA_harmony_SNN.genetic_enrichment.immune_human_2x["SCAVENGE_TRS_tibbles.SCAVENGE.PCA_harmony_SNN.genetic_enrichment.immune_human_2x"]:::none --> SCAVENGE_TRS_summary_tibbles.SCAVENGE.PCA_harmony_SNN.genetic_enrichment.immune_human_2x["SCAVENGE_TRS_summary_tibbles.SCAVENGE.PCA_harmony_SNN.genetic_enrichment.immune_human_2x"]:::none
    SCAVENGE_TRS_tibbles.SCAVENGE.WNN_harmony_SNN.genetic_enrichment.immune_human_2x["SCAVENGE_TRS_tibbles.SCAVENGE.WNN_harmony_SNN.genetic_enrichment.immune_human_2x"]:::none --> SCAVENGE_TRS_summary_tibbles.SCAVENGE.WNN_harmony_SNN.genetic_enrichment.immune_human_2x["SCAVENGE_TRS_summary_tibbles.SCAVENGE.WNN_harmony_SNN.genetic_enrichment.immune_human_2x"]:::none
    metadata_w_cell_types_tibble.WNN.immune_human_2x(["metadata_w_cell_types_tibble.WNN.immune_human_2x"]):::none --> SCAVENGE_TRS_summary_tibbles.SCAVENGE.WNN_harmony_SNN.genetic_enrichment.immune_human_2x["SCAVENGE_TRS_summary_tibbles.SCAVENGE.WNN_harmony_SNN.genetic_enrichment.immune_human_2x"]:::none
    SCAVENGE_graph_matrix.SCAVENGE.LSI_harmony_SNN.genetic_enrichment.immune_human_2x(["SCAVENGE_graph_matrix.SCAVENGE.LSI_harmony_SNN.genetic_enrichment.immune_human_2x"]):::none --> SCAVENGE_TRS_tibbles.SCAVENGE.LSI_harmony_SNN.genetic_enrichment.immune_human_2x["SCAVENGE_TRS_tibbles.SCAVENGE.LSI_harmony_SNN.genetic_enrichment.immune_human_2x"]:::none
    GWAS_chromVAR_ZScore_records.single_cell.genetic_enrichment.immune_human_2x["GWAS_chromVAR_ZScore_records.single_cell.genetic_enrichment.immune_human_2x"]:::none --> SCAVENGE_TRS_tibbles.SCAVENGE.LSI_harmony_SNN.genetic_enrichment.immune_human_2x["SCAVENGE_TRS_tibbles.SCAVENGE.LSI_harmony_SNN.genetic_enrichment.immune_human_2x"]:::none
    GWAS_chromVAR_ZScore_records.single_cell.genetic_enrichment.immune_human_2x["GWAS_chromVAR_ZScore_records.single_cell.genetic_enrichment.immune_human_2x"]:::none --> SCAVENGE_TRS_tibbles.SCAVENGE.PCA_harmony_SNN.genetic_enrichment.immune_human_2x["SCAVENGE_TRS_tibbles.SCAVENGE.PCA_harmony_SNN.genetic_enrichment.immune_human_2x"]:::none
    SCAVENGE_graph_matrix.SCAVENGE.PCA_harmony_SNN.genetic_enrichment.immune_human_2x(["SCAVENGE_graph_matrix.SCAVENGE.PCA_harmony_SNN.genetic_enrichment.immune_human_2x"]):::none --> SCAVENGE_TRS_tibbles.SCAVENGE.PCA_harmony_SNN.genetic_enrichment.immune_human_2x["SCAVENGE_TRS_tibbles.SCAVENGE.PCA_harmony_SNN.genetic_enrichment.immune_human_2x"]:::none
    SCAVENGE_graph_matrix.SCAVENGE.WNN_harmony_SNN.genetic_enrichment.immune_human_2x(["SCAVENGE_graph_matrix.SCAVENGE.WNN_harmony_SNN.genetic_enrichment.immune_human_2x"]):::none --> SCAVENGE_TRS_tibbles.SCAVENGE.WNN_harmony_SNN.genetic_enrichment.immune_human_2x["SCAVENGE_TRS_tibbles.SCAVENGE.WNN_harmony_SNN.genetic_enrichment.immune_human_2x"]:::none
    GWAS_chromVAR_ZScore_records.single_cell.genetic_enrichment.immune_human_2x["GWAS_chromVAR_ZScore_records.single_cell.genetic_enrichment.immune_human_2x"]:::none --> SCAVENGE_TRS_tibbles.SCAVENGE.WNN_harmony_SNN.genetic_enrichment.immune_human_2x["SCAVENGE_TRS_tibbles.SCAVENGE.WNN_harmony_SNN.genetic_enrichment.immune_human_2x"]:::none
    LSI_loadings_tibble.ATAC.immune_human_2x(["LSI_loadings_tibble.ATAC.immune_human_2x"]):::none --> scDblFinder_feature_groups.ATAC.immune_human_2x(["scDblFinder_feature_groups.ATAC.immune_human_2x"]):::none
    scDblFinder_feature_groups.ATAC.immune_human_2x(["scDblFinder_feature_groups.ATAC.immune_human_2x"]):::none --> scDblFinder_feature_matrix.ATAC.immune_human_2x(["scDblFinder_feature_matrix.ATAC.immune_human_2x"]):::none
    peak_QC_filtered_BPCells_matrix.ATAC.immune_human_2x(["peak_QC_filtered_BPCells_matrix.ATAC.immune_human_2x"]):::none --> scDblFinder_feature_matrix.ATAC.immune_human_2x(["scDblFinder_feature_matrix.ATAC.immune_human_2x"]):::none
    QC_filtered_BCs.ATAC.immune_human_2x(["QC_filtered_BCs.ATAC.immune_human_2x"]):::none --> scDblFinder_reaction_tibble.ATAC.immune_human_2x(["scDblFinder_reaction_tibble.ATAC.immune_human_2x"]):::none
    metadata_w_cell_types_unfiltered_tibble.ATAC.immune_human_2x(["metadata_w_cell_types_unfiltered_tibble.ATAC.immune_human_2x"]):::none --> scDblFinder_reaction_tibble.ATAC.immune_human_2x(["scDblFinder_reaction_tibble.ATAC.immune_human_2x"]):::none
    metadata_w_cell_types_unfiltered_tibble.GEX.immune_human_2x(["metadata_w_cell_types_unfiltered_tibble.GEX.immune_human_2x"]):::none --> scDblFinder_reaction_tibble.GEX.immune_human_2x(["scDblFinder_reaction_tibble.GEX.immune_human_2x"]):::none
    scDblFinder_feature_matrix.ATAC.immune_human_2x(["scDblFinder_feature_matrix.ATAC.immune_human_2x"]):::none --> scDblFinder_results_by_reaction_tibble.ATAC.immune_human_2x["scDblFinder_results_by_reaction_tibble.ATAC.immune_human_2x"]:::none
    scDblFinder_reaction_tibble.ATAC.immune_human_2x(["scDblFinder_reaction_tibble.ATAC.immune_human_2x"]):::none --> scDblFinder_results_by_reaction_tibble.ATAC.immune_human_2x["scDblFinder_results_by_reaction_tibble.ATAC.immune_human_2x"]:::none
    aggregated_counts_BPCells_matrix.GEX.immune_human_2x(["aggregated_counts_BPCells_matrix.GEX.immune_human_2x"]):::none --> scDblFinder_results_by_reaction_tibble.GEX.immune_human_2x["scDblFinder_results_by_reaction_tibble.GEX.immune_human_2x"]:::none
    scDblFinder_reaction_tibble.GEX.immune_human_2x(["scDblFinder_reaction_tibble.GEX.immune_human_2x"]):::none --> scDblFinder_results_by_reaction_tibble.GEX.immune_human_2x["scDblFinder_results_by_reaction_tibble.GEX.immune_human_2x"]:::none
    scDblFinder_results_by_reaction_tibble.ATAC.immune_human_2x["scDblFinder_results_by_reaction_tibble.ATAC.immune_human_2x"]:::none --> scDblFinder_results_df.ATAC.immune_human_2x(["scDblFinder_results_df.ATAC.immune_human_2x"]):::none
    scDblFinder_results_by_reaction_tibble.GEX.immune_human_2x["scDblFinder_results_by_reaction_tibble.GEX.immune_human_2x"]:::none --> scDblFinder_results_df.GEX.immune_human_2x(["scDblFinder_results_df.GEX.immune_human_2x"]):::none
    gene_features_df.immune_human_2x(["gene_features_df.immune_human_2x"]):::none --> UCell_GEX_marker_genes_list.immune_human_2x(["UCell_GEX_marker_genes_list.immune_human_2x"]):::none
    harmony_embeddings_matrix.ATAC.immune_human_2x(["harmony_embeddings_matrix.ATAC.immune_human_2x"]):::none --> UMAP_embeddings_tibble.ATAC.immune_human_2x(["UMAP_embeddings_tibble.ATAC.immune_human_2x"]):::none
    PCA_BPCells.GEX.immune_human_2x(["PCA_BPCells.GEX.immune_human_2x"]):::none --> UMAP_embeddings_tibble.GEX_non_harmony.immune_human_2x(["UMAP_embeddings_tibble.GEX_non_harmony.immune_human_2x"]):::none
    harmony_embeddings_matrix.GEX.immune_human_2x(["harmony_embeddings_matrix.GEX.immune_human_2x"]):::none --> UMAP_embeddings_tibble.GEX.immune_human_2x(["UMAP_embeddings_tibble.GEX.immune_human_2x"]):::none
    WNN_results.immune_human_2x(["WNN_results.immune_human_2x"]):::none --> UMAP_embeddings_tibble.WNN.immune_human_2x(["UMAP_embeddings_tibble.WNN.immune_human_2x"]):::none
    cellsnp_dir.healthy_PBMC_human(["cellsnp_dir.healthy_PBMC_human"]):::none --> vireo_donor_ids_tibble.healthy_PBMC_human(["vireo_donor_ids_tibble.healthy_PBMC_human"]):::none
    cellranger_barcodes_tsv.healthy_PBMC_human(["cellranger_barcodes_tsv.healthy_PBMC_human"]):::none --> vireo_donor_ids_tibble.healthy_PBMC_human(["vireo_donor_ids_tibble.healthy_PBMC_human"]):::none
    cellsnp_dir.lymphoma_lymph_human(["cellsnp_dir.lymphoma_lymph_human"]):::none --> vireo_donor_ids_tibble.lymphoma_lymph_human(["vireo_donor_ids_tibble.lymphoma_lymph_human"]):::none
    cellranger_barcodes_tsv.lymphoma_lymph_human(["cellranger_barcodes_tsv.lymphoma_lymph_human"]):::none --> vireo_donor_ids_tibble.lymphoma_lymph_human(["vireo_donor_ids_tibble.lymphoma_lymph_human"]):::none
    peak_GRanges_per_cluster.ATAC.immune_human_2x["peak_GRanges_per_cluster.ATAC.immune_human_2x"]:::none --> within_clusters_collapsed_peaks_per_cluster_GRanges.ATAC.immune_human_2x["within_clusters_collapsed_peaks_per_cluster_GRanges.ATAC.immune_human_2x"]:::none
    peak_calling_cluster_names.ATAC.immune_human_2x(["peak_calling_cluster_names.ATAC.immune_human_2x"]):::none --> within_clusters_collapsed_peaks_per_cluster_GRanges.ATAC.immune_human_2x["within_clusters_collapsed_peaks_per_cluster_GRanges.ATAC.immune_human_2x"]:::none
    embedding_matrices.WNN.immune_human_2x(["embedding_matrices.WNN.immune_human_2x"]):::none --> WNN_results_raw.immune_human_2x(["WNN_results_raw.immune_human_2x"]):::none
    WNN_results_raw.immune_human_2x(["WNN_results_raw.immune_human_2x"]):::none --> WNN_results.immune_human_2x(["WNN_results.immune_human_2x"]):::none
    embedding_matrices.WNN.immune_human_2x(["embedding_matrices.WNN.immune_human_2x"]):::none --> WNN_results.immune_human_2x(["WNN_results.immune_human_2x"]):::none
    clusters_tibble.WNN.immune_human_2x(["clusters_tibble.WNN.immune_human_2x"]):::none --> WNN_results.immune_human_2x(["WNN_results.immune_human_2x"]):::none
