%%{init: {'flowchart': {'defaultRenderer': 'elk'}}}%%
flowchart TB
  chromVAR_obj.ATAC.brain_mouse(["chromVAR_obj.ATAC.&lt;aggregation_name&gt;"]):::none --> chromVAR_background_bins.ATAC.brain_mouse(["chromVAR_background_bins.ATAC.&lt;aggregation_name&gt;"]):::none
  chromVAR_peak_expectation.ATAC.brain_mouse(["chromVAR_peak_expectation.ATAC.&lt;aggregation_name&gt;"]):::none --> chromVAR_background_bins.ATAC.brain_mouse(["chromVAR_background_bins.ATAC.&lt;aggregation_name&gt;"]):::none
  chromVAR_obj.ATAC.brain_mouse(["chromVAR_obj.ATAC.&lt;aggregation_name&gt;"]):::none --> chromVAR_peak_expectation.ATAC.brain_mouse(["chromVAR_peak_expectation.ATAC.&lt;aggregation_name&gt;"]):::none
  open_targets_credible_set_dataset_path(["open_targets_credible_set_dataset_path"]):::none --> GWAS_inputs_tibble.genetic_enrichment.immune_human_2x(["GWAS_inputs_tibble.&lt;module_name&gt;.&lt;aggregation_name&gt;"]):::none
  ZScore_records.single_nucleus.genetic_enrichment.immune_human_2x["ZScore_records.single_nucleus.&lt;module_name&gt;.&lt;aggregation_name&gt;"]:::none --> TRS_tibbles.LSI_harmony_SNN.SCAVENGE.single_nucleus.genetic_enrichment.immune_human_2x["TRS_tibbles.LSI_harmony_SNN.SCAVENGE.single_nucleus.&lt;module_name&gt;.&lt;aggregation_name&gt;"]:::none
  graph_matrix.LSI_harmony_SNN.SCAVENGE.single_nucleus.genetic_enrichment.immune_human_2x(["graph_matrix.LSI_harmony_SNN.SCAVENGE.single_nucleus.&lt;module_name&gt;.&lt;aggregation_name&gt;"]):::none --> TRS_tibbles.LSI_harmony_SNN.SCAVENGE.single_nucleus.genetic_enrichment.immune_human_2x["TRS_tibbles.LSI_harmony_SNN.SCAVENGE.single_nucleus.&lt;module_name&gt;.&lt;aggregation_name&gt;"]:::none
  graph_matrix.PCA_harmony_SNN.SCAVENGE.single_nucleus.genetic_enrichment.immune_human_2x(["graph_matrix.PCA_harmony_SNN.SCAVENGE.single_nucleus.&lt;module_name&gt;.&lt;aggregation_name&gt;"]):::none --> TRS_tibbles.PCA_harmony_SNN.SCAVENGE.single_nucleus.genetic_enrichment.immune_human_2x["TRS_tibbles.PCA_harmony_SNN.SCAVENGE.single_nucleus.&lt;module_name&gt;.&lt;aggregation_name&gt;"]:::none
  ZScore_records.single_nucleus.genetic_enrichment.immune_human_2x["ZScore_records.single_nucleus.&lt;module_name&gt;.&lt;aggregation_name&gt;"]:::none --> TRS_tibbles.PCA_harmony_SNN.SCAVENGE.single_nucleus.genetic_enrichment.immune_human_2x["TRS_tibbles.PCA_harmony_SNN.SCAVENGE.single_nucleus.&lt;module_name&gt;.&lt;aggregation_name&gt;"]:::none
  graph_matrix.WNN_harmony_SNN.SCAVENGE.single_nucleus.genetic_enrichment.immune_human_2x(["graph_matrix.WNN_harmony_SNN.SCAVENGE.single_nucleus.&lt;module_name&gt;.&lt;aggregation_name&gt;"]):::none --> TRS_tibbles.WNN_harmony_SNN.SCAVENGE.single_nucleus.genetic_enrichment.immune_human_2x["TRS_tibbles.WNN_harmony_SNN.SCAVENGE.single_nucleus.&lt;module_name&gt;.&lt;aggregation_name&gt;"]:::none
  ZScore_records.single_nucleus.genetic_enrichment.immune_human_2x["ZScore_records.single_nucleus.&lt;module_name&gt;.&lt;aggregation_name&gt;"]:::none --> TRS_tibbles.WNN_harmony_SNN.SCAVENGE.single_nucleus.genetic_enrichment.immune_human_2x["TRS_tibbles.WNN_harmony_SNN.SCAVENGE.single_nucleus.&lt;module_name&gt;.&lt;aggregation_name&gt;"]:::none
  chromVAR_obj.ATAC.brain_mouse(["chromVAR_obj.ATAC.&lt;aggregation_name&gt;"]):::none --> ZScore_records.single_nucleus.genetic_enrichment.immune_human_2x["ZScore_records.single_nucleus.&lt;module_name&gt;.&lt;aggregation_name&gt;"]:::none
  chromVAR_background_bins.ATAC.brain_mouse(["chromVAR_background_bins.ATAC.&lt;aggregation_name&gt;"]):::none --> ZScore_records.single_nucleus.genetic_enrichment.immune_human_2x["ZScore_records.single_nucleus.&lt;module_name&gt;.&lt;aggregation_name&gt;"]:::none
  chromVAR_peak_expectation.ATAC.brain_mouse(["chromVAR_peak_expectation.ATAC.&lt;aggregation_name&gt;"]):::none --> ZScore_records.single_nucleus.genetic_enrichment.immune_human_2x["ZScore_records.single_nucleus.&lt;module_name&gt;.&lt;aggregation_name&gt;"]:::none
  chromVAR_obj.ATAC.brain_mouse(["chromVAR_obj.ATAC.&lt;aggregation_name&gt;"]):::none --> GWAS_peak_weight_records.genetic_enrichment.immune_human_2x["GWAS_peak_weight_records.&lt;module_name&gt;.&lt;aggregation_name&gt;"]:::none
  GWAS_inputs_tibble.genetic_enrichment.immune_human_2x(["GWAS_inputs_tibble.&lt;module_name&gt;.&lt;aggregation_name&gt;"]):::none --> GWAS_peak_weight_records.genetic_enrichment.immune_human_2x["GWAS_peak_weight_records.&lt;module_name&gt;.&lt;aggregation_name&gt;"]:::none
  open_targets_credible_set_dataset_path(["open_targets_credible_set_dataset_path"]):::none --> GWAS_peak_weight_records.genetic_enrichment.immune_human_2x["GWAS_peak_weight_records.&lt;module_name&gt;.&lt;aggregation_name&gt;"]:::none
  TRS_tibbles.LSI_harmony_SNN.SCAVENGE.single_nucleus.genetic_enrichment.immune_human_2x["TRS_tibbles.LSI_harmony_SNN.SCAVENGE.single_nucleus.&lt;module_name&gt;.&lt;aggregation_name&gt;"]:::none --> TRS_summary_tibble.LSI_harmony_SNN.SCAVENGE.single_nucleus.genetic_enrichment.immune_human_2x(["TRS_summary_tibble.LSI_harmony_SNN.SCAVENGE.single_nucleus.&lt;module_name&gt;.&lt;aggregation_name&gt;"]):::none
  TRS_tibbles.PCA_harmony_SNN.SCAVENGE.single_nucleus.genetic_enrichment.immune_human_2x["TRS_tibbles.PCA_harmony_SNN.SCAVENGE.single_nucleus.&lt;module_name&gt;.&lt;aggregation_name&gt;"]:::none --> TRS_summary_tibble.PCA_harmony_SNN.SCAVENGE.single_nucleus.genetic_enrichment.immune_human_2x(["TRS_summary_tibble.PCA_harmony_SNN.SCAVENGE.single_nucleus.&lt;module_name&gt;.&lt;aggregation_name&gt;"]):::none
  TRS_tibbles.WNN_harmony_SNN.SCAVENGE.single_nucleus.genetic_enrichment.immune_human_2x["TRS_tibbles.WNN_harmony_SNN.SCAVENGE.single_nucleus.&lt;module_name&gt;.&lt;aggregation_name&gt;"]:::none --> TRS_summary_tibble.WNN_harmony_SNN.SCAVENGE.single_nucleus.genetic_enrichment.immune_human_2x(["TRS_summary_tibble.WNN_harmony_SNN.SCAVENGE.single_nucleus.&lt;module_name&gt;.&lt;aggregation_name&gt;"]):::none
  GWAS_peak_weight_records.genetic_enrichment.immune_human_2x["GWAS_peak_weight_records.&lt;module_name&gt;.&lt;aggregation_name&gt;"]:::none --> ZScore_records.single_nucleus.genetic_enrichment.immune_human_2x["ZScore_records.single_nucleus.&lt;module_name&gt;.&lt;aggregation_name&gt;"]:::none
  ZScore_records.single_nucleus.genetic_enrichment.immune_human_2x["ZScore_records.single_nucleus.&lt;module_name&gt;.&lt;aggregation_name&gt;"]:::none --> ZScores_tibble.summarized.single_nucleus.genetic_enrichment.immune_human_2x(["ZScores_tibble.summarized.single_nucleus.&lt;module_name&gt;.&lt;aggregation_name&gt;"]):::none
