%%{init: {'flowchart': {'defaultRenderer': 'elk'}}}%%
flowchart TB
  chromVAR_peak_contribution_tibble.cell_type_pseudobulk.genetic_enrichment.immune_human_2x(["chromVAR_peak_contribution_tibble.cell_type_pseudobulk.&lt;module_name&gt;.&lt;aggregation_name&gt;"]):::none --> chromVAR_deviation_tibble.cell_type_pseudobulk.genetic_enrichment.immune_human_2x(["chromVAR_deviation_tibble.cell_type_pseudobulk.&lt;module_name&gt;.&lt;aggregation_name&gt;"]):::none
  chromVAR_variant_contribution_tibble.cell_type_pseudobulk.genetic_enrichment.immune_human_2x(["chromVAR_variant_contribution_tibble.cell_type_pseudobulk.&lt;module_name&gt;.&lt;aggregation_name&gt;"]):::none --> chromVAR_locus_contribution_tibble.cell_type_pseudobulk.genetic_enrichment.immune_human_2x(["chromVAR_locus_contribution_tibble.cell_type_pseudobulk.&lt;module_name&gt;.&lt;aggregation_name&gt;"]):::none
  GWAS_peak_weight_matrix.genetic_enrichment.immune_human_2x(["GWAS_peak_weight_matrix.&lt;module_name&gt;.&lt;aggregation_name&gt;"]):::none --> chromVAR_peak_contribution_tibble.cell_type_pseudobulk.genetic_enrichment.immune_human_2x(["chromVAR_peak_contribution_tibble.cell_type_pseudobulk.&lt;module_name&gt;.&lt;aggregation_name&gt;"]):::none
  GWAS_inputs_tibble.genetic_enrichment.immune_human_2x(["GWAS_inputs_tibble.&lt;module_name&gt;.&lt;aggregation_name&gt;"]):::none --> chromVAR_peak_contribution_tibble.cell_type_pseudobulk.genetic_enrichment.immune_human_2x(["chromVAR_peak_contribution_tibble.cell_type_pseudobulk.&lt;module_name&gt;.&lt;aggregation_name&gt;"]):::none
  chromVAR_background_record.cell_type_pseudobulk.genetic_enrichment.immune_human_2x(["chromVAR_background_record.cell_type_pseudobulk.&lt;module_name&gt;.&lt;aggregation_name&gt;"]):::none --> chromVAR_peak_contribution_tibble.cell_type_pseudobulk.genetic_enrichment.immune_human_2x(["chromVAR_peak_contribution_tibble.cell_type_pseudobulk.&lt;module_name&gt;.&lt;aggregation_name&gt;"]):::none
  chromVAR_peak_contribution_tibble.cell_type_pseudobulk.genetic_enrichment.immune_human_2x(["chromVAR_peak_contribution_tibble.cell_type_pseudobulk.&lt;module_name&gt;.&lt;aggregation_name&gt;"]):::none --> chromVAR_variant_contribution_tibble.cell_type_pseudobulk.genetic_enrichment.immune_human_2x(["chromVAR_variant_contribution_tibble.cell_type_pseudobulk.&lt;module_name&gt;.&lt;aggregation_name&gt;"]):::none
  cell_type_pseudobulk_counts_BPCells_matrix_dir.ATAC.genetic_enrichment.immune_human_2x(["cell_type_pseudobulk_counts_BPCells_matrix_dir.ATAC.&lt;module_name&gt;.&lt;aggregation_name&gt;"]):::none --> chromVAR_background_record.cell_type_pseudobulk.genetic_enrichment.immune_human_2x(["chromVAR_background_record.cell_type_pseudobulk.&lt;module_name&gt;.&lt;aggregation_name&gt;"]):::none
  cell_type_pseudobulk_counts_BPCells_matrix_dir.ATAC.genetic_enrichment.immune_human_2x(["cell_type_pseudobulk_counts_BPCells_matrix_dir.ATAC.&lt;module_name&gt;.&lt;aggregation_name&gt;"]):::none --> chromVAR_peak_contribution_tibble.cell_type_pseudobulk.genetic_enrichment.immune_human_2x(["chromVAR_peak_contribution_tibble.cell_type_pseudobulk.&lt;module_name&gt;.&lt;aggregation_name&gt;"]):::none
  cell_type_pseudobulk_counts_BPCells_matrix_dir.ATAC.genetic_enrichment.immune_human_2x(["cell_type_pseudobulk_counts_BPCells_matrix_dir.ATAC.&lt;module_name&gt;.&lt;aggregation_name&gt;"]):::none --> chromVAR_deviation_tibble.cell_type_pseudobulk.genetic_enrichment.immune_human_2x(["chromVAR_deviation_tibble.cell_type_pseudobulk.&lt;module_name&gt;.&lt;aggregation_name&gt;"]):::none
  GWAS_inputs_tibble.genetic_enrichment.immune_human_2x(["GWAS_inputs_tibble.&lt;module_name&gt;.&lt;aggregation_name&gt;"]):::none --> GWAS_peak_weight_matrix.genetic_enrichment.immune_human_2x(["GWAS_peak_weight_matrix.&lt;module_name&gt;.&lt;aggregation_name&gt;"]):::none
  GWAS_inputs_tibble.genetic_enrichment.immune_human_2x(["GWAS_inputs_tibble.&lt;module_name&gt;.&lt;aggregation_name&gt;"]):::none --> chromVAR_variant_contribution_tibble.cell_type_pseudobulk.genetic_enrichment.immune_human_2x(["chromVAR_variant_contribution_tibble.cell_type_pseudobulk.&lt;module_name&gt;.&lt;aggregation_name&gt;"]):::none
  GWAS_inputs_tibble.genetic_enrichment.immune_human_2x(["GWAS_inputs_tibble.&lt;module_name&gt;.&lt;aggregation_name&gt;"]):::none --> chromVAR_locus_contribution_tibble.cell_type_pseudobulk.genetic_enrichment.immune_human_2x(["chromVAR_locus_contribution_tibble.cell_type_pseudobulk.&lt;module_name&gt;.&lt;aggregation_name&gt;"]):::none
