%%{init: {'flowchart': {'defaultRenderer': 'elk'}}}%%
flowchart TB
  GWAS_absolute_effect_peak_weight_records.genetic_enrichment.immune_human_2x(["GWAS_absolute_effect_peak_weight_records.&lt;module_name&gt;.&lt;aggregation_name&gt;"]):::none --> GWAS_absolute_effect_peak_weight_matrix.genetic_enrichment.immune_human_2x(["GWAS_absolute_effect_peak_weight_matrix.&lt;module_name&gt;.&lt;aggregation_name&gt;"]):::none
  GWAS_absolute_effect_peak_weight_matrix.genetic_enrichment.immune_human_2x(["GWAS_absolute_effect_peak_weight_matrix.&lt;module_name&gt;.&lt;aggregation_name&gt;"]):::none --> chromVAR_absolute_effect_deviation_tibble.cell_type_pseudobulk.genetic_enrichment.immune_human_2x(["chromVAR_absolute_effect_deviation_tibble.cell_type_pseudobulk.&lt;module_name&gt;.&lt;aggregation_name&gt;"]):::none
