%%{init: {'flowchart': {'defaultRenderer': 'elk'}}}%%
flowchart TB
  chromVAR_obj.ATAC.brain_mouse(["chromVAR_obj.ATAC"]):::none --> chromVAR_background_bins.ATAC.brain_mouse(["chromVAR_background_bins.ATAC"]):::none
  chromVAR_peak_expectation.ATAC.brain_mouse(["chromVAR_peak_expectation.ATAC"]):::none --> chromVAR_background_bins.ATAC.brain_mouse(["chromVAR_background_bins.ATAC"]):::none
  chromVAR_peak_expectation.ATAC.immune_human_2x(["chromVAR_peak_expectation.ATAC"]):::none --> chromVAR_background_bins.ATAC.immune_human_2x(["chromVAR_background_bins.ATAC"]):::none
  chromVAR_obj.ATAC.immune_human_2x(["chromVAR_obj.ATAC"]):::none --> chromVAR_background_bins.ATAC.immune_human_2x(["chromVAR_background_bins.ATAC"]):::none
  chromVAR_peak_expectation.ATAC.PBMC_human_6x(["chromVAR_peak_expectation.ATAC"]):::none --> chromVAR_background_bins.ATAC.PBMC_human_6x(["chromVAR_background_bins.ATAC"]):::none
  chromVAR_obj.ATAC.PBMC_human_6x(["chromVAR_obj.ATAC"]):::none --> chromVAR_background_bins.ATAC.PBMC_human_6x(["chromVAR_background_bins.ATAC"]):::none
  chromVAR_obj.ATAC.brain_mouse(["chromVAR_obj.ATAC"]):::none --> chromVAR_peak_expectation.ATAC.brain_mouse(["chromVAR_peak_expectation.ATAC"]):::none
  chromVAR_obj.ATAC.immune_human_2x(["chromVAR_obj.ATAC"]):::none --> chromVAR_peak_expectation.ATAC.immune_human_2x(["chromVAR_peak_expectation.ATAC"]):::none
  chromVAR_obj.ATAC.PBMC_human_6x(["chromVAR_obj.ATAC"]):::none --> chromVAR_peak_expectation.ATAC.PBMC_human_6x(["chromVAR_peak_expectation.ATAC"]):::none
  open_targets_credible_set_dataset_path(["open_targets_credible_set_dataset_path"]):::none --> GWAS_inputs_tibble.genetic_enrichment.immune_human_2x(["GWAS_inputs_tibble"]):::none
  open_targets_credible_set_dataset_path(["open_targets_credible_set_dataset_path"]):::none --> GWAS_inputs_tibble.genetic_enrichment.PBMC_human_6x(["GWAS_inputs_tibble"]):::none
  ZScore_records.single_nucleus.genetic_enrichment.immune_human_2x["ZScore_records.single_nucleus"]:::none --> TRS_tibbles.LSI_harmony_SNN.SCAVENGE.single_nucleus.genetic_enrichment.immune_human_2x["TRS_tibbles.LSI_harmony_SNN.SCAVENGE.single_nucleus"]:::none
  graph_matrix.LSI_harmony_SNN.SCAVENGE.single_nucleus.genetic_enrichment.immune_human_2x(["graph_matrix.LSI_harmony_SNN.SCAVENGE.single_nucleus"]):::none --> TRS_tibbles.LSI_harmony_SNN.SCAVENGE.single_nucleus.genetic_enrichment.immune_human_2x["TRS_tibbles.LSI_harmony_SNN.SCAVENGE.single_nucleus"]:::none
  ZScore_records.single_nucleus.genetic_enrichment.PBMC_human_6x["ZScore_records.single_nucleus"]:::none --> TRS_tibbles.LSI_harmony_SNN.SCAVENGE.single_nucleus.genetic_enrichment.PBMC_human_6x["TRS_tibbles.LSI_harmony_SNN.SCAVENGE.single_nucleus"]:::none
  graph_matrix.LSI_harmony_SNN.SCAVENGE.single_nucleus.genetic_enrichment.PBMC_human_6x(["graph_matrix.LSI_harmony_SNN.SCAVENGE.single_nucleus"]):::none --> TRS_tibbles.LSI_harmony_SNN.SCAVENGE.single_nucleus.genetic_enrichment.PBMC_human_6x["TRS_tibbles.LSI_harmony_SNN.SCAVENGE.single_nucleus"]:::none
  graph_matrix.PCA_harmony_SNN.SCAVENGE.single_nucleus.genetic_enrichment.immune_human_2x(["graph_matrix.PCA_harmony_SNN.SCAVENGE.single_nucleus"]):::none --> TRS_tibbles.PCA_harmony_SNN.SCAVENGE.single_nucleus.genetic_enrichment.immune_human_2x["TRS_tibbles.PCA_harmony_SNN.SCAVENGE.single_nucleus"]:::none
  ZScore_records.single_nucleus.genetic_enrichment.immune_human_2x["ZScore_records.single_nucleus"]:::none --> TRS_tibbles.PCA_harmony_SNN.SCAVENGE.single_nucleus.genetic_enrichment.immune_human_2x["TRS_tibbles.PCA_harmony_SNN.SCAVENGE.single_nucleus"]:::none
  ZScore_records.single_nucleus.genetic_enrichment.PBMC_human_6x["ZScore_records.single_nucleus"]:::none --> TRS_tibbles.PCA_harmony_SNN.SCAVENGE.single_nucleus.genetic_enrichment.PBMC_human_6x["TRS_tibbles.PCA_harmony_SNN.SCAVENGE.single_nucleus"]:::none
  graph_matrix.PCA_harmony_SNN.SCAVENGE.single_nucleus.genetic_enrichment.PBMC_human_6x(["graph_matrix.PCA_harmony_SNN.SCAVENGE.single_nucleus"]):::none --> TRS_tibbles.PCA_harmony_SNN.SCAVENGE.single_nucleus.genetic_enrichment.PBMC_human_6x["TRS_tibbles.PCA_harmony_SNN.SCAVENGE.single_nucleus"]:::none
  graph_matrix.WNN_harmony_SNN.SCAVENGE.single_nucleus.genetic_enrichment.immune_human_2x(["graph_matrix.WNN_harmony_SNN.SCAVENGE.single_nucleus"]):::none --> TRS_tibbles.WNN_harmony_SNN.SCAVENGE.single_nucleus.genetic_enrichment.immune_human_2x["TRS_tibbles.WNN_harmony_SNN.SCAVENGE.single_nucleus"]:::none
  ZScore_records.single_nucleus.genetic_enrichment.immune_human_2x["ZScore_records.single_nucleus"]:::none --> TRS_tibbles.WNN_harmony_SNN.SCAVENGE.single_nucleus.genetic_enrichment.immune_human_2x["TRS_tibbles.WNN_harmony_SNN.SCAVENGE.single_nucleus"]:::none
  graph_matrix.WNN_harmony_SNN.SCAVENGE.single_nucleus.genetic_enrichment.PBMC_human_6x(["graph_matrix.WNN_harmony_SNN.SCAVENGE.single_nucleus"]):::none --> TRS_tibbles.WNN_harmony_SNN.SCAVENGE.single_nucleus.genetic_enrichment.PBMC_human_6x["TRS_tibbles.WNN_harmony_SNN.SCAVENGE.single_nucleus"]:::none
  ZScore_records.single_nucleus.genetic_enrichment.PBMC_human_6x["ZScore_records.single_nucleus"]:::none --> TRS_tibbles.WNN_harmony_SNN.SCAVENGE.single_nucleus.genetic_enrichment.PBMC_human_6x["TRS_tibbles.WNN_harmony_SNN.SCAVENGE.single_nucleus"]:::none
  chromVAR_obj.ATAC.immune_human_2x(["chromVAR_obj.ATAC"]):::none --> ZScore_records.single_nucleus.genetic_enrichment.immune_human_2x["ZScore_records.single_nucleus"]:::none
  chromVAR_obj.ATAC.PBMC_human_6x(["chromVAR_obj.ATAC"]):::none --> ZScore_records.single_nucleus.genetic_enrichment.PBMC_human_6x["ZScore_records.single_nucleus"]:::none
  chromVAR_background_bins.ATAC.immune_human_2x(["chromVAR_background_bins.ATAC"]):::none --> ZScore_records.single_nucleus.genetic_enrichment.immune_human_2x["ZScore_records.single_nucleus"]:::none
  chromVAR_peak_expectation.ATAC.immune_human_2x(["chromVAR_peak_expectation.ATAC"]):::none --> ZScore_records.single_nucleus.genetic_enrichment.immune_human_2x["ZScore_records.single_nucleus"]:::none
  chromVAR_background_bins.ATAC.PBMC_human_6x(["chromVAR_background_bins.ATAC"]):::none --> ZScore_records.single_nucleus.genetic_enrichment.PBMC_human_6x["ZScore_records.single_nucleus"]:::none
  chromVAR_peak_expectation.ATAC.PBMC_human_6x(["chromVAR_peak_expectation.ATAC"]):::none --> ZScore_records.single_nucleus.genetic_enrichment.PBMC_human_6x["ZScore_records.single_nucleus"]:::none
  chromVAR_obj.ATAC.immune_human_2x(["chromVAR_obj.ATAC"]):::none --> GWAS_peak_weight_records.genetic_enrichment.immune_human_2x["GWAS_peak_weight_records"]:::none
  chromVAR_obj.ATAC.PBMC_human_6x(["chromVAR_obj.ATAC"]):::none --> GWAS_peak_weight_records.genetic_enrichment.PBMC_human_6x["GWAS_peak_weight_records"]:::none
  GWAS_inputs_tibble.genetic_enrichment.immune_human_2x(["GWAS_inputs_tibble"]):::none --> GWAS_peak_weight_records.genetic_enrichment.immune_human_2x["GWAS_peak_weight_records"]:::none
  GWAS_inputs_tibble.genetic_enrichment.PBMC_human_6x(["GWAS_inputs_tibble"]):::none --> GWAS_peak_weight_records.genetic_enrichment.PBMC_human_6x["GWAS_peak_weight_records"]:::none
  open_targets_credible_set_dataset_path(["open_targets_credible_set_dataset_path"]):::none --> GWAS_peak_weight_records.genetic_enrichment.immune_human_2x["GWAS_peak_weight_records"]:::none
  open_targets_credible_set_dataset_path(["open_targets_credible_set_dataset_path"]):::none --> GWAS_peak_weight_records.genetic_enrichment.PBMC_human_6x["GWAS_peak_weight_records"]:::none
  TRS_tibbles.LSI_harmony_SNN.SCAVENGE.single_nucleus.genetic_enrichment.immune_human_2x["TRS_tibbles.LSI_harmony_SNN.SCAVENGE.single_nucleus"]:::none --> TRS_summary_tibble.LSI_harmony_SNN.SCAVENGE.single_nucleus.genetic_enrichment.immune_human_2x(["TRS_summary_tibble.LSI_harmony_SNN.SCAVENGE.single_nucleus"]):::none
  TRS_tibbles.LSI_harmony_SNN.SCAVENGE.single_nucleus.genetic_enrichment.PBMC_human_6x["TRS_tibbles.LSI_harmony_SNN.SCAVENGE.single_nucleus"]:::none --> TRS_summary_tibble.LSI_harmony_SNN.SCAVENGE.single_nucleus.genetic_enrichment.PBMC_human_6x(["TRS_summary_tibble.LSI_harmony_SNN.SCAVENGE.single_nucleus"]):::none
  TRS_tibbles.PCA_harmony_SNN.SCAVENGE.single_nucleus.genetic_enrichment.immune_human_2x["TRS_tibbles.PCA_harmony_SNN.SCAVENGE.single_nucleus"]:::none --> TRS_summary_tibble.PCA_harmony_SNN.SCAVENGE.single_nucleus.genetic_enrichment.immune_human_2x(["TRS_summary_tibble.PCA_harmony_SNN.SCAVENGE.single_nucleus"]):::none
  TRS_tibbles.PCA_harmony_SNN.SCAVENGE.single_nucleus.genetic_enrichment.PBMC_human_6x["TRS_tibbles.PCA_harmony_SNN.SCAVENGE.single_nucleus"]:::none --> TRS_summary_tibble.PCA_harmony_SNN.SCAVENGE.single_nucleus.genetic_enrichment.PBMC_human_6x(["TRS_summary_tibble.PCA_harmony_SNN.SCAVENGE.single_nucleus"]):::none
  TRS_tibbles.WNN_harmony_SNN.SCAVENGE.single_nucleus.genetic_enrichment.immune_human_2x["TRS_tibbles.WNN_harmony_SNN.SCAVENGE.single_nucleus"]:::none --> TRS_summary_tibble.WNN_harmony_SNN.SCAVENGE.single_nucleus.genetic_enrichment.immune_human_2x(["TRS_summary_tibble.WNN_harmony_SNN.SCAVENGE.single_nucleus"]):::none
  TRS_tibbles.WNN_harmony_SNN.SCAVENGE.single_nucleus.genetic_enrichment.PBMC_human_6x["TRS_tibbles.WNN_harmony_SNN.SCAVENGE.single_nucleus"]:::none --> TRS_summary_tibble.WNN_harmony_SNN.SCAVENGE.single_nucleus.genetic_enrichment.PBMC_human_6x(["TRS_summary_tibble.WNN_harmony_SNN.SCAVENGE.single_nucleus"]):::none
  GWAS_peak_weight_records.genetic_enrichment.immune_human_2x["GWAS_peak_weight_records"]:::none --> ZScore_records.single_nucleus.genetic_enrichment.immune_human_2x["ZScore_records.single_nucleus"]:::none
  GWAS_peak_weight_records.genetic_enrichment.PBMC_human_6x["GWAS_peak_weight_records"]:::none --> ZScore_records.single_nucleus.genetic_enrichment.PBMC_human_6x["ZScore_records.single_nucleus"]:::none
  ZScore_records.single_nucleus.genetic_enrichment.immune_human_2x["ZScore_records.single_nucleus"]:::none --> ZScores_tibble.summarized.single_nucleus.genetic_enrichment.immune_human_2x(["ZScores_tibble.summarized.single_nucleus"]):::none
  ZScore_records.single_nucleus.genetic_enrichment.PBMC_human_6x["ZScore_records.single_nucleus"]:::none --> ZScores_tibble.summarized.single_nucleus.genetic_enrichment.PBMC_human_6x(["ZScores_tibble.summarized.single_nucleus"]):::none
