%%{init: {'flowchart': {'defaultRenderer': 'elk'}}}%%
flowchart TB
  donor_id_metadata_tibble.muscle(["donor_id_metadata_tibble.&lt;dataset_name&gt;"]):::none --> GEM_well_metadata_tibble.muscle(["GEM_well_metadata_tibble.&lt;dataset_name&gt;"]):::none
  donor_id_metadata_tibble.muscle_test(["donor_id_metadata_tibble.&lt;aggregation_name&gt;"]):::none --> GEM_well_metadata_tibble.muscle_test(["GEM_well_metadata_tibble.&lt;aggregation_name&gt;"]):::none
  metadata_tibble.GEX.muscle(["metadata_tibble.GEX.&lt;dataset_name&gt;"]):::none --> harmony_embeddings_matrix.GEX.muscle(["harmony_embeddings_matrix.GEX.&lt;dataset_name&gt;"]):::none
  PCA_BPCells.GEX.muscle(["PCA_BPCells.GEX.&lt;dataset_name&gt;"]):::none --> harmony_embeddings_matrix.GEX.muscle(["harmony_embeddings_matrix.GEX.&lt;dataset_name&gt;"]):::none
  PCA_BPCells.GEX.muscle_test(["PCA_BPCells.GEX.&lt;aggregation_name&gt;"]):::none --> harmony_embeddings_matrix.GEX.muscle_test(["harmony_embeddings_matrix.GEX.&lt;aggregation_name&gt;"]):::none
  metadata_tibble.GEX.muscle_test(["metadata_tibble.GEX.&lt;aggregation_name&gt;"]):::none --> harmony_embeddings_matrix.GEX.muscle_test(["harmony_embeddings_matrix.GEX.&lt;aggregation_name&gt;"]):::none
  donor_id_metadata_tibble.muscle(["donor_id_metadata_tibble.&lt;dataset_name&gt;"]):::none --> metadata_tibble.GEX.muscle(["metadata_tibble.GEX.&lt;dataset_name&gt;"]):::none
  GEM_well_metadata_tibble.muscle(["GEM_well_metadata_tibble.&lt;dataset_name&gt;"]):::none --> metadata_tibble.GEX.muscle(["metadata_tibble.GEX.&lt;dataset_name&gt;"]):::none
  PCA_BPCells.GEX.muscle(["PCA_BPCells.GEX.&lt;dataset_name&gt;"]):::none --> metadata_tibble.GEX.muscle(["metadata_tibble.GEX.&lt;dataset_name&gt;"]):::none
  GEM_well_metadata_tibble.muscle_test(["GEM_well_metadata_tibble.&lt;aggregation_name&gt;"]):::none --> metadata_tibble.GEX.muscle_test(["metadata_tibble.GEX.&lt;aggregation_name&gt;"]):::none
  donor_id_metadata_tibble.muscle_test(["donor_id_metadata_tibble.&lt;aggregation_name&gt;"]):::none --> metadata_tibble.GEX.muscle_test(["metadata_tibble.GEX.&lt;aggregation_name&gt;"]):::none
  PCA_BPCells.GEX.muscle_test(["PCA_BPCells.GEX.&lt;aggregation_name&gt;"]):::none --> metadata_tibble.GEX.muscle_test(["metadata_tibble.GEX.&lt;aggregation_name&gt;"]):::none
  scDblFinder_results_df.GEX.muscle(["scDblFinder_results_df.GEX.&lt;dataset_name&gt;"]):::none --> metadata_w_cell_types_tibble.GEX.muscle(["metadata_w_cell_types_tibble.GEX.&lt;dataset_name&gt;"]):::none
  scDblFinder_results_df.GEX.muscle_test(["scDblFinder_results_df.GEX.&lt;aggregation_name&gt;"]):::none --> metadata_w_cell_types_tibble.GEX.muscle_test(["metadata_w_cell_types_tibble.GEX.&lt;aggregation_name&gt;"]):::none
  donor_id_metadata_tibble.muscle(["donor_id_metadata_tibble.&lt;dataset_name&gt;"]):::none --> PCA_BPCells.GEX.muscle(["PCA_BPCells.GEX.&lt;dataset_name&gt;"]):::none
  GEM_well_metadata_tibble.muscle(["GEM_well_metadata_tibble.&lt;dataset_name&gt;"]):::none --> PCA_BPCells.GEX.muscle(["PCA_BPCells.GEX.&lt;dataset_name&gt;"]):::none
  donor_id_metadata_tibble.muscle_test(["donor_id_metadata_tibble.&lt;aggregation_name&gt;"]):::none --> PCA_BPCells.GEX.muscle_test(["PCA_BPCells.GEX.&lt;aggregation_name&gt;"]):::none
  GEM_well_metadata_tibble.muscle_test(["GEM_well_metadata_tibble.&lt;aggregation_name&gt;"]):::none --> PCA_BPCells.GEX.muscle_test(["PCA_BPCells.GEX.&lt;aggregation_name&gt;"]):::none
  harmony_embeddings_matrix.GEX.muscle(["harmony_embeddings_matrix.GEX.&lt;dataset_name&gt;"]):::none --> PCA_clusters.GEX.muscle(["PCA_clusters.GEX.&lt;dataset_name&gt;"]):::none
  harmony_embeddings_matrix.GEX.muscle_test(["harmony_embeddings_matrix.GEX.&lt;aggregation_name&gt;"]):::none --> PCA_clusters.GEX.muscle_test(["PCA_clusters.GEX.&lt;aggregation_name&gt;"]):::none
  PCA_BPCells.GEX.muscle(["PCA_BPCells.GEX.&lt;dataset_name&gt;"]):::none --> UMAP_embeddings_tibble.GEX_non_harmony.muscle(["UMAP_embeddings_tibble.GEX_non_harmony.&lt;dataset_name&gt;"]):::none
  PCA_BPCells.GEX.muscle_test(["PCA_BPCells.GEX.&lt;aggregation_name&gt;"]):::none --> UMAP_embeddings_tibble.GEX_non_harmony.muscle_test(["UMAP_embeddings_tibble.GEX_non_harmony.&lt;aggregation_name&gt;"]):::none
  harmony_embeddings_matrix.GEX.muscle(["harmony_embeddings_matrix.GEX.&lt;dataset_name&gt;"]):::none --> UMAP_embeddings_tibble.GEX.muscle(["UMAP_embeddings_tibble.GEX.&lt;dataset_name&gt;"]):::none
  harmony_embeddings_matrix.GEX.muscle_test(["harmony_embeddings_matrix.GEX.&lt;aggregation_name&gt;"]):::none --> UMAP_embeddings_tibble.GEX.muscle_test(["UMAP_embeddings_tibble.GEX.&lt;aggregation_name&gt;"]):::none
  aggregated_GEX_BPCells_matrix_dir.GEX.muscle(["aggregated_GEX_BPCells_matrix_dir.GEX.&lt;dataset_name&gt;"]):::none --> PCA_BPCells.GEX.muscle(["PCA_BPCells.GEX.&lt;dataset_name&gt;"]):::none
  aggregated_GEX_BPCells_matrix_dir.GEX.muscle(["aggregated_GEX_BPCells_matrix_dir.GEX.&lt;dataset_name&gt;"]):::none --> metadata_w_cell_types_tibble.GEX.muscle(["metadata_w_cell_types_tibble.GEX.&lt;dataset_name&gt;"]):::none
  aggregated_GEX_BPCells_matrix_dir.GEX.muscle(["aggregated_GEX_BPCells_matrix_dir.GEX.&lt;dataset_name&gt;"]):::none --> scDblFinder_results_df.GEX.muscle(["scDblFinder_results_df.GEX.&lt;dataset_name&gt;"]):::none
  aggregated_GEX_BPCells_matrix_dir.GEX.muscle_test(["aggregated_GEX_BPCells_matrix_dir.GEX.&lt;aggregation_name&gt;"]):::none --> PCA_BPCells.GEX.muscle_test(["PCA_BPCells.GEX.&lt;aggregation_name&gt;"]):::none
  aggregated_GEX_BPCells_matrix_dir.GEX.muscle_test(["aggregated_GEX_BPCells_matrix_dir.GEX.&lt;aggregation_name&gt;"]):::none --> metadata_w_cell_types_tibble.GEX.muscle_test(["metadata_w_cell_types_tibble.GEX.&lt;aggregation_name&gt;"]):::none
  aggregated_GEX_BPCells_matrix_dir.GEX.muscle_test(["aggregated_GEX_BPCells_matrix_dir.GEX.&lt;aggregation_name&gt;"]):::none --> scDblFinder_results_df.GEX.muscle_test(["scDblFinder_results_df.GEX.&lt;aggregation_name&gt;"]):::none
  UCell_GEX_marker_genes_list.muscle(["UCell_GEX_marker_genes_list.&lt;dataset_name&gt;"]):::none --> metadata_w_cell_types_tibble.GEX.muscle(["metadata_w_cell_types_tibble.GEX.&lt;dataset_name&gt;"]):::none
  UMAP_embeddings_tibble.GEX.muscle(["UMAP_embeddings_tibble.GEX.&lt;dataset_name&gt;"]):::none --> metadata_w_cell_types_tibble.GEX.muscle(["metadata_w_cell_types_tibble.GEX.&lt;dataset_name&gt;"]):::none
  PCA_clusters.GEX.muscle(["PCA_clusters.GEX.&lt;dataset_name&gt;"]):::none --> metadata_w_cell_types_tibble.GEX.muscle(["metadata_w_cell_types_tibble.GEX.&lt;dataset_name&gt;"]):::none
  metadata_tibble.GEX.muscle(["metadata_tibble.GEX.&lt;dataset_name&gt;"]):::none --> metadata_w_cell_types_tibble.GEX.muscle(["metadata_w_cell_types_tibble.GEX.&lt;dataset_name&gt;"]):::none
  UMAP_embeddings_tibble.GEX_non_harmony.muscle(["UMAP_embeddings_tibble.GEX_non_harmony.&lt;dataset_name&gt;"]):::none --> metadata_w_cell_types_tibble.GEX.muscle(["metadata_w_cell_types_tibble.GEX.&lt;dataset_name&gt;"]):::none
  UCell_GEX_marker_genes_list.muscle(["UCell_GEX_marker_genes_list.&lt;dataset_name&gt;"]):::none --> scDblFinder_results_df.GEX.muscle(["scDblFinder_results_df.GEX.&lt;dataset_name&gt;"]):::none
  UMAP_embeddings_tibble.GEX.muscle(["UMAP_embeddings_tibble.GEX.&lt;dataset_name&gt;"]):::none --> scDblFinder_results_df.GEX.muscle(["scDblFinder_results_df.GEX.&lt;dataset_name&gt;"]):::none
  PCA_clusters.GEX.muscle(["PCA_clusters.GEX.&lt;dataset_name&gt;"]):::none --> scDblFinder_results_df.GEX.muscle(["scDblFinder_results_df.GEX.&lt;dataset_name&gt;"]):::none
  metadata_tibble.GEX.muscle(["metadata_tibble.GEX.&lt;dataset_name&gt;"]):::none --> scDblFinder_results_df.GEX.muscle(["scDblFinder_results_df.GEX.&lt;dataset_name&gt;"]):::none
  UMAP_embeddings_tibble.GEX_non_harmony.muscle(["UMAP_embeddings_tibble.GEX_non_harmony.&lt;dataset_name&gt;"]):::none --> scDblFinder_results_df.GEX.muscle(["scDblFinder_results_df.GEX.&lt;dataset_name&gt;"]):::none
  UCell_GEX_marker_genes_list.muscle_test(["UCell_GEX_marker_genes_list.&lt;aggregation_name&gt;"]):::none --> metadata_w_cell_types_tibble.GEX.muscle_test(["metadata_w_cell_types_tibble.GEX.&lt;aggregation_name&gt;"]):::none
  metadata_tibble.GEX.muscle_test(["metadata_tibble.GEX.&lt;aggregation_name&gt;"]):::none --> metadata_w_cell_types_tibble.GEX.muscle_test(["metadata_w_cell_types_tibble.GEX.&lt;aggregation_name&gt;"]):::none
  UMAP_embeddings_tibble.GEX.muscle_test(["UMAP_embeddings_tibble.GEX.&lt;aggregation_name&gt;"]):::none --> metadata_w_cell_types_tibble.GEX.muscle_test(["metadata_w_cell_types_tibble.GEX.&lt;aggregation_name&gt;"]):::none
  PCA_clusters.GEX.muscle_test(["PCA_clusters.GEX.&lt;aggregation_name&gt;"]):::none --> metadata_w_cell_types_tibble.GEX.muscle_test(["metadata_w_cell_types_tibble.GEX.&lt;aggregation_name&gt;"]):::none
  UMAP_embeddings_tibble.GEX_non_harmony.muscle_test(["UMAP_embeddings_tibble.GEX_non_harmony.&lt;aggregation_name&gt;"]):::none --> metadata_w_cell_types_tibble.GEX.muscle_test(["metadata_w_cell_types_tibble.GEX.&lt;aggregation_name&gt;"]):::none
  UCell_GEX_marker_genes_list.muscle_test(["UCell_GEX_marker_genes_list.&lt;aggregation_name&gt;"]):::none --> scDblFinder_results_df.GEX.muscle_test(["scDblFinder_results_df.GEX.&lt;aggregation_name&gt;"]):::none
  metadata_tibble.GEX.muscle_test(["metadata_tibble.GEX.&lt;aggregation_name&gt;"]):::none --> scDblFinder_results_df.GEX.muscle_test(["scDblFinder_results_df.GEX.&lt;aggregation_name&gt;"]):::none
  UMAP_embeddings_tibble.GEX.muscle_test(["UMAP_embeddings_tibble.GEX.&lt;aggregation_name&gt;"]):::none --> scDblFinder_results_df.GEX.muscle_test(["scDblFinder_results_df.GEX.&lt;aggregation_name&gt;"]):::none
  PCA_clusters.GEX.muscle_test(["PCA_clusters.GEX.&lt;aggregation_name&gt;"]):::none --> scDblFinder_results_df.GEX.muscle_test(["scDblFinder_results_df.GEX.&lt;aggregation_name&gt;"]):::none
  UMAP_embeddings_tibble.GEX_non_harmony.muscle_test(["UMAP_embeddings_tibble.GEX_non_harmony.&lt;aggregation_name&gt;"]):::none --> scDblFinder_results_df.GEX.muscle_test(["scDblFinder_results_df.GEX.&lt;aggregation_name&gt;"]):::none
