%%{init: {'flowchart': {'defaultRenderer': 'elk'}}}%%
flowchart TB
  PCA_BPCells.GEX.immune_human_2x(["PCA_BPCells.GEX.&lt;aggregation_name&gt;"]):::none --> harmony_embeddings_matrix.GEX.immune_human_2x(["harmony_embeddings_matrix.GEX.&lt;aggregation_name&gt;"]):::none
  PCA_BPCells.GEX.immune_human_2x(["PCA_BPCells.GEX.&lt;aggregation_name&gt;"]):::none --> metadata_tibble.GEX.immune_human_2x(["metadata_tibble.GEX.&lt;aggregation_name&gt;"]):::none
  scDblFinder_results_df.GEX.immune_human_2x(["scDblFinder_results_df.GEX.&lt;aggregation_name&gt;"]):::none --> metadata_w_cell_types_tibble.GEX.immune_human_2x(["metadata_w_cell_types_tibble.GEX.&lt;aggregation_name&gt;"]):::none
  harmony_embeddings_matrix.GEX.immune_human_2x(["harmony_embeddings_matrix.GEX.&lt;aggregation_name&gt;"]):::none --> PCA_clusters.GEX.immune_human_2x(["PCA_clusters.GEX.&lt;aggregation_name&gt;"]):::none
  PCA_BPCells.GEX.immune_human_2x(["PCA_BPCells.GEX.&lt;aggregation_name&gt;"]):::none --> UMAP_embeddings_tibble.GEX_non_harmony.immune_human_2x(["UMAP_embeddings_tibble.GEX_non_harmony.&lt;aggregation_name&gt;"]):::none
  harmony_embeddings_matrix.GEX.immune_human_2x(["harmony_embeddings_matrix.GEX.&lt;aggregation_name&gt;"]):::none --> UMAP_embeddings_tibble.GEX.immune_human_2x(["UMAP_embeddings_tibble.GEX.&lt;aggregation_name&gt;"]):::none
  aggregated_GEX_BPCells_matrix_dir.GEX.immune_human_2x(["aggregated_GEX_BPCells_matrix_dir.GEX.&lt;aggregation_name&gt;"]):::none --> PCA_BPCells.GEX.immune_human_2x(["PCA_BPCells.GEX.&lt;aggregation_name&gt;"]):::none
  aggregated_GEX_BPCells_matrix_dir.GEX.immune_human_2x(["aggregated_GEX_BPCells_matrix_dir.GEX.&lt;aggregation_name&gt;"]):::none --> metadata_w_cell_types_tibble.GEX.immune_human_2x(["metadata_w_cell_types_tibble.GEX.&lt;aggregation_name&gt;"]):::none
  aggregated_GEX_BPCells_matrix_dir.GEX.immune_human_2x(["aggregated_GEX_BPCells_matrix_dir.GEX.&lt;aggregation_name&gt;"]):::none --> scDblFinder_results_df.GEX.immune_human_2x(["scDblFinder_results_df.GEX.&lt;aggregation_name&gt;"]):::none
  donor_id_metadata_tibble.immune_human_2x(["donor_id_metadata_tibble.&lt;aggregation_name&gt;"]):::none --> harmony_embeddings_matrix.GEX.immune_human_2x(["harmony_embeddings_matrix.GEX.&lt;aggregation_name&gt;"]):::none
  donor_id_metadata_tibble.immune_human_2x(["donor_id_metadata_tibble.&lt;aggregation_name&gt;"]):::none --> PCA_BPCells.GEX.immune_human_2x(["PCA_BPCells.GEX.&lt;aggregation_name&gt;"]):::none
  metadata_tibble.GEX.immune_human_2x(["metadata_tibble.GEX.&lt;aggregation_name&gt;"]):::none --> harmony_embeddings_matrix.GEX.immune_human_2x(["harmony_embeddings_matrix.GEX.&lt;aggregation_name&gt;"]):::none
  UCell_GEX_marker_genes_list.immune_human_2x(["UCell_GEX_marker_genes_list.&lt;aggregation_name&gt;"]):::none --> metadata_w_cell_types_tibble.GEX.immune_human_2x(["metadata_w_cell_types_tibble.GEX.&lt;aggregation_name&gt;"]):::none
  metadata_tibble.GEX.immune_human_2x(["metadata_tibble.GEX.&lt;aggregation_name&gt;"]):::none --> metadata_w_cell_types_tibble.GEX.immune_human_2x(["metadata_w_cell_types_tibble.GEX.&lt;aggregation_name&gt;"]):::none
  PCA_clusters.GEX.immune_human_2x(["PCA_clusters.GEX.&lt;aggregation_name&gt;"]):::none --> metadata_w_cell_types_tibble.GEX.immune_human_2x(["metadata_w_cell_types_tibble.GEX.&lt;aggregation_name&gt;"]):::none
  UMAP_embeddings_tibble.GEX.immune_human_2x(["UMAP_embeddings_tibble.GEX.&lt;aggregation_name&gt;"]):::none --> metadata_w_cell_types_tibble.GEX.immune_human_2x(["metadata_w_cell_types_tibble.GEX.&lt;aggregation_name&gt;"]):::none
  UMAP_embeddings_tibble.GEX_non_harmony.immune_human_2x(["UMAP_embeddings_tibble.GEX_non_harmony.&lt;aggregation_name&gt;"]):::none --> metadata_w_cell_types_tibble.GEX.immune_human_2x(["metadata_w_cell_types_tibble.GEX.&lt;aggregation_name&gt;"]):::none
  UCell_GEX_marker_genes_list.immune_human_2x(["UCell_GEX_marker_genes_list.&lt;aggregation_name&gt;"]):::none --> scDblFinder_results_df.GEX.immune_human_2x(["scDblFinder_results_df.GEX.&lt;aggregation_name&gt;"]):::none
  metadata_tibble.GEX.immune_human_2x(["metadata_tibble.GEX.&lt;aggregation_name&gt;"]):::none --> scDblFinder_results_df.GEX.immune_human_2x(["scDblFinder_results_df.GEX.&lt;aggregation_name&gt;"]):::none
  PCA_clusters.GEX.immune_human_2x(["PCA_clusters.GEX.&lt;aggregation_name&gt;"]):::none --> scDblFinder_results_df.GEX.immune_human_2x(["scDblFinder_results_df.GEX.&lt;aggregation_name&gt;"]):::none
  UMAP_embeddings_tibble.GEX.immune_human_2x(["UMAP_embeddings_tibble.GEX.&lt;aggregation_name&gt;"]):::none --> scDblFinder_results_df.GEX.immune_human_2x(["scDblFinder_results_df.GEX.&lt;aggregation_name&gt;"]):::none
  UMAP_embeddings_tibble.GEX_non_harmony.immune_human_2x(["UMAP_embeddings_tibble.GEX_non_harmony.&lt;aggregation_name&gt;"]):::none --> scDblFinder_results_df.GEX.immune_human_2x(["scDblFinder_results_df.GEX.&lt;aggregation_name&gt;"]):::none
