#!/usr/bin/env python3
"""Bypass selected nodes in tar_mermaid-style Mermaid graphs.

By default, this script reads bypass patterns from:

    <input_stem>_bypass_patterns.txt

The pattern file is generated by mermaid_gen_patterns.py and contains one regex
per line. Each regex is matched against the node label shown inside the Mermaid
graph node. Blank lines and lines starting with # are ignored.

With --keep-patterns, active regexes are interpreted as nodes to keep instead:
every node that does not match at least one active regex is bypassed.

Inline %% markers in the Mermaid file are still supported. Mark nodes for
bypassing by adding a line that starts with "%%", for example:

    %% metadata_tibble.GEX.brain_mouse

For tar_mermaid graphs, nodes often only appear inside edge lines. In that
case, comment the edge line and the left-hand node is bypassed:

    %% node_to_prune(["node_to_prune"]):::none --> child_node(["child_node"]):::none

The marked node is removed. If it has at least one retained parent and at least
one retained child, direct bypass edges are added from parents to children.
Multiple marked nodes are bypassed simultaneously.
Mermaid directive lines such as %%{init: ...}%% are preserved.

By default, an input file named example.mmd writes:

    example_pruned.mmd
"""

from __future__ import annotations

import argparse
import re
import sys
from collections import defaultdict, deque
from pathlib import Path


EDGE_REPLACEMENTS = ("-->", "---", "-.->")
SHAPE_STARTS = ("([", "[", "{{", ">", "(")


def split_edge(line: str) -> tuple[str, str, str, str] | None:
    for arrow in EDGE_REPLACEMENTS:
        token = f" {arrow} "
        if token in line:
            left, right = line.split(token, 1)
            return left[: len(left) - len(left.lstrip())], left.strip(), arrow, right.strip()
    return None


def mermaid_prune_payload(line: str) -> str | None:
    stripped = line.lstrip()
    if not stripped.startswith("%%") or stripped.startswith("%%{"):
        return None
    return stripped[2:].strip()


def graph_line(line: str) -> str | None:
    payload = mermaid_prune_payload(line)
    if payload is not None:
        return payload
    if line.lstrip().startswith("%%{"):
        return None
    return line


def node_id(node_expr: str) -> str:
    node_expr = node_expr.strip()
    for marker in SHAPE_STARTS:
        index = node_expr.find(marker)
        if index > 0:
            return node_expr[:index].strip()
    return node_expr.split()[0] if node_expr.split() else ""


def node_label(node_expr: str) -> str:
    label_start = node_expr.find('["')
    if label_start < 0:
        return node_id(node_expr)

    label_start += 2
    label_end = node_expr.find('"]', label_start)
    if label_end < 0:
        return node_id(node_expr)

    return node_expr[label_start:label_end]


def parse_edges(lines: list[str]) -> tuple[list[dict[str, object]], dict[str, str]]:
    edges = []
    node_exprs = {}

    for index, line in enumerate(lines):
        edge_line = graph_line(line)
        if edge_line is None:
            continue

        parsed = split_edge(edge_line)
        if parsed is None:
            continue

        indent, from_expr, arrow, to_expr = parsed
        from_id = node_id(from_expr)
        to_id = node_id(to_expr)
        if not from_id or not to_id:
            continue

        node_exprs.setdefault(from_id, from_expr)
        node_exprs.setdefault(to_id, to_expr)
        edges.append(
            {
                "index": index,
                "indent": indent,
                "arrow": arrow,
                "from_id": from_id,
                "to_id": to_id,
            }
        )

    return edges, node_exprs


def add_marked_node(marked: set[str], payload: str, node_exprs: dict[str, str]) -> None:
    parsed_edge = split_edge(payload)
    candidate = node_id(parsed_edge[1] if parsed_edge is not None else payload)
    if candidate not in node_exprs:
        raise ValueError(f"%% bypass marker did not match a graph node: {payload}")
    marked.add(candidate)


def marked_nodes(
    graph_lines: list[str],
    node_exprs: dict[str, str],
    pattern_file_lines: list[str] | None = None,
    keep_patterns: bool = False,
) -> tuple[set[str], set[int]]:
    marked = set()
    marker_indices = set()

    for index, line in enumerate(graph_lines):
        payload = mermaid_prune_payload(line)
        if payload is None:
            continue

        if not payload:
            continue

        add_marked_node(marked, payload, node_exprs)
        marker_indices.add(index)

    if keep_patterns and pattern_file_lines is None:
        raise ValueError("--keep-patterns requires a pattern file")

    if pattern_file_lines is not None:
        labels_by_id = {node: node_label(expr) for node, expr in node_exprs.items()}
        pattern_matches = set()
        active_patterns = 0
        for line_number, line in enumerate(pattern_file_lines, start=1):
            pattern = line.strip()
            if not pattern or pattern.startswith("#"):
                continue
            active_patterns += 1

            try:
                compiled = re.compile(pattern)
            except re.error as error:
                raise ValueError(
                    f"invalid regex in bypass pattern file on line {line_number}: {error}"
                ) from error

            matches = {
                node for node, label in labels_by_id.items() if compiled.search(label)
            }
            if not matches:
                raise ValueError(
                    "regex in bypass pattern file matched no graph node labels "
                    f"on line {line_number}: {pattern}"
                )
            pattern_matches.update(matches)

        if keep_patterns:
            if active_patterns == 0:
                raise ValueError("--keep-patterns requires at least one active pattern")
            marked.update(set(node_exprs) - pattern_matches)
        else:
            marked.update(pattern_matches)

    return marked, marker_indices


def nearest_retained(start: str, adjacency: dict[str, set[str]], removed: set[str]) -> set[str]:
    retained = set()
    seen = {start}
    queue = deque(adjacency.get(start, set()))

    while queue:
        current = queue.popleft()
        if current in seen:
            continue
        seen.add(current)

        if current in removed:
            queue.extend(adjacency.get(current, set()))
        else:
            retained.add(current)

    return retained


def prune_lines(
    lines: list[str],
    pattern_file_lines: list[str] | None = None,
    keep_patterns: bool = False,
) -> tuple[list[str], dict[str, int]]:
    edges, node_exprs = parse_edges(lines)
    removed, marker_indices = marked_nodes(
        lines,
        node_exprs,
        pattern_file_lines,
        keep_patterns,
    )
    if not removed:
        raise ValueError("no bypass patterns or %% bypass markers found")

    forward = defaultdict(set)
    reverse = defaultdict(set)
    edge_indices = set()
    edges_by_index = {}
    for edge in edges:
        from_id = str(edge["from_id"])
        to_id = str(edge["to_id"])
        forward[from_id].add(to_id)
        reverse[to_id].add(from_id)
        edge_index = int(edge["index"])
        edge_indices.add(edge_index)
        edges_by_index[edge_index] = edge

    bypass_pairs = set()
    for node in removed:
        parents = nearest_retained(node, reverse, removed)
        children = nearest_retained(node, forward, removed)
        for parent in parents:
            for child in children:
                if parent != child:
                    bypass_pairs.add((parent, child))

    kept_pairs = {
        (str(edge["from_id"]), str(edge["to_id"]))
        for edge in edges
        if str(edge["from_id"]) not in removed and str(edge["to_id"]) not in removed
    }
    bypass_pairs -= kept_pairs

    first_edge = edges[0] if edges else {"indent": "    ", "arrow": "-->"}
    indent = str(first_edge["indent"])
    arrow = str(first_edge["arrow"])
    bypass_lines = [
        f"{indent}{node_exprs[parent]} {arrow} {node_exprs[child]}\n"
        for parent, child in sorted(bypass_pairs)
    ]

    insert_index = bypass_line_insert_index(lines)
    output = []
    for index, line in enumerate(lines):
        if index in marker_indices:
            continue

        if index in edge_indices:
            edge = edges_by_index[index]
            if str(edge["from_id"]) in removed or str(edge["to_id"]) in removed:
                continue

        if index == insert_index:
            output.extend(bypass_lines)
        output.append(line)

    if insert_index is None:
        output.extend(bypass_lines)

    removed_edges = sum(
        1
        for edge in edges
        if str(edge["from_id"]) in removed or str(edge["to_id"]) in removed
    )

    return output, {
        "marked_nodes": len(removed),
        "removed_edges": removed_edges,
        "added_bypass_edges": len(bypass_pairs),
    }


def default_output_path(input_path: Path) -> Path:
    return input_path.with_name(f"{input_path.stem}_pruned{input_path.suffix}")


def bypass_line_insert_index(lines: list[str]) -> int | None:
    for index in range(len(lines) - 1, -1, -1):
        if lines[index].strip() == "end":
            return index
    return None


def default_patterns_path(input_path: Path) -> Path:
    return input_path.with_name(f"{input_path.stem}_bypass_patterns.txt")


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("mermaid_file", type=Path, help="Input Mermaid .mmd file.")
    parser.add_argument(
        "-o",
        "--output",
        type=Path,
        help="Output file. Defaults to <input_stem>_pruned.mmd.",
    )
    parser.add_argument(
        "--patterns-file",
        type=Path,
        help="Regex bypass pattern file. Defaults to <input_stem>_bypass_patterns.txt.",
    )
    parser.add_argument(
        "--keep-patterns",
        action="store_true",
        help=(
            "Interpret active regexes as nodes to keep and bypass all other nodes. "
            "Commented patterns still remain inactive."
        ),
    )
    return parser.parse_args()


def main() -> None:
    args = parse_args()
    output_path = args.output or default_output_path(args.mermaid_file)
    patterns_path = args.patterns_file or default_patterns_path(args.mermaid_file)
    if args.patterns_file is not None and not patterns_path.exists():
        raise SystemExit(f"patterns file does not exist: {patterns_path}")

    lines = args.mermaid_file.read_text().splitlines(keepends=True)
    pattern_file_lines = (
        patterns_path.read_text().splitlines(keepends=True)
        if patterns_path.exists()
        else None
    )
    try:
        output, summary = prune_lines(lines, pattern_file_lines, args.keep_patterns)
    except ValueError as error:
        raise SystemExit(str(error)) from error

    output_path.write_text("".join(output))

    print(
        "bypassed Mermaid graph nodes: "
        f"output={output_path}, "
        f"patterns={patterns_path if pattern_file_lines is not None else 'none'}, "
        f"mode={'keep' if args.keep_patterns else 'bypass'}, "
        f"marked_nodes={summary['marked_nodes']}, "
        f"removed_edges={summary['removed_edges']}, "
        f"added_bypass_edges={summary['added_bypass_edges']}",
        file=sys.stderr,
    )


if __name__ == "__main__":
    main()
