%%{init: {'flowchart': {'defaultRenderer': 'elk'}}}%%
flowchart TB
  cellranger_barcodes_tsv.embryonic_brain_mouse(["cellranger_barcodes_tsv"]):::none --> amulet_metrics_tibble.embryonic_brain_mouse(["amulet_metrics_tibble"]):::none
  cellranger_barcodes_tsv.healthy_PBMC_human(["cellranger_barcodes_tsv"]):::none --> amulet_metrics_tibble.healthy_PBMC_human(["amulet_metrics_tibble"]):::none
  cellranger_barcodes_tsv.lymphoma_lymph_human(["cellranger_barcodes_tsv"]):::none --> amulet_metrics_tibble.lymphoma_lymph_human(["amulet_metrics_tibble"]):::none
  cellranger_barcodes_tsv.pbmc_10k_chromium_controller(["cellranger_barcodes_tsv"]):::none --> amulet_metrics_tibble.pbmc_10k_chromium_controller(["amulet_metrics_tibble"]):::none
  cellranger_barcodes_tsv.pbmc_10k_chromium_x(["cellranger_barcodes_tsv"]):::none --> amulet_metrics_tibble.pbmc_10k_chromium_x(["amulet_metrics_tibble"]):::none
  cellranger_barcodes_tsv.pbmc_granulocyte_sorted_10k(["cellranger_barcodes_tsv"]):::none --> amulet_metrics_tibble.pbmc_granulocyte_sorted_10k(["amulet_metrics_tibble"]):::none
  cellranger_barcodes_tsv.pbmc_unsorted_10k(["cellranger_barcodes_tsv"]):::none --> amulet_metrics_tibble.pbmc_unsorted_10k(["amulet_metrics_tibble"]):::none
  cellranger_barcodes_tsv.pbmc_unsorted_3k(["cellranger_barcodes_tsv"]):::none --> amulet_metrics_tibble.pbmc_unsorted_3k(["amulet_metrics_tibble"]):::none
  cellranger_barcodes_tsv.embryonic_brain_mouse(["cellranger_barcodes_tsv"]):::none --> cellsnp_dir.embryonic_brain_mouse(["cellsnp_dir"]):::none
  cellranger_barcodes_tsv.healthy_PBMC_human(["cellranger_barcodes_tsv"]):::none --> cellsnp_dir.healthy_PBMC_human(["cellsnp_dir"]):::none
  cellranger_barcodes_tsv.lymphoma_lymph_human(["cellranger_barcodes_tsv"]):::none --> cellsnp_dir.lymphoma_lymph_human(["cellsnp_dir"]):::none
  cellranger_barcodes_tsv.pbmc_10k_chromium_controller(["cellranger_barcodes_tsv"]):::none --> cellsnp_dir.pbmc_10k_chromium_controller(["cellsnp_dir"]):::none
  cellranger_barcodes_tsv.pbmc_10k_chromium_x(["cellranger_barcodes_tsv"]):::none --> cellsnp_dir.pbmc_10k_chromium_x(["cellsnp_dir"]):::none
  cellranger_barcodes_tsv.pbmc_granulocyte_sorted_10k(["cellranger_barcodes_tsv"]):::none --> cellsnp_dir.pbmc_granulocyte_sorted_10k(["cellsnp_dir"]):::none
  cellranger_barcodes_tsv.pbmc_unsorted_10k(["cellranger_barcodes_tsv"]):::none --> cellsnp_dir.pbmc_unsorted_10k(["cellsnp_dir"]):::none
  cellranger_barcodes_tsv.pbmc_unsorted_3k(["cellranger_barcodes_tsv"]):::none --> cellsnp_dir.pbmc_unsorted_3k(["cellsnp_dir"]):::none
  consensus_peak_GRanges.ATAC.brain_mouse(["consensus_peak_GRanges.ATAC"]):::none --> chromVAR_obj.ATAC.brain_mouse(["chromVAR_obj.ATAC"]):::none
  metadata_w_cell_types_tibble.ATAC.brain_mouse(["metadata_w_cell_types_tibble.ATAC"]):::none --> chromVAR_obj.ATAC.brain_mouse(["chromVAR_obj.ATAC"]):::none
  metadata_w_cell_types_tibble.ATAC.immune_human_2x(["metadata_w_cell_types_tibble.ATAC"]):::none --> chromVAR_obj.ATAC.immune_human_2x(["chromVAR_obj.ATAC"]):::none
  consensus_peak_GRanges.ATAC.immune_human_2x(["consensus_peak_GRanges.ATAC"]):::none --> chromVAR_obj.ATAC.immune_human_2x(["chromVAR_obj.ATAC"]):::none
  metadata_w_cell_types_tibble.ATAC.PBMC_human_6x(["metadata_w_cell_types_tibble.ATAC"]):::none --> chromVAR_obj.ATAC.PBMC_human_6x(["chromVAR_obj.ATAC"]):::none
  consensus_peak_GRanges.ATAC.PBMC_human_6x(["consensus_peak_GRanges.ATAC"]):::none --> chromVAR_obj.ATAC.PBMC_human_6x(["chromVAR_obj.ATAC"]):::none
  WNN_results.subgroups.brain_mouse["WNN_results.subgroups"]:::none --> clusters_tibble.WNN.subgroups.brain_mouse["clusters_tibble.WNN.subgroups"]:::none
  WNN_results.subgroups.immune_human_2x["WNN_results.subgroups"]:::none --> clusters_tibble.WNN.subgroups.immune_human_2x["clusters_tibble.WNN.subgroups"]:::none
  WNN_results.subgroups.PBMC_human_6x["WNN_results.subgroups"]:::none --> clusters_tibble.WNN.subgroups.PBMC_human_6x["clusters_tibble.WNN.subgroups"]:::none
  consensus_peak_GRanges.ATAC.brain_mouse(["consensus_peak_GRanges.ATAC"]):::none --> consensus_peak_BPCells_matrix_dir.ATAC.brain_mouse(["consensus_peak_BPCells_matrix_dir.ATAC"]):::none
  metadata_w_cell_types_tibble.GEX.brain_mouse(["metadata_w_cell_types_tibble.GEX"]):::none --> consensus_peak_BPCells_matrix_dir.ATAC.brain_mouse(["consensus_peak_BPCells_matrix_dir.ATAC"]):::none
  combined_BPCells_fragment_obj.ATAC.brain_mouse(["combined_BPCells_fragment_obj.ATAC"]):::none --> consensus_peak_BPCells_matrix_dir.ATAC.brain_mouse(["consensus_peak_BPCells_matrix_dir.ATAC"]):::none
  combined_BPCells_fragment_obj.ATAC.immune_human_2x(["combined_BPCells_fragment_obj.ATAC"]):::none --> consensus_peak_BPCells_matrix_dir.ATAC.immune_human_2x(["consensus_peak_BPCells_matrix_dir.ATAC"]):::none
  consensus_peak_GRanges.ATAC.immune_human_2x(["consensus_peak_GRanges.ATAC"]):::none --> consensus_peak_BPCells_matrix_dir.ATAC.immune_human_2x(["consensus_peak_BPCells_matrix_dir.ATAC"]):::none
  metadata_w_cell_types_tibble.GEX.immune_human_2x(["metadata_w_cell_types_tibble.GEX"]):::none --> consensus_peak_BPCells_matrix_dir.ATAC.immune_human_2x(["consensus_peak_BPCells_matrix_dir.ATAC"]):::none
  combined_BPCells_fragment_obj.ATAC.PBMC_human_6x(["combined_BPCells_fragment_obj.ATAC"]):::none --> consensus_peak_BPCells_matrix_dir.ATAC.PBMC_human_6x(["consensus_peak_BPCells_matrix_dir.ATAC"]):::none
  consensus_peak_GRanges.ATAC.PBMC_human_6x(["consensus_peak_GRanges.ATAC"]):::none --> consensus_peak_BPCells_matrix_dir.ATAC.PBMC_human_6x(["consensus_peak_BPCells_matrix_dir.ATAC"]):::none
  metadata_w_cell_types_tibble.GEX.PBMC_human_6x(["metadata_w_cell_types_tibble.GEX"]):::none --> consensus_peak_BPCells_matrix_dir.ATAC.PBMC_human_6x(["consensus_peak_BPCells_matrix_dir.ATAC"]):::none
  within_clusters_collapsed_peaks_per_cluster_GRanges.ATAC.brain_mouse["within_clusters_collapsed_peaks_per_cluster_GRanges.ATAC"]:::none --> consensus_peak_GRanges.ATAC.brain_mouse(["consensus_peak_GRanges.ATAC"]):::none
  within_clusters_collapsed_peaks_per_cluster_GRanges.ATAC.immune_human_2x["within_clusters_collapsed_peaks_per_cluster_GRanges.ATAC"]:::none --> consensus_peak_GRanges.ATAC.immune_human_2x(["consensus_peak_GRanges.ATAC"]):::none
  within_clusters_collapsed_peaks_per_cluster_GRanges.ATAC.PBMC_human_6x["within_clusters_collapsed_peaks_per_cluster_GRanges.ATAC"]:::none --> consensus_peak_GRanges.ATAC.PBMC_human_6x(["consensus_peak_GRanges.ATAC"]):::none
  metadata_w_cell_types_tibble.ATAC.brain_mouse(["metadata_w_cell_types_tibble.ATAC"]):::none --> embedding_matrices.WNN.brain_mouse(["embedding_matrices.WNN"]):::none
  harmony_embeddings_matrix.ATAC.brain_mouse(["harmony_embeddings_matrix.ATAC"]):::none --> embedding_matrices.WNN.brain_mouse(["embedding_matrices.WNN"]):::none
  harmony_embeddings_matrix.GEX.brain_mouse(["harmony_embeddings_matrix.GEX"]):::none --> embedding_matrices.WNN.brain_mouse(["embedding_matrices.WNN"]):::none
  metadata_w_cell_types_tibble.ATAC.immune_human_2x(["metadata_w_cell_types_tibble.ATAC"]):::none --> embedding_matrices.WNN.immune_human_2x(["embedding_matrices.WNN"]):::none
  harmony_embeddings_matrix.GEX.immune_human_2x(["harmony_embeddings_matrix.GEX"]):::none --> embedding_matrices.WNN.immune_human_2x(["embedding_matrices.WNN"]):::none
  harmony_embeddings_matrix.ATAC.immune_human_2x(["harmony_embeddings_matrix.ATAC"]):::none --> embedding_matrices.WNN.immune_human_2x(["embedding_matrices.WNN"]):::none
  harmony_embeddings_matrix.GEX.PBMC_human_6x(["harmony_embeddings_matrix.GEX"]):::none --> embedding_matrices.WNN.PBMC_human_6x(["embedding_matrices.WNN"]):::none
  metadata_w_cell_types_tibble.ATAC.PBMC_human_6x(["metadata_w_cell_types_tibble.ATAC"]):::none --> embedding_matrices.WNN.PBMC_human_6x(["embedding_matrices.WNN"]):::none
  harmony_embeddings_matrix.ATAC.PBMC_human_6x(["harmony_embeddings_matrix.ATAC"]):::none --> embedding_matrices.WNN.PBMC_human_6x(["embedding_matrices.WNN"]):::none
  full_metadata_tibble.embryonic_brain_mouse(["full_metadata_tibble"]):::none --> excluded_cellranger_only_barcodes_by_type_list.embryonic_brain_mouse(["excluded_cellranger_only_barcodes_by_type_list"]):::none
  full_metadata_tibble.healthy_PBMC_human(["full_metadata_tibble"]):::none --> excluded_cellranger_only_barcodes_by_type_list.healthy_PBMC_human(["excluded_cellranger_only_barcodes_by_type_list"]):::none
  full_metadata_tibble.lymphoma_lymph_human(["full_metadata_tibble"]):::none --> excluded_cellranger_only_barcodes_by_type_list.lymphoma_lymph_human(["excluded_cellranger_only_barcodes_by_type_list"]):::none
  full_metadata_tibble.pbmc_10k_chromium_controller(["full_metadata_tibble"]):::none --> excluded_cellranger_only_barcodes_by_type_list.pbmc_10k_chromium_controller(["excluded_cellranger_only_barcodes_by_type_list"]):::none
  full_metadata_tibble.pbmc_10k_chromium_x(["full_metadata_tibble"]):::none --> excluded_cellranger_only_barcodes_by_type_list.pbmc_10k_chromium_x(["excluded_cellranger_only_barcodes_by_type_list"]):::none
  full_metadata_tibble.pbmc_granulocyte_sorted_10k(["full_metadata_tibble"]):::none --> excluded_cellranger_only_barcodes_by_type_list.pbmc_granulocyte_sorted_10k(["excluded_cellranger_only_barcodes_by_type_list"]):::none
  full_metadata_tibble.pbmc_unsorted_10k(["full_metadata_tibble"]):::none --> excluded_cellranger_only_barcodes_by_type_list.pbmc_unsorted_10k(["excluded_cellranger_only_barcodes_by_type_list"]):::none
  full_metadata_tibble.pbmc_unsorted_3k(["full_metadata_tibble"]):::none --> excluded_cellranger_only_barcodes_by_type_list.pbmc_unsorted_3k(["excluded_cellranger_only_barcodes_by_type_list"]):::none
  ATAC_qc_metrics_tibble.embryonic_brain_mouse(["ATAC_qc_metrics_tibble"]):::none --> full_metadata_tibble.embryonic_brain_mouse(["full_metadata_tibble"]):::none
  per_barcode_metrics_tibble.embryonic_brain_mouse(["per_barcode_metrics_tibble"]):::none --> full_metadata_tibble.embryonic_brain_mouse(["full_metadata_tibble"]):::none
  amulet_metrics_tibble.embryonic_brain_mouse(["amulet_metrics_tibble"]):::none --> full_metadata_tibble.embryonic_brain_mouse(["full_metadata_tibble"]):::none
  vireo_donor_ids_tibble.embryonic_brain_mouse(["vireo_donor_ids_tibble"]):::none --> full_metadata_tibble.embryonic_brain_mouse(["full_metadata_tibble"]):::none
  per_barcode_metrics_tibble.healthy_PBMC_human(["per_barcode_metrics_tibble"]):::none --> full_metadata_tibble.healthy_PBMC_human(["full_metadata_tibble"]):::none
  ATAC_qc_metrics_tibble.healthy_PBMC_human(["ATAC_qc_metrics_tibble"]):::none --> full_metadata_tibble.healthy_PBMC_human(["full_metadata_tibble"]):::none
  vireo_donor_ids_tibble.healthy_PBMC_human(["vireo_donor_ids_tibble"]):::none --> full_metadata_tibble.healthy_PBMC_human(["full_metadata_tibble"]):::none
  amulet_metrics_tibble.healthy_PBMC_human(["amulet_metrics_tibble"]):::none --> full_metadata_tibble.healthy_PBMC_human(["full_metadata_tibble"]):::none
  vireo_donor_ids_tibble.lymphoma_lymph_human(["vireo_donor_ids_tibble"]):::none --> full_metadata_tibble.lymphoma_lymph_human(["full_metadata_tibble"]):::none
  amulet_metrics_tibble.lymphoma_lymph_human(["amulet_metrics_tibble"]):::none --> full_metadata_tibble.lymphoma_lymph_human(["full_metadata_tibble"]):::none
  per_barcode_metrics_tibble.lymphoma_lymph_human(["per_barcode_metrics_tibble"]):::none --> full_metadata_tibble.lymphoma_lymph_human(["full_metadata_tibble"]):::none
  ATAC_qc_metrics_tibble.lymphoma_lymph_human(["ATAC_qc_metrics_tibble"]):::none --> full_metadata_tibble.lymphoma_lymph_human(["full_metadata_tibble"]):::none
  per_barcode_metrics_tibble.pbmc_10k_chromium_controller(["per_barcode_metrics_tibble"]):::none --> full_metadata_tibble.pbmc_10k_chromium_controller(["full_metadata_tibble"]):::none
  vireo_donor_ids_tibble.pbmc_10k_chromium_controller(["vireo_donor_ids_tibble"]):::none --> full_metadata_tibble.pbmc_10k_chromium_controller(["full_metadata_tibble"]):::none
  amulet_metrics_tibble.pbmc_10k_chromium_controller(["amulet_metrics_tibble"]):::none --> full_metadata_tibble.pbmc_10k_chromium_controller(["full_metadata_tibble"]):::none
  ATAC_qc_metrics_tibble.pbmc_10k_chromium_controller(["ATAC_qc_metrics_tibble"]):::none --> full_metadata_tibble.pbmc_10k_chromium_controller(["full_metadata_tibble"]):::none
  ATAC_qc_metrics_tibble.pbmc_10k_chromium_x(["ATAC_qc_metrics_tibble"]):::none --> full_metadata_tibble.pbmc_10k_chromium_x(["full_metadata_tibble"]):::none
  amulet_metrics_tibble.pbmc_10k_chromium_x(["amulet_metrics_tibble"]):::none --> full_metadata_tibble.pbmc_10k_chromium_x(["full_metadata_tibble"]):::none
  per_barcode_metrics_tibble.pbmc_10k_chromium_x(["per_barcode_metrics_tibble"]):::none --> full_metadata_tibble.pbmc_10k_chromium_x(["full_metadata_tibble"]):::none
  vireo_donor_ids_tibble.pbmc_10k_chromium_x(["vireo_donor_ids_tibble"]):::none --> full_metadata_tibble.pbmc_10k_chromium_x(["full_metadata_tibble"]):::none
  per_barcode_metrics_tibble.pbmc_granulocyte_sorted_10k(["per_barcode_metrics_tibble"]):::none --> full_metadata_tibble.pbmc_granulocyte_sorted_10k(["full_metadata_tibble"]):::none
  amulet_metrics_tibble.pbmc_granulocyte_sorted_10k(["amulet_metrics_tibble"]):::none --> full_metadata_tibble.pbmc_granulocyte_sorted_10k(["full_metadata_tibble"]):::none
  ATAC_qc_metrics_tibble.pbmc_granulocyte_sorted_10k(["ATAC_qc_metrics_tibble"]):::none --> full_metadata_tibble.pbmc_granulocyte_sorted_10k(["full_metadata_tibble"]):::none
  vireo_donor_ids_tibble.pbmc_granulocyte_sorted_10k(["vireo_donor_ids_tibble"]):::none --> full_metadata_tibble.pbmc_granulocyte_sorted_10k(["full_metadata_tibble"]):::none
  amulet_metrics_tibble.pbmc_unsorted_10k(["amulet_metrics_tibble"]):::none --> full_metadata_tibble.pbmc_unsorted_10k(["full_metadata_tibble"]):::none
  vireo_donor_ids_tibble.pbmc_unsorted_10k(["vireo_donor_ids_tibble"]):::none --> full_metadata_tibble.pbmc_unsorted_10k(["full_metadata_tibble"]):::none
  per_barcode_metrics_tibble.pbmc_unsorted_10k(["per_barcode_metrics_tibble"]):::none --> full_metadata_tibble.pbmc_unsorted_10k(["full_metadata_tibble"]):::none
  ATAC_qc_metrics_tibble.pbmc_unsorted_10k(["ATAC_qc_metrics_tibble"]):::none --> full_metadata_tibble.pbmc_unsorted_10k(["full_metadata_tibble"]):::none
  vireo_donor_ids_tibble.pbmc_unsorted_3k(["vireo_donor_ids_tibble"]):::none --> full_metadata_tibble.pbmc_unsorted_3k(["full_metadata_tibble"]):::none
  amulet_metrics_tibble.pbmc_unsorted_3k(["amulet_metrics_tibble"]):::none --> full_metadata_tibble.pbmc_unsorted_3k(["full_metadata_tibble"]):::none
  per_barcode_metrics_tibble.pbmc_unsorted_3k(["per_barcode_metrics_tibble"]):::none --> full_metadata_tibble.pbmc_unsorted_3k(["full_metadata_tibble"]):::none
  ATAC_qc_metrics_tibble.pbmc_unsorted_3k(["ATAC_qc_metrics_tibble"]):::none --> full_metadata_tibble.pbmc_unsorted_3k(["full_metadata_tibble"]):::none
  cellbender_h5_file.embryonic_brain_mouse(["cellbender_h5_file"]):::none --> GEX_counts_BPcells_matrix_dir.embryonic_brain_mouse(["GEX_counts_BPcells_matrix_dir"]):::none
  cellbender_h5_file.healthy_PBMC_human(["cellbender_h5_file"]):::none --> GEX_counts_BPcells_matrix_dir.healthy_PBMC_human(["GEX_counts_BPcells_matrix_dir"]):::none
  cellbender_h5_file.lymphoma_lymph_human(["cellbender_h5_file"]):::none --> GEX_counts_BPcells_matrix_dir.lymphoma_lymph_human(["GEX_counts_BPcells_matrix_dir"]):::none
  cellbender_h5_file.pbmc_10k_chromium_controller(["cellbender_h5_file"]):::none --> GEX_counts_BPcells_matrix_dir.pbmc_10k_chromium_controller(["GEX_counts_BPcells_matrix_dir"]):::none
  cellbender_h5_file.pbmc_10k_chromium_x(["cellbender_h5_file"]):::none --> GEX_counts_BPcells_matrix_dir.pbmc_10k_chromium_x(["GEX_counts_BPcells_matrix_dir"]):::none
  cellbender_h5_file.pbmc_granulocyte_sorted_10k(["cellbender_h5_file"]):::none --> GEX_counts_BPcells_matrix_dir.pbmc_granulocyte_sorted_10k(["GEX_counts_BPcells_matrix_dir"]):::none
  cellbender_h5_file.pbmc_unsorted_10k(["cellbender_h5_file"]):::none --> GEX_counts_BPcells_matrix_dir.pbmc_unsorted_10k(["GEX_counts_BPcells_matrix_dir"]):::none
  cellbender_h5_file.pbmc_unsorted_3k(["cellbender_h5_file"]):::none --> GEX_counts_BPcells_matrix_dir.pbmc_unsorted_3k(["GEX_counts_BPcells_matrix_dir"]):::none
  LSI_BPCells.ATAC.brain_mouse(["LSI_BPCells.ATAC"]):::none --> harmony_embeddings_matrix.ATAC.brain_mouse(["harmony_embeddings_matrix.ATAC"]):::none
  LSI_BPCells.ATAC.immune_human_2x(["LSI_BPCells.ATAC"]):::none --> harmony_embeddings_matrix.ATAC.immune_human_2x(["harmony_embeddings_matrix.ATAC"]):::none
  LSI_BPCells.ATAC.PBMC_human_6x(["LSI_BPCells.ATAC"]):::none --> harmony_embeddings_matrix.ATAC.PBMC_human_6x(["harmony_embeddings_matrix.ATAC"]):::none
  LSI_BPCells.ATAC.subgroups.brain_mouse["LSI_BPCells.ATAC.subgroups"]:::none --> harmony_embeddings_matrix.ATAC.subgroups.brain_mouse["harmony_embeddings_matrix.ATAC.subgroups"]:::none
  LSI_BPCells.ATAC.subgroups.immune_human_2x["LSI_BPCells.ATAC.subgroups"]:::none --> harmony_embeddings_matrix.ATAC.subgroups.immune_human_2x["harmony_embeddings_matrix.ATAC.subgroups"]:::none
  LSI_BPCells.ATAC.subgroups.PBMC_human_6x["LSI_BPCells.ATAC.subgroups"]:::none --> harmony_embeddings_matrix.ATAC.subgroups.PBMC_human_6x["harmony_embeddings_matrix.ATAC.subgroups"]:::none
  metadata_tibble.GEX.brain_mouse(["metadata_tibble.GEX"]):::none --> harmony_embeddings_matrix.GEX.brain_mouse(["harmony_embeddings_matrix.GEX"]):::none
  PCA_BPCells.GEX.brain_mouse(["PCA_BPCells.GEX"]):::none --> harmony_embeddings_matrix.GEX.brain_mouse(["harmony_embeddings_matrix.GEX"]):::none
  PCA_BPCells.GEX.immune_human_2x(["PCA_BPCells.GEX"]):::none --> harmony_embeddings_matrix.GEX.immune_human_2x(["harmony_embeddings_matrix.GEX"]):::none
  metadata_tibble.GEX.immune_human_2x(["metadata_tibble.GEX"]):::none --> harmony_embeddings_matrix.GEX.immune_human_2x(["harmony_embeddings_matrix.GEX"]):::none
  metadata_tibble.GEX.PBMC_human_6x(["metadata_tibble.GEX"]):::none --> harmony_embeddings_matrix.GEX.PBMC_human_6x(["harmony_embeddings_matrix.GEX"]):::none
  PCA_BPCells.GEX.PBMC_human_6x(["PCA_BPCells.GEX"]):::none --> harmony_embeddings_matrix.GEX.PBMC_human_6x(["harmony_embeddings_matrix.GEX"]):::none
  PCA_BPCells.GEX.subgroups.brain_mouse["PCA_BPCells.GEX.subgroups"]:::none --> harmony_embeddings_matrix.GEX.subgroups.brain_mouse["harmony_embeddings_matrix.GEX.subgroups"]:::none
  PCA_BPCells.GEX.subgroups.immune_human_2x["PCA_BPCells.GEX.subgroups"]:::none --> harmony_embeddings_matrix.GEX.subgroups.immune_human_2x["harmony_embeddings_matrix.GEX.subgroups"]:::none
  PCA_BPCells.GEX.subgroups.PBMC_human_6x["PCA_BPCells.GEX.subgroups"]:::none --> harmony_embeddings_matrix.GEX.subgroups.PBMC_human_6x["harmony_embeddings_matrix.GEX.subgroups"]:::none
  harmony_embeddings_matrix.ATAC.brain_mouse(["harmony_embeddings_matrix.ATAC"]):::none --> LSI_clusters.ATAC.brain_mouse(["LSI_clusters.ATAC"]):::none
  harmony_embeddings_matrix.ATAC.immune_human_2x(["harmony_embeddings_matrix.ATAC"]):::none --> LSI_clusters.ATAC.immune_human_2x(["LSI_clusters.ATAC"]):::none
  harmony_embeddings_matrix.ATAC.PBMC_human_6x(["harmony_embeddings_matrix.ATAC"]):::none --> LSI_clusters.ATAC.PBMC_human_6x(["LSI_clusters.ATAC"]):::none
  harmony_embeddings_matrix.ATAC.subgroups.brain_mouse["harmony_embeddings_matrix.ATAC.subgroups"]:::none --> LSI_clusters.ATAC.subgroups.brain_mouse["LSI_clusters.ATAC.subgroups"]:::none
  harmony_embeddings_matrix.ATAC.subgroups.immune_human_2x["harmony_embeddings_matrix.ATAC.subgroups"]:::none --> LSI_clusters.ATAC.subgroups.immune_human_2x["LSI_clusters.ATAC.subgroups"]:::none
  harmony_embeddings_matrix.ATAC.subgroups.PBMC_human_6x["harmony_embeddings_matrix.ATAC.subgroups"]:::none --> LSI_clusters.ATAC.subgroups.PBMC_human_6x["LSI_clusters.ATAC.subgroups"]:::none
  PCA_BPCells.GEX.brain_mouse(["PCA_BPCells.GEX"]):::none --> metadata_tibble.GEX.brain_mouse(["metadata_tibble.GEX"]):::none
  GEM_well_metadata_tibble.brain_mouse(["GEM_well_metadata_tibble"]):::none --> metadata_tibble.GEX.brain_mouse(["metadata_tibble.GEX"]):::none
  donor_id_metadata_tibble.brain_mouse(["donor_id_metadata_tibble"]):::none --> metadata_tibble.GEX.brain_mouse(["metadata_tibble.GEX"]):::none
  PCA_BPCells.GEX.immune_human_2x(["PCA_BPCells.GEX"]):::none --> metadata_tibble.GEX.immune_human_2x(["metadata_tibble.GEX"]):::none
  GEM_well_metadata_tibble.immune_human_2x(["GEM_well_metadata_tibble"]):::none --> metadata_tibble.GEX.immune_human_2x(["metadata_tibble.GEX"]):::none
  donor_id_metadata_tibble.immune_human_2x(["donor_id_metadata_tibble"]):::none --> metadata_tibble.GEX.immune_human_2x(["metadata_tibble.GEX"]):::none
  GEM_well_metadata_tibble.PBMC_human_6x(["GEM_well_metadata_tibble"]):::none --> metadata_tibble.GEX.PBMC_human_6x(["metadata_tibble.GEX"]):::none
  PCA_BPCells.GEX.PBMC_human_6x(["PCA_BPCells.GEX"]):::none --> metadata_tibble.GEX.PBMC_human_6x(["metadata_tibble.GEX"]):::none
  donor_id_metadata_tibble.PBMC_human_6x(["donor_id_metadata_tibble"]):::none --> metadata_tibble.GEX.PBMC_human_6x(["metadata_tibble.GEX"]):::none
  scDblFinder_results_df.ATAC.brain_mouse(["scDblFinder_results_df.ATAC"]):::none --> metadata_w_cell_types_tibble.ATAC.brain_mouse(["metadata_w_cell_types_tibble.ATAC"]):::none
  scDblFinder_results_df.ATAC.immune_human_2x(["scDblFinder_results_df.ATAC"]):::none --> metadata_w_cell_types_tibble.ATAC.immune_human_2x(["metadata_w_cell_types_tibble.ATAC"]):::none
  scDblFinder_results_df.ATAC.PBMC_human_6x(["scDblFinder_results_df.ATAC"]):::none --> metadata_w_cell_types_tibble.ATAC.PBMC_human_6x(["metadata_w_cell_types_tibble.ATAC"]):::none
  scDblFinder_results_df.GEX.brain_mouse(["scDblFinder_results_df.GEX"]):::none --> metadata_w_cell_types_tibble.GEX.brain_mouse(["metadata_w_cell_types_tibble.GEX"]):::none
  scDblFinder_results_df.GEX.immune_human_2x(["scDblFinder_results_df.GEX"]):::none --> metadata_w_cell_types_tibble.GEX.immune_human_2x(["metadata_w_cell_types_tibble.GEX"]):::none
  scDblFinder_results_df.GEX.PBMC_human_6x(["scDblFinder_results_df.GEX"]):::none --> metadata_w_cell_types_tibble.GEX.PBMC_human_6x(["metadata_w_cell_types_tibble.GEX"]):::none
  UCell_GEX_marker_genes_list.brain_mouse(["UCell_GEX_marker_genes_list"]):::none --> metadata_w_cell_types_tibble.WNN.brain_mouse(["metadata_w_cell_types_tibble.WNN"]):::none
  UCell_GEX_marker_genes_list.immune_human_2x(["UCell_GEX_marker_genes_list"]):::none --> metadata_w_cell_types_tibble.WNN.immune_human_2x(["metadata_w_cell_types_tibble.WNN"]):::none
  UCell_GEX_marker_genes_list.PBMC_human_6x(["UCell_GEX_marker_genes_list"]):::none --> metadata_w_cell_types_tibble.WNN.PBMC_human_6x(["metadata_w_cell_types_tibble.WNN"]):::none
  donor_id_metadata_tibble.brain_mouse(["donor_id_metadata_tibble"]):::none --> PCA_BPCells.GEX.brain_mouse(["PCA_BPCells.GEX"]):::none
  GEM_well_metadata_tibble.brain_mouse(["GEM_well_metadata_tibble"]):::none --> PCA_BPCells.GEX.brain_mouse(["PCA_BPCells.GEX"]):::none
  donor_id_metadata_tibble.immune_human_2x(["donor_id_metadata_tibble"]):::none --> PCA_BPCells.GEX.immune_human_2x(["PCA_BPCells.GEX"]):::none
  GEM_well_metadata_tibble.immune_human_2x(["GEM_well_metadata_tibble"]):::none --> PCA_BPCells.GEX.immune_human_2x(["PCA_BPCells.GEX"]):::none
  donor_id_metadata_tibble.PBMC_human_6x(["donor_id_metadata_tibble"]):::none --> PCA_BPCells.GEX.PBMC_human_6x(["PCA_BPCells.GEX"]):::none
  GEM_well_metadata_tibble.PBMC_human_6x(["GEM_well_metadata_tibble"]):::none --> PCA_BPCells.GEX.PBMC_human_6x(["PCA_BPCells.GEX"]):::none
  harmony_embeddings_matrix.GEX.brain_mouse(["harmony_embeddings_matrix.GEX"]):::none --> PCA_clusters.GEX.brain_mouse(["PCA_clusters.GEX"]):::none
  harmony_embeddings_matrix.GEX.immune_human_2x(["harmony_embeddings_matrix.GEX"]):::none --> PCA_clusters.GEX.immune_human_2x(["PCA_clusters.GEX"]):::none
  harmony_embeddings_matrix.GEX.PBMC_human_6x(["harmony_embeddings_matrix.GEX"]):::none --> PCA_clusters.GEX.PBMC_human_6x(["PCA_clusters.GEX"]):::none
  harmony_embeddings_matrix.GEX.subgroups.brain_mouse["harmony_embeddings_matrix.GEX.subgroups"]:::none --> PCA_clusters.GEX.subgroups.brain_mouse["PCA_clusters.GEX.subgroups"]:::none
  harmony_embeddings_matrix.GEX.subgroups.immune_human_2x["harmony_embeddings_matrix.GEX.subgroups"]:::none --> PCA_clusters.GEX.subgroups.immune_human_2x["PCA_clusters.GEX.subgroups"]:::none
  harmony_embeddings_matrix.GEX.subgroups.PBMC_human_6x["harmony_embeddings_matrix.GEX.subgroups"]:::none --> PCA_clusters.GEX.subgroups.PBMC_human_6x["PCA_clusters.GEX.subgroups"]:::none
  consensus_peak_GRanges.ATAC.brain_mouse(["consensus_peak_GRanges.ATAC"]):::none --> peak_TF_motif_matrix.ATAC.brain_mouse(["peak_TF_motif_matrix.ATAC"]):::none
  ATAC_marker_TFs_list.brain_mouse(["ATAC_marker_TFs_list"]):::none --> peak_TF_motif_matrix.ATAC.brain_mouse(["peak_TF_motif_matrix.ATAC"]):::none
  consensus_peak_GRanges.ATAC.immune_human_2x(["consensus_peak_GRanges.ATAC"]):::none --> peak_TF_motif_matrix.ATAC.immune_human_2x(["peak_TF_motif_matrix.ATAC"]):::none
  ATAC_marker_TFs_list.immune_human_2x(["ATAC_marker_TFs_list"]):::none --> peak_TF_motif_matrix.ATAC.immune_human_2x(["peak_TF_motif_matrix.ATAC"]):::none
  ATAC_marker_TFs_list.PBMC_human_6x(["ATAC_marker_TFs_list"]):::none --> peak_TF_motif_matrix.ATAC.PBMC_human_6x(["peak_TF_motif_matrix.ATAC"]):::none
  consensus_peak_GRanges.ATAC.PBMC_human_6x(["consensus_peak_GRanges.ATAC"]):::none --> peak_TF_motif_matrix.ATAC.PBMC_human_6x(["peak_TF_motif_matrix.ATAC"]):::none
  combined_BPCells_fragment_obj.ATAC.brain_mouse(["combined_BPCells_fragment_obj.ATAC"]):::none --> peaks_per_cluster_narrowPeaks.peaks.ATAC.brain_mouse["peaks_per_cluster_narrowPeaks.peaks.ATAC"]:::none
  combined_BPCells_fragment_obj.ATAC.immune_human_2x(["combined_BPCells_fragment_obj.ATAC"]):::none --> peaks_per_cluster_narrowPeaks.peaks.ATAC.immune_human_2x["peaks_per_cluster_narrowPeaks.peaks.ATAC"]:::none
  combined_BPCells_fragment_obj.ATAC.PBMC_human_6x(["combined_BPCells_fragment_obj.ATAC"]):::none --> peaks_per_cluster_narrowPeaks.peaks.ATAC.PBMC_human_6x["peaks_per_cluster_narrowPeaks.peaks.ATAC"]:::none
  donor_id_metadata_tibble.brain_mouse(["donor_id_metadata_tibble"]):::none --> GEM_well_metadata_tibble.brain_mouse(["GEM_well_metadata_tibble"]):::none
  donor_id_metadata_tibble.immune_human_2x(["donor_id_metadata_tibble"]):::none --> GEM_well_metadata_tibble.immune_human_2x(["GEM_well_metadata_tibble"]):::none
  donor_id_metadata_tibble.PBMC_human_6x(["donor_id_metadata_tibble"]):::none --> GEM_well_metadata_tibble.PBMC_human_6x(["GEM_well_metadata_tibble"]):::none
  harmony_embeddings_matrix.ATAC.brain_mouse(["harmony_embeddings_matrix.ATAC"]):::none --> UMAP_embeddings_tibble.ATAC.brain_mouse(["UMAP_embeddings_tibble.ATAC"]):::none
  harmony_embeddings_matrix.ATAC.immune_human_2x(["harmony_embeddings_matrix.ATAC"]):::none --> UMAP_embeddings_tibble.ATAC.immune_human_2x(["UMAP_embeddings_tibble.ATAC"]):::none
  harmony_embeddings_matrix.ATAC.PBMC_human_6x(["harmony_embeddings_matrix.ATAC"]):::none --> UMAP_embeddings_tibble.ATAC.PBMC_human_6x(["UMAP_embeddings_tibble.ATAC"]):::none
  harmony_embeddings_matrix.ATAC.subgroups.brain_mouse["harmony_embeddings_matrix.ATAC.subgroups"]:::none --> UMAP_embeddings_tibble.ATAC.subgroups.brain_mouse["UMAP_embeddings_tibble.ATAC.subgroups"]:::none
  harmony_embeddings_matrix.ATAC.subgroups.immune_human_2x["harmony_embeddings_matrix.ATAC.subgroups"]:::none --> UMAP_embeddings_tibble.ATAC.subgroups.immune_human_2x["UMAP_embeddings_tibble.ATAC.subgroups"]:::none
  harmony_embeddings_matrix.ATAC.subgroups.PBMC_human_6x["harmony_embeddings_matrix.ATAC.subgroups"]:::none --> UMAP_embeddings_tibble.ATAC.subgroups.PBMC_human_6x["UMAP_embeddings_tibble.ATAC.subgroups"]:::none
  PCA_BPCells.GEX.brain_mouse(["PCA_BPCells.GEX"]):::none --> UMAP_embeddings_tibble.GEX_non_harmony.brain_mouse(["UMAP_embeddings_tibble.GEX_non_harmony"]):::none
  PCA_BPCells.GEX.immune_human_2x(["PCA_BPCells.GEX"]):::none --> UMAP_embeddings_tibble.GEX_non_harmony.immune_human_2x(["UMAP_embeddings_tibble.GEX_non_harmony"]):::none
  PCA_BPCells.GEX.PBMC_human_6x(["PCA_BPCells.GEX"]):::none --> UMAP_embeddings_tibble.GEX_non_harmony.PBMC_human_6x(["UMAP_embeddings_tibble.GEX_non_harmony"]):::none
  harmony_embeddings_matrix.GEX.brain_mouse(["harmony_embeddings_matrix.GEX"]):::none --> UMAP_embeddings_tibble.GEX.brain_mouse(["UMAP_embeddings_tibble.GEX"]):::none
  harmony_embeddings_matrix.GEX.immune_human_2x(["harmony_embeddings_matrix.GEX"]):::none --> UMAP_embeddings_tibble.GEX.immune_human_2x(["UMAP_embeddings_tibble.GEX"]):::none
  harmony_embeddings_matrix.GEX.PBMC_human_6x(["harmony_embeddings_matrix.GEX"]):::none --> UMAP_embeddings_tibble.GEX.PBMC_human_6x(["UMAP_embeddings_tibble.GEX"]):::none
  harmony_embeddings_matrix.GEX.subgroups.brain_mouse["harmony_embeddings_matrix.GEX.subgroups"]:::none --> UMAP_embeddings_tibble.GEX.subgroups.brain_mouse["UMAP_embeddings_tibble.GEX.subgroups"]:::none
  harmony_embeddings_matrix.GEX.subgroups.immune_human_2x["harmony_embeddings_matrix.GEX.subgroups"]:::none --> UMAP_embeddings_tibble.GEX.subgroups.immune_human_2x["UMAP_embeddings_tibble.GEX.subgroups"]:::none
  harmony_embeddings_matrix.GEX.subgroups.PBMC_human_6x["harmony_embeddings_matrix.GEX.subgroups"]:::none --> UMAP_embeddings_tibble.GEX.subgroups.PBMC_human_6x["UMAP_embeddings_tibble.GEX.subgroups"]:::none
  WNN_results.brain_mouse(["WNN_results"]):::none --> UMAP_embeddings_tibble.WNN.brain_mouse(["UMAP_embeddings_tibble.WNN"]):::none
  WNN_results.immune_human_2x(["WNN_results"]):::none --> UMAP_embeddings_tibble.WNN.immune_human_2x(["UMAP_embeddings_tibble.WNN"]):::none
  WNN_results.PBMC_human_6x(["WNN_results"]):::none --> UMAP_embeddings_tibble.WNN.PBMC_human_6x(["UMAP_embeddings_tibble.WNN"]):::none
  WNN_results.subgroups.brain_mouse["WNN_results.subgroups"]:::none --> UMAP_embeddings_tibble.WNN.subgroups.brain_mouse["UMAP_embeddings_tibble.WNN.subgroups"]:::none
  WNN_results.subgroups.immune_human_2x["WNN_results.subgroups"]:::none --> UMAP_embeddings_tibble.WNN.subgroups.immune_human_2x["UMAP_embeddings_tibble.WNN.subgroups"]:::none
  WNN_results.subgroups.PBMC_human_6x["WNN_results.subgroups"]:::none --> UMAP_embeddings_tibble.WNN.subgroups.PBMC_human_6x["UMAP_embeddings_tibble.WNN.subgroups"]:::none
  cellsnp_dir.embryonic_brain_mouse(["cellsnp_dir"]):::none --> vireo_donor_ids_tibble.embryonic_brain_mouse(["vireo_donor_ids_tibble"]):::none
  cellranger_barcodes_tsv.embryonic_brain_mouse(["cellranger_barcodes_tsv"]):::none --> vireo_donor_ids_tibble.embryonic_brain_mouse(["vireo_donor_ids_tibble"]):::none
  cellsnp_dir.healthy_PBMC_human(["cellsnp_dir"]):::none --> vireo_donor_ids_tibble.healthy_PBMC_human(["vireo_donor_ids_tibble"]):::none
  cellranger_barcodes_tsv.healthy_PBMC_human(["cellranger_barcodes_tsv"]):::none --> vireo_donor_ids_tibble.healthy_PBMC_human(["vireo_donor_ids_tibble"]):::none
  cellsnp_dir.lymphoma_lymph_human(["cellsnp_dir"]):::none --> vireo_donor_ids_tibble.lymphoma_lymph_human(["vireo_donor_ids_tibble"]):::none
  cellranger_barcodes_tsv.lymphoma_lymph_human(["cellranger_barcodes_tsv"]):::none --> vireo_donor_ids_tibble.lymphoma_lymph_human(["vireo_donor_ids_tibble"]):::none
  cellranger_barcodes_tsv.pbmc_10k_chromium_controller(["cellranger_barcodes_tsv"]):::none --> vireo_donor_ids_tibble.pbmc_10k_chromium_controller(["vireo_donor_ids_tibble"]):::none
  cellsnp_dir.pbmc_10k_chromium_controller(["cellsnp_dir"]):::none --> vireo_donor_ids_tibble.pbmc_10k_chromium_controller(["vireo_donor_ids_tibble"]):::none
  cellranger_barcodes_tsv.pbmc_10k_chromium_x(["cellranger_barcodes_tsv"]):::none --> vireo_donor_ids_tibble.pbmc_10k_chromium_x(["vireo_donor_ids_tibble"]):::none
  cellsnp_dir.pbmc_10k_chromium_x(["cellsnp_dir"]):::none --> vireo_donor_ids_tibble.pbmc_10k_chromium_x(["vireo_donor_ids_tibble"]):::none
  cellsnp_dir.pbmc_granulocyte_sorted_10k(["cellsnp_dir"]):::none --> vireo_donor_ids_tibble.pbmc_granulocyte_sorted_10k(["vireo_donor_ids_tibble"]):::none
  cellranger_barcodes_tsv.pbmc_granulocyte_sorted_10k(["cellranger_barcodes_tsv"]):::none --> vireo_donor_ids_tibble.pbmc_granulocyte_sorted_10k(["vireo_donor_ids_tibble"]):::none
  cellsnp_dir.pbmc_unsorted_10k(["cellsnp_dir"]):::none --> vireo_donor_ids_tibble.pbmc_unsorted_10k(["vireo_donor_ids_tibble"]):::none
  cellranger_barcodes_tsv.pbmc_unsorted_10k(["cellranger_barcodes_tsv"]):::none --> vireo_donor_ids_tibble.pbmc_unsorted_10k(["vireo_donor_ids_tibble"]):::none
  cellsnp_dir.pbmc_unsorted_3k(["cellsnp_dir"]):::none --> vireo_donor_ids_tibble.pbmc_unsorted_3k(["vireo_donor_ids_tibble"]):::none
  cellranger_barcodes_tsv.pbmc_unsorted_3k(["cellranger_barcodes_tsv"]):::none --> vireo_donor_ids_tibble.pbmc_unsorted_3k(["vireo_donor_ids_tibble"]):::none
  embedding_matrices.WNN.brain_mouse(["embedding_matrices.WNN"]):::none --> WNN_results.brain_mouse(["WNN_results"]):::none
  clusters_tibble.WNN.brain_mouse(["clusters_tibble.WNN"]):::none --> WNN_results.brain_mouse(["WNN_results"]):::none
  clusters_tibble.WNN.immune_human_2x(["clusters_tibble.WNN"]):::none --> WNN_results.immune_human_2x(["WNN_results"]):::none
  embedding_matrices.WNN.immune_human_2x(["embedding_matrices.WNN"]):::none --> WNN_results.immune_human_2x(["WNN_results"]):::none
  embedding_matrices.WNN.PBMC_human_6x(["embedding_matrices.WNN"]):::none --> WNN_results.PBMC_human_6x(["WNN_results"]):::none
  clusters_tibble.WNN.PBMC_human_6x(["clusters_tibble.WNN"]):::none --> WNN_results.PBMC_human_6x(["WNN_results"]):::none
  aggregated_GEX_BPCells_matrix_dir.GEX.brain_mouse(["aggregated_GEX_BPCells_matrix_dir.GEX"]):::none --> PCA_BPCells.GEX.brain_mouse(["PCA_BPCells.GEX"]):::none
  aggregated_GEX_BPCells_matrix_dir.GEX.brain_mouse(["aggregated_GEX_BPCells_matrix_dir.GEX"]):::none --> PCA_BPCells.GEX.subgroups.brain_mouse["PCA_BPCells.GEX.subgroups"]:::none
  aggregated_GEX_BPCells_matrix_dir.GEX.brain_mouse(["aggregated_GEX_BPCells_matrix_dir.GEX"]):::none --> metadata_w_cell_types_tibble.GEX.brain_mouse(["metadata_w_cell_types_tibble.GEX"]):::none
  aggregated_GEX_BPCells_matrix_dir.GEX.brain_mouse(["aggregated_GEX_BPCells_matrix_dir.GEX"]):::none --> scDblFinder_results_df.GEX.brain_mouse(["scDblFinder_results_df.GEX"]):::none
  aggregated_GEX_BPCells_matrix_dir.GEX.immune_human_2x(["aggregated_GEX_BPCells_matrix_dir.GEX"]):::none --> PCA_BPCells.GEX.immune_human_2x(["PCA_BPCells.GEX"]):::none
  aggregated_GEX_BPCells_matrix_dir.GEX.immune_human_2x(["aggregated_GEX_BPCells_matrix_dir.GEX"]):::none --> PCA_BPCells.GEX.subgroups.immune_human_2x["PCA_BPCells.GEX.subgroups"]:::none
  aggregated_GEX_BPCells_matrix_dir.GEX.immune_human_2x(["aggregated_GEX_BPCells_matrix_dir.GEX"]):::none --> metadata_w_cell_types_tibble.GEX.immune_human_2x(["metadata_w_cell_types_tibble.GEX"]):::none
  aggregated_GEX_BPCells_matrix_dir.GEX.immune_human_2x(["aggregated_GEX_BPCells_matrix_dir.GEX"]):::none --> scDblFinder_results_df.GEX.immune_human_2x(["scDblFinder_results_df.GEX"]):::none
  aggregated_GEX_BPCells_matrix_dir.GEX.PBMC_human_6x(["aggregated_GEX_BPCells_matrix_dir.GEX"]):::none --> PCA_BPCells.GEX.PBMC_human_6x(["PCA_BPCells.GEX"]):::none
  aggregated_GEX_BPCells_matrix_dir.GEX.PBMC_human_6x(["aggregated_GEX_BPCells_matrix_dir.GEX"]):::none --> PCA_BPCells.GEX.subgroups.PBMC_human_6x["PCA_BPCells.GEX.subgroups"]:::none
  aggregated_GEX_BPCells_matrix_dir.GEX.PBMC_human_6x(["aggregated_GEX_BPCells_matrix_dir.GEX"]):::none --> metadata_w_cell_types_tibble.GEX.PBMC_human_6x(["metadata_w_cell_types_tibble.GEX"]):::none
  aggregated_GEX_BPCells_matrix_dir.GEX.PBMC_human_6x(["aggregated_GEX_BPCells_matrix_dir.GEX"]):::none --> scDblFinder_results_df.GEX.PBMC_human_6x(["scDblFinder_results_df.GEX"]):::none
  metadata_w_cell_types_tibble.GEX.brain_mouse(["metadata_w_cell_types_tibble.GEX"]):::none --> peaks_per_cluster_narrowPeaks.peaks.ATAC.brain_mouse["peaks_per_cluster_narrowPeaks.peaks.ATAC"]:::none
  metadata_w_cell_types_tibble.GEX.immune_human_2x(["metadata_w_cell_types_tibble.GEX"]):::none --> peaks_per_cluster_narrowPeaks.peaks.ATAC.immune_human_2x["peaks_per_cluster_narrowPeaks.peaks.ATAC"]:::none
  metadata_w_cell_types_tibble.GEX.PBMC_human_6x(["metadata_w_cell_types_tibble.GEX"]):::none --> peaks_per_cluster_narrowPeaks.peaks.ATAC.PBMC_human_6x["peaks_per_cluster_narrowPeaks.peaks.ATAC"]:::none
  full_metadata_tibble.embryonic_brain_mouse(["full_metadata_tibble"]):::none --> metadata_tibble.GEX.brain_mouse(["metadata_tibble.GEX"]):::none
  full_metadata_tibble.embryonic_brain_mouse(["full_metadata_tibble"]):::none --> PCA_BPCells.GEX.brain_mouse(["PCA_BPCells.GEX"]):::none
  full_metadata_tibble.healthy_PBMC_human(["full_metadata_tibble"]):::none --> metadata_tibble.GEX.immune_human_2x(["metadata_tibble.GEX"]):::none
  full_metadata_tibble.healthy_PBMC_human(["full_metadata_tibble"]):::none --> PCA_BPCells.GEX.immune_human_2x(["PCA_BPCells.GEX"]):::none
  full_metadata_tibble.healthy_PBMC_human(["full_metadata_tibble"]):::none --> metadata_tibble.GEX.PBMC_human_6x(["metadata_tibble.GEX"]):::none
  full_metadata_tibble.healthy_PBMC_human(["full_metadata_tibble"]):::none --> PCA_BPCells.GEX.PBMC_human_6x(["PCA_BPCells.GEX"]):::none
  full_metadata_tibble.lymphoma_lymph_human(["full_metadata_tibble"]):::none --> metadata_tibble.GEX.immune_human_2x(["metadata_tibble.GEX"]):::none
  full_metadata_tibble.lymphoma_lymph_human(["full_metadata_tibble"]):::none --> PCA_BPCells.GEX.immune_human_2x(["PCA_BPCells.GEX"]):::none
  full_metadata_tibble.pbmc_10k_chromium_controller(["full_metadata_tibble"]):::none --> metadata_tibble.GEX.PBMC_human_6x(["metadata_tibble.GEX"]):::none
  full_metadata_tibble.pbmc_10k_chromium_controller(["full_metadata_tibble"]):::none --> PCA_BPCells.GEX.PBMC_human_6x(["PCA_BPCells.GEX"]):::none
  full_metadata_tibble.pbmc_10k_chromium_x(["full_metadata_tibble"]):::none --> metadata_tibble.GEX.PBMC_human_6x(["metadata_tibble.GEX"]):::none
  full_metadata_tibble.pbmc_10k_chromium_x(["full_metadata_tibble"]):::none --> PCA_BPCells.GEX.PBMC_human_6x(["PCA_BPCells.GEX"]):::none
  full_metadata_tibble.pbmc_granulocyte_sorted_10k(["full_metadata_tibble"]):::none --> metadata_tibble.GEX.PBMC_human_6x(["metadata_tibble.GEX"]):::none
  full_metadata_tibble.pbmc_granulocyte_sorted_10k(["full_metadata_tibble"]):::none --> PCA_BPCells.GEX.PBMC_human_6x(["PCA_BPCells.GEX"]):::none
  full_metadata_tibble.pbmc_unsorted_10k(["full_metadata_tibble"]):::none --> metadata_tibble.GEX.PBMC_human_6x(["metadata_tibble.GEX"]):::none
  full_metadata_tibble.pbmc_unsorted_10k(["full_metadata_tibble"]):::none --> PCA_BPCells.GEX.PBMC_human_6x(["PCA_BPCells.GEX"]):::none
  full_metadata_tibble.pbmc_unsorted_3k(["full_metadata_tibble"]):::none --> metadata_tibble.GEX.PBMC_human_6x(["metadata_tibble.GEX"]):::none
  full_metadata_tibble.pbmc_unsorted_3k(["full_metadata_tibble"]):::none --> PCA_BPCells.GEX.PBMC_human_6x(["PCA_BPCells.GEX"]):::none
  chromVAR_obj.ATAC.brain_mouse(["chromVAR_obj.ATAC"]):::none --> TF_activity_BPCells_matrix_dir.ATAC.brain_mouse(["TF_activity_BPCells_matrix_dir.ATAC"]):::none
  chromVAR_obj.ATAC.immune_human_2x(["chromVAR_obj.ATAC"]):::none --> TF_activity_BPCells_matrix_dir.ATAC.immune_human_2x(["TF_activity_BPCells_matrix_dir.ATAC"]):::none
  chromVAR_obj.ATAC.PBMC_human_6x(["chromVAR_obj.ATAC"]):::none --> TF_activity_BPCells_matrix_dir.ATAC.PBMC_human_6x(["TF_activity_BPCells_matrix_dir.ATAC"]):::none
  peak_TF_motif_matrix.ATAC.brain_mouse(["peak_TF_motif_matrix.ATAC"]):::none --> TF_activity_BPCells_matrix_dir.ATAC.brain_mouse(["TF_activity_BPCells_matrix_dir.ATAC"]):::none
  peak_TF_motif_matrix.ATAC.immune_human_2x(["peak_TF_motif_matrix.ATAC"]):::none --> TF_activity_BPCells_matrix_dir.ATAC.immune_human_2x(["TF_activity_BPCells_matrix_dir.ATAC"]):::none
  peak_TF_motif_matrix.ATAC.PBMC_human_6x(["peak_TF_motif_matrix.ATAC"]):::none --> TF_activity_BPCells_matrix_dir.ATAC.PBMC_human_6x(["TF_activity_BPCells_matrix_dir.ATAC"]):::none
  embedding_matrices.WNN.brain_mouse(["embedding_matrices.WNN"]):::none --> clusters_tibble.WNN.brain_mouse(["clusters_tibble.WNN"]):::none
  embedding_matrices.WNN.immune_human_2x(["embedding_matrices.WNN"]):::none --> clusters_tibble.WNN.immune_human_2x(["clusters_tibble.WNN"]):::none
  embedding_matrices.WNN.PBMC_human_6x(["embedding_matrices.WNN"]):::none --> clusters_tibble.WNN.PBMC_human_6x(["clusters_tibble.WNN"]):::none
  consensus_peak_BPCells_matrix_dir.ATAC.brain_mouse(["consensus_peak_BPCells_matrix_dir.ATAC"]):::none --> chromVAR_obj.ATAC.brain_mouse(["chromVAR_obj.ATAC"]):::none
  consensus_peak_BPCells_matrix_dir.ATAC.brain_mouse(["consensus_peak_BPCells_matrix_dir.ATAC"]):::none --> peak_TF_motif_matrix.ATAC.brain_mouse(["peak_TF_motif_matrix.ATAC"]):::none
  consensus_peak_BPCells_matrix_dir.ATAC.brain_mouse(["consensus_peak_BPCells_matrix_dir.ATAC"]):::none --> LSI_BPCells.ATAC.brain_mouse(["LSI_BPCells.ATAC"]):::none
  consensus_peak_BPCells_matrix_dir.ATAC.brain_mouse(["consensus_peak_BPCells_matrix_dir.ATAC"]):::none --> LSI_BPCells.ATAC.subgroups.brain_mouse["LSI_BPCells.ATAC.subgroups"]:::none
  consensus_peak_BPCells_matrix_dir.ATAC.brain_mouse(["consensus_peak_BPCells_matrix_dir.ATAC"]):::none --> harmony_embeddings_matrix.ATAC.brain_mouse(["harmony_embeddings_matrix.ATAC"]):::none
  consensus_peak_BPCells_matrix_dir.ATAC.brain_mouse(["consensus_peak_BPCells_matrix_dir.ATAC"]):::none --> scDblFinder_results_df.ATAC.brain_mouse(["scDblFinder_results_df.ATAC"]):::none
  consensus_peak_BPCells_matrix_dir.ATAC.brain_mouse(["consensus_peak_BPCells_matrix_dir.ATAC"]):::none --> metadata_w_cell_types_tibble.ATAC.brain_mouse(["metadata_w_cell_types_tibble.ATAC"]):::none
  consensus_peak_BPCells_matrix_dir.ATAC.immune_human_2x(["consensus_peak_BPCells_matrix_dir.ATAC"]):::none --> chromVAR_obj.ATAC.immune_human_2x(["chromVAR_obj.ATAC"]):::none
  consensus_peak_BPCells_matrix_dir.ATAC.immune_human_2x(["consensus_peak_BPCells_matrix_dir.ATAC"]):::none --> peak_TF_motif_matrix.ATAC.immune_human_2x(["peak_TF_motif_matrix.ATAC"]):::none
  consensus_peak_BPCells_matrix_dir.ATAC.immune_human_2x(["consensus_peak_BPCells_matrix_dir.ATAC"]):::none --> LSI_BPCells.ATAC.immune_human_2x(["LSI_BPCells.ATAC"]):::none
  consensus_peak_BPCells_matrix_dir.ATAC.immune_human_2x(["consensus_peak_BPCells_matrix_dir.ATAC"]):::none --> LSI_BPCells.ATAC.subgroups.immune_human_2x["LSI_BPCells.ATAC.subgroups"]:::none
  consensus_peak_BPCells_matrix_dir.ATAC.immune_human_2x(["consensus_peak_BPCells_matrix_dir.ATAC"]):::none --> harmony_embeddings_matrix.ATAC.immune_human_2x(["harmony_embeddings_matrix.ATAC"]):::none
  consensus_peak_BPCells_matrix_dir.ATAC.immune_human_2x(["consensus_peak_BPCells_matrix_dir.ATAC"]):::none --> scDblFinder_results_df.ATAC.immune_human_2x(["scDblFinder_results_df.ATAC"]):::none
  consensus_peak_BPCells_matrix_dir.ATAC.immune_human_2x(["consensus_peak_BPCells_matrix_dir.ATAC"]):::none --> metadata_w_cell_types_tibble.ATAC.immune_human_2x(["metadata_w_cell_types_tibble.ATAC"]):::none
  consensus_peak_BPCells_matrix_dir.ATAC.PBMC_human_6x(["consensus_peak_BPCells_matrix_dir.ATAC"]):::none --> chromVAR_obj.ATAC.PBMC_human_6x(["chromVAR_obj.ATAC"]):::none
  consensus_peak_BPCells_matrix_dir.ATAC.PBMC_human_6x(["consensus_peak_BPCells_matrix_dir.ATAC"]):::none --> peak_TF_motif_matrix.ATAC.PBMC_human_6x(["peak_TF_motif_matrix.ATAC"]):::none
  consensus_peak_BPCells_matrix_dir.ATAC.PBMC_human_6x(["consensus_peak_BPCells_matrix_dir.ATAC"]):::none --> LSI_BPCells.ATAC.PBMC_human_6x(["LSI_BPCells.ATAC"]):::none
  consensus_peak_BPCells_matrix_dir.ATAC.PBMC_human_6x(["consensus_peak_BPCells_matrix_dir.ATAC"]):::none --> LSI_BPCells.ATAC.subgroups.PBMC_human_6x["LSI_BPCells.ATAC.subgroups"]:::none
  consensus_peak_BPCells_matrix_dir.ATAC.PBMC_human_6x(["consensus_peak_BPCells_matrix_dir.ATAC"]):::none --> harmony_embeddings_matrix.ATAC.PBMC_human_6x(["harmony_embeddings_matrix.ATAC"]):::none
  consensus_peak_BPCells_matrix_dir.ATAC.PBMC_human_6x(["consensus_peak_BPCells_matrix_dir.ATAC"]):::none --> scDblFinder_results_df.ATAC.PBMC_human_6x(["scDblFinder_results_df.ATAC"]):::none
  consensus_peak_BPCells_matrix_dir.ATAC.PBMC_human_6x(["consensus_peak_BPCells_matrix_dir.ATAC"]):::none --> metadata_w_cell_types_tibble.ATAC.PBMC_human_6x(["metadata_w_cell_types_tibble.ATAC"]):::none
  harmony_embeddings_matrix.ATAC.subgroups.brain_mouse["harmony_embeddings_matrix.ATAC.subgroups"]:::none --> WNN_results.subgroups.brain_mouse["WNN_results.subgroups"]:::none
  harmony_embeddings_matrix.GEX.subgroups.brain_mouse["harmony_embeddings_matrix.GEX.subgroups"]:::none --> WNN_results.subgroups.brain_mouse["WNN_results.subgroups"]:::none
  metadata_w_cell_types_tibble.WNN.brain_mouse(["metadata_w_cell_types_tibble.WNN"]):::none --> WNN_results.subgroups.brain_mouse["WNN_results.subgroups"]:::none
  harmony_embeddings_matrix.ATAC.subgroups.immune_human_2x["harmony_embeddings_matrix.ATAC.subgroups"]:::none --> WNN_results.subgroups.immune_human_2x["WNN_results.subgroups"]:::none
  harmony_embeddings_matrix.GEX.subgroups.immune_human_2x["harmony_embeddings_matrix.GEX.subgroups"]:::none --> WNN_results.subgroups.immune_human_2x["WNN_results.subgroups"]:::none
  metadata_w_cell_types_tibble.WNN.immune_human_2x(["metadata_w_cell_types_tibble.WNN"]):::none --> WNN_results.subgroups.immune_human_2x["WNN_results.subgroups"]:::none
  harmony_embeddings_matrix.GEX.subgroups.PBMC_human_6x["harmony_embeddings_matrix.GEX.subgroups"]:::none --> WNN_results.subgroups.PBMC_human_6x["WNN_results.subgroups"]:::none
  harmony_embeddings_matrix.ATAC.subgroups.PBMC_human_6x["harmony_embeddings_matrix.ATAC.subgroups"]:::none --> WNN_results.subgroups.PBMC_human_6x["WNN_results.subgroups"]:::none
  metadata_w_cell_types_tibble.WNN.PBMC_human_6x(["metadata_w_cell_types_tibble.WNN"]):::none --> WNN_results.subgroups.PBMC_human_6x["WNN_results.subgroups"]:::none
  fragments_w_prefix_bpcells_dir.embryonic_brain_mouse(["fragments_w_prefix_bpcells_dir"]):::none --> ATAC_qc_metrics_tibble.embryonic_brain_mouse(["ATAC_qc_metrics_tibble"]):::none
  fragments_w_prefix_bpcells_dir.embryonic_brain_mouse(["fragments_w_prefix_bpcells_dir"]):::none --> combined_BPCells_fragment_obj.ATAC.brain_mouse(["combined_BPCells_fragment_obj.ATAC"]):::none
  fragments_w_prefix_bpcells_dir.healthy_PBMC_human(["fragments_w_prefix_bpcells_dir"]):::none --> ATAC_qc_metrics_tibble.healthy_PBMC_human(["ATAC_qc_metrics_tibble"]):::none
  fragments_w_prefix_bpcells_dir.healthy_PBMC_human(["fragments_w_prefix_bpcells_dir"]):::none --> combined_BPCells_fragment_obj.ATAC.immune_human_2x(["combined_BPCells_fragment_obj.ATAC"]):::none
  fragments_w_prefix_bpcells_dir.healthy_PBMC_human(["fragments_w_prefix_bpcells_dir"]):::none --> combined_BPCells_fragment_obj.ATAC.PBMC_human_6x(["combined_BPCells_fragment_obj.ATAC"]):::none
  fragments_w_prefix_bpcells_dir.lymphoma_lymph_human(["fragments_w_prefix_bpcells_dir"]):::none --> ATAC_qc_metrics_tibble.lymphoma_lymph_human(["ATAC_qc_metrics_tibble"]):::none
  fragments_w_prefix_bpcells_dir.lymphoma_lymph_human(["fragments_w_prefix_bpcells_dir"]):::none --> combined_BPCells_fragment_obj.ATAC.immune_human_2x(["combined_BPCells_fragment_obj.ATAC"]):::none
  fragments_w_prefix_bpcells_dir.pbmc_10k_chromium_controller(["fragments_w_prefix_bpcells_dir"]):::none --> ATAC_qc_metrics_tibble.pbmc_10k_chromium_controller(["ATAC_qc_metrics_tibble"]):::none
  fragments_w_prefix_bpcells_dir.pbmc_10k_chromium_controller(["fragments_w_prefix_bpcells_dir"]):::none --> combined_BPCells_fragment_obj.ATAC.PBMC_human_6x(["combined_BPCells_fragment_obj.ATAC"]):::none
  fragments_w_prefix_bpcells_dir.pbmc_10k_chromium_x(["fragments_w_prefix_bpcells_dir"]):::none --> ATAC_qc_metrics_tibble.pbmc_10k_chromium_x(["ATAC_qc_metrics_tibble"]):::none
  fragments_w_prefix_bpcells_dir.pbmc_10k_chromium_x(["fragments_w_prefix_bpcells_dir"]):::none --> combined_BPCells_fragment_obj.ATAC.PBMC_human_6x(["combined_BPCells_fragment_obj.ATAC"]):::none
  fragments_w_prefix_bpcells_dir.pbmc_granulocyte_sorted_10k(["fragments_w_prefix_bpcells_dir"]):::none --> ATAC_qc_metrics_tibble.pbmc_granulocyte_sorted_10k(["ATAC_qc_metrics_tibble"]):::none
  fragments_w_prefix_bpcells_dir.pbmc_granulocyte_sorted_10k(["fragments_w_prefix_bpcells_dir"]):::none --> combined_BPCells_fragment_obj.ATAC.PBMC_human_6x(["combined_BPCells_fragment_obj.ATAC"]):::none
  fragments_w_prefix_bpcells_dir.pbmc_unsorted_10k(["fragments_w_prefix_bpcells_dir"]):::none --> ATAC_qc_metrics_tibble.pbmc_unsorted_10k(["ATAC_qc_metrics_tibble"]):::none
  fragments_w_prefix_bpcells_dir.pbmc_unsorted_10k(["fragments_w_prefix_bpcells_dir"]):::none --> combined_BPCells_fragment_obj.ATAC.PBMC_human_6x(["combined_BPCells_fragment_obj.ATAC"]):::none
  fragments_w_prefix_bpcells_dir.pbmc_unsorted_3k(["fragments_w_prefix_bpcells_dir"]):::none --> ATAC_qc_metrics_tibble.pbmc_unsorted_3k(["ATAC_qc_metrics_tibble"]):::none
  fragments_w_prefix_bpcells_dir.pbmc_unsorted_3k(["fragments_w_prefix_bpcells_dir"]):::none --> combined_BPCells_fragment_obj.ATAC.PBMC_human_6x(["combined_BPCells_fragment_obj.ATAC"]):::none
  GEX_counts_BPcells_matrix_dir.embryonic_brain_mouse(["GEX_counts_BPcells_matrix_dir"]):::none --> full_metadata_tibble.embryonic_brain_mouse(["full_metadata_tibble"]):::none
  GEX_counts_BPcells_matrix_dir.healthy_PBMC_human(["GEX_counts_BPcells_matrix_dir"]):::none --> full_metadata_tibble.healthy_PBMC_human(["full_metadata_tibble"]):::none
  GEX_counts_BPcells_matrix_dir.lymphoma_lymph_human(["GEX_counts_BPcells_matrix_dir"]):::none --> full_metadata_tibble.lymphoma_lymph_human(["full_metadata_tibble"]):::none
  GEX_counts_BPcells_matrix_dir.pbmc_10k_chromium_controller(["GEX_counts_BPcells_matrix_dir"]):::none --> full_metadata_tibble.pbmc_10k_chromium_controller(["full_metadata_tibble"]):::none
  GEX_counts_BPcells_matrix_dir.pbmc_10k_chromium_x(["GEX_counts_BPcells_matrix_dir"]):::none --> full_metadata_tibble.pbmc_10k_chromium_x(["full_metadata_tibble"]):::none
  GEX_counts_BPcells_matrix_dir.pbmc_granulocyte_sorted_10k(["GEX_counts_BPcells_matrix_dir"]):::none --> full_metadata_tibble.pbmc_granulocyte_sorted_10k(["full_metadata_tibble"]):::none
  GEX_counts_BPcells_matrix_dir.pbmc_unsorted_10k(["GEX_counts_BPcells_matrix_dir"]):::none --> full_metadata_tibble.pbmc_unsorted_10k(["full_metadata_tibble"]):::none
  GEX_counts_BPcells_matrix_dir.pbmc_unsorted_3k(["GEX_counts_BPcells_matrix_dir"]):::none --> full_metadata_tibble.pbmc_unsorted_3k(["full_metadata_tibble"]):::none
  excluded_cellranger_only_barcodes_by_type_list.embryonic_brain_mouse(["excluded_cellranger_only_barcodes_by_type_list"]):::none --> metadata_tibble.GEX.brain_mouse(["metadata_tibble.GEX"]):::none
  excluded_cellranger_only_barcodes_by_type_list.embryonic_brain_mouse(["excluded_cellranger_only_barcodes_by_type_list"]):::none --> PCA_BPCells.GEX.brain_mouse(["PCA_BPCells.GEX"]):::none
  excluded_cellranger_only_barcodes_by_type_list.lymphoma_lymph_human(["excluded_cellranger_only_barcodes_by_type_list"]):::none --> metadata_tibble.GEX.immune_human_2x(["metadata_tibble.GEX"]):::none
  excluded_cellranger_only_barcodes_by_type_list.healthy_PBMC_human(["excluded_cellranger_only_barcodes_by_type_list"]):::none --> metadata_tibble.GEX.immune_human_2x(["metadata_tibble.GEX"]):::none
  excluded_cellranger_only_barcodes_by_type_list.lymphoma_lymph_human(["excluded_cellranger_only_barcodes_by_type_list"]):::none --> PCA_BPCells.GEX.immune_human_2x(["PCA_BPCells.GEX"]):::none
  excluded_cellranger_only_barcodes_by_type_list.healthy_PBMC_human(["excluded_cellranger_only_barcodes_by_type_list"]):::none --> PCA_BPCells.GEX.immune_human_2x(["PCA_BPCells.GEX"]):::none
  excluded_cellranger_only_barcodes_by_type_list.pbmc_10k_chromium_controller(["excluded_cellranger_only_barcodes_by_type_list"]):::none --> metadata_tibble.GEX.PBMC_human_6x(["metadata_tibble.GEX"]):::none
  excluded_cellranger_only_barcodes_by_type_list.pbmc_unsorted_10k(["excluded_cellranger_only_barcodes_by_type_list"]):::none --> metadata_tibble.GEX.PBMC_human_6x(["metadata_tibble.GEX"]):::none
  excluded_cellranger_only_barcodes_by_type_list.pbmc_granulocyte_sorted_10k(["excluded_cellranger_only_barcodes_by_type_list"]):::none --> metadata_tibble.GEX.PBMC_human_6x(["metadata_tibble.GEX"]):::none
  excluded_cellranger_only_barcodes_by_type_list.pbmc_unsorted_3k(["excluded_cellranger_only_barcodes_by_type_list"]):::none --> metadata_tibble.GEX.PBMC_human_6x(["metadata_tibble.GEX"]):::none
  excluded_cellranger_only_barcodes_by_type_list.pbmc_10k_chromium_x(["excluded_cellranger_only_barcodes_by_type_list"]):::none --> metadata_tibble.GEX.PBMC_human_6x(["metadata_tibble.GEX"]):::none
  excluded_cellranger_only_barcodes_by_type_list.healthy_PBMC_human(["excluded_cellranger_only_barcodes_by_type_list"]):::none --> metadata_tibble.GEX.PBMC_human_6x(["metadata_tibble.GEX"]):::none
  excluded_cellranger_only_barcodes_by_type_list.pbmc_10k_chromium_controller(["excluded_cellranger_only_barcodes_by_type_list"]):::none --> PCA_BPCells.GEX.PBMC_human_6x(["PCA_BPCells.GEX"]):::none
  excluded_cellranger_only_barcodes_by_type_list.pbmc_unsorted_10k(["excluded_cellranger_only_barcodes_by_type_list"]):::none --> PCA_BPCells.GEX.PBMC_human_6x(["PCA_BPCells.GEX"]):::none
  excluded_cellranger_only_barcodes_by_type_list.pbmc_granulocyte_sorted_10k(["excluded_cellranger_only_barcodes_by_type_list"]):::none --> PCA_BPCells.GEX.PBMC_human_6x(["PCA_BPCells.GEX"]):::none
  excluded_cellranger_only_barcodes_by_type_list.pbmc_unsorted_3k(["excluded_cellranger_only_barcodes_by_type_list"]):::none --> PCA_BPCells.GEX.PBMC_human_6x(["PCA_BPCells.GEX"]):::none
  excluded_cellranger_only_barcodes_by_type_list.pbmc_10k_chromium_x(["excluded_cellranger_only_barcodes_by_type_list"]):::none --> PCA_BPCells.GEX.PBMC_human_6x(["PCA_BPCells.GEX"]):::none
  excluded_cellranger_only_barcodes_by_type_list.healthy_PBMC_human(["excluded_cellranger_only_barcodes_by_type_list"]):::none --> PCA_BPCells.GEX.PBMC_human_6x(["PCA_BPCells.GEX"]):::none
  GEX_counts_BPcells_matrix_dir.embryonic_brain_mouse(["GEX_counts_BPcells_matrix_dir"]):::none --> aggregated_GEX_BPCells_matrix_dir.GEX.brain_mouse(["aggregated_GEX_BPCells_matrix_dir.GEX"]):::none
  GEX_counts_BPcells_matrix_dir.healthy_PBMC_human(["GEX_counts_BPcells_matrix_dir"]):::none --> aggregated_GEX_BPCells_matrix_dir.GEX.immune_human_2x(["aggregated_GEX_BPCells_matrix_dir.GEX"]):::none
  GEX_counts_BPcells_matrix_dir.healthy_PBMC_human(["GEX_counts_BPcells_matrix_dir"]):::none --> aggregated_GEX_BPCells_matrix_dir.GEX.PBMC_human_6x(["aggregated_GEX_BPCells_matrix_dir.GEX"]):::none
  GEX_counts_BPcells_matrix_dir.lymphoma_lymph_human(["GEX_counts_BPcells_matrix_dir"]):::none --> aggregated_GEX_BPCells_matrix_dir.GEX.immune_human_2x(["aggregated_GEX_BPCells_matrix_dir.GEX"]):::none
  GEX_counts_BPcells_matrix_dir.pbmc_10k_chromium_controller(["GEX_counts_BPcells_matrix_dir"]):::none --> aggregated_GEX_BPCells_matrix_dir.GEX.PBMC_human_6x(["aggregated_GEX_BPCells_matrix_dir.GEX"]):::none
  GEX_counts_BPcells_matrix_dir.pbmc_10k_chromium_x(["GEX_counts_BPcells_matrix_dir"]):::none --> aggregated_GEX_BPCells_matrix_dir.GEX.PBMC_human_6x(["aggregated_GEX_BPCells_matrix_dir.GEX"]):::none
  GEX_counts_BPcells_matrix_dir.pbmc_granulocyte_sorted_10k(["GEX_counts_BPcells_matrix_dir"]):::none --> aggregated_GEX_BPCells_matrix_dir.GEX.PBMC_human_6x(["aggregated_GEX_BPCells_matrix_dir.GEX"]):::none
  GEX_counts_BPcells_matrix_dir.pbmc_unsorted_10k(["GEX_counts_BPcells_matrix_dir"]):::none --> aggregated_GEX_BPCells_matrix_dir.GEX.PBMC_human_6x(["aggregated_GEX_BPCells_matrix_dir.GEX"]):::none
  GEX_counts_BPcells_matrix_dir.pbmc_unsorted_3k(["GEX_counts_BPcells_matrix_dir"]):::none --> aggregated_GEX_BPCells_matrix_dir.GEX.PBMC_human_6x(["aggregated_GEX_BPCells_matrix_dir.GEX"]):::none
  LSI_BPCells.ATAC.brain_mouse(["LSI_BPCells.ATAC"]):::none --> scDblFinder_results_df.ATAC.brain_mouse(["scDblFinder_results_df.ATAC"]):::none
  LSI_BPCells.ATAC.immune_human_2x(["LSI_BPCells.ATAC"]):::none --> scDblFinder_results_df.ATAC.immune_human_2x(["scDblFinder_results_df.ATAC"]):::none
  LSI_BPCells.ATAC.PBMC_human_6x(["LSI_BPCells.ATAC"]):::none --> scDblFinder_results_df.ATAC.PBMC_human_6x(["scDblFinder_results_df.ATAC"]):::none
  metadata_w_cell_types_tibble.GEX.brain_mouse(["metadata_w_cell_types_tibble.GEX"]):::none --> harmony_embeddings_matrix.ATAC.brain_mouse(["harmony_embeddings_matrix.ATAC"]):::none
  combined_BPCells_fragment_obj.ATAC.brain_mouse(["combined_BPCells_fragment_obj.ATAC"]):::none --> harmony_embeddings_matrix.ATAC.brain_mouse(["harmony_embeddings_matrix.ATAC"]):::none
  consensus_peak_GRanges.ATAC.brain_mouse(["consensus_peak_GRanges.ATAC"]):::none --> harmony_embeddings_matrix.ATAC.brain_mouse(["harmony_embeddings_matrix.ATAC"]):::none
  metadata_w_cell_types_tibble.GEX.brain_mouse(["metadata_w_cell_types_tibble.GEX"]):::none --> metadata_w_cell_types_tibble.ATAC.brain_mouse(["metadata_w_cell_types_tibble.ATAC"]):::none
  combined_BPCells_fragment_obj.ATAC.brain_mouse(["combined_BPCells_fragment_obj.ATAC"]):::none --> metadata_w_cell_types_tibble.ATAC.brain_mouse(["metadata_w_cell_types_tibble.ATAC"]):::none
  consensus_peak_GRanges.ATAC.brain_mouse(["consensus_peak_GRanges.ATAC"]):::none --> metadata_w_cell_types_tibble.ATAC.brain_mouse(["metadata_w_cell_types_tibble.ATAC"]):::none
  metadata_w_cell_types_tibble.GEX.brain_mouse(["metadata_w_cell_types_tibble.GEX"]):::none --> scDblFinder_results_df.ATAC.brain_mouse(["scDblFinder_results_df.ATAC"]):::none
  combined_BPCells_fragment_obj.ATAC.brain_mouse(["combined_BPCells_fragment_obj.ATAC"]):::none --> scDblFinder_results_df.ATAC.brain_mouse(["scDblFinder_results_df.ATAC"]):::none
  consensus_peak_GRanges.ATAC.brain_mouse(["consensus_peak_GRanges.ATAC"]):::none --> scDblFinder_results_df.ATAC.brain_mouse(["scDblFinder_results_df.ATAC"]):::none
  combined_BPCells_fragment_obj.ATAC.immune_human_2x(["combined_BPCells_fragment_obj.ATAC"]):::none --> harmony_embeddings_matrix.ATAC.immune_human_2x(["harmony_embeddings_matrix.ATAC"]):::none
  consensus_peak_GRanges.ATAC.immune_human_2x(["consensus_peak_GRanges.ATAC"]):::none --> harmony_embeddings_matrix.ATAC.immune_human_2x(["harmony_embeddings_matrix.ATAC"]):::none
  metadata_w_cell_types_tibble.GEX.immune_human_2x(["metadata_w_cell_types_tibble.GEX"]):::none --> harmony_embeddings_matrix.ATAC.immune_human_2x(["harmony_embeddings_matrix.ATAC"]):::none
  combined_BPCells_fragment_obj.ATAC.immune_human_2x(["combined_BPCells_fragment_obj.ATAC"]):::none --> metadata_w_cell_types_tibble.ATAC.immune_human_2x(["metadata_w_cell_types_tibble.ATAC"]):::none
  consensus_peak_GRanges.ATAC.immune_human_2x(["consensus_peak_GRanges.ATAC"]):::none --> metadata_w_cell_types_tibble.ATAC.immune_human_2x(["metadata_w_cell_types_tibble.ATAC"]):::none
  metadata_w_cell_types_tibble.GEX.immune_human_2x(["metadata_w_cell_types_tibble.GEX"]):::none --> metadata_w_cell_types_tibble.ATAC.immune_human_2x(["metadata_w_cell_types_tibble.ATAC"]):::none
  combined_BPCells_fragment_obj.ATAC.immune_human_2x(["combined_BPCells_fragment_obj.ATAC"]):::none --> scDblFinder_results_df.ATAC.immune_human_2x(["scDblFinder_results_df.ATAC"]):::none
  consensus_peak_GRanges.ATAC.immune_human_2x(["consensus_peak_GRanges.ATAC"]):::none --> scDblFinder_results_df.ATAC.immune_human_2x(["scDblFinder_results_df.ATAC"]):::none
  metadata_w_cell_types_tibble.GEX.immune_human_2x(["metadata_w_cell_types_tibble.GEX"]):::none --> scDblFinder_results_df.ATAC.immune_human_2x(["scDblFinder_results_df.ATAC"]):::none
  metadata_w_cell_types_tibble.GEX.PBMC_human_6x(["metadata_w_cell_types_tibble.GEX"]):::none --> harmony_embeddings_matrix.ATAC.PBMC_human_6x(["harmony_embeddings_matrix.ATAC"]):::none
  combined_BPCells_fragment_obj.ATAC.PBMC_human_6x(["combined_BPCells_fragment_obj.ATAC"]):::none --> harmony_embeddings_matrix.ATAC.PBMC_human_6x(["harmony_embeddings_matrix.ATAC"]):::none
  consensus_peak_GRanges.ATAC.PBMC_human_6x(["consensus_peak_GRanges.ATAC"]):::none --> harmony_embeddings_matrix.ATAC.PBMC_human_6x(["harmony_embeddings_matrix.ATAC"]):::none
  metadata_w_cell_types_tibble.GEX.PBMC_human_6x(["metadata_w_cell_types_tibble.GEX"]):::none --> metadata_w_cell_types_tibble.ATAC.PBMC_human_6x(["metadata_w_cell_types_tibble.ATAC"]):::none
  combined_BPCells_fragment_obj.ATAC.PBMC_human_6x(["combined_BPCells_fragment_obj.ATAC"]):::none --> metadata_w_cell_types_tibble.ATAC.PBMC_human_6x(["metadata_w_cell_types_tibble.ATAC"]):::none
  consensus_peak_GRanges.ATAC.PBMC_human_6x(["consensus_peak_GRanges.ATAC"]):::none --> metadata_w_cell_types_tibble.ATAC.PBMC_human_6x(["metadata_w_cell_types_tibble.ATAC"]):::none
  metadata_w_cell_types_tibble.GEX.PBMC_human_6x(["metadata_w_cell_types_tibble.GEX"]):::none --> scDblFinder_results_df.ATAC.PBMC_human_6x(["scDblFinder_results_df.ATAC"]):::none
  combined_BPCells_fragment_obj.ATAC.PBMC_human_6x(["combined_BPCells_fragment_obj.ATAC"]):::none --> scDblFinder_results_df.ATAC.PBMC_human_6x(["scDblFinder_results_df.ATAC"]):::none
  consensus_peak_GRanges.ATAC.PBMC_human_6x(["consensus_peak_GRanges.ATAC"]):::none --> scDblFinder_results_df.ATAC.PBMC_human_6x(["scDblFinder_results_df.ATAC"]):::none
  metadata_w_cell_types_tibble.WNN.brain_mouse(["metadata_w_cell_types_tibble.WNN"]):::none --> harmony_embeddings_matrix.ATAC.subgroups.brain_mouse["harmony_embeddings_matrix.ATAC.subgroups"]:::none
  metadata_w_cell_types_tibble.WNN.brain_mouse(["metadata_w_cell_types_tibble.WNN"]):::none --> harmony_embeddings_matrix.GEX.subgroups.brain_mouse["harmony_embeddings_matrix.GEX.subgroups"]:::none
  metadata_w_cell_types_tibble.WNN.brain_mouse(["metadata_w_cell_types_tibble.WNN"]):::none --> LSI_BPCells.ATAC.subgroups.brain_mouse["LSI_BPCells.ATAC.subgroups"]:::none
  metadata_w_cell_types_tibble.WNN.brain_mouse(["metadata_w_cell_types_tibble.WNN"]):::none --> PCA_BPCells.GEX.subgroups.brain_mouse["PCA_BPCells.GEX.subgroups"]:::none
  metadata_w_cell_types_tibble.WNN.immune_human_2x(["metadata_w_cell_types_tibble.WNN"]):::none --> harmony_embeddings_matrix.ATAC.subgroups.immune_human_2x["harmony_embeddings_matrix.ATAC.subgroups"]:::none
  metadata_w_cell_types_tibble.WNN.immune_human_2x(["metadata_w_cell_types_tibble.WNN"]):::none --> harmony_embeddings_matrix.GEX.subgroups.immune_human_2x["harmony_embeddings_matrix.GEX.subgroups"]:::none
  metadata_w_cell_types_tibble.WNN.immune_human_2x(["metadata_w_cell_types_tibble.WNN"]):::none --> LSI_BPCells.ATAC.subgroups.immune_human_2x["LSI_BPCells.ATAC.subgroups"]:::none
  metadata_w_cell_types_tibble.WNN.immune_human_2x(["metadata_w_cell_types_tibble.WNN"]):::none --> PCA_BPCells.GEX.subgroups.immune_human_2x["PCA_BPCells.GEX.subgroups"]:::none
  metadata_w_cell_types_tibble.WNN.PBMC_human_6x(["metadata_w_cell_types_tibble.WNN"]):::none --> harmony_embeddings_matrix.ATAC.subgroups.PBMC_human_6x["harmony_embeddings_matrix.ATAC.subgroups"]:::none
  metadata_w_cell_types_tibble.WNN.PBMC_human_6x(["metadata_w_cell_types_tibble.WNN"]):::none --> harmony_embeddings_matrix.GEX.subgroups.PBMC_human_6x["harmony_embeddings_matrix.GEX.subgroups"]:::none
  metadata_w_cell_types_tibble.WNN.PBMC_human_6x(["metadata_w_cell_types_tibble.WNN"]):::none --> LSI_BPCells.ATAC.subgroups.PBMC_human_6x["LSI_BPCells.ATAC.subgroups"]:::none
  metadata_w_cell_types_tibble.WNN.PBMC_human_6x(["metadata_w_cell_types_tibble.WNN"]):::none --> PCA_BPCells.GEX.subgroups.PBMC_human_6x["PCA_BPCells.GEX.subgroups"]:::none
  UCell_GEX_marker_genes_list.brain_mouse(["UCell_GEX_marker_genes_list"]):::none --> metadata_w_cell_types_tibble.ATAC.brain_mouse(["metadata_w_cell_types_tibble.ATAC"]):::none
  UMAP_embeddings_tibble.ATAC.brain_mouse(["UMAP_embeddings_tibble.ATAC"]):::none --> metadata_w_cell_types_tibble.ATAC.brain_mouse(["metadata_w_cell_types_tibble.ATAC"]):::none
  LSI_clusters.ATAC.brain_mouse(["LSI_clusters.ATAC"]):::none --> metadata_w_cell_types_tibble.ATAC.brain_mouse(["metadata_w_cell_types_tibble.ATAC"]):::none
  UCell_GEX_marker_genes_list.brain_mouse(["UCell_GEX_marker_genes_list"]):::none --> scDblFinder_results_df.ATAC.brain_mouse(["scDblFinder_results_df.ATAC"]):::none
  UMAP_embeddings_tibble.ATAC.brain_mouse(["UMAP_embeddings_tibble.ATAC"]):::none --> scDblFinder_results_df.ATAC.brain_mouse(["scDblFinder_results_df.ATAC"]):::none
  LSI_clusters.ATAC.brain_mouse(["LSI_clusters.ATAC"]):::none --> scDblFinder_results_df.ATAC.brain_mouse(["scDblFinder_results_df.ATAC"]):::none
  UCell_GEX_marker_genes_list.immune_human_2x(["UCell_GEX_marker_genes_list"]):::none --> metadata_w_cell_types_tibble.ATAC.immune_human_2x(["metadata_w_cell_types_tibble.ATAC"]):::none
  LSI_clusters.ATAC.immune_human_2x(["LSI_clusters.ATAC"]):::none --> metadata_w_cell_types_tibble.ATAC.immune_human_2x(["metadata_w_cell_types_tibble.ATAC"]):::none
  UMAP_embeddings_tibble.ATAC.immune_human_2x(["UMAP_embeddings_tibble.ATAC"]):::none --> metadata_w_cell_types_tibble.ATAC.immune_human_2x(["metadata_w_cell_types_tibble.ATAC"]):::none
  UCell_GEX_marker_genes_list.immune_human_2x(["UCell_GEX_marker_genes_list"]):::none --> scDblFinder_results_df.ATAC.immune_human_2x(["scDblFinder_results_df.ATAC"]):::none
  LSI_clusters.ATAC.immune_human_2x(["LSI_clusters.ATAC"]):::none --> scDblFinder_results_df.ATAC.immune_human_2x(["scDblFinder_results_df.ATAC"]):::none
  UMAP_embeddings_tibble.ATAC.immune_human_2x(["UMAP_embeddings_tibble.ATAC"]):::none --> scDblFinder_results_df.ATAC.immune_human_2x(["scDblFinder_results_df.ATAC"]):::none
  UCell_GEX_marker_genes_list.PBMC_human_6x(["UCell_GEX_marker_genes_list"]):::none --> metadata_w_cell_types_tibble.ATAC.PBMC_human_6x(["metadata_w_cell_types_tibble.ATAC"]):::none
  LSI_clusters.ATAC.PBMC_human_6x(["LSI_clusters.ATAC"]):::none --> metadata_w_cell_types_tibble.ATAC.PBMC_human_6x(["metadata_w_cell_types_tibble.ATAC"]):::none
  UMAP_embeddings_tibble.ATAC.PBMC_human_6x(["UMAP_embeddings_tibble.ATAC"]):::none --> metadata_w_cell_types_tibble.ATAC.PBMC_human_6x(["metadata_w_cell_types_tibble.ATAC"]):::none
  UCell_GEX_marker_genes_list.PBMC_human_6x(["UCell_GEX_marker_genes_list"]):::none --> scDblFinder_results_df.ATAC.PBMC_human_6x(["scDblFinder_results_df.ATAC"]):::none
  LSI_clusters.ATAC.PBMC_human_6x(["LSI_clusters.ATAC"]):::none --> scDblFinder_results_df.ATAC.PBMC_human_6x(["scDblFinder_results_df.ATAC"]):::none
  UMAP_embeddings_tibble.ATAC.PBMC_human_6x(["UMAP_embeddings_tibble.ATAC"]):::none --> scDblFinder_results_df.ATAC.PBMC_human_6x(["scDblFinder_results_df.ATAC"]):::none
  UCell_GEX_marker_genes_list.brain_mouse(["UCell_GEX_marker_genes_list"]):::none --> metadata_w_cell_types_tibble.GEX.brain_mouse(["metadata_w_cell_types_tibble.GEX"]):::none
  metadata_tibble.GEX.brain_mouse(["metadata_tibble.GEX"]):::none --> metadata_w_cell_types_tibble.GEX.brain_mouse(["metadata_w_cell_types_tibble.GEX"]):::none
  UMAP_embeddings_tibble.GEX_non_harmony.brain_mouse(["UMAP_embeddings_tibble.GEX_non_harmony"]):::none --> metadata_w_cell_types_tibble.GEX.brain_mouse(["metadata_w_cell_types_tibble.GEX"]):::none
  UMAP_embeddings_tibble.GEX.brain_mouse(["UMAP_embeddings_tibble.GEX"]):::none --> metadata_w_cell_types_tibble.GEX.brain_mouse(["metadata_w_cell_types_tibble.GEX"]):::none
  PCA_clusters.GEX.brain_mouse(["PCA_clusters.GEX"]):::none --> metadata_w_cell_types_tibble.GEX.brain_mouse(["metadata_w_cell_types_tibble.GEX"]):::none
  UCell_GEX_marker_genes_list.brain_mouse(["UCell_GEX_marker_genes_list"]):::none --> scDblFinder_results_df.GEX.brain_mouse(["scDblFinder_results_df.GEX"]):::none
  metadata_tibble.GEX.brain_mouse(["metadata_tibble.GEX"]):::none --> scDblFinder_results_df.GEX.brain_mouse(["scDblFinder_results_df.GEX"]):::none
  UMAP_embeddings_tibble.GEX_non_harmony.brain_mouse(["UMAP_embeddings_tibble.GEX_non_harmony"]):::none --> scDblFinder_results_df.GEX.brain_mouse(["scDblFinder_results_df.GEX"]):::none
  UMAP_embeddings_tibble.GEX.brain_mouse(["UMAP_embeddings_tibble.GEX"]):::none --> scDblFinder_results_df.GEX.brain_mouse(["scDblFinder_results_df.GEX"]):::none
  PCA_clusters.GEX.brain_mouse(["PCA_clusters.GEX"]):::none --> scDblFinder_results_df.GEX.brain_mouse(["scDblFinder_results_df.GEX"]):::none
  UCell_GEX_marker_genes_list.immune_human_2x(["UCell_GEX_marker_genes_list"]):::none --> metadata_w_cell_types_tibble.GEX.immune_human_2x(["metadata_w_cell_types_tibble.GEX"]):::none
  UMAP_embeddings_tibble.GEX.immune_human_2x(["UMAP_embeddings_tibble.GEX"]):::none --> metadata_w_cell_types_tibble.GEX.immune_human_2x(["metadata_w_cell_types_tibble.GEX"]):::none
  PCA_clusters.GEX.immune_human_2x(["PCA_clusters.GEX"]):::none --> metadata_w_cell_types_tibble.GEX.immune_human_2x(["metadata_w_cell_types_tibble.GEX"]):::none
  UMAP_embeddings_tibble.GEX_non_harmony.immune_human_2x(["UMAP_embeddings_tibble.GEX_non_harmony"]):::none --> metadata_w_cell_types_tibble.GEX.immune_human_2x(["metadata_w_cell_types_tibble.GEX"]):::none
  metadata_tibble.GEX.immune_human_2x(["metadata_tibble.GEX"]):::none --> metadata_w_cell_types_tibble.GEX.immune_human_2x(["metadata_w_cell_types_tibble.GEX"]):::none
  UCell_GEX_marker_genes_list.immune_human_2x(["UCell_GEX_marker_genes_list"]):::none --> scDblFinder_results_df.GEX.immune_human_2x(["scDblFinder_results_df.GEX"]):::none
  UMAP_embeddings_tibble.GEX.immune_human_2x(["UMAP_embeddings_tibble.GEX"]):::none --> scDblFinder_results_df.GEX.immune_human_2x(["scDblFinder_results_df.GEX"]):::none
  PCA_clusters.GEX.immune_human_2x(["PCA_clusters.GEX"]):::none --> scDblFinder_results_df.GEX.immune_human_2x(["scDblFinder_results_df.GEX"]):::none
  UMAP_embeddings_tibble.GEX_non_harmony.immune_human_2x(["UMAP_embeddings_tibble.GEX_non_harmony"]):::none --> scDblFinder_results_df.GEX.immune_human_2x(["scDblFinder_results_df.GEX"]):::none
  metadata_tibble.GEX.immune_human_2x(["metadata_tibble.GEX"]):::none --> scDblFinder_results_df.GEX.immune_human_2x(["scDblFinder_results_df.GEX"]):::none
  UCell_GEX_marker_genes_list.PBMC_human_6x(["UCell_GEX_marker_genes_list"]):::none --> metadata_w_cell_types_tibble.GEX.PBMC_human_6x(["metadata_w_cell_types_tibble.GEX"]):::none
  PCA_clusters.GEX.PBMC_human_6x(["PCA_clusters.GEX"]):::none --> metadata_w_cell_types_tibble.GEX.PBMC_human_6x(["metadata_w_cell_types_tibble.GEX"]):::none
  metadata_tibble.GEX.PBMC_human_6x(["metadata_tibble.GEX"]):::none --> metadata_w_cell_types_tibble.GEX.PBMC_human_6x(["metadata_w_cell_types_tibble.GEX"]):::none
  UMAP_embeddings_tibble.GEX_non_harmony.PBMC_human_6x(["UMAP_embeddings_tibble.GEX_non_harmony"]):::none --> metadata_w_cell_types_tibble.GEX.PBMC_human_6x(["metadata_w_cell_types_tibble.GEX"]):::none
  UMAP_embeddings_tibble.GEX.PBMC_human_6x(["UMAP_embeddings_tibble.GEX"]):::none --> metadata_w_cell_types_tibble.GEX.PBMC_human_6x(["metadata_w_cell_types_tibble.GEX"]):::none
  UCell_GEX_marker_genes_list.PBMC_human_6x(["UCell_GEX_marker_genes_list"]):::none --> scDblFinder_results_df.GEX.PBMC_human_6x(["scDblFinder_results_df.GEX"]):::none
  PCA_clusters.GEX.PBMC_human_6x(["PCA_clusters.GEX"]):::none --> scDblFinder_results_df.GEX.PBMC_human_6x(["scDblFinder_results_df.GEX"]):::none
  metadata_tibble.GEX.PBMC_human_6x(["metadata_tibble.GEX"]):::none --> scDblFinder_results_df.GEX.PBMC_human_6x(["scDblFinder_results_df.GEX"]):::none
  UMAP_embeddings_tibble.GEX_non_harmony.PBMC_human_6x(["UMAP_embeddings_tibble.GEX_non_harmony"]):::none --> scDblFinder_results_df.GEX.PBMC_human_6x(["scDblFinder_results_df.GEX"]):::none
  UMAP_embeddings_tibble.GEX.PBMC_human_6x(["UMAP_embeddings_tibble.GEX"]):::none --> scDblFinder_results_df.GEX.PBMC_human_6x(["scDblFinder_results_df.GEX"]):::none
  WNN_results.brain_mouse(["WNN_results"]):::none --> metadata_w_cell_types_tibble.WNN.brain_mouse(["metadata_w_cell_types_tibble.WNN"]):::none
  clusters_tibble.WNN.brain_mouse(["clusters_tibble.WNN"]):::none --> metadata_w_cell_types_tibble.WNN.brain_mouse(["metadata_w_cell_types_tibble.WNN"]):::none
  UMAP_embeddings_tibble.GEX.brain_mouse(["UMAP_embeddings_tibble.GEX"]):::none --> metadata_w_cell_types_tibble.WNN.brain_mouse(["metadata_w_cell_types_tibble.WNN"]):::none
  metadata_w_cell_types_tibble.ATAC.brain_mouse(["metadata_w_cell_types_tibble.ATAC"]):::none --> metadata_w_cell_types_tibble.WNN.brain_mouse(["metadata_w_cell_types_tibble.WNN"]):::none
  UMAP_embeddings_tibble.WNN.brain_mouse(["UMAP_embeddings_tibble.WNN"]):::none --> metadata_w_cell_types_tibble.WNN.brain_mouse(["metadata_w_cell_types_tibble.WNN"]):::none
  UMAP_embeddings_tibble.WNN.immune_human_2x(["UMAP_embeddings_tibble.WNN"]):::none --> metadata_w_cell_types_tibble.WNN.immune_human_2x(["metadata_w_cell_types_tibble.WNN"]):::none
  WNN_results.immune_human_2x(["WNN_results"]):::none --> metadata_w_cell_types_tibble.WNN.immune_human_2x(["metadata_w_cell_types_tibble.WNN"]):::none
  clusters_tibble.WNN.immune_human_2x(["clusters_tibble.WNN"]):::none --> metadata_w_cell_types_tibble.WNN.immune_human_2x(["metadata_w_cell_types_tibble.WNN"]):::none
  UMAP_embeddings_tibble.GEX.immune_human_2x(["UMAP_embeddings_tibble.GEX"]):::none --> metadata_w_cell_types_tibble.WNN.immune_human_2x(["metadata_w_cell_types_tibble.WNN"]):::none
  metadata_w_cell_types_tibble.ATAC.immune_human_2x(["metadata_w_cell_types_tibble.ATAC"]):::none --> metadata_w_cell_types_tibble.WNN.immune_human_2x(["metadata_w_cell_types_tibble.WNN"]):::none
  WNN_results.PBMC_human_6x(["WNN_results"]):::none --> metadata_w_cell_types_tibble.WNN.PBMC_human_6x(["metadata_w_cell_types_tibble.WNN"]):::none
  clusters_tibble.WNN.PBMC_human_6x(["clusters_tibble.WNN"]):::none --> metadata_w_cell_types_tibble.WNN.PBMC_human_6x(["metadata_w_cell_types_tibble.WNN"]):::none
  metadata_w_cell_types_tibble.ATAC.PBMC_human_6x(["metadata_w_cell_types_tibble.ATAC"]):::none --> metadata_w_cell_types_tibble.WNN.PBMC_human_6x(["metadata_w_cell_types_tibble.WNN"]):::none
  UMAP_embeddings_tibble.WNN.PBMC_human_6x(["UMAP_embeddings_tibble.WNN"]):::none --> metadata_w_cell_types_tibble.WNN.PBMC_human_6x(["metadata_w_cell_types_tibble.WNN"]):::none
  UMAP_embeddings_tibble.GEX.PBMC_human_6x(["UMAP_embeddings_tibble.GEX"]):::none --> metadata_w_cell_types_tibble.WNN.PBMC_human_6x(["metadata_w_cell_types_tibble.WNN"]):::none
  metadata_w_cell_types_tibble.GEX.brain_mouse(["metadata_w_cell_types_tibble.GEX"]):::none --> LSI_BPCells.ATAC.brain_mouse(["LSI_BPCells.ATAC"]):::none
  combined_BPCells_fragment_obj.ATAC.brain_mouse(["combined_BPCells_fragment_obj.ATAC"]):::none --> LSI_BPCells.ATAC.brain_mouse(["LSI_BPCells.ATAC"]):::none
  consensus_peak_GRanges.ATAC.brain_mouse(["consensus_peak_GRanges.ATAC"]):::none --> LSI_BPCells.ATAC.brain_mouse(["LSI_BPCells.ATAC"]):::none
  metadata_w_cell_types_tibble.GEX.brain_mouse(["metadata_w_cell_types_tibble.GEX"]):::none --> LSI_BPCells.ATAC.subgroups.brain_mouse["LSI_BPCells.ATAC.subgroups"]:::none
  combined_BPCells_fragment_obj.ATAC.brain_mouse(["combined_BPCells_fragment_obj.ATAC"]):::none --> LSI_BPCells.ATAC.subgroups.brain_mouse["LSI_BPCells.ATAC.subgroups"]:::none
  consensus_peak_GRanges.ATAC.brain_mouse(["consensus_peak_GRanges.ATAC"]):::none --> LSI_BPCells.ATAC.subgroups.brain_mouse["LSI_BPCells.ATAC.subgroups"]:::none
  combined_BPCells_fragment_obj.ATAC.immune_human_2x(["combined_BPCells_fragment_obj.ATAC"]):::none --> LSI_BPCells.ATAC.immune_human_2x(["LSI_BPCells.ATAC"]):::none
  consensus_peak_GRanges.ATAC.immune_human_2x(["consensus_peak_GRanges.ATAC"]):::none --> LSI_BPCells.ATAC.immune_human_2x(["LSI_BPCells.ATAC"]):::none
  metadata_w_cell_types_tibble.GEX.immune_human_2x(["metadata_w_cell_types_tibble.GEX"]):::none --> LSI_BPCells.ATAC.immune_human_2x(["LSI_BPCells.ATAC"]):::none
  combined_BPCells_fragment_obj.ATAC.immune_human_2x(["combined_BPCells_fragment_obj.ATAC"]):::none --> LSI_BPCells.ATAC.subgroups.immune_human_2x["LSI_BPCells.ATAC.subgroups"]:::none
  consensus_peak_GRanges.ATAC.immune_human_2x(["consensus_peak_GRanges.ATAC"]):::none --> LSI_BPCells.ATAC.subgroups.immune_human_2x["LSI_BPCells.ATAC.subgroups"]:::none
  metadata_w_cell_types_tibble.GEX.immune_human_2x(["metadata_w_cell_types_tibble.GEX"]):::none --> LSI_BPCells.ATAC.subgroups.immune_human_2x["LSI_BPCells.ATAC.subgroups"]:::none
  metadata_w_cell_types_tibble.GEX.PBMC_human_6x(["metadata_w_cell_types_tibble.GEX"]):::none --> LSI_BPCells.ATAC.PBMC_human_6x(["LSI_BPCells.ATAC"]):::none
  combined_BPCells_fragment_obj.ATAC.PBMC_human_6x(["combined_BPCells_fragment_obj.ATAC"]):::none --> LSI_BPCells.ATAC.PBMC_human_6x(["LSI_BPCells.ATAC"]):::none
  consensus_peak_GRanges.ATAC.PBMC_human_6x(["consensus_peak_GRanges.ATAC"]):::none --> LSI_BPCells.ATAC.PBMC_human_6x(["LSI_BPCells.ATAC"]):::none
  metadata_w_cell_types_tibble.GEX.PBMC_human_6x(["metadata_w_cell_types_tibble.GEX"]):::none --> LSI_BPCells.ATAC.subgroups.PBMC_human_6x["LSI_BPCells.ATAC.subgroups"]:::none
  combined_BPCells_fragment_obj.ATAC.PBMC_human_6x(["combined_BPCells_fragment_obj.ATAC"]):::none --> LSI_BPCells.ATAC.subgroups.PBMC_human_6x["LSI_BPCells.ATAC.subgroups"]:::none
  consensus_peak_GRanges.ATAC.PBMC_human_6x(["consensus_peak_GRanges.ATAC"]):::none --> LSI_BPCells.ATAC.subgroups.PBMC_human_6x["LSI_BPCells.ATAC.subgroups"]:::none
  ATAC_marker_TFs_list.brain_mouse(["ATAC_marker_TFs_list"]):::none --> TF_activity_BPCells_matrix_dir.ATAC.brain_mouse(["TF_activity_BPCells_matrix_dir.ATAC"]):::none
  ATAC_marker_TFs_list.immune_human_2x(["ATAC_marker_TFs_list"]):::none --> TF_activity_BPCells_matrix_dir.ATAC.immune_human_2x(["TF_activity_BPCells_matrix_dir.ATAC"]):::none
  ATAC_marker_TFs_list.PBMC_human_6x(["ATAC_marker_TFs_list"]):::none --> TF_activity_BPCells_matrix_dir.ATAC.PBMC_human_6x(["TF_activity_BPCells_matrix_dir.ATAC"]):::none
  metadata_w_cell_types_tibble.GEX.brain_mouse(["metadata_w_cell_types_tibble.GEX"]):::none --> within_clusters_collapsed_peaks_per_cluster_GRanges.ATAC.brain_mouse["within_clusters_collapsed_peaks_per_cluster_GRanges.ATAC"]:::none
  metadata_w_cell_types_tibble.GEX.immune_human_2x(["metadata_w_cell_types_tibble.GEX"]):::none --> within_clusters_collapsed_peaks_per_cluster_GRanges.ATAC.immune_human_2x["within_clusters_collapsed_peaks_per_cluster_GRanges.ATAC"]:::none
  metadata_w_cell_types_tibble.GEX.PBMC_human_6x(["metadata_w_cell_types_tibble.GEX"]):::none --> within_clusters_collapsed_peaks_per_cluster_GRanges.ATAC.PBMC_human_6x["within_clusters_collapsed_peaks_per_cluster_GRanges.ATAC"]:::none
  peaks_per_cluster_narrowPeaks.peaks.ATAC.brain_mouse["peaks_per_cluster_narrowPeaks.peaks.ATAC"]:::none --> within_clusters_collapsed_peaks_per_cluster_GRanges.ATAC.brain_mouse["within_clusters_collapsed_peaks_per_cluster_GRanges.ATAC"]:::none
  peaks_per_cluster_narrowPeaks.peaks.ATAC.immune_human_2x["peaks_per_cluster_narrowPeaks.peaks.ATAC"]:::none --> within_clusters_collapsed_peaks_per_cluster_GRanges.ATAC.immune_human_2x["within_clusters_collapsed_peaks_per_cluster_GRanges.ATAC"]:::none
  peaks_per_cluster_narrowPeaks.peaks.ATAC.PBMC_human_6x["peaks_per_cluster_narrowPeaks.peaks.ATAC"]:::none --> within_clusters_collapsed_peaks_per_cluster_GRanges.ATAC.PBMC_human_6x["within_clusters_collapsed_peaks_per_cluster_GRanges.ATAC"]:::none
  donor_id_metadata_tibble.extended.differential_analyses.immune_human_2x(["donor_id_metadata_tibble.extended"]):::none
