%%{init: {'flowchart': {'defaultRenderer': 'elk'}}}%%
flowchart TB
  cellranger_barcodes_tsv.muscle_A1(["cellranger_barcodes_tsv.&lt;GEM_well_ID&gt;"]):::none --> amulet_metrics_tibble.muscle_A1(["amulet_metrics_tibble.&lt;GEM_well_ID&gt;"]):::none
  cellranger_barcodes_tsv.muscle_A1(["cellranger_barcodes_tsv.&lt;GEM_well_ID&gt;"]):::none --> cellsnp_dir.muscle_A1(["cellsnp_dir.&lt;GEM_well_ID&gt;"]):::none
  full_metadata_tibble.muscle_A1(["full_metadata_tibble.&lt;GEM_well_ID&gt;"]):::none --> excluded_cellranger_only_barcodes_by_type_list.muscle_A1(["excluded_cellranger_only_barcodes_by_type_list.&lt;GEM_well_ID&gt;"]):::none
  ATAC_qc_metrics_tibble.muscle_A1(["ATAC_qc_metrics_tibble.&lt;GEM_well_ID&gt;"]):::none --> full_metadata_tibble.muscle_A1(["full_metadata_tibble.&lt;GEM_well_ID&gt;"]):::none
  amulet_metrics_tibble.muscle_A1(["amulet_metrics_tibble.&lt;GEM_well_ID&gt;"]):::none --> full_metadata_tibble.muscle_A1(["full_metadata_tibble.&lt;GEM_well_ID&gt;"]):::none
  vireo_donor_ids_tibble.muscle_A1(["vireo_donor_ids_tibble.&lt;GEM_well_ID&gt;"]):::none --> full_metadata_tibble.muscle_A1(["full_metadata_tibble.&lt;GEM_well_ID&gt;"]):::none
  donor_id_metadata_tibble.muscle(["donor_id_metadata_tibble.&lt;dataset_name&gt;"]):::none --> GEM_well_metadata_tibble.muscle(["GEM_well_metadata_tibble.&lt;dataset_name&gt;"]):::none
  donor_id_metadata_tibble.muscle_test(["donor_id_metadata_tibble.&lt;aggregation_name&gt;"]):::none --> GEM_well_metadata_tibble.muscle_test(["GEM_well_metadata_tibble.&lt;aggregation_name&gt;"]):::none
  cellbender_h5_file.muscle_A1(["cellbender_h5_file.&lt;GEM_well_ID&gt;"]):::none --> GEX_counts_BPcells_matrix_dir.muscle_A1(["GEX_counts_BPcells_matrix_dir.&lt;GEM_well_ID&gt;"]):::none
  cellranger_barcodes_tsv.muscle_A1(["cellranger_barcodes_tsv.&lt;GEM_well_ID&gt;"]):::none --> vireo_donor_ids_tibble.muscle_A1(["vireo_donor_ids_tibble.&lt;GEM_well_ID&gt;"]):::none
  cellsnp_dir.muscle_A1(["cellsnp_dir.&lt;GEM_well_ID&gt;"]):::none --> vireo_donor_ids_tibble.muscle_A1(["vireo_donor_ids_tibble.&lt;GEM_well_ID&gt;"]):::none
  fragments_w_prefix_bpcells_dir.muscle_A1(["fragments_w_prefix_bpcells_dir.&lt;GEM_well_ID&gt;"]):::none --> amulet_metrics_tibble.muscle_A1(["amulet_metrics_tibble.&lt;GEM_well_ID&gt;"]):::none
  fragments_w_prefix_bpcells_dir.muscle_A1(["fragments_w_prefix_bpcells_dir.&lt;GEM_well_ID&gt;"]):::none --> ATAC_qc_metrics_tibble.muscle_A1(["ATAC_qc_metrics_tibble.&lt;GEM_well_ID&gt;"]):::none
  fragments_w_prefix_bpcells_dir.muscle_A1(["fragments_w_prefix_bpcells_dir.&lt;GEM_well_ID&gt;"]):::none --> combined_BPCells_fragment_obj.ATAC.muscle(["combined_BPCells_fragment_obj.ATAC.&lt;dataset_name&gt;"]):::none
  fragments_w_prefix_bpcells_dir.muscle_A1(["fragments_w_prefix_bpcells_dir.&lt;GEM_well_ID&gt;"]):::none --> combined_BPCells_fragment_obj.ATAC.muscle_test(["combined_BPCells_fragment_obj.ATAC.&lt;aggregation_name&gt;"]):::none
  GEX_counts_BPcells_matrix_dir.muscle_A1(["GEX_counts_BPcells_matrix_dir.&lt;GEM_well_ID&gt;"]):::none --> full_metadata_tibble.muscle_A1(["full_metadata_tibble.&lt;GEM_well_ID&gt;"]):::none
  GEX_counts_BPcells_matrix_dir.muscle_A1(["GEX_counts_BPcells_matrix_dir.&lt;GEM_well_ID&gt;"]):::none --> aggregated_GEX_BPCells_matrix_dir.GEX.muscle(["aggregated_GEX_BPCells_matrix_dir.GEX.&lt;dataset_name&gt;"]):::none
  GEX_counts_BPcells_matrix_dir.muscle_A1(["GEX_counts_BPcells_matrix_dir.&lt;GEM_well_ID&gt;"]):::none --> aggregated_GEX_BPCells_matrix_dir.GEX.muscle_test(["aggregated_GEX_BPCells_matrix_dir.GEX.&lt;aggregation_name&gt;"]):::none
