%%{init: {'flowchart': {'defaultRenderer': 'elk'}}}%%
flowchart TB
  cellranger_barcodes_tsv.embryonic_brain_mouse(["cellranger_barcodes_tsv"]):::none --> amulet_metrics_tibble.embryonic_brain_mouse(["amulet_metrics_tibble"]):::none
  cellranger_barcodes_tsv.healthy_PBMC_human(["cellranger_barcodes_tsv"]):::none --> amulet_metrics_tibble.healthy_PBMC_human(["amulet_metrics_tibble"]):::none
  cellranger_barcodes_tsv.lymphoma_lymph_human(["cellranger_barcodes_tsv"]):::none --> amulet_metrics_tibble.lymphoma_lymph_human(["amulet_metrics_tibble"]):::none
  cellranger_barcodes_tsv.pbmc_10k_chromium_controller(["cellranger_barcodes_tsv"]):::none --> amulet_metrics_tibble.pbmc_10k_chromium_controller(["amulet_metrics_tibble"]):::none
  cellranger_barcodes_tsv.pbmc_10k_chromium_x(["cellranger_barcodes_tsv"]):::none --> amulet_metrics_tibble.pbmc_10k_chromium_x(["amulet_metrics_tibble"]):::none
  cellranger_barcodes_tsv.pbmc_granulocyte_sorted_10k(["cellranger_barcodes_tsv"]):::none --> amulet_metrics_tibble.pbmc_granulocyte_sorted_10k(["amulet_metrics_tibble"]):::none
  cellranger_barcodes_tsv.pbmc_unsorted_10k(["cellranger_barcodes_tsv"]):::none --> amulet_metrics_tibble.pbmc_unsorted_10k(["amulet_metrics_tibble"]):::none
  cellranger_barcodes_tsv.pbmc_unsorted_3k(["cellranger_barcodes_tsv"]):::none --> amulet_metrics_tibble.pbmc_unsorted_3k(["amulet_metrics_tibble"]):::none
  cellranger_barcodes_tsv.embryonic_brain_mouse(["cellranger_barcodes_tsv"]):::none --> cellsnp_dir.embryonic_brain_mouse(["cellsnp_dir"]):::none
  cellranger_barcodes_tsv.healthy_PBMC_human(["cellranger_barcodes_tsv"]):::none --> cellsnp_dir.healthy_PBMC_human(["cellsnp_dir"]):::none
  cellranger_barcodes_tsv.lymphoma_lymph_human(["cellranger_barcodes_tsv"]):::none --> cellsnp_dir.lymphoma_lymph_human(["cellsnp_dir"]):::none
  cellranger_barcodes_tsv.pbmc_10k_chromium_controller(["cellranger_barcodes_tsv"]):::none --> cellsnp_dir.pbmc_10k_chromium_controller(["cellsnp_dir"]):::none
  cellranger_barcodes_tsv.pbmc_10k_chromium_x(["cellranger_barcodes_tsv"]):::none --> cellsnp_dir.pbmc_10k_chromium_x(["cellsnp_dir"]):::none
  cellranger_barcodes_tsv.pbmc_granulocyte_sorted_10k(["cellranger_barcodes_tsv"]):::none --> cellsnp_dir.pbmc_granulocyte_sorted_10k(["cellsnp_dir"]):::none
  cellranger_barcodes_tsv.pbmc_unsorted_10k(["cellranger_barcodes_tsv"]):::none --> cellsnp_dir.pbmc_unsorted_10k(["cellsnp_dir"]):::none
  cellranger_barcodes_tsv.pbmc_unsorted_3k(["cellranger_barcodes_tsv"]):::none --> cellsnp_dir.pbmc_unsorted_3k(["cellsnp_dir"]):::none
  full_metadata_tibble.embryonic_brain_mouse(["full_metadata_tibble"]):::none --> excluded_cellranger_only_barcodes_by_type_list.embryonic_brain_mouse(["excluded_cellranger_only_barcodes_by_type_list"]):::none
  full_metadata_tibble.healthy_PBMC_human(["full_metadata_tibble"]):::none --> excluded_cellranger_only_barcodes_by_type_list.healthy_PBMC_human(["excluded_cellranger_only_barcodes_by_type_list"]):::none
  full_metadata_tibble.lymphoma_lymph_human(["full_metadata_tibble"]):::none --> excluded_cellranger_only_barcodes_by_type_list.lymphoma_lymph_human(["excluded_cellranger_only_barcodes_by_type_list"]):::none
  full_metadata_tibble.pbmc_10k_chromium_controller(["full_metadata_tibble"]):::none --> excluded_cellranger_only_barcodes_by_type_list.pbmc_10k_chromium_controller(["excluded_cellranger_only_barcodes_by_type_list"]):::none
  full_metadata_tibble.pbmc_10k_chromium_x(["full_metadata_tibble"]):::none --> excluded_cellranger_only_barcodes_by_type_list.pbmc_10k_chromium_x(["excluded_cellranger_only_barcodes_by_type_list"]):::none
  full_metadata_tibble.pbmc_granulocyte_sorted_10k(["full_metadata_tibble"]):::none --> excluded_cellranger_only_barcodes_by_type_list.pbmc_granulocyte_sorted_10k(["excluded_cellranger_only_barcodes_by_type_list"]):::none
  full_metadata_tibble.pbmc_unsorted_10k(["full_metadata_tibble"]):::none --> excluded_cellranger_only_barcodes_by_type_list.pbmc_unsorted_10k(["excluded_cellranger_only_barcodes_by_type_list"]):::none
  full_metadata_tibble.pbmc_unsorted_3k(["full_metadata_tibble"]):::none --> excluded_cellranger_only_barcodes_by_type_list.pbmc_unsorted_3k(["excluded_cellranger_only_barcodes_by_type_list"]):::none
  amulet_metrics_tibble.embryonic_brain_mouse(["amulet_metrics_tibble"]):::none --> full_metadata_tibble.embryonic_brain_mouse(["full_metadata_tibble"]):::none
  vireo_donor_ids_tibble.embryonic_brain_mouse(["vireo_donor_ids_tibble"]):::none --> full_metadata_tibble.embryonic_brain_mouse(["full_metadata_tibble"]):::none
  ATAC_qc_metrics_tibble.embryonic_brain_mouse(["ATAC_qc_metrics_tibble"]):::none --> full_metadata_tibble.embryonic_brain_mouse(["full_metadata_tibble"]):::none
  vireo_donor_ids_tibble.healthy_PBMC_human(["vireo_donor_ids_tibble"]):::none --> full_metadata_tibble.healthy_PBMC_human(["full_metadata_tibble"]):::none
  ATAC_qc_metrics_tibble.healthy_PBMC_human(["ATAC_qc_metrics_tibble"]):::none --> full_metadata_tibble.healthy_PBMC_human(["full_metadata_tibble"]):::none
  amulet_metrics_tibble.healthy_PBMC_human(["amulet_metrics_tibble"]):::none --> full_metadata_tibble.healthy_PBMC_human(["full_metadata_tibble"]):::none
  vireo_donor_ids_tibble.lymphoma_lymph_human(["vireo_donor_ids_tibble"]):::none --> full_metadata_tibble.lymphoma_lymph_human(["full_metadata_tibble"]):::none
  ATAC_qc_metrics_tibble.lymphoma_lymph_human(["ATAC_qc_metrics_tibble"]):::none --> full_metadata_tibble.lymphoma_lymph_human(["full_metadata_tibble"]):::none
  amulet_metrics_tibble.lymphoma_lymph_human(["amulet_metrics_tibble"]):::none --> full_metadata_tibble.lymphoma_lymph_human(["full_metadata_tibble"]):::none
  ATAC_qc_metrics_tibble.pbmc_10k_chromium_controller(["ATAC_qc_metrics_tibble"]):::none --> full_metadata_tibble.pbmc_10k_chromium_controller(["full_metadata_tibble"]):::none
  vireo_donor_ids_tibble.pbmc_10k_chromium_controller(["vireo_donor_ids_tibble"]):::none --> full_metadata_tibble.pbmc_10k_chromium_controller(["full_metadata_tibble"]):::none
  amulet_metrics_tibble.pbmc_10k_chromium_controller(["amulet_metrics_tibble"]):::none --> full_metadata_tibble.pbmc_10k_chromium_controller(["full_metadata_tibble"]):::none
  vireo_donor_ids_tibble.pbmc_10k_chromium_x(["vireo_donor_ids_tibble"]):::none --> full_metadata_tibble.pbmc_10k_chromium_x(["full_metadata_tibble"]):::none
  ATAC_qc_metrics_tibble.pbmc_10k_chromium_x(["ATAC_qc_metrics_tibble"]):::none --> full_metadata_tibble.pbmc_10k_chromium_x(["full_metadata_tibble"]):::none
  amulet_metrics_tibble.pbmc_10k_chromium_x(["amulet_metrics_tibble"]):::none --> full_metadata_tibble.pbmc_10k_chromium_x(["full_metadata_tibble"]):::none
  ATAC_qc_metrics_tibble.pbmc_granulocyte_sorted_10k(["ATAC_qc_metrics_tibble"]):::none --> full_metadata_tibble.pbmc_granulocyte_sorted_10k(["full_metadata_tibble"]):::none
  amulet_metrics_tibble.pbmc_granulocyte_sorted_10k(["amulet_metrics_tibble"]):::none --> full_metadata_tibble.pbmc_granulocyte_sorted_10k(["full_metadata_tibble"]):::none
  vireo_donor_ids_tibble.pbmc_granulocyte_sorted_10k(["vireo_donor_ids_tibble"]):::none --> full_metadata_tibble.pbmc_granulocyte_sorted_10k(["full_metadata_tibble"]):::none
  vireo_donor_ids_tibble.pbmc_unsorted_10k(["vireo_donor_ids_tibble"]):::none --> full_metadata_tibble.pbmc_unsorted_10k(["full_metadata_tibble"]):::none
  ATAC_qc_metrics_tibble.pbmc_unsorted_10k(["ATAC_qc_metrics_tibble"]):::none --> full_metadata_tibble.pbmc_unsorted_10k(["full_metadata_tibble"]):::none
  amulet_metrics_tibble.pbmc_unsorted_10k(["amulet_metrics_tibble"]):::none --> full_metadata_tibble.pbmc_unsorted_10k(["full_metadata_tibble"]):::none
  ATAC_qc_metrics_tibble.pbmc_unsorted_3k(["ATAC_qc_metrics_tibble"]):::none --> full_metadata_tibble.pbmc_unsorted_3k(["full_metadata_tibble"]):::none
  vireo_donor_ids_tibble.pbmc_unsorted_3k(["vireo_donor_ids_tibble"]):::none --> full_metadata_tibble.pbmc_unsorted_3k(["full_metadata_tibble"]):::none
  amulet_metrics_tibble.pbmc_unsorted_3k(["amulet_metrics_tibble"]):::none --> full_metadata_tibble.pbmc_unsorted_3k(["full_metadata_tibble"]):::none
  cellbender_h5_file.embryonic_brain_mouse(["cellbender_h5_file"]):::none --> GEX_counts_BPcells_matrix_dir.embryonic_brain_mouse(["GEX_counts_BPcells_matrix_dir"]):::none
  cellbender_h5_file.healthy_PBMC_human(["cellbender_h5_file"]):::none --> GEX_counts_BPcells_matrix_dir.healthy_PBMC_human(["GEX_counts_BPcells_matrix_dir"]):::none
  cellbender_h5_file.lymphoma_lymph_human(["cellbender_h5_file"]):::none --> GEX_counts_BPcells_matrix_dir.lymphoma_lymph_human(["GEX_counts_BPcells_matrix_dir"]):::none
  cellbender_h5_file.pbmc_10k_chromium_controller(["cellbender_h5_file"]):::none --> GEX_counts_BPcells_matrix_dir.pbmc_10k_chromium_controller(["GEX_counts_BPcells_matrix_dir"]):::none
  cellbender_h5_file.pbmc_10k_chromium_x(["cellbender_h5_file"]):::none --> GEX_counts_BPcells_matrix_dir.pbmc_10k_chromium_x(["GEX_counts_BPcells_matrix_dir"]):::none
  cellbender_h5_file.pbmc_granulocyte_sorted_10k(["cellbender_h5_file"]):::none --> GEX_counts_BPcells_matrix_dir.pbmc_granulocyte_sorted_10k(["GEX_counts_BPcells_matrix_dir"]):::none
  cellbender_h5_file.pbmc_unsorted_10k(["cellbender_h5_file"]):::none --> GEX_counts_BPcells_matrix_dir.pbmc_unsorted_10k(["GEX_counts_BPcells_matrix_dir"]):::none
  cellbender_h5_file.pbmc_unsorted_3k(["cellbender_h5_file"]):::none --> GEX_counts_BPcells_matrix_dir.pbmc_unsorted_3k(["GEX_counts_BPcells_matrix_dir"]):::none
  donor_id_metadata_tibble.brain_mouse(["donor_id_metadata_tibble"]):::none --> GEM_well_metadata_tibble.brain_mouse(["GEM_well_metadata_tibble"]):::none
  donor_id_metadata_tibble.immune_human_2x(["donor_id_metadata_tibble"]):::none --> GEM_well_metadata_tibble.immune_human_2x(["GEM_well_metadata_tibble"]):::none
  donor_id_metadata_tibble.PBMC_human_6x(["donor_id_metadata_tibble"]):::none --> GEM_well_metadata_tibble.PBMC_human_6x(["GEM_well_metadata_tibble"]):::none
  cellranger_barcodes_tsv.embryonic_brain_mouse(["cellranger_barcodes_tsv"]):::none --> vireo_donor_ids_tibble.embryonic_brain_mouse(["vireo_donor_ids_tibble"]):::none
  cellsnp_dir.embryonic_brain_mouse(["cellsnp_dir"]):::none --> vireo_donor_ids_tibble.embryonic_brain_mouse(["vireo_donor_ids_tibble"]):::none
  cellsnp_dir.healthy_PBMC_human(["cellsnp_dir"]):::none --> vireo_donor_ids_tibble.healthy_PBMC_human(["vireo_donor_ids_tibble"]):::none
  cellranger_barcodes_tsv.healthy_PBMC_human(["cellranger_barcodes_tsv"]):::none --> vireo_donor_ids_tibble.healthy_PBMC_human(["vireo_donor_ids_tibble"]):::none
  cellsnp_dir.lymphoma_lymph_human(["cellsnp_dir"]):::none --> vireo_donor_ids_tibble.lymphoma_lymph_human(["vireo_donor_ids_tibble"]):::none
  cellranger_barcodes_tsv.lymphoma_lymph_human(["cellranger_barcodes_tsv"]):::none --> vireo_donor_ids_tibble.lymphoma_lymph_human(["vireo_donor_ids_tibble"]):::none
  cellsnp_dir.pbmc_10k_chromium_controller(["cellsnp_dir"]):::none --> vireo_donor_ids_tibble.pbmc_10k_chromium_controller(["vireo_donor_ids_tibble"]):::none
  cellranger_barcodes_tsv.pbmc_10k_chromium_controller(["cellranger_barcodes_tsv"]):::none --> vireo_donor_ids_tibble.pbmc_10k_chromium_controller(["vireo_donor_ids_tibble"]):::none
  cellsnp_dir.pbmc_10k_chromium_x(["cellsnp_dir"]):::none --> vireo_donor_ids_tibble.pbmc_10k_chromium_x(["vireo_donor_ids_tibble"]):::none
  cellranger_barcodes_tsv.pbmc_10k_chromium_x(["cellranger_barcodes_tsv"]):::none --> vireo_donor_ids_tibble.pbmc_10k_chromium_x(["vireo_donor_ids_tibble"]):::none
  cellsnp_dir.pbmc_granulocyte_sorted_10k(["cellsnp_dir"]):::none --> vireo_donor_ids_tibble.pbmc_granulocyte_sorted_10k(["vireo_donor_ids_tibble"]):::none
  cellranger_barcodes_tsv.pbmc_granulocyte_sorted_10k(["cellranger_barcodes_tsv"]):::none --> vireo_donor_ids_tibble.pbmc_granulocyte_sorted_10k(["vireo_donor_ids_tibble"]):::none
  cellranger_barcodes_tsv.pbmc_unsorted_10k(["cellranger_barcodes_tsv"]):::none --> vireo_donor_ids_tibble.pbmc_unsorted_10k(["vireo_donor_ids_tibble"]):::none
  cellsnp_dir.pbmc_unsorted_10k(["cellsnp_dir"]):::none --> vireo_donor_ids_tibble.pbmc_unsorted_10k(["vireo_donor_ids_tibble"]):::none
  cellranger_barcodes_tsv.pbmc_unsorted_3k(["cellranger_barcodes_tsv"]):::none --> vireo_donor_ids_tibble.pbmc_unsorted_3k(["vireo_donor_ids_tibble"]):::none
  cellsnp_dir.pbmc_unsorted_3k(["cellsnp_dir"]):::none --> vireo_donor_ids_tibble.pbmc_unsorted_3k(["vireo_donor_ids_tibble"]):::none
  fragments_w_prefix_bpcells_dir.embryonic_brain_mouse(["fragments_w_prefix_bpcells_dir"]):::none --> ATAC_qc_metrics_tibble.embryonic_brain_mouse(["ATAC_qc_metrics_tibble"]):::none
  fragments_w_prefix_bpcells_dir.embryonic_brain_mouse(["fragments_w_prefix_bpcells_dir"]):::none --> combined_BPCells_fragment_obj.ATAC.brain_mouse(["combined_BPCells_fragment_obj.ATAC"]):::none
  fragments_w_prefix_bpcells_dir.healthy_PBMC_human(["fragments_w_prefix_bpcells_dir"]):::none --> ATAC_qc_metrics_tibble.healthy_PBMC_human(["ATAC_qc_metrics_tibble"]):::none
  fragments_w_prefix_bpcells_dir.healthy_PBMC_human(["fragments_w_prefix_bpcells_dir"]):::none --> combined_BPCells_fragment_obj.ATAC.immune_human_2x(["combined_BPCells_fragment_obj.ATAC"]):::none
  fragments_w_prefix_bpcells_dir.healthy_PBMC_human(["fragments_w_prefix_bpcells_dir"]):::none --> combined_BPCells_fragment_obj.ATAC.PBMC_human_6x(["combined_BPCells_fragment_obj.ATAC"]):::none
  fragments_w_prefix_bpcells_dir.lymphoma_lymph_human(["fragments_w_prefix_bpcells_dir"]):::none --> ATAC_qc_metrics_tibble.lymphoma_lymph_human(["ATAC_qc_metrics_tibble"]):::none
  fragments_w_prefix_bpcells_dir.lymphoma_lymph_human(["fragments_w_prefix_bpcells_dir"]):::none --> combined_BPCells_fragment_obj.ATAC.immune_human_2x(["combined_BPCells_fragment_obj.ATAC"]):::none
  fragments_w_prefix_bpcells_dir.pbmc_10k_chromium_controller(["fragments_w_prefix_bpcells_dir"]):::none --> ATAC_qc_metrics_tibble.pbmc_10k_chromium_controller(["ATAC_qc_metrics_tibble"]):::none
  fragments_w_prefix_bpcells_dir.pbmc_10k_chromium_controller(["fragments_w_prefix_bpcells_dir"]):::none --> combined_BPCells_fragment_obj.ATAC.PBMC_human_6x(["combined_BPCells_fragment_obj.ATAC"]):::none
  fragments_w_prefix_bpcells_dir.pbmc_10k_chromium_x(["fragments_w_prefix_bpcells_dir"]):::none --> ATAC_qc_metrics_tibble.pbmc_10k_chromium_x(["ATAC_qc_metrics_tibble"]):::none
  fragments_w_prefix_bpcells_dir.pbmc_10k_chromium_x(["fragments_w_prefix_bpcells_dir"]):::none --> combined_BPCells_fragment_obj.ATAC.PBMC_human_6x(["combined_BPCells_fragment_obj.ATAC"]):::none
  fragments_w_prefix_bpcells_dir.pbmc_granulocyte_sorted_10k(["fragments_w_prefix_bpcells_dir"]):::none --> ATAC_qc_metrics_tibble.pbmc_granulocyte_sorted_10k(["ATAC_qc_metrics_tibble"]):::none
  fragments_w_prefix_bpcells_dir.pbmc_granulocyte_sorted_10k(["fragments_w_prefix_bpcells_dir"]):::none --> combined_BPCells_fragment_obj.ATAC.PBMC_human_6x(["combined_BPCells_fragment_obj.ATAC"]):::none
  fragments_w_prefix_bpcells_dir.pbmc_unsorted_10k(["fragments_w_prefix_bpcells_dir"]):::none --> ATAC_qc_metrics_tibble.pbmc_unsorted_10k(["ATAC_qc_metrics_tibble"]):::none
  fragments_w_prefix_bpcells_dir.pbmc_unsorted_10k(["fragments_w_prefix_bpcells_dir"]):::none --> combined_BPCells_fragment_obj.ATAC.PBMC_human_6x(["combined_BPCells_fragment_obj.ATAC"]):::none
  fragments_w_prefix_bpcells_dir.pbmc_unsorted_3k(["fragments_w_prefix_bpcells_dir"]):::none --> ATAC_qc_metrics_tibble.pbmc_unsorted_3k(["ATAC_qc_metrics_tibble"]):::none
  fragments_w_prefix_bpcells_dir.pbmc_unsorted_3k(["fragments_w_prefix_bpcells_dir"]):::none --> combined_BPCells_fragment_obj.ATAC.PBMC_human_6x(["combined_BPCells_fragment_obj.ATAC"]):::none
  GEX_counts_BPcells_matrix_dir.embryonic_brain_mouse(["GEX_counts_BPcells_matrix_dir"]):::none --> full_metadata_tibble.embryonic_brain_mouse(["full_metadata_tibble"]):::none
  GEX_counts_BPcells_matrix_dir.healthy_PBMC_human(["GEX_counts_BPcells_matrix_dir"]):::none --> full_metadata_tibble.healthy_PBMC_human(["full_metadata_tibble"]):::none
  GEX_counts_BPcells_matrix_dir.lymphoma_lymph_human(["GEX_counts_BPcells_matrix_dir"]):::none --> full_metadata_tibble.lymphoma_lymph_human(["full_metadata_tibble"]):::none
  GEX_counts_BPcells_matrix_dir.pbmc_10k_chromium_controller(["GEX_counts_BPcells_matrix_dir"]):::none --> full_metadata_tibble.pbmc_10k_chromium_controller(["full_metadata_tibble"]):::none
  GEX_counts_BPcells_matrix_dir.pbmc_10k_chromium_x(["GEX_counts_BPcells_matrix_dir"]):::none --> full_metadata_tibble.pbmc_10k_chromium_x(["full_metadata_tibble"]):::none
  GEX_counts_BPcells_matrix_dir.pbmc_granulocyte_sorted_10k(["GEX_counts_BPcells_matrix_dir"]):::none --> full_metadata_tibble.pbmc_granulocyte_sorted_10k(["full_metadata_tibble"]):::none
  GEX_counts_BPcells_matrix_dir.pbmc_unsorted_10k(["GEX_counts_BPcells_matrix_dir"]):::none --> full_metadata_tibble.pbmc_unsorted_10k(["full_metadata_tibble"]):::none
  GEX_counts_BPcells_matrix_dir.pbmc_unsorted_3k(["GEX_counts_BPcells_matrix_dir"]):::none --> full_metadata_tibble.pbmc_unsorted_3k(["full_metadata_tibble"]):::none
  GEX_counts_BPcells_matrix_dir.embryonic_brain_mouse(["GEX_counts_BPcells_matrix_dir"]):::none --> aggregated_GEX_BPCells_matrix_dir.GEX.brain_mouse(["aggregated_GEX_BPCells_matrix_dir.GEX"]):::none
  GEX_counts_BPcells_matrix_dir.healthy_PBMC_human(["GEX_counts_BPcells_matrix_dir"]):::none --> aggregated_GEX_BPCells_matrix_dir.GEX.immune_human_2x(["aggregated_GEX_BPCells_matrix_dir.GEX"]):::none
  GEX_counts_BPcells_matrix_dir.healthy_PBMC_human(["GEX_counts_BPcells_matrix_dir"]):::none --> aggregated_GEX_BPCells_matrix_dir.GEX.PBMC_human_6x(["aggregated_GEX_BPCells_matrix_dir.GEX"]):::none
  GEX_counts_BPcells_matrix_dir.lymphoma_lymph_human(["GEX_counts_BPcells_matrix_dir"]):::none --> aggregated_GEX_BPCells_matrix_dir.GEX.immune_human_2x(["aggregated_GEX_BPCells_matrix_dir.GEX"]):::none
  GEX_counts_BPcells_matrix_dir.pbmc_10k_chromium_controller(["GEX_counts_BPcells_matrix_dir"]):::none --> aggregated_GEX_BPCells_matrix_dir.GEX.PBMC_human_6x(["aggregated_GEX_BPCells_matrix_dir.GEX"]):::none
  GEX_counts_BPcells_matrix_dir.pbmc_10k_chromium_x(["GEX_counts_BPcells_matrix_dir"]):::none --> aggregated_GEX_BPCells_matrix_dir.GEX.PBMC_human_6x(["aggregated_GEX_BPCells_matrix_dir.GEX"]):::none
  GEX_counts_BPcells_matrix_dir.pbmc_granulocyte_sorted_10k(["GEX_counts_BPcells_matrix_dir"]):::none --> aggregated_GEX_BPCells_matrix_dir.GEX.PBMC_human_6x(["aggregated_GEX_BPCells_matrix_dir.GEX"]):::none
  GEX_counts_BPcells_matrix_dir.pbmc_unsorted_10k(["GEX_counts_BPcells_matrix_dir"]):::none --> aggregated_GEX_BPCells_matrix_dir.GEX.PBMC_human_6x(["aggregated_GEX_BPCells_matrix_dir.GEX"]):::none
  GEX_counts_BPcells_matrix_dir.pbmc_unsorted_3k(["GEX_counts_BPcells_matrix_dir"]):::none --> aggregated_GEX_BPCells_matrix_dir.GEX.PBMC_human_6x(["aggregated_GEX_BPCells_matrix_dir.GEX"]):::none
  ATAC_marker_TFs_list.brain_mouse(["ATAC_marker_TFs_list"]):::none
  ATAC_marker_TFs_list.immune_human_2x(["ATAC_marker_TFs_list"]):::none
  ATAC_marker_TFs_list.PBMC_human_6x(["ATAC_marker_TFs_list"]):::none
