%%{init: {'flowchart': {'defaultRenderer': 'elk'}}}%%
flowchart TB
  peak_gene_correlation_results_tibble.WNN.peak_gene_correlation.immune_human_2x(["peak_gene_correlation_results_tibble.WNN.&lt;module_name&gt;.&lt;aggregation_name&gt;"]):::none --> correlation_histogram_plot.peak_gene_correlation.immune_human_2x(["correlation_histogram_plot.&lt;module_name&gt;.&lt;aggregation_name&gt;"]):::none
  peak_gene_correlation_diagnostics_tibble.WNN.peak_gene_correlation.immune_human_2x(["peak_gene_correlation_diagnostics_tibble.WNN.&lt;module_name&gt;.&lt;aggregation_name&gt;"]):::none --> diagnostics_plot.peak_gene_correlation.immune_human_2x(["diagnostics_plot.&lt;module_name&gt;.&lt;aggregation_name&gt;"]):::none
  peak_gene_correlation_results_tibble.WNN.peak_gene_correlation.immune_human_2x(["peak_gene_correlation_results_tibble.WNN.&lt;module_name&gt;.&lt;aggregation_name&gt;"]):::none --> distance_correlation_plot.peak_gene_correlation.immune_human_2x(["distance_correlation_plot.&lt;module_name&gt;.&lt;aggregation_name&gt;"]):::none
  peak_gene_correlation_filter_diagnostics_tibble.WNN.peak_gene_correlation.immune_human_2x(["peak_gene_correlation_filter_diagnostics_tibble.WNN.&lt;module_name&gt;.&lt;aggregation_name&gt;"]):::none --> filter_retention_plot.peak_gene_correlation.immune_human_2x(["filter_retention_plot.&lt;module_name&gt;.&lt;aggregation_name&gt;"]):::none
  peak_gene_correlation_candidate_pairs_tibble.WNN.peak_gene_correlation.immune_human_2x(["peak_gene_correlation_candidate_pairs_tibble.WNN.&lt;module_name&gt;.&lt;aggregation_name&gt;"]):::none --> peak_gene_correlation_aggregate_matrices.WNN.peak_gene_correlation.immune_human_2x["peak_gene_correlation_aggregate_matrices.WNN.&lt;module_name&gt;.&lt;aggregation_name&gt;"]:::none
  peak_gene_correlation_group_chromosome_tibble.WNN.peak_gene_correlation.immune_human_2x(["peak_gene_correlation_group_chromosome_tibble.WNN.&lt;module_name&gt;.&lt;aggregation_name&gt;"]):::none --> peak_gene_correlation_aggregate_matrices.WNN.peak_gene_correlation.immune_human_2x["peak_gene_correlation_aggregate_matrices.WNN.&lt;module_name&gt;.&lt;aggregation_name&gt;"]:::none
  peak_gene_correlation_donor_state_aggregates_tibble.WNN.peak_gene_correlation.immune_human_2x(["peak_gene_correlation_donor_state_aggregates_tibble.WNN.&lt;module_name&gt;.&lt;aggregation_name&gt;"]):::none --> peak_gene_correlation_aggregate_matrices.WNN.peak_gene_correlation.immune_human_2x["peak_gene_correlation_aggregate_matrices.WNN.&lt;module_name&gt;.&lt;aggregation_name&gt;"]:::none
  peak_gene_correlation_normalized_aggregate_matrices.WNN.peak_gene_correlation.immune_human_2x["peak_gene_correlation_normalized_aggregate_matrices.WNN.&lt;module_name&gt;.&lt;aggregation_name&gt;"]:::none --> peak_gene_correlation_branch_diagnostics_tibbles.WNN.peak_gene_correlation.immune_human_2x["peak_gene_correlation_branch_diagnostics_tibbles.WNN.&lt;module_name&gt;.&lt;aggregation_name&gt;"]:::none
  peak_gene_correlation_filter_records.WNN.peak_gene_correlation.immune_human_2x["peak_gene_correlation_filter_records.WNN.&lt;module_name&gt;.&lt;aggregation_name&gt;"]:::none --> peak_gene_correlation_branch_diagnostics_tibbles.WNN.peak_gene_correlation.immune_human_2x["peak_gene_correlation_branch_diagnostics_tibbles.WNN.&lt;module_name&gt;.&lt;aggregation_name&gt;"]:::none
  peak_gene_correlation_gene_TSS_tibble.WNN.peak_gene_correlation.immune_human_2x(["peak_gene_correlation_gene_TSS_tibble.WNN.&lt;module_name&gt;.&lt;aggregation_name&gt;"]):::none --> peak_gene_correlation_candidate_pairs_tibble.WNN.peak_gene_correlation.immune_human_2x(["peak_gene_correlation_candidate_pairs_tibble.WNN.&lt;module_name&gt;.&lt;aggregation_name&gt;"]):::none
  peak_gene_correlation_candidate_pairs_tibble.WNN.peak_gene_correlation.immune_human_2x(["peak_gene_correlation_candidate_pairs_tibble.WNN.&lt;module_name&gt;.&lt;aggregation_name&gt;"]):::none --> peak_gene_correlation_chromosome_tibble.WNN.peak_gene_correlation.immune_human_2x(["peak_gene_correlation_chromosome_tibble.WNN.&lt;module_name&gt;.&lt;aggregation_name&gt;"]):::none
  peak_gene_correlation_branch_diagnostics_tibbles.WNN.peak_gene_correlation.immune_human_2x["peak_gene_correlation_branch_diagnostics_tibbles.WNN.&lt;module_name&gt;.&lt;aggregation_name&gt;"]:::none --> peak_gene_correlation_diagnostics_tibble.WNN.peak_gene_correlation.immune_human_2x(["peak_gene_correlation_diagnostics_tibble.WNN.&lt;module_name&gt;.&lt;aggregation_name&gt;"]):::none
  peak_gene_correlation_donor_state_diagnostics_tibble.WNN.peak_gene_correlation.immune_human_2x(["peak_gene_correlation_donor_state_diagnostics_tibble.WNN.&lt;module_name&gt;.&lt;aggregation_name&gt;"]):::none --> peak_gene_correlation_diagnostics_tibble.WNN.peak_gene_correlation.immune_human_2x(["peak_gene_correlation_diagnostics_tibble.WNN.&lt;module_name&gt;.&lt;aggregation_name&gt;"]):::none
  peak_gene_correlation_cell_group_diagnostics_tibble.WNN.peak_gene_correlation.immune_human_2x(["peak_gene_correlation_cell_group_diagnostics_tibble.WNN.&lt;module_name&gt;.&lt;aggregation_name&gt;"]):::none --> peak_gene_correlation_diagnostics_tibble.WNN.peak_gene_correlation.immune_human_2x(["peak_gene_correlation_diagnostics_tibble.WNN.&lt;module_name&gt;.&lt;aggregation_name&gt;"]):::none
  peak_gene_correlation_donor_state_records.WNN.peak_gene_correlation.immune_human_2x["peak_gene_correlation_donor_state_records.WNN.&lt;module_name&gt;.&lt;aggregation_name&gt;"]:::none --> peak_gene_correlation_donor_state_aggregates_tibble.WNN.peak_gene_correlation.immune_human_2x(["peak_gene_correlation_donor_state_aggregates_tibble.WNN.&lt;module_name&gt;.&lt;aggregation_name&gt;"]):::none
  peak_gene_correlation_donor_state_records.WNN.peak_gene_correlation.immune_human_2x["peak_gene_correlation_donor_state_records.WNN.&lt;module_name&gt;.&lt;aggregation_name&gt;"]:::none --> peak_gene_correlation_donor_state_diagnostics_tibble.WNN.peak_gene_correlation.immune_human_2x(["peak_gene_correlation_donor_state_diagnostics_tibble.WNN.&lt;module_name&gt;.&lt;aggregation_name&gt;"]):::none
  peak_gene_correlation_cell_groups_tibble.WNN.peak_gene_correlation.immune_human_2x(["peak_gene_correlation_cell_groups_tibble.WNN.&lt;module_name&gt;.&lt;aggregation_name&gt;"]):::none --> peak_gene_correlation_donor_state_records.WNN.peak_gene_correlation.immune_human_2x["peak_gene_correlation_donor_state_records.WNN.&lt;module_name&gt;.&lt;aggregation_name&gt;"]:::none
  peak_gene_correlation_filter_records.WNN.peak_gene_correlation.immune_human_2x["peak_gene_correlation_filter_records.WNN.&lt;module_name&gt;.&lt;aggregation_name&gt;"]:::none --> peak_gene_correlation_filter_diagnostics_tibble.WNN.peak_gene_correlation.immune_human_2x(["peak_gene_correlation_filter_diagnostics_tibble.WNN.&lt;module_name&gt;.&lt;aggregation_name&gt;"]):::none
  peak_gene_correlation_aggregate_matrices.WNN.peak_gene_correlation.immune_human_2x["peak_gene_correlation_aggregate_matrices.WNN.&lt;module_name&gt;.&lt;aggregation_name&gt;"]:::none --> peak_gene_correlation_filter_records.WNN.peak_gene_correlation.immune_human_2x["peak_gene_correlation_filter_records.WNN.&lt;module_name&gt;.&lt;aggregation_name&gt;"]:::none
  peak_gene_correlation_normalized_aggregate_matrices.WNN.peak_gene_correlation.immune_human_2x["peak_gene_correlation_normalized_aggregate_matrices.WNN.&lt;module_name&gt;.&lt;aggregation_name&gt;"]:::none --> peak_gene_correlation_filter_records.WNN.peak_gene_correlation.immune_human_2x["peak_gene_correlation_filter_records.WNN.&lt;module_name&gt;.&lt;aggregation_name&gt;"]:::none
  peak_gene_correlation_candidate_pairs_tibble.WNN.peak_gene_correlation.immune_human_2x(["peak_gene_correlation_candidate_pairs_tibble.WNN.&lt;module_name&gt;.&lt;aggregation_name&gt;"]):::none --> peak_gene_correlation_filter_records.WNN.peak_gene_correlation.immune_human_2x["peak_gene_correlation_filter_records.WNN.&lt;module_name&gt;.&lt;aggregation_name&gt;"]:::none
  peak_gene_correlation_finemapped_links_tibbles.WNN.peak_gene_correlation.immune_human_2x["peak_gene_correlation_finemapped_links_tibbles.WNN.&lt;module_name&gt;.&lt;aggregation_name&gt;"]:::none --> peak_gene_correlation_finemapped_links_tibble.WNN.peak_gene_correlation.immune_human_2x(["peak_gene_correlation_finemapped_links_tibble.WNN.&lt;module_name&gt;.&lt;aggregation_name&gt;"]):::none
  peak_gene_correlation_normalized_aggregate_matrices.WNN.peak_gene_correlation.immune_human_2x["peak_gene_correlation_normalized_aggregate_matrices.WNN.&lt;module_name&gt;.&lt;aggregation_name&gt;"]:::none --> peak_gene_correlation_finemapped_links_tibbles.WNN.peak_gene_correlation.immune_human_2x["peak_gene_correlation_finemapped_links_tibbles.WNN.&lt;module_name&gt;.&lt;aggregation_name&gt;"]:::none
  peak_gene_correlation_results_tibbles.WNN.peak_gene_correlation.immune_human_2x["peak_gene_correlation_results_tibbles.WNN.&lt;module_name&gt;.&lt;aggregation_name&gt;"]:::none --> peak_gene_correlation_finemapped_links_tibbles.WNN.peak_gene_correlation.immune_human_2x["peak_gene_correlation_finemapped_links_tibbles.WNN.&lt;module_name&gt;.&lt;aggregation_name&gt;"]:::none
  peak_gene_correlation_finemapping_reference.WNN.peak_gene_correlation.immune_human_2x(["peak_gene_correlation_finemapping_reference.WNN.&lt;module_name&gt;.&lt;aggregation_name&gt;"]):::none --> peak_gene_correlation_finemapped_links_tibbles.WNN.peak_gene_correlation.immune_human_2x["peak_gene_correlation_finemapped_links_tibbles.WNN.&lt;module_name&gt;.&lt;aggregation_name&gt;"]:::none
  peak_gene_correlation_candidate_pairs_tibble.WNN.peak_gene_correlation.immune_human_2x(["peak_gene_correlation_candidate_pairs_tibble.WNN.&lt;module_name&gt;.&lt;aggregation_name&gt;"]):::none --> peak_gene_correlation_finemapping_reference.WNN.peak_gene_correlation.immune_human_2x(["peak_gene_correlation_finemapping_reference.WNN.&lt;module_name&gt;.&lt;aggregation_name&gt;"]):::none
  peak_gene_correlation_results_tibble.WNN.peak_gene_correlation.immune_human_2x(["peak_gene_correlation_results_tibble.WNN.&lt;module_name&gt;.&lt;aggregation_name&gt;"]):::none --> peak_gene_correlation_finemapping_reference.WNN.peak_gene_correlation.immune_human_2x(["peak_gene_correlation_finemapping_reference.WNN.&lt;module_name&gt;.&lt;aggregation_name&gt;"]):::none
  peak_gene_correlation_candidate_pairs_tibble.WNN.peak_gene_correlation.immune_human_2x(["peak_gene_correlation_candidate_pairs_tibble.WNN.&lt;module_name&gt;.&lt;aggregation_name&gt;"]):::none --> peak_gene_correlation_group_chromosome_tibble.WNN.peak_gene_correlation.immune_human_2x(["peak_gene_correlation_group_chromosome_tibble.WNN.&lt;module_name&gt;.&lt;aggregation_name&gt;"]):::none
  peak_gene_correlation_chromosome_tibble.WNN.peak_gene_correlation.immune_human_2x(["peak_gene_correlation_chromosome_tibble.WNN.&lt;module_name&gt;.&lt;aggregation_name&gt;"]):::none --> peak_gene_correlation_group_chromosome_tibble.WNN.peak_gene_correlation.immune_human_2x(["peak_gene_correlation_group_chromosome_tibble.WNN.&lt;module_name&gt;.&lt;aggregation_name&gt;"]):::none
  peak_gene_correlation_donor_state_aggregates_tibble.WNN.peak_gene_correlation.immune_human_2x(["peak_gene_correlation_donor_state_aggregates_tibble.WNN.&lt;module_name&gt;.&lt;aggregation_name&gt;"]):::none --> peak_gene_correlation_group_chromosome_tibble.WNN.peak_gene_correlation.immune_human_2x(["peak_gene_correlation_group_chromosome_tibble.WNN.&lt;module_name&gt;.&lt;aggregation_name&gt;"]):::none
  peak_gene_correlation_hierarchical_results_tibbles.WNN.peak_gene_correlation.immune_human_2x["peak_gene_correlation_hierarchical_results_tibbles.WNN.&lt;module_name&gt;.&lt;aggregation_name&gt;"]:::none --> peak_gene_correlation_hierarchical_results_tibble.WNN.peak_gene_correlation.immune_human_2x(["peak_gene_correlation_hierarchical_results_tibble.WNN.&lt;module_name&gt;.&lt;aggregation_name&gt;"]):::none
  peak_gene_REML_native_source_file.peak_gene_correlation.immune_human_2x(["peak_gene_REML_native_source_file.&lt;module_name&gt;.&lt;aggregation_name&gt;"]):::none --> peak_gene_correlation_hierarchical_results_tibbles.WNN.peak_gene_correlation.immune_human_2x["peak_gene_correlation_hierarchical_results_tibbles.WNN.&lt;module_name&gt;.&lt;aggregation_name&gt;"]:::none
  peak_gene_correlation_filter_records.WNN.peak_gene_correlation.immune_human_2x["peak_gene_correlation_filter_records.WNN.&lt;module_name&gt;.&lt;aggregation_name&gt;"]:::none --> peak_gene_correlation_hierarchical_results_tibbles.WNN.peak_gene_correlation.immune_human_2x["peak_gene_correlation_hierarchical_results_tibbles.WNN.&lt;module_name&gt;.&lt;aggregation_name&gt;"]:::none
  peak_gene_correlation_normalized_aggregate_matrices.WNN.peak_gene_correlation.immune_human_2x["peak_gene_correlation_normalized_aggregate_matrices.WNN.&lt;module_name&gt;.&lt;aggregation_name&gt;"]:::none --> peak_gene_correlation_hierarchical_results_tibbles.WNN.peak_gene_correlation.immune_human_2x["peak_gene_correlation_hierarchical_results_tibbles.WNN.&lt;module_name&gt;.&lt;aggregation_name&gt;"]:::none
  peak_gene_KR_native_source_file.peak_gene_correlation.immune_human_2x(["peak_gene_KR_native_source_file.&lt;module_name&gt;.&lt;aggregation_name&gt;"]):::none --> peak_gene_correlation_hierarchical_results_tibbles.WNN.peak_gene_correlation.immune_human_2x["peak_gene_correlation_hierarchical_results_tibbles.WNN.&lt;module_name&gt;.&lt;aggregation_name&gt;"]:::none
  peak_gene_correlation_results_tibble.WNN.peak_gene_correlation.immune_human_2x(["peak_gene_correlation_results_tibble.WNN.&lt;module_name&gt;.&lt;aggregation_name&gt;"]):::none --> peak_gene_correlation_links_tibble.WNN.peak_gene_correlation.immune_human_2x(["peak_gene_correlation_links_tibble.WNN.&lt;module_name&gt;.&lt;aggregation_name&gt;"]):::none
  peak_gene_correlation_aggregate_matrices.WNN.peak_gene_correlation.immune_human_2x["peak_gene_correlation_aggregate_matrices.WNN.&lt;module_name&gt;.&lt;aggregation_name&gt;"]:::none --> peak_gene_correlation_normalized_aggregate_matrices.WNN.peak_gene_correlation.immune_human_2x["peak_gene_correlation_normalized_aggregate_matrices.WNN.&lt;module_name&gt;.&lt;aggregation_name&gt;"]:::none
  peak_gene_correlation_results_tibbles.WNN.peak_gene_correlation.immune_human_2x["peak_gene_correlation_results_tibbles.WNN.&lt;module_name&gt;.&lt;aggregation_name&gt;"]:::none --> peak_gene_correlation_results_tibble.WNN.peak_gene_correlation.immune_human_2x(["peak_gene_correlation_results_tibble.WNN.&lt;module_name&gt;.&lt;aggregation_name&gt;"]):::none
  peak_gene_correlation_normalized_aggregate_matrices.WNN.peak_gene_correlation.immune_human_2x["peak_gene_correlation_normalized_aggregate_matrices.WNN.&lt;module_name&gt;.&lt;aggregation_name&gt;"]:::none --> peak_gene_correlation_results_tibbles.WNN.peak_gene_correlation.immune_human_2x["peak_gene_correlation_results_tibbles.WNN.&lt;module_name&gt;.&lt;aggregation_name&gt;"]:::none
  peak_gene_correlation_filter_records.WNN.peak_gene_correlation.immune_human_2x["peak_gene_correlation_filter_records.WNN.&lt;module_name&gt;.&lt;aggregation_name&gt;"]:::none --> peak_gene_correlation_results_tibbles.WNN.peak_gene_correlation.immune_human_2x["peak_gene_correlation_results_tibbles.WNN.&lt;module_name&gt;.&lt;aggregation_name&gt;"]:::none
  peak_gene_correlation_candidate_pairs_tibble.WNN.peak_gene_correlation.immune_human_2x(["peak_gene_correlation_candidate_pairs_tibble.WNN.&lt;module_name&gt;.&lt;aggregation_name&gt;"]):::none --> peak_gene_correlation_top_gene_context_tibble.WNN.peak_gene_correlation.immune_human_2x(["peak_gene_correlation_top_gene_context_tibble.WNN.&lt;module_name&gt;.&lt;aggregation_name&gt;"]):::none
  peak_gene_correlation_top_gene_context_tibbles.WNN.peak_gene_correlation.immune_human_2x["peak_gene_correlation_top_gene_context_tibbles.WNN.&lt;module_name&gt;.&lt;aggregation_name&gt;"]:::none --> peak_gene_correlation_top_gene_context_tibble.WNN.peak_gene_correlation.immune_human_2x(["peak_gene_correlation_top_gene_context_tibble.WNN.&lt;module_name&gt;.&lt;aggregation_name&gt;"]):::none
  peak_gene_correlation_hierarchical_results_tibbles.WNN.peak_gene_correlation.immune_human_2x["peak_gene_correlation_hierarchical_results_tibbles.WNN.&lt;module_name&gt;.&lt;aggregation_name&gt;"]:::none --> peak_gene_correlation_top_gene_context_tibbles.WNN.peak_gene_correlation.immune_human_2x["peak_gene_correlation_top_gene_context_tibbles.WNN.&lt;module_name&gt;.&lt;aggregation_name&gt;"]:::none
  peak_gene_correlation_top_links_tibble.WNN.peak_gene_correlation.immune_human_2x(["peak_gene_correlation_top_links_tibble.WNN.&lt;module_name&gt;.&lt;aggregation_name&gt;"]):::none --> peak_gene_correlation_top_gene_context_tibbles.WNN.peak_gene_correlation.immune_human_2x["peak_gene_correlation_top_gene_context_tibbles.WNN.&lt;module_name&gt;.&lt;aggregation_name&gt;"]:::none
  peak_gene_correlation_top_link_aggregate_values_tibble.WNN.peak_gene_correlation.immune_human_2x(["peak_gene_correlation_top_link_aggregate_values_tibble.WNN.&lt;module_name&gt;.&lt;aggregation_name&gt;"]):::none --> peak_gene_correlation_top_link_aggregate_scatter_tibble.WNN.peak_gene_correlation.immune_human_2x["peak_gene_correlation_top_link_aggregate_scatter_tibble.WNN.&lt;module_name&gt;.&lt;aggregation_name&gt;"]:::none
  peak_gene_correlation_top_links_tibble.WNN.peak_gene_correlation.immune_human_2x(["peak_gene_correlation_top_links_tibble.WNN.&lt;module_name&gt;.&lt;aggregation_name&gt;"]):::none --> peak_gene_correlation_top_link_aggregate_scatter_tibble.WNN.peak_gene_correlation.immune_human_2x["peak_gene_correlation_top_link_aggregate_scatter_tibble.WNN.&lt;module_name&gt;.&lt;aggregation_name&gt;"]:::none
  peak_gene_correlation_top_link_aggregate_values_tibbles.WNN.peak_gene_correlation.immune_human_2x["peak_gene_correlation_top_link_aggregate_values_tibbles.WNN.&lt;module_name&gt;.&lt;aggregation_name&gt;"]:::none --> peak_gene_correlation_top_link_aggregate_values_tibble.WNN.peak_gene_correlation.immune_human_2x(["peak_gene_correlation_top_link_aggregate_values_tibble.WNN.&lt;module_name&gt;.&lt;aggregation_name&gt;"]):::none
  peak_gene_correlation_normalized_aggregate_matrices.WNN.peak_gene_correlation.immune_human_2x["peak_gene_correlation_normalized_aggregate_matrices.WNN.&lt;module_name&gt;.&lt;aggregation_name&gt;"]:::none --> peak_gene_correlation_top_link_aggregate_values_tibbles.WNN.peak_gene_correlation.immune_human_2x["peak_gene_correlation_top_link_aggregate_values_tibbles.WNN.&lt;module_name&gt;.&lt;aggregation_name&gt;"]:::none
  peak_gene_correlation_top_links_tibble.WNN.peak_gene_correlation.immune_human_2x(["peak_gene_correlation_top_links_tibble.WNN.&lt;module_name&gt;.&lt;aggregation_name&gt;"]):::none --> peak_gene_correlation_top_link_aggregate_values_tibbles.WNN.peak_gene_correlation.immune_human_2x["peak_gene_correlation_top_link_aggregate_values_tibbles.WNN.&lt;module_name&gt;.&lt;aggregation_name&gt;"]:::none
  peak_gene_correlation_top_link_plot_data.WNN.peak_gene_correlation.immune_human_2x["peak_gene_correlation_top_link_plot_data.WNN.&lt;module_name&gt;.&lt;aggregation_name&gt;"]:::none --> peak_gene_correlation_top_link_focal_ATAC_coverage_tibble.WNN.peak_gene_correlation.immune_human_2x["peak_gene_correlation_top_link_focal_ATAC_coverage_tibble.WNN.&lt;module_name&gt;.&lt;aggregation_name&gt;"]:::none
  peak_gene_correlation_top_links_tibble.WNN.peak_gene_correlation.immune_human_2x(["peak_gene_correlation_top_links_tibble.WNN.&lt;module_name&gt;.&lt;aggregation_name&gt;"]):::none --> peak_gene_correlation_top_link_plot_data.WNN.peak_gene_correlation.immune_human_2x["peak_gene_correlation_top_link_plot_data.WNN.&lt;module_name&gt;.&lt;aggregation_name&gt;"]:::none
  peak_gene_correlation_top_gene_context_tibble.WNN.peak_gene_correlation.immune_human_2x(["peak_gene_correlation_top_gene_context_tibble.WNN.&lt;module_name&gt;.&lt;aggregation_name&gt;"]):::none --> peak_gene_correlation_top_link_plot_data.WNN.peak_gene_correlation.immune_human_2x["peak_gene_correlation_top_link_plot_data.WNN.&lt;module_name&gt;.&lt;aggregation_name&gt;"]:::none
  peak_gene_correlation_hierarchical_results_tibble.WNN.peak_gene_correlation.immune_human_2x(["peak_gene_correlation_hierarchical_results_tibble.WNN.&lt;module_name&gt;.&lt;aggregation_name&gt;"]):::none --> peak_gene_correlation_top_links_tibble.WNN.peak_gene_correlation.immune_human_2x(["peak_gene_correlation_top_links_tibble.WNN.&lt;module_name&gt;.&lt;aggregation_name&gt;"]):::none
  peak_gene_correlation_candidate_pairs_tibble.WNN.peak_gene_correlation.immune_human_2x(["peak_gene_correlation_candidate_pairs_tibble.WNN.&lt;module_name&gt;.&lt;aggregation_name&gt;"]):::none --> peak_gene_correlation_top_links_tibble.WNN.peak_gene_correlation.immune_human_2x(["peak_gene_correlation_top_links_tibble.WNN.&lt;module_name&gt;.&lt;aggregation_name&gt;"]):::none
  peak_gene_correlation_results_tibble.WNN.peak_gene_correlation.immune_human_2x(["peak_gene_correlation_results_tibble.WNN.&lt;module_name&gt;.&lt;aggregation_name&gt;"]):::none --> significant_pairs_technical_features_tibble.WNN.peak_gene_correlation.immune_human_2x(["significant_pairs_technical_features_tibble.WNN.&lt;module_name&gt;.&lt;aggregation_name&gt;"]):::none
  peak_gene_correlation_donor_state_aggregates_tibble.WNN.peak_gene_correlation.immune_human_2x(["peak_gene_correlation_donor_state_aggregates_tibble.WNN.&lt;module_name&gt;.&lt;aggregation_name&gt;"]):::none --> significant_pairs_technical_features_tibble.WNN.peak_gene_correlation.immune_human_2x(["significant_pairs_technical_features_tibble.WNN.&lt;module_name&gt;.&lt;aggregation_name&gt;"]):::none
  significant_pairs_technical_features_tibble.WNN.peak_gene_correlation.immune_human_2x(["significant_pairs_technical_features_tibble.WNN.&lt;module_name&gt;.&lt;aggregation_name&gt;"]):::none --> significant_pairs_vs_technical_features_plot.peak_gene_correlation.immune_human_2x(["significant_pairs_vs_technical_features_plot.&lt;module_name&gt;.&lt;aggregation_name&gt;"]):::none
  peak_gene_correlation_results_tibble.WNN.peak_gene_correlation.immune_human_2x(["peak_gene_correlation_results_tibble.WNN.&lt;module_name&gt;.&lt;aggregation_name&gt;"]):::none --> support_counts_plot.peak_gene_correlation.immune_human_2x(["support_counts_plot.&lt;module_name&gt;.&lt;aggregation_name&gt;"]):::none
  peak_gene_correlation_top_link_aggregate_scatter_tibble.WNN.peak_gene_correlation.immune_human_2x["peak_gene_correlation_top_link_aggregate_scatter_tibble.WNN.&lt;module_name&gt;.&lt;aggregation_name&gt;"]:::none --> top_link_aggregate_scatter_plots.peak_gene_correlation.immune_human_2x["top_link_aggregate_scatter_plots.&lt;module_name&gt;.&lt;aggregation_name&gt;"]:::none
  peak_gene_correlation_top_link_plot_data.WNN.peak_gene_correlation.immune_human_2x["peak_gene_correlation_top_link_plot_data.WNN.&lt;module_name&gt;.&lt;aggregation_name&gt;"]:::none --> top_link_aggregate_scatter_plots.peak_gene_correlation.immune_human_2x["top_link_aggregate_scatter_plots.&lt;module_name&gt;.&lt;aggregation_name&gt;"]:::none
  peak_gene_correlation_top_link_focal_ATAC_coverage_tibble.WNN.peak_gene_correlation.immune_human_2x["peak_gene_correlation_top_link_focal_ATAC_coverage_tibble.WNN.&lt;module_name&gt;.&lt;aggregation_name&gt;"]:::none --> top_link_aggregate_scatter_plots.peak_gene_correlation.immune_human_2x["top_link_aggregate_scatter_plots.&lt;module_name&gt;.&lt;aggregation_name&gt;"]:::none
