%%{init: {'flowchart': {'defaultRenderer': 'elk'}}}%%
flowchart TB
  style Graph fill:#FFFFFF00,stroke:#000000;
  subgraph Graph
    direction TB
    pseudobulk_counts_matrix.ATAC.immune_human_2x(["pseudobulk_counts_matrix.ATAC.immune_human_2x"]):::none --> activity_matrix.gene_level.pseudobulk.genetic_enrichment.immune_human_2x(["activity_matrix.gene_level.pseudobulk.genetic_enrichment.immune_human_2x"]):::none
    peak_weight_matrix.gene_level.pseudobulk.genetic_enrichment.immune_human_2x(["peak_weight_matrix.gene_level.pseudobulk.genetic_enrichment.immune_human_2x"]):::none --> activity_matrix.gene_level.pseudobulk.genetic_enrichment.immune_human_2x(["activity_matrix.gene_level.pseudobulk.genetic_enrichment.immune_human_2x"]):::none
    pseudobulk_counts_matrix.ATAC.immune_human_2x(["pseudobulk_counts_matrix.ATAC.immune_human_2x"]):::none --> activity_matrix.trait_level.pseudobulk.genetic_enrichment.immune_human_2x(["activity_matrix.trait_level.pseudobulk.genetic_enrichment.immune_human_2x"]):::none
    peak_weight_matrix.trait_level.pseudobulk.genetic_enrichment.immune_human_2x(["peak_weight_matrix.trait_level.pseudobulk.genetic_enrichment.immune_human_2x"]):::none --> activity_matrix.trait_level.pseudobulk.genetic_enrichment.immune_human_2x(["activity_matrix.trait_level.pseudobulk.genetic_enrichment.immune_human_2x"]):::none
    inputs_tibble.gene_level.pseudobulk.genetic_enrichment.immune_human_2x(["inputs_tibble.gene_level.pseudobulk.genetic_enrichment.immune_human_2x"]):::none --> credible_set_variants_tibble.gene_level.pseudobulk.genetic_enrichment.immune_human_2x(["credible_set_variants_tibble.gene_level.pseudobulk.genetic_enrichment.immune_human_2x"]):::none
    open_targets_gwas_credible_sets_evidence_dataset_path(["open_targets_gwas_credible_sets_evidence_dataset_path"]):::none --> L2G_tibble.gene_level.pseudobulk.genetic_enrichment.immune_human_2x(["L2G_tibble.gene_level.pseudobulk.genetic_enrichment.immune_human_2x"]):::none
    credible_set_variants_tibble.gene_level.pseudobulk.genetic_enrichment.immune_human_2x(["credible_set_variants_tibble.gene_level.pseudobulk.genetic_enrichment.immune_human_2x"]):::none --> L2G_tibble.gene_level.pseudobulk.genetic_enrichment.immune_human_2x(["L2G_tibble.gene_level.pseudobulk.genetic_enrichment.immune_human_2x"]):::none
    GWAS_inputs_tibble.genetic_enrichment.immune_human_2x(["GWAS_inputs_tibble.genetic_enrichment.immune_human_2x"]):::none --> results_tibble.trait_level.pseudobulk.genetic_enrichment.immune_human_2x(["results_tibble.trait_level.pseudobulk.genetic_enrichment.immune_human_2x"]):::none
    GWAS_inputs_tibble.genetic_enrichment.immune_human_2x(["GWAS_inputs_tibble.genetic_enrichment.immune_human_2x"]):::none --> inputs_tibble.gene_level.pseudobulk.genetic_enrichment.immune_human_2x(["inputs_tibble.gene_level.pseudobulk.genetic_enrichment.immune_human_2x"]):::none
    GWAS_inputs_tibble.genetic_enrichment.immune_human_2x(["GWAS_inputs_tibble.genetic_enrichment.immune_human_2x"]):::none --> peak_weight_matrix.trait_level.pseudobulk.genetic_enrichment.immune_human_2x(["peak_weight_matrix.trait_level.pseudobulk.genetic_enrichment.immune_human_2x"]):::none
    L2G_tibble.gene_level.pseudobulk.genetic_enrichment.immune_human_2x(["L2G_tibble.gene_level.pseudobulk.genetic_enrichment.immune_human_2x"]):::none --> peak_weight_matrix.gene_level.pseudobulk.genetic_enrichment.immune_human_2x(["peak_weight_matrix.gene_level.pseudobulk.genetic_enrichment.immune_human_2x"]):::none
    L2G_tibble.gene_level.pseudobulk.genetic_enrichment.immune_human_2x(["L2G_tibble.gene_level.pseudobulk.genetic_enrichment.immune_human_2x"]):::none --> results_tibble.gene_level.pseudobulk.genetic_enrichment.immune_human_2x(["results_tibble.gene_level.pseudobulk.genetic_enrichment.immune_human_2x"]):::none
    activity_matrix.gene_level.pseudobulk.genetic_enrichment.immune_human_2x(["activity_matrix.gene_level.pseudobulk.genetic_enrichment.immune_human_2x"]):::none --> results_tibble.gene_level.pseudobulk.genetic_enrichment.immune_human_2x(["results_tibble.gene_level.pseudobulk.genetic_enrichment.immune_human_2x"]):::none
    activity_matrix.trait_level.pseudobulk.genetic_enrichment.immune_human_2x(["activity_matrix.trait_level.pseudobulk.genetic_enrichment.immune_human_2x"]):::none --> results_tibble.trait_level.pseudobulk.genetic_enrichment.immune_human_2x(["results_tibble.trait_level.pseudobulk.genetic_enrichment.immune_human_2x"]):::none
    credible_set_variants_tibble.gene_level.pseudobulk.genetic_enrichment.immune_human_2x(["credible_set_variants_tibble.gene_level.pseudobulk.genetic_enrichment.immune_human_2x"]):::none --> peak_weight_matrix.gene_level.pseudobulk.genetic_enrichment.immune_human_2x(["peak_weight_matrix.gene_level.pseudobulk.genetic_enrichment.immune_human_2x"]):::none
    credible_set_variants_tibble.gene_level.pseudobulk.genetic_enrichment.immune_human_2x(["credible_set_variants_tibble.gene_level.pseudobulk.genetic_enrichment.immune_human_2x"]):::none --> results_tibble.gene_level.pseudobulk.genetic_enrichment.immune_human_2x(["results_tibble.gene_level.pseudobulk.genetic_enrichment.immune_human_2x"]):::none
    inputs_tibble.gene_level.pseudobulk.genetic_enrichment.immune_human_2x(["inputs_tibble.gene_level.pseudobulk.genetic_enrichment.immune_human_2x"]):::none --> peak_weight_matrix.gene_level.pseudobulk.genetic_enrichment.immune_human_2x(["peak_weight_matrix.gene_level.pseudobulk.genetic_enrichment.immune_human_2x"]):::none
    inputs_tibble.gene_level.pseudobulk.genetic_enrichment.immune_human_2x(["inputs_tibble.gene_level.pseudobulk.genetic_enrichment.immune_human_2x"]):::none --> results_tibble.gene_level.pseudobulk.genetic_enrichment.immune_human_2x(["results_tibble.gene_level.pseudobulk.genetic_enrichment.immune_human_2x"]):::none
    models.trait_level.pseudobulk.genetic_enrichment.immune_human_2x(["models.trait_level.pseudobulk.genetic_enrichment.immune_human_2x"]):::none --> results_tibble.gene_level.pseudobulk.genetic_enrichment.immune_human_2x(["results_tibble.gene_level.pseudobulk.genetic_enrichment.immune_human_2x"]):::none
    models.trait_level.pseudobulk.genetic_enrichment.immune_human_2x(["models.trait_level.pseudobulk.genetic_enrichment.immune_human_2x"]):::none --> results_tibble.trait_level.pseudobulk.genetic_enrichment.immune_human_2x(["results_tibble.trait_level.pseudobulk.genetic_enrichment.immune_human_2x"]):::none
    pseudobulk_counts_matrix.ATAC.immune_human_2x(["pseudobulk_counts_matrix.ATAC.immune_human_2x"]):::none --> results_tibble.gene_level.pseudobulk.genetic_enrichment.immune_human_2x(["results_tibble.gene_level.pseudobulk.genetic_enrichment.immune_human_2x"]):::none
    pseudobulk_counts_matrix.ATAC.immune_human_2x(["pseudobulk_counts_matrix.ATAC.immune_human_2x"]):::none --> results_tibble.trait_level.pseudobulk.genetic_enrichment.immune_human_2x(["results_tibble.trait_level.pseudobulk.genetic_enrichment.immune_human_2x"]):::none
  end
