%%{init: {'flowchart': {'defaultRenderer': 'elk'}}}%%
flowchart TB
  cellranger_barcodes_tsv.embryonic_brain_mouse(["cellranger_barcodes_tsv.&lt;GEM_well_ID&gt;"]):::none --> amulet_metrics_tibble.embryonic_brain_mouse(["amulet_metrics_tibble.&lt;GEM_well_ID&gt;"]):::none
  cellranger_barcodes_tsv.embryonic_brain_mouse(["cellranger_barcodes_tsv.&lt;GEM_well_ID&gt;"]):::none --> cellsnp_dir.embryonic_brain_mouse(["cellsnp_dir.&lt;GEM_well_ID&gt;"]):::none
  metadata_w_cell_types_tibble.ATAC.brain_mouse(["metadata_w_cell_types_tibble.ATAC.&lt;aggregation_name&gt;"]):::none --> chromVAR_obj.ATAC.brain_mouse(["chromVAR_obj.ATAC.&lt;aggregation_name&gt;"]):::none
  consensus_peak_GRanges.ATAC.brain_mouse(["consensus_peak_GRanges.ATAC.&lt;aggregation_name&gt;"]):::none --> chromVAR_obj.ATAC.brain_mouse(["chromVAR_obj.ATAC.&lt;aggregation_name&gt;"]):::none
  combined_BPCells_fragment_obj.ATAC.brain_mouse(["combined_BPCells_fragment_obj.ATAC.&lt;aggregation_name&gt;"]):::none --> consensus_peak_BPCells_matrix_dir.ATAC.brain_mouse(["consensus_peak_BPCells_matrix_dir.ATAC.&lt;aggregation_name&gt;"]):::none
  consensus_peak_GRanges.ATAC.brain_mouse(["consensus_peak_GRanges.ATAC.&lt;aggregation_name&gt;"]):::none --> consensus_peak_BPCells_matrix_dir.ATAC.brain_mouse(["consensus_peak_BPCells_matrix_dir.ATAC.&lt;aggregation_name&gt;"]):::none
  metadata_w_cell_types_tibble.GEX.brain_mouse(["metadata_w_cell_types_tibble.GEX.&lt;aggregation_name&gt;"]):::none --> consensus_peak_BPCells_matrix_dir.ATAC.brain_mouse(["consensus_peak_BPCells_matrix_dir.ATAC.&lt;aggregation_name&gt;"]):::none
  within_clusters_collapsed_peaks_per_cluster_GRanges.ATAC.brain_mouse["within_clusters_collapsed_peaks_per_cluster_GRanges.ATAC.&lt;aggregation_name&gt;"]:::none --> consensus_peak_GRanges.ATAC.brain_mouse(["consensus_peak_GRanges.ATAC.&lt;aggregation_name&gt;"]):::none
  harmony_embeddings_matrix.GEX.brain_mouse(["harmony_embeddings_matrix.GEX.&lt;aggregation_name&gt;"]):::none --> embedding_matrices.WNN.brain_mouse(["embedding_matrices.WNN.&lt;aggregation_name&gt;"]):::none
  metadata_w_cell_types_tibble.ATAC.brain_mouse(["metadata_w_cell_types_tibble.ATAC.&lt;aggregation_name&gt;"]):::none --> embedding_matrices.WNN.brain_mouse(["embedding_matrices.WNN.&lt;aggregation_name&gt;"]):::none
  harmony_embeddings_matrix.ATAC.brain_mouse(["harmony_embeddings_matrix.ATAC.&lt;aggregation_name&gt;"]):::none --> embedding_matrices.WNN.brain_mouse(["embedding_matrices.WNN.&lt;aggregation_name&gt;"]):::none
  full_metadata_tibble.embryonic_brain_mouse(["full_metadata_tibble.&lt;GEM_well_ID&gt;"]):::none --> excluded_cellranger_only_barcodes_by_type_list.embryonic_brain_mouse(["excluded_cellranger_only_barcodes_by_type_list.&lt;GEM_well_ID&gt;"]):::none
  amulet_metrics_tibble.embryonic_brain_mouse(["amulet_metrics_tibble.&lt;GEM_well_ID&gt;"]):::none --> full_metadata_tibble.embryonic_brain_mouse(["full_metadata_tibble.&lt;GEM_well_ID&gt;"]):::none
  per_barcode_metrics_tibble.embryonic_brain_mouse(["per_barcode_metrics_tibble.&lt;GEM_well_ID&gt;"]):::none --> full_metadata_tibble.embryonic_brain_mouse(["full_metadata_tibble.&lt;GEM_well_ID&gt;"]):::none
  vireo_donor_ids_tibble.embryonic_brain_mouse(["vireo_donor_ids_tibble.&lt;GEM_well_ID&gt;"]):::none --> full_metadata_tibble.embryonic_brain_mouse(["full_metadata_tibble.&lt;GEM_well_ID&gt;"]):::none
  ATAC_qc_metrics_tibble.embryonic_brain_mouse(["ATAC_qc_metrics_tibble.&lt;GEM_well_ID&gt;"]):::none --> full_metadata_tibble.embryonic_brain_mouse(["full_metadata_tibble.&lt;GEM_well_ID&gt;"]):::none
  cellbender_h5_file.embryonic_brain_mouse(["cellbender_h5_file.&lt;GEM_well_ID&gt;"]):::none --> GEX_counts_BPcells_matrix_dir.embryonic_brain_mouse(["GEX_counts_BPcells_matrix_dir.&lt;GEM_well_ID&gt;"]):::none
  LSI_BPCells.ATAC.brain_mouse(["LSI_BPCells.ATAC.&lt;aggregation_name&gt;"]):::none --> harmony_embeddings_matrix.ATAC.brain_mouse(["harmony_embeddings_matrix.ATAC.&lt;aggregation_name&gt;"]):::none
  PCA_BPCells.GEX.brain_mouse(["PCA_BPCells.GEX.&lt;aggregation_name&gt;"]):::none --> harmony_embeddings_matrix.GEX.brain_mouse(["harmony_embeddings_matrix.GEX.&lt;aggregation_name&gt;"]):::none
  metadata_tibble.GEX.brain_mouse(["metadata_tibble.GEX.&lt;aggregation_name&gt;"]):::none --> harmony_embeddings_matrix.GEX.brain_mouse(["harmony_embeddings_matrix.GEX.&lt;aggregation_name&gt;"]):::none
  harmony_embeddings_matrix.ATAC.brain_mouse(["harmony_embeddings_matrix.ATAC.&lt;aggregation_name&gt;"]):::none --> LSI_clusters.ATAC.brain_mouse(["LSI_clusters.ATAC.&lt;aggregation_name&gt;"]):::none
  GEM_well_metadata_tibble.brain_mouse(["GEM_well_metadata_tibble.&lt;aggregation_name&gt;"]):::none --> metadata_tibble.GEX.brain_mouse(["metadata_tibble.GEX.&lt;aggregation_name&gt;"]):::none
  donor_id_metadata_tibble.brain_mouse(["donor_id_metadata_tibble.&lt;aggregation_name&gt;"]):::none --> metadata_tibble.GEX.brain_mouse(["metadata_tibble.GEX.&lt;aggregation_name&gt;"]):::none
  PCA_BPCells.GEX.brain_mouse(["PCA_BPCells.GEX.&lt;aggregation_name&gt;"]):::none --> metadata_tibble.GEX.brain_mouse(["metadata_tibble.GEX.&lt;aggregation_name&gt;"]):::none
  scDblFinder_results_df.ATAC.brain_mouse(["scDblFinder_results_df.ATAC.&lt;aggregation_name&gt;"]):::none --> metadata_w_cell_types_tibble.ATAC.brain_mouse(["metadata_w_cell_types_tibble.ATAC.&lt;aggregation_name&gt;"]):::none
  scDblFinder_results_df.GEX.brain_mouse(["scDblFinder_results_df.GEX.&lt;aggregation_name&gt;"]):::none --> metadata_w_cell_types_tibble.GEX.brain_mouse(["metadata_w_cell_types_tibble.GEX.&lt;aggregation_name&gt;"]):::none
  UCell_GEX_marker_genes_list.brain_mouse(["UCell_GEX_marker_genes_list.&lt;aggregation_name&gt;"]):::none --> metadata_w_cell_types_tibble.WNN.brain_mouse(["metadata_w_cell_types_tibble.WNN.&lt;aggregation_name&gt;"]):::none
  GEM_well_metadata_tibble.brain_mouse(["GEM_well_metadata_tibble.&lt;aggregation_name&gt;"]):::none --> PCA_BPCells.GEX.brain_mouse(["PCA_BPCells.GEX.&lt;aggregation_name&gt;"]):::none
  donor_id_metadata_tibble.brain_mouse(["donor_id_metadata_tibble.&lt;aggregation_name&gt;"]):::none --> PCA_BPCells.GEX.brain_mouse(["PCA_BPCells.GEX.&lt;aggregation_name&gt;"]):::none
  harmony_embeddings_matrix.GEX.brain_mouse(["harmony_embeddings_matrix.GEX.&lt;aggregation_name&gt;"]):::none --> PCA_clusters.GEX.brain_mouse(["PCA_clusters.GEX.&lt;aggregation_name&gt;"]):::none
  consensus_peak_GRanges.ATAC.brain_mouse(["consensus_peak_GRanges.ATAC.&lt;aggregation_name&gt;"]):::none --> peak_TF_motif_matrix.ATAC.brain_mouse(["peak_TF_motif_matrix.ATAC.&lt;aggregation_name&gt;"]):::none
  ATAC_marker_TFs_list.brain_mouse(["ATAC_marker_TFs_list.&lt;aggregation_name&gt;"]):::none --> peak_TF_motif_matrix.ATAC.brain_mouse(["peak_TF_motif_matrix.ATAC.&lt;aggregation_name&gt;"]):::none
  combined_BPCells_fragment_obj.ATAC.brain_mouse(["combined_BPCells_fragment_obj.ATAC.&lt;aggregation_name&gt;"]):::none --> peaks_per_cluster_narrowPeaks.peaks.ATAC.brain_mouse["peaks_per_cluster_narrowPeaks.peaks.ATAC.&lt;aggregation_name&gt;"]:::none
  donor_id_metadata_tibble.brain_mouse(["donor_id_metadata_tibble.&lt;aggregation_name&gt;"]):::none --> GEM_well_metadata_tibble.brain_mouse(["GEM_well_metadata_tibble.&lt;aggregation_name&gt;"]):::none
  harmony_embeddings_matrix.ATAC.brain_mouse(["harmony_embeddings_matrix.ATAC.&lt;aggregation_name&gt;"]):::none --> UMAP_embeddings_tibble.ATAC.brain_mouse(["UMAP_embeddings_tibble.ATAC.&lt;aggregation_name&gt;"]):::none
  PCA_BPCells.GEX.brain_mouse(["PCA_BPCells.GEX.&lt;aggregation_name&gt;"]):::none --> UMAP_embeddings_tibble.GEX_non_harmony.brain_mouse(["UMAP_embeddings_tibble.GEX_non_harmony.&lt;aggregation_name&gt;"]):::none
  harmony_embeddings_matrix.GEX.brain_mouse(["harmony_embeddings_matrix.GEX.&lt;aggregation_name&gt;"]):::none --> UMAP_embeddings_tibble.GEX.brain_mouse(["UMAP_embeddings_tibble.GEX.&lt;aggregation_name&gt;"]):::none
  WNN_results.brain_mouse(["WNN_results.&lt;aggregation_name&gt;"]):::none --> UMAP_embeddings_tibble.WNN.brain_mouse(["UMAP_embeddings_tibble.WNN.&lt;aggregation_name&gt;"]):::none
  cellranger_barcodes_tsv.embryonic_brain_mouse(["cellranger_barcodes_tsv.&lt;GEM_well_ID&gt;"]):::none --> vireo_donor_ids_tibble.embryonic_brain_mouse(["vireo_donor_ids_tibble.&lt;GEM_well_ID&gt;"]):::none
  cellsnp_dir.embryonic_brain_mouse(["cellsnp_dir.&lt;GEM_well_ID&gt;"]):::none --> vireo_donor_ids_tibble.embryonic_brain_mouse(["vireo_donor_ids_tibble.&lt;GEM_well_ID&gt;"]):::none
  clusters_tibble.WNN.brain_mouse(["clusters_tibble.WNN.&lt;aggregation_name&gt;"]):::none --> WNN_results.brain_mouse(["WNN_results.&lt;aggregation_name&gt;"]):::none
  embedding_matrices.WNN.brain_mouse(["embedding_matrices.WNN.&lt;aggregation_name&gt;"]):::none --> WNN_results.brain_mouse(["WNN_results.&lt;aggregation_name&gt;"]):::none
  aggregated_GEX_BPCells_matrix_dir.GEX.brain_mouse(["aggregated_GEX_BPCells_matrix_dir.GEX.&lt;aggregation_name&gt;"]):::none --> PCA_BPCells.GEX.brain_mouse(["PCA_BPCells.GEX.&lt;aggregation_name&gt;"]):::none
  aggregated_GEX_BPCells_matrix_dir.GEX.brain_mouse(["aggregated_GEX_BPCells_matrix_dir.GEX.&lt;aggregation_name&gt;"]):::none --> metadata_w_cell_types_tibble.GEX.brain_mouse(["metadata_w_cell_types_tibble.GEX.&lt;aggregation_name&gt;"]):::none
  aggregated_GEX_BPCells_matrix_dir.GEX.brain_mouse(["aggregated_GEX_BPCells_matrix_dir.GEX.&lt;aggregation_name&gt;"]):::none --> scDblFinder_results_df.GEX.brain_mouse(["scDblFinder_results_df.GEX.&lt;aggregation_name&gt;"]):::none
  metadata_w_cell_types_tibble.GEX.brain_mouse(["metadata_w_cell_types_tibble.GEX.&lt;aggregation_name&gt;"]):::none --> peaks_per_cluster_narrowPeaks.peaks.ATAC.brain_mouse["peaks_per_cluster_narrowPeaks.peaks.ATAC.&lt;aggregation_name&gt;"]:::none
  full_metadata_tibble.embryonic_brain_mouse(["full_metadata_tibble.&lt;GEM_well_ID&gt;"]):::none --> metadata_tibble.GEX.brain_mouse(["metadata_tibble.GEX.&lt;aggregation_name&gt;"]):::none
  full_metadata_tibble.embryonic_brain_mouse(["full_metadata_tibble.&lt;GEM_well_ID&gt;"]):::none --> PCA_BPCells.GEX.brain_mouse(["PCA_BPCells.GEX.&lt;aggregation_name&gt;"]):::none
  chromVAR_obj.ATAC.brain_mouse(["chromVAR_obj.ATAC.&lt;aggregation_name&gt;"]):::none --> TF_activity_BPCells_matrix_dir.ATAC.brain_mouse(["TF_activity_BPCells_matrix_dir.ATAC.&lt;aggregation_name&gt;"]):::none
  peak_TF_motif_matrix.ATAC.brain_mouse(["peak_TF_motif_matrix.ATAC.&lt;aggregation_name&gt;"]):::none --> TF_activity_BPCells_matrix_dir.ATAC.brain_mouse(["TF_activity_BPCells_matrix_dir.ATAC.&lt;aggregation_name&gt;"]):::none
  embedding_matrices.WNN.brain_mouse(["embedding_matrices.WNN.&lt;aggregation_name&gt;"]):::none --> clusters_tibble.WNN.brain_mouse(["clusters_tibble.WNN.&lt;aggregation_name&gt;"]):::none
  consensus_peak_BPCells_matrix_dir.ATAC.brain_mouse(["consensus_peak_BPCells_matrix_dir.ATAC.&lt;aggregation_name&gt;"]):::none --> chromVAR_obj.ATAC.brain_mouse(["chromVAR_obj.ATAC.&lt;aggregation_name&gt;"]):::none
  consensus_peak_BPCells_matrix_dir.ATAC.brain_mouse(["consensus_peak_BPCells_matrix_dir.ATAC.&lt;aggregation_name&gt;"]):::none --> peak_TF_motif_matrix.ATAC.brain_mouse(["peak_TF_motif_matrix.ATAC.&lt;aggregation_name&gt;"]):::none
  consensus_peak_BPCells_matrix_dir.ATAC.brain_mouse(["consensus_peak_BPCells_matrix_dir.ATAC.&lt;aggregation_name&gt;"]):::none --> LSI_BPCells.ATAC.brain_mouse(["LSI_BPCells.ATAC.&lt;aggregation_name&gt;"]):::none
  consensus_peak_BPCells_matrix_dir.ATAC.brain_mouse(["consensus_peak_BPCells_matrix_dir.ATAC.&lt;aggregation_name&gt;"]):::none --> harmony_embeddings_matrix.ATAC.brain_mouse(["harmony_embeddings_matrix.ATAC.&lt;aggregation_name&gt;"]):::none
  consensus_peak_BPCells_matrix_dir.ATAC.brain_mouse(["consensus_peak_BPCells_matrix_dir.ATAC.&lt;aggregation_name&gt;"]):::none --> scDblFinder_results_df.ATAC.brain_mouse(["scDblFinder_results_df.ATAC.&lt;aggregation_name&gt;"]):::none
  consensus_peak_BPCells_matrix_dir.ATAC.brain_mouse(["consensus_peak_BPCells_matrix_dir.ATAC.&lt;aggregation_name&gt;"]):::none --> metadata_w_cell_types_tibble.ATAC.brain_mouse(["metadata_w_cell_types_tibble.ATAC.&lt;aggregation_name&gt;"]):::none
  fragments_w_prefix_bpcells_dir.embryonic_brain_mouse(["fragments_w_prefix_bpcells_dir.&lt;GEM_well_ID&gt;"]):::none --> ATAC_qc_metrics_tibble.embryonic_brain_mouse(["ATAC_qc_metrics_tibble.&lt;GEM_well_ID&gt;"]):::none
  fragments_w_prefix_bpcells_dir.embryonic_brain_mouse(["fragments_w_prefix_bpcells_dir.&lt;GEM_well_ID&gt;"]):::none --> combined_BPCells_fragment_obj.ATAC.brain_mouse(["combined_BPCells_fragment_obj.ATAC.&lt;aggregation_name&gt;"]):::none
  GEX_counts_BPcells_matrix_dir.embryonic_brain_mouse(["GEX_counts_BPcells_matrix_dir.&lt;GEM_well_ID&gt;"]):::none --> full_metadata_tibble.embryonic_brain_mouse(["full_metadata_tibble.&lt;GEM_well_ID&gt;"]):::none
  excluded_cellranger_only_barcodes_by_type_list.embryonic_brain_mouse(["excluded_cellranger_only_barcodes_by_type_list.&lt;GEM_well_ID&gt;"]):::none --> metadata_tibble.GEX.brain_mouse(["metadata_tibble.GEX.&lt;aggregation_name&gt;"]):::none
  excluded_cellranger_only_barcodes_by_type_list.embryonic_brain_mouse(["excluded_cellranger_only_barcodes_by_type_list.&lt;GEM_well_ID&gt;"]):::none --> PCA_BPCells.GEX.brain_mouse(["PCA_BPCells.GEX.&lt;aggregation_name&gt;"]):::none
  GEX_counts_BPcells_matrix_dir.embryonic_brain_mouse(["GEX_counts_BPcells_matrix_dir.&lt;GEM_well_ID&gt;"]):::none --> aggregated_GEX_BPCells_matrix_dir.GEX.brain_mouse(["aggregated_GEX_BPCells_matrix_dir.GEX.&lt;aggregation_name&gt;"]):::none
  LSI_BPCells.ATAC.brain_mouse(["LSI_BPCells.ATAC.&lt;aggregation_name&gt;"]):::none --> scDblFinder_results_df.ATAC.brain_mouse(["scDblFinder_results_df.ATAC.&lt;aggregation_name&gt;"]):::none
  combined_BPCells_fragment_obj.ATAC.brain_mouse(["combined_BPCells_fragment_obj.ATAC.&lt;aggregation_name&gt;"]):::none --> harmony_embeddings_matrix.ATAC.brain_mouse(["harmony_embeddings_matrix.ATAC.&lt;aggregation_name&gt;"]):::none
  metadata_w_cell_types_tibble.GEX.brain_mouse(["metadata_w_cell_types_tibble.GEX.&lt;aggregation_name&gt;"]):::none --> harmony_embeddings_matrix.ATAC.brain_mouse(["harmony_embeddings_matrix.ATAC.&lt;aggregation_name&gt;"]):::none
  consensus_peak_GRanges.ATAC.brain_mouse(["consensus_peak_GRanges.ATAC.&lt;aggregation_name&gt;"]):::none --> harmony_embeddings_matrix.ATAC.brain_mouse(["harmony_embeddings_matrix.ATAC.&lt;aggregation_name&gt;"]):::none
  combined_BPCells_fragment_obj.ATAC.brain_mouse(["combined_BPCells_fragment_obj.ATAC.&lt;aggregation_name&gt;"]):::none --> metadata_w_cell_types_tibble.ATAC.brain_mouse(["metadata_w_cell_types_tibble.ATAC.&lt;aggregation_name&gt;"]):::none
  metadata_w_cell_types_tibble.GEX.brain_mouse(["metadata_w_cell_types_tibble.GEX.&lt;aggregation_name&gt;"]):::none --> metadata_w_cell_types_tibble.ATAC.brain_mouse(["metadata_w_cell_types_tibble.ATAC.&lt;aggregation_name&gt;"]):::none
  consensus_peak_GRanges.ATAC.brain_mouse(["consensus_peak_GRanges.ATAC.&lt;aggregation_name&gt;"]):::none --> metadata_w_cell_types_tibble.ATAC.brain_mouse(["metadata_w_cell_types_tibble.ATAC.&lt;aggregation_name&gt;"]):::none
  combined_BPCells_fragment_obj.ATAC.brain_mouse(["combined_BPCells_fragment_obj.ATAC.&lt;aggregation_name&gt;"]):::none --> scDblFinder_results_df.ATAC.brain_mouse(["scDblFinder_results_df.ATAC.&lt;aggregation_name&gt;"]):::none
  metadata_w_cell_types_tibble.GEX.brain_mouse(["metadata_w_cell_types_tibble.GEX.&lt;aggregation_name&gt;"]):::none --> scDblFinder_results_df.ATAC.brain_mouse(["scDblFinder_results_df.ATAC.&lt;aggregation_name&gt;"]):::none
  consensus_peak_GRanges.ATAC.brain_mouse(["consensus_peak_GRanges.ATAC.&lt;aggregation_name&gt;"]):::none --> scDblFinder_results_df.ATAC.brain_mouse(["scDblFinder_results_df.ATAC.&lt;aggregation_name&gt;"]):::none
  UCell_GEX_marker_genes_list.brain_mouse(["UCell_GEX_marker_genes_list.&lt;aggregation_name&gt;"]):::none --> metadata_w_cell_types_tibble.ATAC.brain_mouse(["metadata_w_cell_types_tibble.ATAC.&lt;aggregation_name&gt;"]):::none
  LSI_clusters.ATAC.brain_mouse(["LSI_clusters.ATAC.&lt;aggregation_name&gt;"]):::none --> metadata_w_cell_types_tibble.ATAC.brain_mouse(["metadata_w_cell_types_tibble.ATAC.&lt;aggregation_name&gt;"]):::none
  UMAP_embeddings_tibble.ATAC.brain_mouse(["UMAP_embeddings_tibble.ATAC.&lt;aggregation_name&gt;"]):::none --> metadata_w_cell_types_tibble.ATAC.brain_mouse(["metadata_w_cell_types_tibble.ATAC.&lt;aggregation_name&gt;"]):::none
  UCell_GEX_marker_genes_list.brain_mouse(["UCell_GEX_marker_genes_list.&lt;aggregation_name&gt;"]):::none --> scDblFinder_results_df.ATAC.brain_mouse(["scDblFinder_results_df.ATAC.&lt;aggregation_name&gt;"]):::none
  LSI_clusters.ATAC.brain_mouse(["LSI_clusters.ATAC.&lt;aggregation_name&gt;"]):::none --> scDblFinder_results_df.ATAC.brain_mouse(["scDblFinder_results_df.ATAC.&lt;aggregation_name&gt;"]):::none
  UMAP_embeddings_tibble.ATAC.brain_mouse(["UMAP_embeddings_tibble.ATAC.&lt;aggregation_name&gt;"]):::none --> scDblFinder_results_df.ATAC.brain_mouse(["scDblFinder_results_df.ATAC.&lt;aggregation_name&gt;"]):::none
  UCell_GEX_marker_genes_list.brain_mouse(["UCell_GEX_marker_genes_list.&lt;aggregation_name&gt;"]):::none --> metadata_w_cell_types_tibble.GEX.brain_mouse(["metadata_w_cell_types_tibble.GEX.&lt;aggregation_name&gt;"]):::none
  UMAP_embeddings_tibble.GEX.brain_mouse(["UMAP_embeddings_tibble.GEX.&lt;aggregation_name&gt;"]):::none --> metadata_w_cell_types_tibble.GEX.brain_mouse(["metadata_w_cell_types_tibble.GEX.&lt;aggregation_name&gt;"]):::none
  UMAP_embeddings_tibble.GEX_non_harmony.brain_mouse(["UMAP_embeddings_tibble.GEX_non_harmony.&lt;aggregation_name&gt;"]):::none --> metadata_w_cell_types_tibble.GEX.brain_mouse(["metadata_w_cell_types_tibble.GEX.&lt;aggregation_name&gt;"]):::none
  metadata_tibble.GEX.brain_mouse(["metadata_tibble.GEX.&lt;aggregation_name&gt;"]):::none --> metadata_w_cell_types_tibble.GEX.brain_mouse(["metadata_w_cell_types_tibble.GEX.&lt;aggregation_name&gt;"]):::none
  PCA_clusters.GEX.brain_mouse(["PCA_clusters.GEX.&lt;aggregation_name&gt;"]):::none --> metadata_w_cell_types_tibble.GEX.brain_mouse(["metadata_w_cell_types_tibble.GEX.&lt;aggregation_name&gt;"]):::none
  UCell_GEX_marker_genes_list.brain_mouse(["UCell_GEX_marker_genes_list.&lt;aggregation_name&gt;"]):::none --> scDblFinder_results_df.GEX.brain_mouse(["scDblFinder_results_df.GEX.&lt;aggregation_name&gt;"]):::none
  UMAP_embeddings_tibble.GEX.brain_mouse(["UMAP_embeddings_tibble.GEX.&lt;aggregation_name&gt;"]):::none --> scDblFinder_results_df.GEX.brain_mouse(["scDblFinder_results_df.GEX.&lt;aggregation_name&gt;"]):::none
  UMAP_embeddings_tibble.GEX_non_harmony.brain_mouse(["UMAP_embeddings_tibble.GEX_non_harmony.&lt;aggregation_name&gt;"]):::none --> scDblFinder_results_df.GEX.brain_mouse(["scDblFinder_results_df.GEX.&lt;aggregation_name&gt;"]):::none
  metadata_tibble.GEX.brain_mouse(["metadata_tibble.GEX.&lt;aggregation_name&gt;"]):::none --> scDblFinder_results_df.GEX.brain_mouse(["scDblFinder_results_df.GEX.&lt;aggregation_name&gt;"]):::none
  PCA_clusters.GEX.brain_mouse(["PCA_clusters.GEX.&lt;aggregation_name&gt;"]):::none --> scDblFinder_results_df.GEX.brain_mouse(["scDblFinder_results_df.GEX.&lt;aggregation_name&gt;"]):::none
  WNN_results.brain_mouse(["WNN_results.&lt;aggregation_name&gt;"]):::none --> metadata_w_cell_types_tibble.WNN.brain_mouse(["metadata_w_cell_types_tibble.WNN.&lt;aggregation_name&gt;"]):::none
  UMAP_embeddings_tibble.GEX.brain_mouse(["UMAP_embeddings_tibble.GEX.&lt;aggregation_name&gt;"]):::none --> metadata_w_cell_types_tibble.WNN.brain_mouse(["metadata_w_cell_types_tibble.WNN.&lt;aggregation_name&gt;"]):::none
  clusters_tibble.WNN.brain_mouse(["clusters_tibble.WNN.&lt;aggregation_name&gt;"]):::none --> metadata_w_cell_types_tibble.WNN.brain_mouse(["metadata_w_cell_types_tibble.WNN.&lt;aggregation_name&gt;"]):::none
  metadata_w_cell_types_tibble.ATAC.brain_mouse(["metadata_w_cell_types_tibble.ATAC.&lt;aggregation_name&gt;"]):::none --> metadata_w_cell_types_tibble.WNN.brain_mouse(["metadata_w_cell_types_tibble.WNN.&lt;aggregation_name&gt;"]):::none
  UMAP_embeddings_tibble.WNN.brain_mouse(["UMAP_embeddings_tibble.WNN.&lt;aggregation_name&gt;"]):::none --> metadata_w_cell_types_tibble.WNN.brain_mouse(["metadata_w_cell_types_tibble.WNN.&lt;aggregation_name&gt;"]):::none
  combined_BPCells_fragment_obj.ATAC.brain_mouse(["combined_BPCells_fragment_obj.ATAC.&lt;aggregation_name&gt;"]):::none --> LSI_BPCells.ATAC.brain_mouse(["LSI_BPCells.ATAC.&lt;aggregation_name&gt;"]):::none
  metadata_w_cell_types_tibble.GEX.brain_mouse(["metadata_w_cell_types_tibble.GEX.&lt;aggregation_name&gt;"]):::none --> LSI_BPCells.ATAC.brain_mouse(["LSI_BPCells.ATAC.&lt;aggregation_name&gt;"]):::none
  consensus_peak_GRanges.ATAC.brain_mouse(["consensus_peak_GRanges.ATAC.&lt;aggregation_name&gt;"]):::none --> LSI_BPCells.ATAC.brain_mouse(["LSI_BPCells.ATAC.&lt;aggregation_name&gt;"]):::none
  ATAC_marker_TFs_list.brain_mouse(["ATAC_marker_TFs_list.&lt;aggregation_name&gt;"]):::none --> TF_activity_BPCells_matrix_dir.ATAC.brain_mouse(["TF_activity_BPCells_matrix_dir.ATAC.&lt;aggregation_name&gt;"]):::none
  metadata_w_cell_types_tibble.GEX.brain_mouse(["metadata_w_cell_types_tibble.GEX.&lt;aggregation_name&gt;"]):::none --> within_clusters_collapsed_peaks_per_cluster_GRanges.ATAC.brain_mouse["within_clusters_collapsed_peaks_per_cluster_GRanges.ATAC.&lt;aggregation_name&gt;"]:::none
  peaks_per_cluster_narrowPeaks.peaks.ATAC.brain_mouse["peaks_per_cluster_narrowPeaks.peaks.ATAC.&lt;aggregation_name&gt;"]:::none --> within_clusters_collapsed_peaks_per_cluster_GRanges.ATAC.brain_mouse["within_clusters_collapsed_peaks_per_cluster_GRanges.ATAC.&lt;aggregation_name&gt;"]:::none
