%%{init: {'flowchart': {'defaultRenderer': 'elk'}}}%%
flowchart TB
    harmony_embeddings_matrix.ATAC.brain_mouse(["harmony_embeddings_matrix.ATAC.brain_mouse"]):::none --> embedding_matrices.WNN.brain_mouse(["embedding_matrices.WNN.brain_mouse"]):::none
    metadata_w_cell_types_tibble.ATAC.brain_mouse(["metadata_w_cell_types_tibble.ATAC.brain_mouse"]):::none --> embedding_matrices.WNN.brain_mouse(["embedding_matrices.WNN.brain_mouse"]):::none
    harmony_embeddings_matrix.GEX.brain_mouse(["harmony_embeddings_matrix.GEX.brain_mouse"]):::none --> embedding_matrices.WNN.brain_mouse(["embedding_matrices.WNN.brain_mouse"]):::none
    UCell_GEX_marker_genes_list.brain_mouse(["UCell_GEX_marker_genes_list.brain_mouse"]):::none --> metadata_w_cell_types_tibble.WNN.brain_mouse(["metadata_w_cell_types_tibble.WNN.brain_mouse"]):::none
    WNN_results.brain_mouse(["WNN_results.brain_mouse"]):::none --> UMAP_embeddings_tibble.WNN.brain_mouse(["UMAP_embeddings_tibble.WNN.brain_mouse"]):::none
    clusters_tibble.WNN.brain_mouse(["clusters_tibble.WNN.brain_mouse"]):::none --> WNN_results.brain_mouse(["WNN_results.brain_mouse"]):::none
    embedding_matrices.WNN.brain_mouse(["embedding_matrices.WNN.brain_mouse"]):::none --> WNN_results.brain_mouse(["WNN_results.brain_mouse"]):::none
    UCell_GEX_marker_genes_list.brain_mouse(["UCell_GEX_marker_genes_list.brain_mouse"]):::none --> harmony_embeddings_matrix.ATAC.brain_mouse(["harmony_embeddings_matrix.ATAC.brain_mouse"]):::none
    UCell_GEX_marker_genes_list.brain_mouse(["UCell_GEX_marker_genes_list.brain_mouse"]):::none --> metadata_w_cell_types_tibble.ATAC.brain_mouse(["metadata_w_cell_types_tibble.ATAC.brain_mouse"]):::none
    UMAP_embeddings_tibble.WNN.brain_mouse(["UMAP_embeddings_tibble.WNN.brain_mouse"]):::none --> metadata_w_cell_types_tibble.WNN.brain_mouse(["metadata_w_cell_types_tibble.WNN.brain_mouse"]):::none
    WNN_results.brain_mouse(["WNN_results.brain_mouse"]):::none --> metadata_w_cell_types_tibble.WNN.brain_mouse(["metadata_w_cell_types_tibble.WNN.brain_mouse"]):::none
    clusters_tibble.WNN.brain_mouse(["clusters_tibble.WNN.brain_mouse"]):::none --> metadata_w_cell_types_tibble.WNN.brain_mouse(["metadata_w_cell_types_tibble.WNN.brain_mouse"]):::none
    embedding_matrices.WNN.brain_mouse(["embedding_matrices.WNN.brain_mouse"]):::none --> clusters_tibble.WNN.brain_mouse(["clusters_tibble.WNN.brain_mouse"]):::none
    harmony_embeddings_matrix.ATAC.brain_mouse(["harmony_embeddings_matrix.ATAC.brain_mouse"]):::none --> metadata_w_cell_types_tibble.ATAC.brain_mouse(["metadata_w_cell_types_tibble.ATAC.brain_mouse"]):::none
    harmony_embeddings_matrix.GEX.brain_mouse(["harmony_embeddings_matrix.GEX.brain_mouse"]):::none --> harmony_embeddings_matrix.ATAC.brain_mouse(["harmony_embeddings_matrix.ATAC.brain_mouse"]):::none
    harmony_embeddings_matrix.GEX.brain_mouse(["harmony_embeddings_matrix.GEX.brain_mouse"]):::none --> metadata_w_cell_types_tibble.ATAC.brain_mouse(["metadata_w_cell_types_tibble.ATAC.brain_mouse"]):::none
    harmony_embeddings_matrix.GEX.brain_mouse(["harmony_embeddings_matrix.GEX.brain_mouse"]):::none --> metadata_w_cell_types_tibble.WNN.brain_mouse(["metadata_w_cell_types_tibble.WNN.brain_mouse"]):::none
    metadata_w_cell_types_tibble.ATAC.brain_mouse(["metadata_w_cell_types_tibble.ATAC.brain_mouse"]):::none --> metadata_w_cell_types_tibble.WNN.brain_mouse(["metadata_w_cell_types_tibble.WNN.brain_mouse"]):::none
