%%{init: {'flowchart': {'defaultRenderer': 'elk'}}}%%
flowchart TB
  WNN_results.subgroups.brain_mouse["WNN_results.subgroups"]:::none --> clusters_tibble.WNN.subgroups.brain_mouse["clusters_tibble.WNN.subgroups"]:::none
  WNN_results.subgroups.immune_human_2x["WNN_results.subgroups"]:::none --> clusters_tibble.WNN.subgroups.immune_human_2x["clusters_tibble.WNN.subgroups"]:::none
  WNN_results.subgroups.PBMC_human_6x["WNN_results.subgroups"]:::none --> clusters_tibble.WNN.subgroups.PBMC_human_6x["clusters_tibble.WNN.subgroups"]:::none
  harmony_embeddings_matrix.GEX.brain_mouse(["harmony_embeddings_matrix.GEX"]):::none --> embedding_matrices.WNN.brain_mouse(["embedding_matrices.WNN"]):::none
  harmony_embeddings_matrix.ATAC.brain_mouse(["harmony_embeddings_matrix.ATAC"]):::none --> embedding_matrices.WNN.brain_mouse(["embedding_matrices.WNN"]):::none
  metadata_w_cell_types_tibble.ATAC.brain_mouse(["metadata_w_cell_types_tibble.ATAC"]):::none --> embedding_matrices.WNN.brain_mouse(["embedding_matrices.WNN"]):::none
  harmony_embeddings_matrix.GEX.immune_human_2x(["harmony_embeddings_matrix.GEX"]):::none --> embedding_matrices.WNN.immune_human_2x(["embedding_matrices.WNN"]):::none
  metadata_w_cell_types_tibble.ATAC.immune_human_2x(["metadata_w_cell_types_tibble.ATAC"]):::none --> embedding_matrices.WNN.immune_human_2x(["embedding_matrices.WNN"]):::none
  harmony_embeddings_matrix.ATAC.immune_human_2x(["harmony_embeddings_matrix.ATAC"]):::none --> embedding_matrices.WNN.immune_human_2x(["embedding_matrices.WNN"]):::none
  metadata_w_cell_types_tibble.ATAC.PBMC_human_6x(["metadata_w_cell_types_tibble.ATAC"]):::none --> embedding_matrices.WNN.PBMC_human_6x(["embedding_matrices.WNN"]):::none
  harmony_embeddings_matrix.GEX.PBMC_human_6x(["harmony_embeddings_matrix.GEX"]):::none --> embedding_matrices.WNN.PBMC_human_6x(["embedding_matrices.WNN"]):::none
  harmony_embeddings_matrix.ATAC.PBMC_human_6x(["harmony_embeddings_matrix.ATAC"]):::none --> embedding_matrices.WNN.PBMC_human_6x(["embedding_matrices.WNN"]):::none
  UCell_GEX_marker_genes_list.brain_mouse(["UCell_GEX_marker_genes_list"]):::none --> metadata_w_cell_types_tibble.WNN.brain_mouse(["metadata_w_cell_types_tibble.WNN"]):::none
  UCell_GEX_marker_genes_list.immune_human_2x(["UCell_GEX_marker_genes_list"]):::none --> metadata_w_cell_types_tibble.WNN.immune_human_2x(["metadata_w_cell_types_tibble.WNN"]):::none
  UCell_GEX_marker_genes_list.PBMC_human_6x(["UCell_GEX_marker_genes_list"]):::none --> metadata_w_cell_types_tibble.WNN.PBMC_human_6x(["metadata_w_cell_types_tibble.WNN"]):::none
  WNN_results.brain_mouse(["WNN_results"]):::none --> UMAP_embeddings_tibble.WNN.brain_mouse(["UMAP_embeddings_tibble.WNN"]):::none
  WNN_results.immune_human_2x(["WNN_results"]):::none --> UMAP_embeddings_tibble.WNN.immune_human_2x(["UMAP_embeddings_tibble.WNN"]):::none
  WNN_results.PBMC_human_6x(["WNN_results"]):::none --> UMAP_embeddings_tibble.WNN.PBMC_human_6x(["UMAP_embeddings_tibble.WNN"]):::none
  WNN_results.subgroups.brain_mouse["WNN_results.subgroups"]:::none --> UMAP_embeddings_tibble.WNN.subgroups.brain_mouse["UMAP_embeddings_tibble.WNN.subgroups"]:::none
  WNN_results.subgroups.immune_human_2x["WNN_results.subgroups"]:::none --> UMAP_embeddings_tibble.WNN.subgroups.immune_human_2x["UMAP_embeddings_tibble.WNN.subgroups"]:::none
  WNN_results.subgroups.PBMC_human_6x["WNN_results.subgroups"]:::none --> UMAP_embeddings_tibble.WNN.subgroups.PBMC_human_6x["UMAP_embeddings_tibble.WNN.subgroups"]:::none
  clusters_tibble.WNN.brain_mouse(["clusters_tibble.WNN"]):::none --> WNN_results.brain_mouse(["WNN_results"]):::none
  embedding_matrices.WNN.brain_mouse(["embedding_matrices.WNN"]):::none --> WNN_results.brain_mouse(["WNN_results"]):::none
  embedding_matrices.WNN.immune_human_2x(["embedding_matrices.WNN"]):::none --> WNN_results.immune_human_2x(["WNN_results"]):::none
  clusters_tibble.WNN.immune_human_2x(["clusters_tibble.WNN"]):::none --> WNN_results.immune_human_2x(["WNN_results"]):::none
  embedding_matrices.WNN.PBMC_human_6x(["embedding_matrices.WNN"]):::none --> WNN_results.PBMC_human_6x(["WNN_results"]):::none
  clusters_tibble.WNN.PBMC_human_6x(["clusters_tibble.WNN"]):::none --> WNN_results.PBMC_human_6x(["WNN_results"]):::none
  UCell_GEX_marker_genes_list.brain_mouse(["UCell_GEX_marker_genes_list"]):::none --> harmony_embeddings_matrix.ATAC.brain_mouse(["harmony_embeddings_matrix.ATAC"]):::none
  harmony_embeddings_matrix.GEX.brain_mouse(["harmony_embeddings_matrix.GEX"]):::none --> harmony_embeddings_matrix.ATAC.brain_mouse(["harmony_embeddings_matrix.ATAC"]):::none
  UCell_GEX_marker_genes_list.brain_mouse(["UCell_GEX_marker_genes_list"]):::none --> harmony_embeddings_matrix.ATAC.subgroups.brain_mouse["harmony_embeddings_matrix.ATAC.subgroups"]:::none
  harmony_embeddings_matrix.GEX.brain_mouse(["harmony_embeddings_matrix.GEX"]):::none --> harmony_embeddings_matrix.ATAC.subgroups.brain_mouse["harmony_embeddings_matrix.ATAC.subgroups"]:::none
  UCell_GEX_marker_genes_list.brain_mouse(["UCell_GEX_marker_genes_list"]):::none --> metadata_w_cell_types_tibble.ATAC.brain_mouse(["metadata_w_cell_types_tibble.ATAC"]):::none
  harmony_embeddings_matrix.GEX.brain_mouse(["harmony_embeddings_matrix.GEX"]):::none --> metadata_w_cell_types_tibble.ATAC.brain_mouse(["metadata_w_cell_types_tibble.ATAC"]):::none
  UCell_GEX_marker_genes_list.immune_human_2x(["UCell_GEX_marker_genes_list"]):::none --> harmony_embeddings_matrix.ATAC.immune_human_2x(["harmony_embeddings_matrix.ATAC"]):::none
  harmony_embeddings_matrix.GEX.immune_human_2x(["harmony_embeddings_matrix.GEX"]):::none --> harmony_embeddings_matrix.ATAC.immune_human_2x(["harmony_embeddings_matrix.ATAC"]):::none
  UCell_GEX_marker_genes_list.immune_human_2x(["UCell_GEX_marker_genes_list"]):::none --> harmony_embeddings_matrix.ATAC.subgroups.immune_human_2x["harmony_embeddings_matrix.ATAC.subgroups"]:::none
  harmony_embeddings_matrix.GEX.immune_human_2x(["harmony_embeddings_matrix.GEX"]):::none --> harmony_embeddings_matrix.ATAC.subgroups.immune_human_2x["harmony_embeddings_matrix.ATAC.subgroups"]:::none
  UCell_GEX_marker_genes_list.immune_human_2x(["UCell_GEX_marker_genes_list"]):::none --> metadata_w_cell_types_tibble.ATAC.immune_human_2x(["metadata_w_cell_types_tibble.ATAC"]):::none
  harmony_embeddings_matrix.GEX.immune_human_2x(["harmony_embeddings_matrix.GEX"]):::none --> metadata_w_cell_types_tibble.ATAC.immune_human_2x(["metadata_w_cell_types_tibble.ATAC"]):::none
  UCell_GEX_marker_genes_list.PBMC_human_6x(["UCell_GEX_marker_genes_list"]):::none --> harmony_embeddings_matrix.ATAC.PBMC_human_6x(["harmony_embeddings_matrix.ATAC"]):::none
  harmony_embeddings_matrix.GEX.PBMC_human_6x(["harmony_embeddings_matrix.GEX"]):::none --> harmony_embeddings_matrix.ATAC.PBMC_human_6x(["harmony_embeddings_matrix.ATAC"]):::none
  UCell_GEX_marker_genes_list.PBMC_human_6x(["UCell_GEX_marker_genes_list"]):::none --> harmony_embeddings_matrix.ATAC.subgroups.PBMC_human_6x["harmony_embeddings_matrix.ATAC.subgroups"]:::none
  harmony_embeddings_matrix.GEX.PBMC_human_6x(["harmony_embeddings_matrix.GEX"]):::none --> harmony_embeddings_matrix.ATAC.subgroups.PBMC_human_6x["harmony_embeddings_matrix.ATAC.subgroups"]:::none
  UCell_GEX_marker_genes_list.PBMC_human_6x(["UCell_GEX_marker_genes_list"]):::none --> metadata_w_cell_types_tibble.ATAC.PBMC_human_6x(["metadata_w_cell_types_tibble.ATAC"]):::none
  harmony_embeddings_matrix.GEX.PBMC_human_6x(["harmony_embeddings_matrix.GEX"]):::none --> metadata_w_cell_types_tibble.ATAC.PBMC_human_6x(["metadata_w_cell_types_tibble.ATAC"]):::none
  embedding_matrices.WNN.brain_mouse(["embedding_matrices.WNN"]):::none --> clusters_tibble.WNN.brain_mouse(["clusters_tibble.WNN"]):::none
  embedding_matrices.WNN.immune_human_2x(["embedding_matrices.WNN"]):::none --> clusters_tibble.WNN.immune_human_2x(["clusters_tibble.WNN"]):::none
  embedding_matrices.WNN.PBMC_human_6x(["embedding_matrices.WNN"]):::none --> clusters_tibble.WNN.PBMC_human_6x(["clusters_tibble.WNN"]):::none
  harmony_embeddings_matrix.ATAC.subgroups.brain_mouse["harmony_embeddings_matrix.ATAC.subgroups"]:::none --> WNN_results.subgroups.brain_mouse["WNN_results.subgroups"]:::none
  harmony_embeddings_matrix.GEX.subgroups.brain_mouse["harmony_embeddings_matrix.GEX.subgroups"]:::none --> WNN_results.subgroups.brain_mouse["WNN_results.subgroups"]:::none
  metadata_w_cell_types_tibble.WNN.brain_mouse(["metadata_w_cell_types_tibble.WNN"]):::none --> WNN_results.subgroups.brain_mouse["WNN_results.subgroups"]:::none
  harmony_embeddings_matrix.GEX.subgroups.immune_human_2x["harmony_embeddings_matrix.GEX.subgroups"]:::none --> WNN_results.subgroups.immune_human_2x["WNN_results.subgroups"]:::none
  harmony_embeddings_matrix.ATAC.subgroups.immune_human_2x["harmony_embeddings_matrix.ATAC.subgroups"]:::none --> WNN_results.subgroups.immune_human_2x["WNN_results.subgroups"]:::none
  metadata_w_cell_types_tibble.WNN.immune_human_2x(["metadata_w_cell_types_tibble.WNN"]):::none --> WNN_results.subgroups.immune_human_2x["WNN_results.subgroups"]:::none
  harmony_embeddings_matrix.GEX.subgroups.PBMC_human_6x["harmony_embeddings_matrix.GEX.subgroups"]:::none --> WNN_results.subgroups.PBMC_human_6x["WNN_results.subgroups"]:::none
  harmony_embeddings_matrix.ATAC.subgroups.PBMC_human_6x["harmony_embeddings_matrix.ATAC.subgroups"]:::none --> WNN_results.subgroups.PBMC_human_6x["WNN_results.subgroups"]:::none
  metadata_w_cell_types_tibble.WNN.PBMC_human_6x(["metadata_w_cell_types_tibble.WNN"]):::none --> WNN_results.subgroups.PBMC_human_6x["WNN_results.subgroups"]:::none
  metadata_w_cell_types_tibble.WNN.brain_mouse(["metadata_w_cell_types_tibble.WNN"]):::none --> harmony_embeddings_matrix.ATAC.subgroups.brain_mouse["harmony_embeddings_matrix.ATAC.subgroups"]:::none
  metadata_w_cell_types_tibble.WNN.immune_human_2x(["metadata_w_cell_types_tibble.WNN"]):::none --> harmony_embeddings_matrix.ATAC.subgroups.immune_human_2x["harmony_embeddings_matrix.ATAC.subgroups"]:::none
  metadata_w_cell_types_tibble.WNN.PBMC_human_6x(["metadata_w_cell_types_tibble.WNN"]):::none --> harmony_embeddings_matrix.ATAC.subgroups.PBMC_human_6x["harmony_embeddings_matrix.ATAC.subgroups"]:::none
  harmony_embeddings_matrix.ATAC.brain_mouse(["harmony_embeddings_matrix.ATAC"]):::none --> metadata_w_cell_types_tibble.ATAC.brain_mouse(["metadata_w_cell_types_tibble.ATAC"]):::none
  harmony_embeddings_matrix.ATAC.immune_human_2x(["harmony_embeddings_matrix.ATAC"]):::none --> metadata_w_cell_types_tibble.ATAC.immune_human_2x(["metadata_w_cell_types_tibble.ATAC"]):::none
  harmony_embeddings_matrix.ATAC.PBMC_human_6x(["harmony_embeddings_matrix.ATAC"]):::none --> metadata_w_cell_types_tibble.ATAC.PBMC_human_6x(["metadata_w_cell_types_tibble.ATAC"]):::none
  metadata_w_cell_types_tibble.WNN.brain_mouse(["metadata_w_cell_types_tibble.WNN"]):::none --> harmony_embeddings_matrix.GEX.subgroups.brain_mouse["harmony_embeddings_matrix.GEX.subgroups"]:::none
  metadata_w_cell_types_tibble.WNN.immune_human_2x(["metadata_w_cell_types_tibble.WNN"]):::none --> harmony_embeddings_matrix.GEX.subgroups.immune_human_2x["harmony_embeddings_matrix.GEX.subgroups"]:::none
  metadata_w_cell_types_tibble.WNN.PBMC_human_6x(["metadata_w_cell_types_tibble.WNN"]):::none --> harmony_embeddings_matrix.GEX.subgroups.PBMC_human_6x["harmony_embeddings_matrix.GEX.subgroups"]:::none
  UMAP_embeddings_tibble.WNN.brain_mouse(["UMAP_embeddings_tibble.WNN"]):::none --> metadata_w_cell_types_tibble.WNN.brain_mouse(["metadata_w_cell_types_tibble.WNN"]):::none
  clusters_tibble.WNN.brain_mouse(["clusters_tibble.WNN"]):::none --> metadata_w_cell_types_tibble.WNN.brain_mouse(["metadata_w_cell_types_tibble.WNN"]):::none
  metadata_w_cell_types_tibble.ATAC.brain_mouse(["metadata_w_cell_types_tibble.ATAC"]):::none --> metadata_w_cell_types_tibble.WNN.brain_mouse(["metadata_w_cell_types_tibble.WNN"]):::none
  WNN_results.brain_mouse(["WNN_results"]):::none --> metadata_w_cell_types_tibble.WNN.brain_mouse(["metadata_w_cell_types_tibble.WNN"]):::none
  harmony_embeddings_matrix.GEX.brain_mouse(["harmony_embeddings_matrix.GEX"]):::none --> metadata_w_cell_types_tibble.WNN.brain_mouse(["metadata_w_cell_types_tibble.WNN"]):::none
  WNN_results.immune_human_2x(["WNN_results"]):::none --> metadata_w_cell_types_tibble.WNN.immune_human_2x(["metadata_w_cell_types_tibble.WNN"]):::none
  clusters_tibble.WNN.immune_human_2x(["clusters_tibble.WNN"]):::none --> metadata_w_cell_types_tibble.WNN.immune_human_2x(["metadata_w_cell_types_tibble.WNN"]):::none
  UMAP_embeddings_tibble.WNN.immune_human_2x(["UMAP_embeddings_tibble.WNN"]):::none --> metadata_w_cell_types_tibble.WNN.immune_human_2x(["metadata_w_cell_types_tibble.WNN"]):::none
  metadata_w_cell_types_tibble.ATAC.immune_human_2x(["metadata_w_cell_types_tibble.ATAC"]):::none --> metadata_w_cell_types_tibble.WNN.immune_human_2x(["metadata_w_cell_types_tibble.WNN"]):::none
  harmony_embeddings_matrix.GEX.immune_human_2x(["harmony_embeddings_matrix.GEX"]):::none --> metadata_w_cell_types_tibble.WNN.immune_human_2x(["metadata_w_cell_types_tibble.WNN"]):::none
  metadata_w_cell_types_tibble.ATAC.PBMC_human_6x(["metadata_w_cell_types_tibble.ATAC"]):::none --> metadata_w_cell_types_tibble.WNN.PBMC_human_6x(["metadata_w_cell_types_tibble.WNN"]):::none
  UMAP_embeddings_tibble.WNN.PBMC_human_6x(["UMAP_embeddings_tibble.WNN"]):::none --> metadata_w_cell_types_tibble.WNN.PBMC_human_6x(["metadata_w_cell_types_tibble.WNN"]):::none
  clusters_tibble.WNN.PBMC_human_6x(["clusters_tibble.WNN"]):::none --> metadata_w_cell_types_tibble.WNN.PBMC_human_6x(["metadata_w_cell_types_tibble.WNN"]):::none
  WNN_results.PBMC_human_6x(["WNN_results"]):::none --> metadata_w_cell_types_tibble.WNN.PBMC_human_6x(["metadata_w_cell_types_tibble.WNN"]):::none
  harmony_embeddings_matrix.GEX.PBMC_human_6x(["harmony_embeddings_matrix.GEX"]):::none --> metadata_w_cell_types_tibble.WNN.PBMC_human_6x(["metadata_w_cell_types_tibble.WNN"]):::none
