%%{init: {'flowchart': {'defaultRenderer': 'elk'}}}%%
flowchart TB
  harmony_embeddings_matrix.ATAC.muscle(["harmony_embeddings_matrix.ATAC.&lt;dataset_name&gt;"]):::none --> embedding_matrices.WNN.muscle(["embedding_matrices.WNN.&lt;dataset_name&gt;"]):::none
  metadata_w_cell_types_tibble.ATAC.muscle(["metadata_w_cell_types_tibble.ATAC.&lt;dataset_name&gt;"]):::none --> embedding_matrices.WNN.muscle(["embedding_matrices.WNN.&lt;dataset_name&gt;"]):::none
  harmony_embeddings_matrix.GEX.muscle(["harmony_embeddings_matrix.GEX.&lt;dataset_name&gt;"]):::none --> embedding_matrices.WNN.muscle(["embedding_matrices.WNN.&lt;dataset_name&gt;"]):::none
  harmony_embeddings_matrix.GEX.muscle_test(["harmony_embeddings_matrix.GEX.&lt;aggregation_name&gt;"]):::none --> embedding_matrices.WNN.muscle_test(["embedding_matrices.WNN.&lt;aggregation_name&gt;"]):::none
  harmony_embeddings_matrix.ATAC.muscle_test(["harmony_embeddings_matrix.ATAC.&lt;aggregation_name&gt;"]):::none --> embedding_matrices.WNN.muscle_test(["embedding_matrices.WNN.&lt;aggregation_name&gt;"]):::none
  metadata_w_cell_types_tibble.ATAC.muscle_test(["metadata_w_cell_types_tibble.ATAC.&lt;aggregation_name&gt;"]):::none --> embedding_matrices.WNN.muscle_test(["embedding_matrices.WNN.&lt;aggregation_name&gt;"]):::none
  UCell_GEX_marker_genes_list.muscle(["UCell_GEX_marker_genes_list.&lt;dataset_name&gt;"]):::none --> metadata_w_cell_types_tibble.WNN.muscle(["metadata_w_cell_types_tibble.WNN.&lt;dataset_name&gt;"]):::none
  UCell_GEX_marker_genes_list.muscle_test(["UCell_GEX_marker_genes_list.&lt;aggregation_name&gt;"]):::none --> metadata_w_cell_types_tibble.WNN.muscle_test(["metadata_w_cell_types_tibble.WNN.&lt;aggregation_name&gt;"]):::none
  WNN_results.muscle(["WNN_results.&lt;dataset_name&gt;"]):::none --> UMAP_embeddings_tibble.WNN.muscle(["UMAP_embeddings_tibble.WNN.&lt;dataset_name&gt;"]):::none
  WNN_results.muscle_test(["WNN_results.&lt;aggregation_name&gt;"]):::none --> UMAP_embeddings_tibble.WNN.muscle_test(["UMAP_embeddings_tibble.WNN.&lt;aggregation_name&gt;"]):::none
  clusters_tibble.WNN.muscle(["clusters_tibble.WNN.&lt;dataset_name&gt;"]):::none --> WNN_results.muscle(["WNN_results.&lt;dataset_name&gt;"]):::none
  embedding_matrices.WNN.muscle(["embedding_matrices.WNN.&lt;dataset_name&gt;"]):::none --> WNN_results.muscle(["WNN_results.&lt;dataset_name&gt;"]):::none
  embedding_matrices.WNN.muscle_test(["embedding_matrices.WNN.&lt;aggregation_name&gt;"]):::none --> WNN_results.muscle_test(["WNN_results.&lt;aggregation_name&gt;"]):::none
  clusters_tibble.WNN.muscle_test(["clusters_tibble.WNN.&lt;aggregation_name&gt;"]):::none --> WNN_results.muscle_test(["WNN_results.&lt;aggregation_name&gt;"]):::none
  UCell_GEX_marker_genes_list.muscle(["UCell_GEX_marker_genes_list.&lt;dataset_name&gt;"]):::none --> harmony_embeddings_matrix.ATAC.muscle(["harmony_embeddings_matrix.ATAC.&lt;dataset_name&gt;"]):::none
  harmony_embeddings_matrix.GEX.muscle(["harmony_embeddings_matrix.GEX.&lt;dataset_name&gt;"]):::none --> harmony_embeddings_matrix.ATAC.muscle(["harmony_embeddings_matrix.ATAC.&lt;dataset_name&gt;"]):::none
  UCell_GEX_marker_genes_list.muscle(["UCell_GEX_marker_genes_list.&lt;dataset_name&gt;"]):::none --> metadata_w_cell_types_tibble.ATAC.muscle(["metadata_w_cell_types_tibble.ATAC.&lt;dataset_name&gt;"]):::none
  harmony_embeddings_matrix.GEX.muscle(["harmony_embeddings_matrix.GEX.&lt;dataset_name&gt;"]):::none --> metadata_w_cell_types_tibble.ATAC.muscle(["metadata_w_cell_types_tibble.ATAC.&lt;dataset_name&gt;"]):::none
  UCell_GEX_marker_genes_list.muscle_test(["UCell_GEX_marker_genes_list.&lt;aggregation_name&gt;"]):::none --> harmony_embeddings_matrix.ATAC.muscle_test(["harmony_embeddings_matrix.ATAC.&lt;aggregation_name&gt;"]):::none
  harmony_embeddings_matrix.GEX.muscle_test(["harmony_embeddings_matrix.GEX.&lt;aggregation_name&gt;"]):::none --> harmony_embeddings_matrix.ATAC.muscle_test(["harmony_embeddings_matrix.ATAC.&lt;aggregation_name&gt;"]):::none
  UCell_GEX_marker_genes_list.muscle_test(["UCell_GEX_marker_genes_list.&lt;aggregation_name&gt;"]):::none --> metadata_w_cell_types_tibble.ATAC.muscle_test(["metadata_w_cell_types_tibble.ATAC.&lt;aggregation_name&gt;"]):::none
  harmony_embeddings_matrix.GEX.muscle_test(["harmony_embeddings_matrix.GEX.&lt;aggregation_name&gt;"]):::none --> metadata_w_cell_types_tibble.ATAC.muscle_test(["metadata_w_cell_types_tibble.ATAC.&lt;aggregation_name&gt;"]):::none
  embedding_matrices.WNN.muscle(["embedding_matrices.WNN.&lt;dataset_name&gt;"]):::none --> clusters_tibble.WNN.muscle(["clusters_tibble.WNN.&lt;dataset_name&gt;"]):::none
  embedding_matrices.WNN.muscle_test(["embedding_matrices.WNN.&lt;aggregation_name&gt;"]):::none --> clusters_tibble.WNN.muscle_test(["clusters_tibble.WNN.&lt;aggregation_name&gt;"]):::none
  harmony_embeddings_matrix.ATAC.muscle(["harmony_embeddings_matrix.ATAC.&lt;dataset_name&gt;"]):::none --> metadata_w_cell_types_tibble.ATAC.muscle(["metadata_w_cell_types_tibble.ATAC.&lt;dataset_name&gt;"]):::none
  harmony_embeddings_matrix.ATAC.muscle_test(["harmony_embeddings_matrix.ATAC.&lt;aggregation_name&gt;"]):::none --> metadata_w_cell_types_tibble.ATAC.muscle_test(["metadata_w_cell_types_tibble.ATAC.&lt;aggregation_name&gt;"]):::none
  metadata_w_cell_types_tibble.ATAC.muscle(["metadata_w_cell_types_tibble.ATAC.&lt;dataset_name&gt;"]):::none --> metadata_w_cell_types_tibble.WNN.muscle(["metadata_w_cell_types_tibble.WNN.&lt;dataset_name&gt;"]):::none
  WNN_results.muscle(["WNN_results.&lt;dataset_name&gt;"]):::none --> metadata_w_cell_types_tibble.WNN.muscle(["metadata_w_cell_types_tibble.WNN.&lt;dataset_name&gt;"]):::none
  UMAP_embeddings_tibble.WNN.muscle(["UMAP_embeddings_tibble.WNN.&lt;dataset_name&gt;"]):::none --> metadata_w_cell_types_tibble.WNN.muscle(["metadata_w_cell_types_tibble.WNN.&lt;dataset_name&gt;"]):::none
  clusters_tibble.WNN.muscle(["clusters_tibble.WNN.&lt;dataset_name&gt;"]):::none --> metadata_w_cell_types_tibble.WNN.muscle(["metadata_w_cell_types_tibble.WNN.&lt;dataset_name&gt;"]):::none
  harmony_embeddings_matrix.GEX.muscle(["harmony_embeddings_matrix.GEX.&lt;dataset_name&gt;"]):::none --> metadata_w_cell_types_tibble.WNN.muscle(["metadata_w_cell_types_tibble.WNN.&lt;dataset_name&gt;"]):::none
  UMAP_embeddings_tibble.WNN.muscle_test(["UMAP_embeddings_tibble.WNN.&lt;aggregation_name&gt;"]):::none --> metadata_w_cell_types_tibble.WNN.muscle_test(["metadata_w_cell_types_tibble.WNN.&lt;aggregation_name&gt;"]):::none
  WNN_results.muscle_test(["WNN_results.&lt;aggregation_name&gt;"]):::none --> metadata_w_cell_types_tibble.WNN.muscle_test(["metadata_w_cell_types_tibble.WNN.&lt;aggregation_name&gt;"]):::none
  clusters_tibble.WNN.muscle_test(["clusters_tibble.WNN.&lt;aggregation_name&gt;"]):::none --> metadata_w_cell_types_tibble.WNN.muscle_test(["metadata_w_cell_types_tibble.WNN.&lt;aggregation_name&gt;"]):::none
  metadata_w_cell_types_tibble.ATAC.muscle_test(["metadata_w_cell_types_tibble.ATAC.&lt;aggregation_name&gt;"]):::none --> metadata_w_cell_types_tibble.WNN.muscle_test(["metadata_w_cell_types_tibble.WNN.&lt;aggregation_name&gt;"]):::none
  harmony_embeddings_matrix.GEX.muscle_test(["harmony_embeddings_matrix.GEX.&lt;aggregation_name&gt;"]):::none --> metadata_w_cell_types_tibble.WNN.muscle_test(["metadata_w_cell_types_tibble.WNN.&lt;aggregation_name&gt;"]):::none
