%%{init: {'flowchart': {'defaultRenderer': 'elk'}}}%%
flowchart TB
  metadata_w_cell_types_tibble.ATAC.brain_mouse(["metadata_w_cell_types_tibble.ATAC.&lt;aggregation_name&gt;"]):::none --> embedding_matrices.WNN.brain_mouse(["embedding_matrices.WNN.&lt;aggregation_name&gt;"]):::none
  harmony_embeddings_matrix.GEX.brain_mouse(["harmony_embeddings_matrix.GEX.&lt;aggregation_name&gt;"]):::none --> embedding_matrices.WNN.brain_mouse(["embedding_matrices.WNN.&lt;aggregation_name&gt;"]):::none
  harmony_embeddings_matrix.ATAC.brain_mouse(["harmony_embeddings_matrix.ATAC.&lt;aggregation_name&gt;"]):::none --> embedding_matrices.WNN.brain_mouse(["embedding_matrices.WNN.&lt;aggregation_name&gt;"]):::none
  UCell_GEX_marker_genes_list.brain_mouse(["UCell_GEX_marker_genes_list.&lt;aggregation_name&gt;"]):::none --> metadata_w_cell_types_tibble.WNN.brain_mouse(["metadata_w_cell_types_tibble.WNN.&lt;aggregation_name&gt;"]):::none
  WNN_results.brain_mouse(["WNN_results.&lt;aggregation_name&gt;"]):::none --> UMAP_embeddings_tibble.WNN.brain_mouse(["UMAP_embeddings_tibble.WNN.&lt;aggregation_name&gt;"]):::none
  clusters_tibble.WNN.brain_mouse(["clusters_tibble.WNN.&lt;aggregation_name&gt;"]):::none --> WNN_results.brain_mouse(["WNN_results.&lt;aggregation_name&gt;"]):::none
  embedding_matrices.WNN.brain_mouse(["embedding_matrices.WNN.&lt;aggregation_name&gt;"]):::none --> WNN_results.brain_mouse(["WNN_results.&lt;aggregation_name&gt;"]):::none
  UCell_GEX_marker_genes_list.brain_mouse(["UCell_GEX_marker_genes_list.&lt;aggregation_name&gt;"]):::none --> harmony_embeddings_matrix.ATAC.brain_mouse(["harmony_embeddings_matrix.ATAC.&lt;aggregation_name&gt;"]):::none
  harmony_embeddings_matrix.GEX.brain_mouse(["harmony_embeddings_matrix.GEX.&lt;aggregation_name&gt;"]):::none --> harmony_embeddings_matrix.ATAC.brain_mouse(["harmony_embeddings_matrix.ATAC.&lt;aggregation_name&gt;"]):::none
  UCell_GEX_marker_genes_list.brain_mouse(["UCell_GEX_marker_genes_list.&lt;aggregation_name&gt;"]):::none --> metadata_w_cell_types_tibble.ATAC.brain_mouse(["metadata_w_cell_types_tibble.ATAC.&lt;aggregation_name&gt;"]):::none
  harmony_embeddings_matrix.GEX.brain_mouse(["harmony_embeddings_matrix.GEX.&lt;aggregation_name&gt;"]):::none --> metadata_w_cell_types_tibble.ATAC.brain_mouse(["metadata_w_cell_types_tibble.ATAC.&lt;aggregation_name&gt;"]):::none
  embedding_matrices.WNN.brain_mouse(["embedding_matrices.WNN.&lt;aggregation_name&gt;"]):::none --> clusters_tibble.WNN.brain_mouse(["clusters_tibble.WNN.&lt;aggregation_name&gt;"]):::none
  harmony_embeddings_matrix.ATAC.brain_mouse(["harmony_embeddings_matrix.ATAC.&lt;aggregation_name&gt;"]):::none --> metadata_w_cell_types_tibble.ATAC.brain_mouse(["metadata_w_cell_types_tibble.ATAC.&lt;aggregation_name&gt;"]):::none
  UMAP_embeddings_tibble.WNN.brain_mouse(["UMAP_embeddings_tibble.WNN.&lt;aggregation_name&gt;"]):::none --> metadata_w_cell_types_tibble.WNN.brain_mouse(["metadata_w_cell_types_tibble.WNN.&lt;aggregation_name&gt;"]):::none
  clusters_tibble.WNN.brain_mouse(["clusters_tibble.WNN.&lt;aggregation_name&gt;"]):::none --> metadata_w_cell_types_tibble.WNN.brain_mouse(["metadata_w_cell_types_tibble.WNN.&lt;aggregation_name&gt;"]):::none
  WNN_results.brain_mouse(["WNN_results.&lt;aggregation_name&gt;"]):::none --> metadata_w_cell_types_tibble.WNN.brain_mouse(["metadata_w_cell_types_tibble.WNN.&lt;aggregation_name&gt;"]):::none
  metadata_w_cell_types_tibble.ATAC.brain_mouse(["metadata_w_cell_types_tibble.ATAC.&lt;aggregation_name&gt;"]):::none --> metadata_w_cell_types_tibble.WNN.brain_mouse(["metadata_w_cell_types_tibble.WNN.&lt;aggregation_name&gt;"]):::none
  harmony_embeddings_matrix.GEX.brain_mouse(["harmony_embeddings_matrix.GEX.&lt;aggregation_name&gt;"]):::none --> metadata_w_cell_types_tibble.WNN.brain_mouse(["metadata_w_cell_types_tibble.WNN.&lt;aggregation_name&gt;"]):::none
