project:
  type: book
  output-dir: ../docs

book:
  title: "multiomeR Manual"
  site-url: https://koefoeden.github.io/multiomeR/
  repo-url: https://github.com/koefoeden/multiomeR
  repo-actions: [source, issue]
  page-navigation: true
  sidebar:
    collapse-level: 2
  chapters:
    - part: "Introduction"
      chapters:
        - index.qmd
        - intro_manual_usage.qmd
    - part: "Background and design philosophy"
      chapters:
        - background_philosophy.qmd
    - part: "Example data: Quick, full run-through"
      chapters:
        - demo_installation.qmd
        - demo_running.qmd
        - demo_outputs.qmd
    - part: "Your own data: The main pipeline"
      chapters:
        - main_overview.qmd
        - main_inputs.qmd
        - main_running.qmd
    - part: "Your own data: Downstream modules"
      chapters:
        - downstream_differential_analyses.qmd
        - downstream_genetic_enrichment.qmd
    - part: "Performance"
      chapters:
        - performance_overview.qmd
        - performance_distributed_computing.qmd
    - part: "Output gallery"
      chapters:
        - gallery_main.qmd
        - gallery_differential_analyses.qmd
        - gallery_genetic_enrichment.qmd
    - part: "Implementation details"
      chapters:
        - implementation_overview.qmd
        - implementation_main.qmd
        - implementation_differential_analyses.qmd
        - implementation_genetic_enrichment.qmd
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    toc-depth: 3
    code-copy: true
    code-overflow: scroll
    number-sections: true
